-- Generated by kanon from bool.kn, int.kn. Do not edit.
import Tiny.Statements
import Tiny.Lib.Rule
import Tiny.Proofs

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace Tiny

open Classical Kanon

/-- The rule functions, oracles and helpers of the bool module in the model, for the proofs
of its arms by Kanon's library (`Kanon.BoolMod`). -/
def Ops.bool (O : Ops) : BoolMod.Ops boolLang where
  b_and := O.b_and
  b_or := O.b_or
  b_not := O.b_not
  b_ite := O.b_ite
  sem_eq := O.sem_eq
  tag_le := O.orc.tag_le
  sort_by_tag := O.orc.sort_by_tag
  at_most_one := at_most_one
  distinct_check_one := distinct_check_one
  distinct_check := distinct_check

theorem Ops.Sound.bool {O : Ops} (hO : O.Sound) : O.bool.Sound where
  b_and := hO.b_and
  b_or := hO.b_or
  b_not := hO.b_not
  b_ite := hO.b_ite
  sem_eq := hO.sem_eq
  sort_by_tag := hO.orc.sort_by_tag
  at_most_one _ _ _ := rfl
  distinct_check_one_nil _ := by
    dsimp only [Ops.bool]; rw [distinct_check_one]; rfl
  distinct_check_one_cons _ _ _ := by
    dsimp only [Ops.bool]; rw [distinct_check_one]; rfl
  distinct_check_nil := by
    dsimp only [Ops.bool]; rw [distinct_check]; rfl
  distinct_check_cons _ _ := by
    dsimp only [Ops.bool]; rw [distinct_check]; split <;> simp_all [firstSome]

theorem b_and.r_same.main.ok : b_and.r_same.main.Stmt :=
  fun O hO => BoolMod.b_and.r_same.main boolLang O.bool hO.bool

theorem b_and.r_same.proof : b_and.r_same.Stmt := by
  intro O hO v1 v2 res h
  simp only [b_and.r_same] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (b_and.r_same.main.ok O hO)

theorem b_and.r_false_.main.ok : b_and.r_false_.main.Stmt :=
  fun O hO => BoolMod.b_and.r_false_.main boolLang O.bool hO.bool

theorem b_and.r_false_.swap.ok : b_and.r_false_.swap.Stmt :=
  fun O hO => BoolMod.b_and.r_false_.swap boolLang O.bool hO.bool

theorem b_and.r_false_.proof : b_and.r_false_.Stmt := by
  intro O hO v1 v2 res h
  simp only [b_and.r_false_] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (b_and.r_false_.main.ok O hO)
  · kanon_arm h (b_and.r_false_.swap.ok O hO)

theorem b_and.r_true_.main.ok : b_and.r_true_.main.Stmt :=
  fun O hO => BoolMod.b_and.r_true_.main boolLang O.bool hO.bool

theorem b_and.r_true_.swap.ok : b_and.r_true_.swap.Stmt :=
  fun O hO => BoolMod.b_and.r_true_.swap boolLang O.bool hO.bool

theorem b_and.r_true_.proof : b_and.r_true_.Stmt := by
  intro O hO v1 v2 res h
  simp only [b_and.r_true_] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (b_and.r_true_.main.ok O hO)
  · kanon_arm h (b_and.r_true_.swap.ok O hO)

theorem b_and.r_not.main.ok : b_and.r_not.main.Stmt :=
  fun O hO => BoolMod.b_and.r_not.main boolLang O.bool hO.bool

theorem b_and.r_not.swap.ok : b_and.r_not.swap.Stmt :=
  fun O hO => BoolMod.b_and.r_not.swap boolLang O.bool hO.bool

theorem b_and.r_not.proof : b_and.r_not.Stmt := by
  intro O hO v1 v2 res h
  simp only [b_and.r_not] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (b_and.r_not.main.ok O hO)
  · kanon_arm h (b_and.r_not.swap.ok O hO)

theorem b_and.r_and_.main.ok : b_and.r_and_.main.Stmt :=
  fun O hO => BoolMod.b_and.r_and_.main boolLang O.bool hO.bool

theorem b_and.r_and_.swap1.ok : b_and.r_and_.swap1.Stmt :=
  fun O hO => BoolMod.b_and.r_and_.swap1 boolLang O.bool hO.bool

theorem b_and.r_and_.swap2.ok : b_and.r_and_.swap2.Stmt :=
  fun O hO => BoolMod.b_and.r_and_.swap2 boolLang O.bool hO.bool

theorem b_and.r_and_.swap1_swap2.ok : b_and.r_and_.swap1_swap2.Stmt :=
  fun O hO => BoolMod.b_and.r_and_.swap1_swap2 boolLang O.bool hO.bool

theorem b_and.r_and_.proof : b_and.r_and_.Stmt := by
  intro O hO v1 v2 res h
  simp only [b_and.r_and_] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (b_and.r_and_.main.ok O hO)
  · kanon_arm h (b_and.r_and_.swap1.ok O hO)
  · kanon_arm h (b_and.r_and_.swap2.ok O hO)
  · kanon_arm h (b_and.r_and_.swap1_swap2.ok O hO)

theorem b_and.r_or_.main.ok : b_and.r_or_.main.Stmt :=
  fun O hO => BoolMod.b_and.r_or_.main boolLang O.bool hO.bool

theorem b_and.r_or_.swap1.ok : b_and.r_or_.swap1.Stmt :=
  fun O hO => BoolMod.b_and.r_or_.swap1 boolLang O.bool hO.bool

theorem b_and.r_or_.swap2.ok : b_and.r_or_.swap2.Stmt :=
  fun O hO => BoolMod.b_and.r_or_.swap2 boolLang O.bool hO.bool

theorem b_and.r_or_.swap1_swap2.ok : b_and.r_or_.swap1_swap2.Stmt :=
  fun O hO => BoolMod.b_and.r_or_.swap1_swap2 boolLang O.bool hO.bool

theorem b_and.r_or_.proof : b_and.r_or_.Stmt := by
  intro O hO v1 v2 res h
  simp only [b_and.r_or_] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (b_and.r_or_.main.ok O hO)
  · kanon_arm h (b_and.r_or_.swap1.ok O hO)
  · kanon_arm h (b_and.r_or_.swap2.ok O hO)
  · kanon_arm h (b_and.r_or_.swap1_swap2.ok O hO)

theorem b_and.r_eq_neq.main.ok : b_and.r_eq_neq.main.Stmt :=
  fun O hO => BoolMod.b_and.r_eq_neq.main boolLang O.bool hO.bool

theorem b_and.r_eq_neq.swap2.ok : b_and.r_eq_neq.swap2.Stmt :=
  fun O hO => BoolMod.b_and.r_eq_neq.swap2 boolLang O.bool hO.bool

theorem b_and.r_eq_neq.swap1.ok : b_and.r_eq_neq.swap1.Stmt :=
  fun O hO => BoolMod.b_and.r_eq_neq.swap1 boolLang O.bool hO.bool

theorem b_and.r_eq_neq.swap1_swap2.ok : b_and.r_eq_neq.swap1_swap2.Stmt :=
  fun O hO => BoolMod.b_and.r_eq_neq.swap1_swap2 boolLang O.bool hO.bool

theorem b_and.r_eq_neq.proof : b_and.r_eq_neq.Stmt := by
  intro O hO v1 v2 res h
  simp only [b_and.r_eq_neq] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (b_and.r_eq_neq.main.ok O hO)
  · kanon_arm h (b_and.r_eq_neq.swap2.ok O hO)
  · kanon_arm h (b_and.r_eq_neq.swap1.ok O hO)
  · kanon_arm h (b_and.r_eq_neq.swap1_swap2.ok O hO)

theorem b_and.r_default.main.ok : b_and.r_default.main.Stmt :=
  fun O hO => BoolMod.b_and.r_default.main boolLang O.bool hO.bool

theorem b_and.r_default.proof : b_and.r_default.Stmt := by
  intro O hO v1 v2 res h
  simp only [b_and.r_default] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (b_and.r_default.main.ok O hO)

theorem b_or.r_same.main.ok : b_or.r_same.main.Stmt :=
  fun O hO => BoolMod.b_or.r_same.main boolLang O.bool hO.bool

theorem b_or.r_same.proof : b_or.r_same.Stmt := by
  intro O hO v1 v2 res h
  simp only [b_or.r_same] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (b_or.r_same.main.ok O hO)

theorem b_or.r_true_.main.ok : b_or.r_true_.main.Stmt :=
  fun O hO => BoolMod.b_or.r_true_.main boolLang O.bool hO.bool

theorem b_or.r_true_.swap.ok : b_or.r_true_.swap.Stmt :=
  fun O hO => BoolMod.b_or.r_true_.swap boolLang O.bool hO.bool

theorem b_or.r_true_.proof : b_or.r_true_.Stmt := by
  intro O hO v1 v2 res h
  simp only [b_or.r_true_] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (b_or.r_true_.main.ok O hO)
  · kanon_arm h (b_or.r_true_.swap.ok O hO)

theorem b_or.r_false_.main.ok : b_or.r_false_.main.Stmt :=
  fun O hO => BoolMod.b_or.r_false_.main boolLang O.bool hO.bool

theorem b_or.r_false_.swap.ok : b_or.r_false_.swap.Stmt :=
  fun O hO => BoolMod.b_or.r_false_.swap boolLang O.bool hO.bool

theorem b_or.r_false_.proof : b_or.r_false_.Stmt := by
  intro O hO v1 v2 res h
  simp only [b_or.r_false_] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (b_or.r_false_.main.ok O hO)
  · kanon_arm h (b_or.r_false_.swap.ok O hO)

theorem b_or.r_not.main.ok : b_or.r_not.main.Stmt :=
  fun O hO => BoolMod.b_or.r_not.main boolLang O.bool hO.bool

theorem b_or.r_not.swap.ok : b_or.r_not.swap.Stmt :=
  fun O hO => BoolMod.b_or.r_not.swap boolLang O.bool hO.bool

theorem b_or.r_not.proof : b_or.r_not.Stmt := by
  intro O hO v1 v2 res h
  simp only [b_or.r_not] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (b_or.r_not.main.ok O hO)
  · kanon_arm h (b_or.r_not.swap.ok O hO)

theorem b_or.r_or_.main.ok : b_or.r_or_.main.Stmt :=
  fun O hO => BoolMod.b_or.r_or_.main boolLang O.bool hO.bool

theorem b_or.r_or_.swap1.ok : b_or.r_or_.swap1.Stmt :=
  fun O hO => BoolMod.b_or.r_or_.swap1 boolLang O.bool hO.bool

theorem b_or.r_or_.swap2.ok : b_or.r_or_.swap2.Stmt :=
  fun O hO => BoolMod.b_or.r_or_.swap2 boolLang O.bool hO.bool

theorem b_or.r_or_.swap1_swap2.ok : b_or.r_or_.swap1_swap2.Stmt :=
  fun O hO => BoolMod.b_or.r_or_.swap1_swap2 boolLang O.bool hO.bool

theorem b_or.r_or_.proof : b_or.r_or_.Stmt := by
  intro O hO v1 v2 res h
  simp only [b_or.r_or_] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (b_or.r_or_.main.ok O hO)
  · kanon_arm h (b_or.r_or_.swap1.ok O hO)
  · kanon_arm h (b_or.r_or_.swap2.ok O hO)
  · kanon_arm h (b_or.r_or_.swap1_swap2.ok O hO)

theorem b_or.r_and_.main.ok : b_or.r_and_.main.Stmt :=
  fun O hO => BoolMod.b_or.r_and_.main boolLang O.bool hO.bool

theorem b_or.r_and_.swap1.ok : b_or.r_and_.swap1.Stmt :=
  fun O hO => BoolMod.b_or.r_and_.swap1 boolLang O.bool hO.bool

theorem b_or.r_and_.swap2.ok : b_or.r_and_.swap2.Stmt :=
  fun O hO => BoolMod.b_or.r_and_.swap2 boolLang O.bool hO.bool

theorem b_or.r_and_.swap1_swap2.ok : b_or.r_and_.swap1_swap2.Stmt :=
  fun O hO => BoolMod.b_or.r_and_.swap1_swap2 boolLang O.bool hO.bool

theorem b_or.r_and_.proof : b_or.r_and_.Stmt := by
  intro O hO v1 v2 res h
  simp only [b_or.r_and_] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (b_or.r_and_.main.ok O hO)
  · kanon_arm h (b_or.r_and_.swap1.ok O hO)
  · kanon_arm h (b_or.r_and_.swap2.ok O hO)
  · kanon_arm h (b_or.r_and_.swap1_swap2.ok O hO)

theorem b_or.r_default.main.ok : b_or.r_default.main.Stmt :=
  fun O hO => BoolMod.b_or.r_default.main boolLang O.bool hO.bool

theorem b_or.r_default.proof : b_or.r_default.Stmt := by
  intro O hO v1 v2 res h
  simp only [b_or.r_default] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (b_or.r_default.main.ok O hO)

theorem b_not.r_true_.main.ok : b_not.r_true_.main.Stmt :=
  fun O hO => BoolMod.b_not.r_true_.main boolLang O.bool hO.bool

theorem b_not.r_true_.proof : b_not.r_true_.Stmt := by
  intro O hO sv res h
  simp only [b_not.r_true_] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (b_not.r_true_.main.ok O hO)

theorem b_not.r_false_.main.ok : b_not.r_false_.main.Stmt :=
  fun O hO => BoolMod.b_not.r_false_.main boolLang O.bool hO.bool

theorem b_not.r_false_.proof : b_not.r_false_.Stmt := by
  intro O hO sv res h
  simp only [b_not.r_false_] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (b_not.r_false_.main.ok O hO)

theorem b_not.r_not.main.ok : b_not.r_not.main.Stmt :=
  fun O hO => BoolMod.b_not.r_not.main boolLang O.bool hO.bool

theorem b_not.r_not.proof : b_not.r_not.Stmt := by
  intro O hO sv res h
  simp only [b_not.r_not] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (b_not.r_not.main.ok O hO)

theorem b_not.r_or_.main.ok : b_not.r_or_.main.Stmt :=
  fun O hO => BoolMod.b_not.r_or_.main boolLang O.bool hO.bool

theorem b_not.r_or_.proof : b_not.r_or_.Stmt := by
  intro O hO sv res h
  simp only [b_not.r_or_] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (b_not.r_or_.main.ok O hO)

theorem b_not.r_and_.main.ok : b_not.r_and_.main.Stmt :=
  fun O hO => BoolMod.b_not.r_and_.main boolLang O.bool hO.bool

theorem b_not.r_and_.proof : b_not.r_and_.Stmt := by
  intro O hO sv res h
  simp only [b_not.r_and_] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (b_not.r_and_.main.ok O hO)

theorem b_not.r_ite.main.ok : b_not.r_ite.main.Stmt :=
  fun O hO => BoolMod.b_not.r_ite.main boolLang O.bool hO.bool

theorem b_not.r_ite.proof : b_not.r_ite.Stmt := by
  intro O hO sv res h
  simp only [b_not.r_ite] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (b_not.r_ite.main.ok O hO)

theorem b_not.r_distinct.main.ok : b_not.r_distinct.main.Stmt :=
  fun O hO => BoolMod.b_not.r_distinct.main boolLang O.bool hO.bool

theorem b_not.r_distinct.proof : b_not.r_distinct.Stmt := by
  intro O hO sv res h
  simp only [b_not.r_distinct] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (b_not.r_distinct.main.ok O hO)

theorem b_not.r_lt.main.ok : b_not.r_lt.main.Stmt := kanon_proof% b_not.r_lt.main

theorem b_not.r_lt.proof : b_not.r_lt.Stmt := by
  intro O hO sv res h
  simp only [b_not.r_lt] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (b_not.r_lt.main.ok O hO)

theorem b_not.r_leq.main.ok : b_not.r_leq.main.Stmt := kanon_proof% b_not.r_leq.main

theorem b_not.r_leq.proof : b_not.r_leq.Stmt := by
  intro O hO sv res h
  simp only [b_not.r_leq] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (b_not.r_leq.main.ok O hO)

theorem b_not.r_default.main.ok : b_not.r_default.main.Stmt :=
  fun O hO => BoolMod.b_not.r_default.main boolLang O.bool hO.bool

theorem b_not.r_default.proof : b_not.r_default.Stmt := by
  intro O hO sv res h
  simp only [b_not.r_default] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (b_not.r_default.main.ok O hO)

theorem b_ite.r_true_.main.ok : b_ite.r_true_.main.Stmt :=
  fun O hO => BoolMod.b_ite.r_true_.main boolLang O.bool hO.bool

theorem b_ite.r_true_.proof : b_ite.r_true_.Stmt := by
  intro O hO guard if_ else_ res h
  simp only [b_ite.r_true_] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (b_ite.r_true_.main.ok O hO)

theorem b_ite.r_false_.main.ok : b_ite.r_false_.main.Stmt :=
  fun O hO => BoolMod.b_ite.r_false_.main boolLang O.bool hO.bool

theorem b_ite.r_false_.proof : b_ite.r_false_.Stmt := by
  intro O hO guard if_ else_ res h
  simp only [b_ite.r_false_] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (b_ite.r_false_.main.ok O hO)

theorem b_ite.r_bool.main.ok : b_ite.r_bool.main.Stmt :=
  fun O hO => BoolMod.b_ite.r_bool.main boolLang O.bool hO.bool

theorem b_ite.r_bool.proof : b_ite.r_bool.Stmt := by
  intro O hO guard if_ else_ res h
  simp only [b_ite.r_bool] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (b_ite.r_bool.main.ok O hO)

theorem b_ite.r_not_bool.main.ok : b_ite.r_not_bool.main.Stmt :=
  fun O hO => BoolMod.b_ite.r_not_bool.main boolLang O.bool hO.bool

theorem b_ite.r_not_bool.proof : b_ite.r_not_bool.Stmt := by
  intro O hO guard if_ else_ res h
  simp only [b_ite.r_not_bool] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (b_ite.r_not_bool.main.ok O hO)

theorem b_ite.r_false_then.main.ok : b_ite.r_false_then.main.Stmt :=
  fun O hO => BoolMod.b_ite.r_false_then.main boolLang O.bool hO.bool

theorem b_ite.r_false_then.proof : b_ite.r_false_then.Stmt := by
  intro O hO guard if_ else_ res h
  simp only [b_ite.r_false_then] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (b_ite.r_false_then.main.ok O hO)

theorem b_ite.r_true_then.main.ok : b_ite.r_true_then.main.Stmt :=
  fun O hO => BoolMod.b_ite.r_true_then.main boolLang O.bool hO.bool

theorem b_ite.r_true_then.proof : b_ite.r_true_then.Stmt := by
  intro O hO guard if_ else_ res h
  simp only [b_ite.r_true_then] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (b_ite.r_true_then.main.ok O hO)

theorem b_ite.r_false_else.main.ok : b_ite.r_false_else.main.Stmt :=
  fun O hO => BoolMod.b_ite.r_false_else.main boolLang O.bool hO.bool

theorem b_ite.r_false_else.proof : b_ite.r_false_else.Stmt := by
  intro O hO guard if_ else_ res h
  simp only [b_ite.r_false_else] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (b_ite.r_false_else.main.ok O hO)

theorem b_ite.r_true_else.main.ok : b_ite.r_true_else.main.Stmt :=
  fun O hO => BoolMod.b_ite.r_true_else.main boolLang O.bool hO.bool

theorem b_ite.r_true_else.proof : b_ite.r_true_else.Stmt := by
  intro O hO guard if_ else_ res h
  simp only [b_ite.r_true_else] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (b_ite.r_true_else.main.ok O hO)

theorem b_ite.r_not_guard.main.ok : b_ite.r_not_guard.main.Stmt :=
  fun O hO => BoolMod.b_ite.r_not_guard.main boolLang O.bool hO.bool

theorem b_ite.r_not_guard.proof : b_ite.r_not_guard.Stmt := by
  intro O hO guard if_ else_ res h
  simp only [b_ite.r_not_guard] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (b_ite.r_not_guard.main.ok O hO)

theorem b_ite.r_guard_then.main.ok : b_ite.r_guard_then.main.Stmt :=
  fun O hO => BoolMod.b_ite.r_guard_then.main boolLang O.bool hO.bool

theorem b_ite.r_guard_then.proof : b_ite.r_guard_then.Stmt := by
  intro O hO guard if_ else_ res h
  simp only [b_ite.r_guard_then] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (b_ite.r_guard_then.main.ok O hO)

theorem b_ite.r_guard_else.main.ok : b_ite.r_guard_else.main.Stmt :=
  fun O hO => BoolMod.b_ite.r_guard_else.main boolLang O.bool hO.bool

theorem b_ite.r_guard_else.proof : b_ite.r_guard_else.Stmt := by
  intro O hO guard if_ else_ res h
  simp only [b_ite.r_guard_else] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (b_ite.r_guard_else.main.ok O hO)

theorem b_ite.r_ite_then.main.ok : b_ite.r_ite_then.main.Stmt :=
  fun O hO => BoolMod.b_ite.r_ite_then.main boolLang O.bool hO.bool

theorem b_ite.r_ite_then.proof : b_ite.r_ite_then.Stmt := by
  intro O hO guard if_ else_ res h
  simp only [b_ite.r_ite_then] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (b_ite.r_ite_then.main.ok O hO)

theorem b_ite.r_ite_else.main.ok : b_ite.r_ite_else.main.Stmt :=
  fun O hO => BoolMod.b_ite.r_ite_else.main boolLang O.bool hO.bool

theorem b_ite.r_ite_else.proof : b_ite.r_ite_else.Stmt := by
  intro O hO guard if_ else_ res h
  simp only [b_ite.r_ite_else] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (b_ite.r_ite_else.main.ok O hO)

theorem b_ite.r_and_ite_then.main.ok : b_ite.r_and_ite_then.main.Stmt :=
  fun O hO => BoolMod.b_ite.r_and_ite_then.main boolLang O.bool hO.bool

theorem b_ite.r_and_ite_then.swap.ok : b_ite.r_and_ite_then.swap.Stmt :=
  fun O hO => BoolMod.b_ite.r_and_ite_then.swap boolLang O.bool hO.bool

theorem b_ite.r_and_ite_then.proof : b_ite.r_and_ite_then.Stmt := by
  intro O hO guard if_ else_ res h
  simp only [b_ite.r_and_ite_then] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (b_ite.r_and_ite_then.main.ok O hO)
  · kanon_arm h (b_ite.r_and_ite_then.swap.ok O hO)

theorem b_ite.r_or_ite_else.main.ok : b_ite.r_or_ite_else.main.Stmt :=
  fun O hO => BoolMod.b_ite.r_or_ite_else.main boolLang O.bool hO.bool

theorem b_ite.r_or_ite_else.swap.ok : b_ite.r_or_ite_else.swap.Stmt :=
  fun O hO => BoolMod.b_ite.r_or_ite_else.swap boolLang O.bool hO.bool

theorem b_ite.r_or_ite_else.proof : b_ite.r_or_ite_else.Stmt := by
  intro O hO guard if_ else_ res h
  simp only [b_ite.r_or_ite_else] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (b_ite.r_or_ite_else.main.ok O hO)
  · kanon_arm h (b_ite.r_or_ite_else.swap.ok O hO)

theorem b_ite.r_same.main.ok : b_ite.r_same.main.Stmt :=
  fun O hO => BoolMod.b_ite.r_same.main boolLang O.bool hO.bool

theorem b_ite.r_same.proof : b_ite.r_same.Stmt := by
  intro O hO guard if_ else_ res h
  simp only [b_ite.r_same] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (b_ite.r_same.main.ok O hO)

theorem b_ite.r_default.main.ok : b_ite.r_default.main.Stmt :=
  fun O hO => BoolMod.b_ite.r_default.main boolLang O.bool hO.bool

theorem b_ite.r_default.proof : b_ite.r_default.Stmt := by
  intro O hO guard if_ else_ res h
  simp only [b_ite.r_default] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (b_ite.r_default.main.ok O hO)

theorem sem_eq.r_same.main.ok : sem_eq.r_same.main.Stmt :=
  fun O hO => BoolMod.sem_eq.r_same.main boolLang O.bool hO.bool

theorem sem_eq.r_same.proof : sem_eq.r_same.Stmt := by
  intro O hO v1 v2 res h
  simp only [sem_eq.r_same] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (sem_eq.r_same.main.ok O hO)

theorem sem_eq.r_bools.main.ok : sem_eq.r_bools.main.Stmt :=
  fun O hO => BoolMod.sem_eq.r_bools.main boolLang O.bool hO.bool

theorem sem_eq.r_bools.proof : sem_eq.r_bools.Stmt := by
  intro O hO v1 v2 res h
  simp only [sem_eq.r_bools] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (sem_eq.r_bools.main.ok O hO)

theorem sem_eq.r_ite_ite.main.ok : sem_eq.r_ite_ite.main.Stmt :=
  fun O hO => BoolMod.sem_eq.r_ite_ite.main boolLang O.bool hO.bool

theorem sem_eq.r_ite_ite.proof : sem_eq.r_ite_ite.Stmt := by
  intro O hO v1 v2 res h
  simp only [sem_eq.r_ite_ite] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (sem_eq.r_ite_ite.main.ok O hO)

theorem sem_eq.r_false_.main.ok : sem_eq.r_false_.main.Stmt :=
  fun O hO => BoolMod.sem_eq.r_false_.main boolLang O.bool hO.bool

theorem sem_eq.r_false_.swap.ok : sem_eq.r_false_.swap.Stmt :=
  fun O hO => BoolMod.sem_eq.r_false_.swap boolLang O.bool hO.bool

theorem sem_eq.r_false_.proof : sem_eq.r_false_.Stmt := by
  intro O hO v1 v2 res h
  simp only [sem_eq.r_false_] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (sem_eq.r_false_.main.ok O hO)
  · kanon_arm h (sem_eq.r_false_.swap.ok O hO)

theorem sem_eq.r_true_.main.ok : sem_eq.r_true_.main.Stmt :=
  fun O hO => BoolMod.sem_eq.r_true_.main boolLang O.bool hO.bool

theorem sem_eq.r_true_.swap.ok : sem_eq.r_true_.swap.Stmt :=
  fun O hO => BoolMod.sem_eq.r_true_.swap boolLang O.bool hO.bool

theorem sem_eq.r_true_.proof : sem_eq.r_true_.Stmt := by
  intro O hO v1 v2 res h
  simp only [sem_eq.r_true_] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (sem_eq.r_true_.main.ok O hO)
  · kanon_arm h (sem_eq.r_true_.swap.ok O hO)

theorem sem_eq.r_nots.main.ok : sem_eq.r_nots.main.Stmt :=
  fun O hO => BoolMod.sem_eq.r_nots.main boolLang O.bool hO.bool

theorem sem_eq.r_nots.proof : sem_eq.r_nots.Stmt := by
  intro O hO v1 v2 res h
  simp only [sem_eq.r_nots] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (sem_eq.r_nots.main.ok O hO)

theorem sem_eq.r_ints.main.ok : sem_eq.r_ints.main.Stmt := kanon_proof% sem_eq.r_ints.main

theorem sem_eq.r_ints.proof : sem_eq.r_ints.Stmt := by
  intro O hO v1 v2 res h
  simp only [sem_eq.r_ints] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (sem_eq.r_ints.main.ok O hO)

theorem sem_eq.r_add_self.main.ok : sem_eq.r_add_self.main.Stmt := kanon_proof% sem_eq.r_add_self.main

theorem sem_eq.r_add_self.swap1.ok : sem_eq.r_add_self.swap1.Stmt := by
  intro O hO v1 y kanon__3 t__5 hg
  exact Refinement.trans
    (by simp only [sem_eq.spec, ty, Term.ty_mk]; kanon_comm)
    (sem_eq.r_add_self.main.ok O hO v1 kanon__3 y t__5 hg)

theorem sem_eq.r_add_self.swap2.ok : sem_eq.r_add_self.swap2.Stmt := by
  intro O hO v2 kanon__3 y t__5 hg
  exact Refinement.trans
    (by simp only [sem_eq.spec, ty, Term.ty_mk]; kanon_comm)
    (sem_eq.r_add_self.main.ok O hO v2 kanon__3 y t__5 hg)

theorem sem_eq.r_add_self.swap1_swap2.ok : sem_eq.r_add_self.swap1_swap2.Stmt := by
  intro O hO v2 y kanon__3 t__5 hg
  exact Refinement.trans
    (by simp only [sem_eq.spec, ty, Term.ty_mk]; kanon_comm)
    (sem_eq.r_add_self.main.ok O hO v2 kanon__3 y t__5 hg)

theorem sem_eq.r_add_self.proof : sem_eq.r_add_self.Stmt := by
  intro O hO v1 v2 res h
  simp only [sem_eq.r_add_self] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (sem_eq.r_add_self.main.ok O hO)
  · kanon_arm h (sem_eq.r_add_self.swap1.ok O hO)
  · kanon_arm h (sem_eq.r_add_self.swap2.ok O hO)
  · kanon_arm h (sem_eq.r_add_self.swap1_swap2.ok O hO)

theorem sem_eq.r_add_add.main.ok : sem_eq.r_add_add.main.Stmt := kanon_proof% sem_eq.r_add_add.main

theorem sem_eq.r_add_add.swap2.ok : sem_eq.r_add_add.swap2.Stmt := by
  intro O hO a x t__4 y kanon__7 t__9 hg
  exact Refinement.trans
    (by simp only [sem_eq.spec, ty, Term.ty_mk]; kanon_comm)
    (sem_eq.r_add_add.main.ok O hO a x t__4 kanon__7 y t__9 hg)

theorem sem_eq.r_add_add.swap1.ok : sem_eq.r_add_add.swap1.Stmt := by
  intro O hO x a t__4 kanon__7 y t__9 hg
  exact Refinement.trans
    (by simp only [sem_eq.spec, ty, Term.ty_mk]; kanon_comm)
    (sem_eq.r_add_add.main.ok O hO a x t__4 kanon__7 y t__9 hg)

theorem sem_eq.r_add_add.swap1_swap2.ok : sem_eq.r_add_add.swap1_swap2.Stmt := by
  intro O hO x a t__4 y kanon__7 t__9 hg
  exact Refinement.trans
    (by simp only [sem_eq.spec, ty, Term.ty_mk]; kanon_comm)
    (sem_eq.r_add_add.main.ok O hO a x t__4 kanon__7 y t__9 hg)

theorem sem_eq.r_add_add.proof : sem_eq.r_add_add.Stmt := by
  intro O hO v1 v2 res h
  simp only [sem_eq.r_add_add] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (sem_eq.r_add_add.main.ok O hO)
  · kanon_arm h (sem_eq.r_add_add.swap2.ok O hO)
  · kanon_arm h (sem_eq.r_add_add.swap1.ok O hO)
  · kanon_arm h (sem_eq.r_add_add.swap1_swap2.ok O hO)

theorem sem_eq.r_add_const.main.ok : sem_eq.r_add_const.main.Stmt := kanon_proof% sem_eq.r_add_const.main

theorem sem_eq.r_add_const.swap1.ok : sem_eq.r_add_const.swap1.Stmt := by
  intro O hO a t__4 v t__5 b t__8
  exact Refinement.trans
    (by simp only [sem_eq.spec, ty, Term.ty_mk]; kanon_comm)
    (sem_eq.r_add_const.main.ok O hO v a t__4 t__5 b t__8)

theorem sem_eq.r_add_const.swap2.ok : sem_eq.r_add_const.swap2.Stmt := by
  intro O hO b t__8 v a t__4 t__5
  exact Refinement.trans
    (by simp only [sem_eq.spec, ty, Term.ty_mk]; kanon_comm)
    (sem_eq.r_add_const.main.ok O hO v a t__4 t__5 b t__8)

theorem sem_eq.r_add_const.swap1_swap2.ok : sem_eq.r_add_const.swap1_swap2.Stmt := by
  intro O hO b t__8 a t__4 v t__5
  exact Refinement.trans
    (by simp only [sem_eq.spec, ty, Term.ty_mk]; kanon_comm)
    (sem_eq.r_add_const.main.ok O hO v a t__4 t__5 b t__8)

theorem sem_eq.r_add_const.proof : sem_eq.r_add_const.Stmt := by
  intro O hO v1 v2 res h
  simp only [sem_eq.r_add_const] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (sem_eq.r_add_const.main.ok O hO)
  · kanon_arm h (sem_eq.r_add_const.swap1.ok O hO)
  · kanon_arm h (sem_eq.r_add_const.swap2.ok O hO)
  · kanon_arm h (sem_eq.r_add_const.swap1_swap2.ok O hO)

theorem sem_eq.r_sub_const.main.ok : sem_eq.r_sub_const.main.Stmt := kanon_proof% sem_eq.r_sub_const.main

theorem sem_eq.r_sub_const.swap.ok : sem_eq.r_sub_const.swap.Stmt := by
  intro O hO b t__7 v a t__4 t__5
  exact Refinement.trans
    (by simp only [sem_eq.spec, ty, Term.ty_mk]; kanon_comm)
    (sem_eq.r_sub_const.main.ok O hO v a t__4 t__5 b t__7)

theorem sem_eq.r_sub_const.proof : sem_eq.r_sub_const.Stmt := by
  intro O hO v1 v2 res h
  simp only [sem_eq.r_sub_const] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (sem_eq.r_sub_const.main.ok O hO)
  · kanon_arm h (sem_eq.r_sub_const.swap.ok O hO)

theorem sem_eq.r_mul_const.times1.ok : sem_eq.r_mul_const.times1.Stmt := kanon_proof% sem_eq.r_mul_const.times1

theorem sem_eq.r_mul_const.swap1_times1.ok : sem_eq.r_mul_const.swap1_times1.Stmt := by
  intro O hO b t__2 v a t__5 t__7
  exact Refinement.trans
    (by simp only [sem_eq.spec, ty, Term.ty_mk]; kanon_comm)
    (sem_eq.r_mul_const.times1.ok O hO b t__2 a t__5 v t__7)

theorem sem_eq.r_mul_const.times1_swap2.ok : sem_eq.r_mul_const.times1_swap2.Stmt := by
  intro O hO a t__5 v t__7 b t__2
  exact Refinement.trans
    (by simp only [sem_eq.spec, ty, Term.ty_mk]; kanon_comm)
    (sem_eq.r_mul_const.times1.ok O hO b t__2 a t__5 v t__7)

theorem sem_eq.r_mul_const.swap1_times1_swap2.ok : sem_eq.r_mul_const.swap1_times1_swap2.Stmt := by
  intro O hO v a t__5 t__7 b t__2
  exact Refinement.trans
    (by simp only [sem_eq.spec, ty, Term.ty_mk]; kanon_comm)
    (sem_eq.r_mul_const.times1.ok O hO b t__2 a t__5 v t__7)

theorem sem_eq.r_mul_const.proof : sem_eq.r_mul_const.Stmt := by
  intro O hO v1 v2 res h
  simp only [sem_eq.r_mul_const] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (sem_eq.r_mul_const.times1.ok O hO)
  · kanon_arm h (sem_eq.r_mul_const.swap1_times1.ok O hO)
  · kanon_arm h (sem_eq.r_mul_const.times1_swap2.ok O hO)
  · kanon_arm h (sem_eq.r_mul_const.swap1_times1_swap2.ok O hO)

theorem sem_eq.r_default.main.ok : sem_eq.r_default.main.Stmt :=
  fun O hO => BoolMod.sem_eq.r_default.main boolLang O.bool hO.bool

theorem sem_eq.r_default.proof : sem_eq.r_default.Stmt := by
  intro O hO v1 v2 res h
  simp only [sem_eq.r_default] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (sem_eq.r_default.main.ok O hO)

theorem sem_eq_untyped.r_ill_typed.main.ok : sem_eq_untyped.r_ill_typed.main.Stmt :=
  fun O hO => BoolMod.sem_eq_untyped.r_ill_typed.main boolLang O.bool hO.bool

theorem sem_eq_untyped.r_ill_typed.proof : sem_eq_untyped.r_ill_typed.Stmt := by
  intro O hO v1 v2 res h
  simp only [sem_eq_untyped.r_ill_typed] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (sem_eq_untyped.r_ill_typed.main.ok O hO)

theorem sem_eq_untyped.r_typed.main.ok : sem_eq_untyped.r_typed.main.Stmt :=
  fun O hO => BoolMod.sem_eq_untyped.r_typed.main boolLang O.bool hO.bool

theorem sem_eq_untyped.r_typed.proof : sem_eq_untyped.r_typed.Stmt := by
  intro O hO v1 v2 res h
  simp only [sem_eq_untyped.r_typed] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (sem_eq_untyped.r_typed.main.ok O hO)

theorem b_distinct.r_small.main.ok : b_distinct.r_small.main.Stmt :=
  fun O hO => BoolMod.b_distinct.r_small.main boolLang O.bool hO.bool

theorem b_distinct.r_small.proof : b_distinct.r_small.Stmt := by
  intro O hO l res h
  simp only [b_distinct.r_small] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (b_distinct.r_small.main.ok O hO)

theorem b_distinct.r_distinct.main.ok : b_distinct.r_distinct.main.Stmt :=
  fun O hO => BoolMod.b_distinct.r_distinct.main boolLang O.bool hO.bool

theorem b_distinct.r_distinct.proof : b_distinct.r_distinct.Stmt := by
  intro O hO l res h
  simp only [b_distinct.r_distinct] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (b_distinct.r_distinct.main.ok O hO)

theorem b_distinct.r_not_distinct.main.ok : b_distinct.r_not_distinct.main.Stmt :=
  fun O hO => BoolMod.b_distinct.r_not_distinct.main boolLang O.bool hO.bool

theorem b_distinct.r_not_distinct.proof : b_distinct.r_not_distinct.Stmt := by
  intro O hO l res h
  simp only [b_distinct.r_not_distinct] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (b_distinct.r_not_distinct.main.ok O hO)

theorem b_distinct.r_default.main.ok : b_distinct.r_default.main.Stmt :=
  fun O hO => BoolMod.b_distinct.r_default.main boolLang O.bool hO.bool

theorem b_distinct.r_default.proof : b_distinct.r_default.Stmt := by
  intro O hO l res h
  simp only [b_distinct.r_default] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (b_distinct.r_default.main.ok O hO)

theorem add.r_zero.main.ok : add.r_zero.main.Stmt := kanon_proof% add.r_zero.main

theorem add.r_zero.swap.ok : add.r_zero.swap.Stmt := by
  intro O hO v1 kanon__1 t__2 hg
  exact Refinement.trans
    (by simp only [add.spec, ty, Term.ty_mk]; kanon_comm)
    (add.r_zero.main.ok O hO v1 kanon__1 t__2 hg)

theorem add.r_zero.proof : add.r_zero.Stmt := by
  intro O hO v1 v2 res h
  simp only [add.r_zero] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (add.r_zero.main.ok O hO)
  · kanon_arm h (add.r_zero.swap.ok O hO)

theorem add.r_lits.main.ok : add.r_lits.main.Stmt := kanon_proof% add.r_lits.main

theorem add.r_lits.proof : add.r_lits.Stmt := by
  intro O hO v1 v2 res h
  simp only [add.r_lits] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (add.r_lits.main.ok O hO)

theorem add.r_assoc.main.ok : add.r_assoc.main.Stmt := kanon_proof% add.r_assoc.main

theorem add.r_assoc.swap1.ok : add.r_assoc.swap1.Stmt := by
  intro O hO a t__4 x t__5 b t__8
  exact Refinement.trans
    (by simp only [add.spec, ty, Term.ty_mk]; kanon_comm)
    (add.r_assoc.main.ok O hO x a t__4 t__5 b t__8)

theorem add.r_assoc.swap2.ok : add.r_assoc.swap2.Stmt := by
  intro O hO b t__8 x a t__4 t__5
  exact Refinement.trans
    (by simp only [add.spec, ty, Term.ty_mk]; kanon_comm)
    (add.r_assoc.main.ok O hO x a t__4 t__5 b t__8)

theorem add.r_assoc.swap1_swap2.ok : add.r_assoc.swap1_swap2.Stmt := by
  intro O hO b t__8 a t__4 x t__5
  exact Refinement.trans
    (by simp only [add.spec, ty, Term.ty_mk]; kanon_comm)
    (add.r_assoc.main.ok O hO x a t__4 t__5 b t__8)

theorem add.r_assoc.proof : add.r_assoc.Stmt := by
  intro O hO v1 v2 res h
  simp only [add.r_assoc] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (add.r_assoc.main.ok O hO)
  · kanon_arm h (add.r_assoc.swap1.ok O hO)
  · kanon_arm h (add.r_assoc.swap2.ok O hO)
  · kanon_arm h (add.r_assoc.swap1_swap2.ok O hO)

theorem add.r_default.main.ok : add.r_default.main.Stmt := kanon_proof% add.r_default.main

theorem add.r_default.proof : add.r_default.Stmt := by
  intro O hO v1 v2 res h
  simp only [add.r_default] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (add.r_default.main.ok O hO)

theorem sub.r_zero.main.ok : sub.r_zero.main.Stmt := kanon_proof% sub.r_zero.main

theorem sub.r_zero.proof : sub.r_zero.Stmt := by
  intro O hO v1 v2 res h
  simp only [sub.r_zero] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (sub.r_zero.main.ok O hO)

theorem sub.r_lits.main.ok : sub.r_lits.main.Stmt := kanon_proof% sub.r_lits.main

theorem sub.r_lits.proof : sub.r_lits.Stmt := by
  intro O hO v1 v2 res h
  simp only [sub.r_lits] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (sub.r_lits.main.ok O hO)

theorem sub.r_vars.main.ok : sub.r_vars.main.Stmt := kanon_proof% sub.r_vars.main

theorem sub.r_vars.proof : sub.r_vars.Stmt := by
  intro O hO v1 v2 res h
  simp only [sub.r_vars] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (sub.r_vars.main.ok O hO)

theorem sub.r_sub_left.main.ok : sub.r_sub_left.main.Stmt := kanon_proof% sub.r_sub_left.main

theorem sub.r_sub_left.proof : sub.r_sub_left.Stmt := by
  intro O hO v1 v2 res h
  simp only [sub.r_sub_left] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (sub.r_sub_left.main.ok O hO)

theorem sub.r_sub_right.main.ok : sub.r_sub_right.main.Stmt := kanon_proof% sub.r_sub_right.main

theorem sub.r_sub_right.proof : sub.r_sub_right.Stmt := by
  intro O hO v1 v2 res h
  simp only [sub.r_sub_right] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (sub.r_sub_right.main.ok O hO)

theorem sub.r_left_sub.main.ok : sub.r_left_sub.main.Stmt := kanon_proof% sub.r_left_sub.main

theorem sub.r_left_sub.proof : sub.r_left_sub.Stmt := by
  intro O hO v1 v2 res h
  simp only [sub.r_left_sub] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (sub.r_left_sub.main.ok O hO)

theorem sub.r_right_sub.main.ok : sub.r_right_sub.main.Stmt := kanon_proof% sub.r_right_sub.main

theorem sub.r_right_sub.proof : sub.r_right_sub.Stmt := by
  intro O hO v1 v2 res h
  simp only [sub.r_right_sub] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (sub.r_right_sub.main.ok O hO)

theorem sub.r_add_self.main.ok : sub.r_add_self.main.Stmt := kanon_proof% sub.r_add_self.main

theorem sub.r_add_self.swap.ok : sub.r_add_self.swap.Stmt := by
  intro O hO v2 y x t__4 hg
  exact Refinement.trans
    (by simp only [sub.spec, ty, Term.ty_mk]; kanon_comm)
    (sub.r_add_self.main.ok O hO v2 x y t__4 hg)

theorem sub.r_add_self.proof : sub.r_add_self.Stmt := by
  intro O hO v1 v2 res h
  simp only [sub.r_add_self] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (sub.r_add_self.main.ok O hO)
  · kanon_arm h (sub.r_add_self.swap.ok O hO)

theorem sub.r_self_add.main.ok : sub.r_self_add.main.Stmt := kanon_proof% sub.r_self_add.main

theorem sub.r_self_add.swap.ok : sub.r_self_add.swap.Stmt := by
  intro O hO v1 y kanon__3 t__5 hg
  exact Refinement.trans
    (by simp only [sub.spec, ty, Term.ty_mk]; kanon_comm)
    (sub.r_self_add.main.ok O hO v1 kanon__3 y t__5 hg)

theorem sub.r_self_add.proof : sub.r_self_add.Stmt := by
  intro O hO v1 v2 res h
  simp only [sub.r_self_add] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (sub.r_self_add.main.ok O hO)
  · kanon_arm h (sub.r_self_add.swap.ok O hO)

theorem sub.r_default.main.ok : sub.r_default.main.Stmt := kanon_proof% sub.r_default.main

theorem sub.r_default.proof : sub.r_default.Stmt := by
  intro O hO v1 v2 res h
  simp only [sub.r_default] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (sub.r_default.main.ok O hO)

theorem mul.r_zero.main.ok : mul.r_zero.main.Stmt := kanon_proof% mul.r_zero.main

theorem mul.r_zero.swap.ok : mul.r_zero.swap.Stmt := by
  intro O hO v1 kanon__1 t__2 hg
  exact Refinement.trans
    (by simp only [mul.spec, ty, Term.ty_mk]; kanon_comm)
    (mul.r_zero.main.ok O hO v1 kanon__1 t__2 hg)

theorem mul.r_zero.proof : mul.r_zero.Stmt := by
  intro O hO v1 v2 res h
  simp only [mul.r_zero] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (mul.r_zero.main.ok O hO)
  · kanon_arm h (mul.r_zero.swap.ok O hO)

theorem mul.r_one.main.ok : mul.r_one.main.Stmt := kanon_proof% mul.r_one.main

theorem mul.r_one.swap.ok : mul.r_one.swap.Stmt := by
  intro O hO v1 kanon__1 t__2 hg
  exact Refinement.trans
    (by simp only [mul.spec, ty, Term.ty_mk]; kanon_comm)
    (mul.r_one.main.ok O hO v1 kanon__1 t__2 hg)

theorem mul.r_one.proof : mul.r_one.Stmt := by
  intro O hO v1 v2 res h
  simp only [mul.r_one] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (mul.r_one.main.ok O hO)
  · kanon_arm h (mul.r_one.swap.ok O hO)

theorem mul.r_lits.main.ok : mul.r_lits.main.Stmt := kanon_proof% mul.r_lits.main

theorem mul.r_lits.proof : mul.r_lits.Stmt := by
  intro O hO v1 v2 res h
  simp only [mul.r_lits] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (mul.r_lits.main.ok O hO)

theorem mul.r_default.main.ok : mul.r_default.main.Stmt := kanon_proof% mul.r_default.main

theorem mul.r_default.proof : mul.r_default.Stmt := by
  intro O hO v1 v2 res h
  simp only [mul.r_default] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (mul.r_default.main.ok O hO)

theorem div.r_one.main.ok : div.r_one.main.Stmt := kanon_proof% div.r_one.main

theorem div.r_one.proof : div.r_one.Stmt := by
  intro O hO v1 v2 res h
  simp only [div.r_one] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (div.r_one.main.ok O hO)

theorem div.r_lits.main.ok : div.r_lits.main.Stmt := kanon_proof% div.r_lits.main

theorem div.r_lits.proof : div.r_lits.Stmt := by
  intro O hO v1 v2 res h
  simp only [div.r_lits] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (div.r_lits.main.ok O hO)

theorem div.r_mul.main.ok : div.r_mul.main.Stmt := kanon_proof% div.r_mul.main

theorem div.r_mul.swap.ok : div.r_mul.swap.Stmt := by
  intro O hO a t__4 x t__5 b t__8 hg
  exact Refinement.trans
    (by simp only [div.spec, ty, Term.ty_mk]; kanon_comm)
    (div.r_mul.main.ok O hO x a t__4 t__5 b t__8 hg)

theorem div.r_mul.proof : div.r_mul.Stmt := by
  intro O hO v1 v2 res h
  simp only [div.r_mul] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (div.r_mul.main.ok O hO)
  · kanon_arm h (div.r_mul.swap.ok O hO)

theorem div.r_default.main.ok : div.r_default.main.Stmt := kanon_proof% div.r_default.main

theorem div.r_default.proof : div.r_default.Stmt := by
  intro O hO v1 v2 res h
  simp only [div.r_default] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (div.r_default.main.ok O hO)

theorem rem.r_one.main.ok : rem.r_one.main.Stmt := kanon_proof% rem.r_one.main

theorem rem.r_one.proof : rem.r_one.Stmt := by
  intro O hO v1 v2 res h
  simp only [rem.r_one] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (rem.r_one.main.ok O hO)

theorem rem.r_multiple.main.ok : rem.r_multiple.main.Stmt := kanon_proof% rem.r_multiple.main

theorem rem.r_multiple.proof : rem.r_multiple.Stmt := by
  intro O hO v1 v2 res h
  simp only [rem.r_multiple] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (rem.r_multiple.main.ok O hO)

theorem rem.r_lits.main.ok : rem.r_lits.main.Stmt := kanon_proof% rem.r_lits.main

theorem rem.r_lits.proof : rem.r_lits.Stmt := by
  intro O hO v1 v2 res h
  simp only [rem.r_lits] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (rem.r_lits.main.ok O hO)

theorem rem.r_mul.main.ok : rem.r_mul.main.Stmt := kanon_proof% rem.r_mul.main

theorem rem.r_mul.swap2.ok : rem.r_mul.swap2.Stmt := by
  intro O hO x n t__4 t__5 m t__10 y t__11 hg
  exact Refinement.trans
    (by simp only [rem.spec, ty, Term.ty_mk]; kanon_comm)
    (rem.r_mul.main.ok O hO x n t__4 t__5 y m t__10 t__11 hg)

theorem rem.r_mul.swap1.ok : rem.r_mul.swap1.Stmt := by
  intro O hO n t__4 x t__5 y m t__10 t__11 hg
  exact Refinement.trans
    (by simp only [rem.spec, ty, Term.ty_mk]; kanon_comm)
    (rem.r_mul.main.ok O hO x n t__4 t__5 y m t__10 t__11 hg)

theorem rem.r_mul.swap1_swap2.ok : rem.r_mul.swap1_swap2.Stmt := by
  intro O hO n t__4 x t__5 m t__10 y t__11 hg
  exact Refinement.trans
    (by simp only [rem.spec, ty, Term.ty_mk]; kanon_comm)
    (rem.r_mul.main.ok O hO x n t__4 t__5 y m t__10 t__11 hg)

theorem rem.r_mul.proof : rem.r_mul.Stmt := by
  intro O hO v1 v2 res h
  simp only [rem.r_mul] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (rem.r_mul.main.ok O hO)
  · kanon_arm h (rem.r_mul.swap2.ok O hO)
  · kanon_arm h (rem.r_mul.swap1.ok O hO)
  · kanon_arm h (rem.r_mul.swap1_swap2.ok O hO)

theorem rem.r_default.main.ok : rem.r_default.main.Stmt := kanon_proof% rem.r_default.main

theorem rem.r_default.proof : rem.r_default.Stmt := by
  intro O hO v1 v2 res h
  simp only [rem.r_default] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (rem.r_default.main.ok O hO)

theorem mod_.r_one.main.ok : mod_.r_one.main.Stmt := kanon_proof% mod_.r_one.main

theorem mod_.r_one.proof : mod_.r_one.Stmt := by
  intro O hO v1 v2 res h
  simp only [mod_.r_one] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (mod_.r_one.main.ok O hO)

theorem mod_.r_multiple.main.ok : mod_.r_multiple.main.Stmt := kanon_proof% mod_.r_multiple.main

theorem mod_.r_multiple.proof : mod_.r_multiple.Stmt := by
  intro O hO v1 v2 res h
  simp only [mod_.r_multiple] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (mod_.r_multiple.main.ok O hO)

theorem mod_.r_lits.main.ok : mod_.r_lits.main.Stmt := kanon_proof% mod_.r_lits.main

theorem mod_.r_lits.proof : mod_.r_lits.Stmt := by
  intro O hO v1 v2 res h
  simp only [mod_.r_lits] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (mod_.r_lits.main.ok O hO)

theorem mod_.r_mod_mod.main.ok : mod_.r_mod_mod.main.Stmt := kanon_proof% mod_.r_mod_mod.main

theorem mod_.r_mod_mod.proof : mod_.r_mod_mod.Stmt := by
  intro O hO v1 v2 res h
  simp only [mod_.r_mod_mod] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (mod_.r_mod_mod.main.ok O hO)

theorem mod_.r_add_mod.main.ok : mod_.r_add_mod.main.Stmt := kanon_proof% mod_.r_add_mod.main

theorem mod_.r_add_mod.swap.ok : mod_.r_add_mod.swap.Stmt := by
  intro O hO y a t__6 t__7 x t__8 b t__11 hg
  exact Refinement.trans
    (by simp only [mod_.spec, ty, Term.ty_mk]; kanon_comm)
    (mod_.r_add_mod.main.ok O hO x y a t__6 t__7 t__8 b t__11 hg)

theorem mod_.r_add_mod.proof : mod_.r_add_mod.Stmt := by
  intro O hO v1 v2 res h
  simp only [mod_.r_add_mod] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (mod_.r_add_mod.main.ok O hO)
  · kanon_arm h (mod_.r_add_mod.swap.ok O hO)

theorem mod_.r_default.main.ok : mod_.r_default.main.Stmt := kanon_proof% mod_.r_default.main

theorem mod_.r_default.proof : mod_.r_default.Stmt := by
  intro O hO v1 v2 res h
  simp only [mod_.r_default] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (mod_.r_default.main.ok O hO)

theorem neg.r_lit.main.ok : neg.r_lit.main.Stmt := kanon_proof% neg.r_lit.main

theorem neg.r_lit.proof : neg.r_lit.Stmt := by
  intro O hO v res h
  simp only [neg.r_lit] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (neg.r_lit.main.ok O hO)

theorem neg.r_default.main.ok : neg.r_default.main.Stmt := kanon_proof% neg.r_default.main

theorem neg.r_default.proof : neg.r_default.Stmt := by
  intro O hO v res h
  simp only [neg.r_default] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (neg.r_default.main.ok O hO)

theorem lt.r_lits.main.ok : lt.r_lits.main.Stmt := kanon_proof% lt.r_lits.main

theorem lt.r_lits.proof : lt.r_lits.Stmt := by
  intro O hO v1 v2 res h
  simp only [lt.r_lits] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (lt.r_lits.main.ok O hO)

theorem lt.r_same.main.ok : lt.r_same.main.Stmt := kanon_proof% lt.r_same.main

theorem lt.r_same.proof : lt.r_same.Stmt := by
  intro O hO v1 v2 res h
  simp only [lt.r_same] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (lt.r_same.main.ok O hO)

theorem lt.r_self_add.main.ok : lt.r_self_add.main.Stmt := kanon_proof% lt.r_self_add.main

theorem lt.r_self_add.swap.ok : lt.r_self_add.swap.Stmt := by
  intro O hO v1 y kanon__3 t__5 hg
  exact Refinement.trans
    (by simp only [lt.spec, ty, Term.ty_mk]; kanon_comm)
    (lt.r_self_add.main.ok O hO v1 kanon__3 y t__5 hg)

theorem lt.r_self_add.proof : lt.r_self_add.Stmt := by
  intro O hO v1 v2 res h
  simp only [lt.r_self_add] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (lt.r_self_add.main.ok O hO)
  · kanon_arm h (lt.r_self_add.swap.ok O hO)

theorem lt.r_add_self.main.ok : lt.r_add_self.main.Stmt := kanon_proof% lt.r_add_self.main

theorem lt.r_add_self.swap.ok : lt.r_add_self.swap.Stmt := by
  intro O hO v2 y x t__4 hg
  exact Refinement.trans
    (by simp only [lt.spec, ty, Term.ty_mk]; kanon_comm)
    (lt.r_add_self.main.ok O hO v2 x y t__4 hg)

theorem lt.r_add_self.proof : lt.r_add_self.Stmt := by
  intro O hO v1 v2 res h
  simp only [lt.r_add_self] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (lt.r_add_self.main.ok O hO)
  · kanon_arm h (lt.r_add_self.swap.ok O hO)

theorem lt.r_add_add.main.ok : lt.r_add_add.main.Stmt := kanon_proof% lt.r_add_add.main

theorem lt.r_add_add.swap2.ok : lt.r_add_add.swap2.Stmt := by
  intro O hO a x t__4 y kanon__7 t__9 hg
  exact Refinement.trans
    (by simp only [lt.spec, ty, Term.ty_mk]; kanon_comm)
    (lt.r_add_add.main.ok O hO a x t__4 kanon__7 y t__9 hg)

theorem lt.r_add_add.swap1.ok : lt.r_add_add.swap1.Stmt := by
  intro O hO x a t__4 kanon__7 y t__9 hg
  exact Refinement.trans
    (by simp only [lt.spec, ty, Term.ty_mk]; kanon_comm)
    (lt.r_add_add.main.ok O hO a x t__4 kanon__7 y t__9 hg)

theorem lt.r_add_add.swap1_swap2.ok : lt.r_add_add.swap1_swap2.Stmt := by
  intro O hO x a t__4 y kanon__7 t__9 hg
  exact Refinement.trans
    (by simp only [lt.spec, ty, Term.ty_mk]; kanon_comm)
    (lt.r_add_add.main.ok O hO a x t__4 kanon__7 y t__9 hg)

theorem lt.r_add_add.proof : lt.r_add_add.Stmt := by
  intro O hO v1 v2 res h
  simp only [lt.r_add_add] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (lt.r_add_add.main.ok O hO)
  · kanon_arm h (lt.r_add_add.swap2.ok O hO)
  · kanon_arm h (lt.r_add_add.swap1.ok O hO)
  · kanon_arm h (lt.r_add_add.swap1_swap2.ok O hO)

theorem lt.r_add_const.main.ok : lt.r_add_const.main.Stmt := kanon_proof% lt.r_add_const.main

theorem lt.r_add_const.swap.ok : lt.r_add_const.swap.Stmt := by
  intro O hO a t__4 v t__5 b t__8
  exact Refinement.trans
    (by simp only [lt.spec, ty, Term.ty_mk]; kanon_comm)
    (lt.r_add_const.main.ok O hO v a t__4 t__5 b t__8)

theorem lt.r_add_const.proof : lt.r_add_const.Stmt := by
  intro O hO v1 v2 res h
  simp only [lt.r_add_const] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (lt.r_add_const.main.ok O hO)
  · kanon_arm h (lt.r_add_const.swap.ok O hO)

theorem lt.r_const_add.main.ok : lt.r_const_add.main.Stmt := kanon_proof% lt.r_const_add.main

theorem lt.r_const_add.swap.ok : lt.r_const_add.swap.Stmt := by
  intro O hO b t__2 a t__6 v t__7
  exact Refinement.trans
    (by simp only [lt.spec, ty, Term.ty_mk]; kanon_comm)
    (lt.r_const_add.main.ok O hO b t__2 v a t__6 t__7)

theorem lt.r_const_add.proof : lt.r_const_add.Stmt := by
  intro O hO v1 v2 res h
  simp only [lt.r_const_add] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (lt.r_const_add.main.ok O hO)
  · kanon_arm h (lt.r_const_add.swap.ok O hO)

theorem lt.r_sub_const.main.ok : lt.r_sub_const.main.Stmt := kanon_proof% lt.r_sub_const.main

theorem lt.r_sub_const.proof : lt.r_sub_const.Stmt := by
  intro O hO v1 v2 res h
  simp only [lt.r_sub_const] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (lt.r_sub_const.main.ok O hO)

theorem lt.r_rsub_const.main.ok : lt.r_rsub_const.main.Stmt := kanon_proof% lt.r_rsub_const.main

theorem lt.r_rsub_const.proof : lt.r_rsub_const.Stmt := by
  intro O hO v1 v2 res h
  simp only [lt.r_rsub_const] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (lt.r_rsub_const.main.ok O hO)

theorem lt.r_const_sub.main.ok : lt.r_const_sub.main.Stmt := kanon_proof% lt.r_const_sub.main

theorem lt.r_const_sub.proof : lt.r_const_sub.Stmt := by
  intro O hO v1 v2 res h
  simp only [lt.r_const_sub] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (lt.r_const_sub.main.ok O hO)

theorem lt.r_const_rsub.main.ok : lt.r_const_rsub.main.Stmt := kanon_proof% lt.r_const_rsub.main

theorem lt.r_const_rsub.proof : lt.r_const_rsub.Stmt := by
  intro O hO v1 v2 res h
  simp only [lt.r_const_rsub] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (lt.r_const_rsub.main.ok O hO)

theorem lt.r_const_mul.main.ok : lt.r_const_mul.main.Stmt := kanon_proof% lt.r_const_mul.main

theorem lt.r_const_mul.swap.ok : lt.r_const_mul.swap.Stmt := by
  intro O hO b t__2 v a t__5 t__7
  exact Refinement.trans
    (by simp only [lt.spec, ty, Term.ty_mk]; kanon_comm)
    (lt.r_const_mul.main.ok O hO b t__2 a t__5 v t__7)

theorem lt.r_const_mul.proof : lt.r_const_mul.Stmt := by
  intro O hO v1 v2 res h
  simp only [lt.r_const_mul] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (lt.r_const_mul.main.ok O hO)
  · kanon_arm h (lt.r_const_mul.swap.ok O hO)

theorem lt.r_mul_const.main.ok : lt.r_mul_const.main.Stmt := kanon_proof% lt.r_mul_const.main

theorem lt.r_mul_const.swap.ok : lt.r_mul_const.swap.Stmt := by
  intro O hO a t__4 v t__5 b t__8
  exact Refinement.trans
    (by simp only [lt.spec, ty, Term.ty_mk]; kanon_comm)
    (lt.r_mul_const.main.ok O hO v a t__4 t__5 b t__8)

theorem lt.r_mul_const.proof : lt.r_mul_const.Stmt := by
  intro O hO v1 v2 res h
  simp only [lt.r_mul_const] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (lt.r_mul_const.main.ok O hO)
  · kanon_arm h (lt.r_mul_const.swap.ok O hO)

theorem lt.r_mod_const.mod.ok : lt.r_mod_const.mod.Stmt := kanon_proof% lt.r_mod_const.mod

theorem lt.r_mod_const.rem.ok : lt.r_mod_const.rem.Stmt := kanon_proof% lt.r_mod_const.rem

theorem lt.r_mod_const.proof : lt.r_mod_const.Stmt := by
  intro O hO v1 v2 res h
  simp only [lt.r_mod_const] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (lt.r_mod_const.mod.ok O hO)
  · kanon_arm h (lt.r_mod_const.rem.ok O hO)

theorem lt.r_const_mod.mod.ok : lt.r_const_mod.mod.Stmt := kanon_proof% lt.r_const_mod.mod

theorem lt.r_const_mod.rem.ok : lt.r_const_mod.rem.Stmt := kanon_proof% lt.r_const_mod.rem

theorem lt.r_const_mod.proof : lt.r_const_mod.Stmt := by
  intro O hO v1 v2 res h
  simp only [lt.r_const_mod] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (lt.r_const_mod.mod.ok O hO)
  · kanon_arm h (lt.r_const_mod.rem.ok O hO)

theorem lt.r_const_ite.main.ok : lt.r_const_ite.main.Stmt := kanon_proof% lt.r_const_ite.main

theorem lt.r_const_ite.proof : lt.r_const_ite.Stmt := by
  intro O hO v1 v2 res h
  simp only [lt.r_const_ite] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (lt.r_const_ite.main.ok O hO)

theorem lt.r_ite_const.main.ok : lt.r_ite_const.main.Stmt := kanon_proof% lt.r_ite_const.main

theorem lt.r_ite_const.proof : lt.r_ite_const.Stmt := by
  intro O hO v1 v2 res h
  simp only [lt.r_ite_const] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (lt.r_ite_const.main.ok O hO)

theorem lt.r_default.main.ok : lt.r_default.main.Stmt := kanon_proof% lt.r_default.main

theorem lt.r_default.proof : lt.r_default.Stmt := by
  intro O hO v1 v2 res h
  simp only [lt.r_default] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (lt.r_default.main.ok O hO)

theorem leq.r_lits.main.ok : leq.r_lits.main.Stmt := kanon_proof% leq.r_lits.main

theorem leq.r_lits.proof : leq.r_lits.Stmt := by
  intro O hO v1 v2 res h
  simp only [leq.r_lits] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (leq.r_lits.main.ok O hO)

theorem leq.r_same.main.ok : leq.r_same.main.Stmt := kanon_proof% leq.r_same.main

theorem leq.r_same.proof : leq.r_same.Stmt := by
  intro O hO v1 v2 res h
  simp only [leq.r_same] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (leq.r_same.main.ok O hO)

theorem leq.r_self_add.main.ok : leq.r_self_add.main.Stmt := kanon_proof% leq.r_self_add.main

theorem leq.r_self_add.swap.ok : leq.r_self_add.swap.Stmt := by
  intro O hO v1 y kanon__3 t__5 hg
  exact Refinement.trans
    (by simp only [leq.spec, ty, Term.ty_mk]; kanon_comm)
    (leq.r_self_add.main.ok O hO v1 kanon__3 y t__5 hg)

theorem leq.r_self_add.proof : leq.r_self_add.Stmt := by
  intro O hO v1 v2 res h
  simp only [leq.r_self_add] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (leq.r_self_add.main.ok O hO)
  · kanon_arm h (leq.r_self_add.swap.ok O hO)

theorem leq.r_add_add.main.ok : leq.r_add_add.main.Stmt := kanon_proof% leq.r_add_add.main

theorem leq.r_add_add.swap2.ok : leq.r_add_add.swap2.Stmt := by
  intro O hO a x t__4 y kanon__7 t__9 hg
  exact Refinement.trans
    (by simp only [leq.spec, ty, Term.ty_mk]; kanon_comm)
    (leq.r_add_add.main.ok O hO a x t__4 kanon__7 y t__9 hg)

theorem leq.r_add_add.swap1.ok : leq.r_add_add.swap1.Stmt := by
  intro O hO x a t__4 kanon__7 y t__9 hg
  exact Refinement.trans
    (by simp only [leq.spec, ty, Term.ty_mk]; kanon_comm)
    (leq.r_add_add.main.ok O hO a x t__4 kanon__7 y t__9 hg)

theorem leq.r_add_add.swap1_swap2.ok : leq.r_add_add.swap1_swap2.Stmt := by
  intro O hO x a t__4 y kanon__7 t__9 hg
  exact Refinement.trans
    (by simp only [leq.spec, ty, Term.ty_mk]; kanon_comm)
    (leq.r_add_add.main.ok O hO a x t__4 kanon__7 y t__9 hg)

theorem leq.r_add_add.proof : leq.r_add_add.Stmt := by
  intro O hO v1 v2 res h
  simp only [leq.r_add_add] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (leq.r_add_add.main.ok O hO)
  · kanon_arm h (leq.r_add_add.swap2.ok O hO)
  · kanon_arm h (leq.r_add_add.swap1.ok O hO)
  · kanon_arm h (leq.r_add_add.swap1_swap2.ok O hO)

theorem leq.r_add_const.main.ok : leq.r_add_const.main.Stmt := kanon_proof% leq.r_add_const.main

theorem leq.r_add_const.swap.ok : leq.r_add_const.swap.Stmt := by
  intro O hO a t__4 v t__5 b t__8
  exact Refinement.trans
    (by simp only [leq.spec, ty, Term.ty_mk]; kanon_comm)
    (leq.r_add_const.main.ok O hO v a t__4 t__5 b t__8)

theorem leq.r_add_const.proof : leq.r_add_const.Stmt := by
  intro O hO v1 v2 res h
  simp only [leq.r_add_const] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (leq.r_add_const.main.ok O hO)
  · kanon_arm h (leq.r_add_const.swap.ok O hO)

theorem leq.r_const_add.main.ok : leq.r_const_add.main.Stmt := kanon_proof% leq.r_const_add.main

theorem leq.r_const_add.swap.ok : leq.r_const_add.swap.Stmt := by
  intro O hO b t__2 a t__6 v t__7
  exact Refinement.trans
    (by simp only [leq.spec, ty, Term.ty_mk]; kanon_comm)
    (leq.r_const_add.main.ok O hO b t__2 v a t__6 t__7)

theorem leq.r_const_add.proof : leq.r_const_add.Stmt := by
  intro O hO v1 v2 res h
  simp only [leq.r_const_add] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (leq.r_const_add.main.ok O hO)
  · kanon_arm h (leq.r_const_add.swap.ok O hO)

theorem leq.r_sub_const.main.ok : leq.r_sub_const.main.Stmt := kanon_proof% leq.r_sub_const.main

theorem leq.r_sub_const.proof : leq.r_sub_const.Stmt := by
  intro O hO v1 v2 res h
  simp only [leq.r_sub_const] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (leq.r_sub_const.main.ok O hO)

theorem leq.r_rsub_const.main.ok : leq.r_rsub_const.main.Stmt := kanon_proof% leq.r_rsub_const.main

theorem leq.r_rsub_const.proof : leq.r_rsub_const.Stmt := by
  intro O hO v1 v2 res h
  simp only [leq.r_rsub_const] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (leq.r_rsub_const.main.ok O hO)

theorem leq.r_const_sub.main.ok : leq.r_const_sub.main.Stmt := kanon_proof% leq.r_const_sub.main

theorem leq.r_const_sub.proof : leq.r_const_sub.Stmt := by
  intro O hO v1 v2 res h
  simp only [leq.r_const_sub] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (leq.r_const_sub.main.ok O hO)

theorem leq.r_const_rsub.main.ok : leq.r_const_rsub.main.Stmt := kanon_proof% leq.r_const_rsub.main

theorem leq.r_const_rsub.proof : leq.r_const_rsub.Stmt := by
  intro O hO v1 v2 res h
  simp only [leq.r_const_rsub] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (leq.r_const_rsub.main.ok O hO)

theorem leq.r_const_mul.main.ok : leq.r_const_mul.main.Stmt := kanon_proof% leq.r_const_mul.main

theorem leq.r_const_mul.swap.ok : leq.r_const_mul.swap.Stmt := by
  intro O hO b t__2 v a t__5 t__7
  exact Refinement.trans
    (by simp only [leq.spec, ty, Term.ty_mk]; kanon_comm)
    (leq.r_const_mul.main.ok O hO b t__2 a t__5 v t__7)

theorem leq.r_const_mul.proof : leq.r_const_mul.Stmt := by
  intro O hO v1 v2 res h
  simp only [leq.r_const_mul] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (leq.r_const_mul.main.ok O hO)
  · kanon_arm h (leq.r_const_mul.swap.ok O hO)

theorem leq.r_mul_const.main.ok : leq.r_mul_const.main.Stmt := kanon_proof% leq.r_mul_const.main

theorem leq.r_mul_const.swap.ok : leq.r_mul_const.swap.Stmt := by
  intro O hO a t__4 v t__5 b t__8
  exact Refinement.trans
    (by simp only [leq.spec, ty, Term.ty_mk]; kanon_comm)
    (leq.r_mul_const.main.ok O hO v a t__4 t__5 b t__8)

theorem leq.r_mul_const.proof : leq.r_mul_const.Stmt := by
  intro O hO v1 v2 res h
  simp only [leq.r_mul_const] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (leq.r_mul_const.main.ok O hO)
  · kanon_arm h (leq.r_mul_const.swap.ok O hO)

theorem leq.r_mod_const.mod.ok : leq.r_mod_const.mod.Stmt := kanon_proof% leq.r_mod_const.mod

theorem leq.r_mod_const.rem.ok : leq.r_mod_const.rem.Stmt := kanon_proof% leq.r_mod_const.rem

theorem leq.r_mod_const.proof : leq.r_mod_const.Stmt := by
  intro O hO v1 v2 res h
  simp only [leq.r_mod_const] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (leq.r_mod_const.mod.ok O hO)
  · kanon_arm h (leq.r_mod_const.rem.ok O hO)

theorem leq.r_const_rem.main.ok : leq.r_const_rem.main.Stmt := kanon_proof% leq.r_const_rem.main

theorem leq.r_const_rem.proof : leq.r_const_rem.Stmt := by
  intro O hO v1 v2 res h
  simp only [leq.r_const_rem] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (leq.r_const_rem.main.ok O hO)

theorem leq.r_const_mod.main.ok : leq.r_const_mod.main.Stmt := kanon_proof% leq.r_const_mod.main

theorem leq.r_const_mod.proof : leq.r_const_mod.Stmt := by
  intro O hO v1 v2 res h
  simp only [leq.r_const_mod] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (leq.r_const_mod.main.ok O hO)

theorem leq.r_const_ite.main.ok : leq.r_const_ite.main.Stmt := kanon_proof% leq.r_const_ite.main

theorem leq.r_const_ite.proof : leq.r_const_ite.Stmt := by
  intro O hO v1 v2 res h
  simp only [leq.r_const_ite] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (leq.r_const_ite.main.ok O hO)

theorem leq.r_ite_const.main.ok : leq.r_ite_const.main.Stmt := kanon_proof% leq.r_ite_const.main

theorem leq.r_ite_const.proof : leq.r_ite_const.Stmt := by
  intro O hO v1 v2 res h
  simp only [leq.r_ite_const] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (leq.r_ite_const.main.ok O hO)

theorem leq.r_default.main.ok : leq.r_default.main.Stmt := kanon_proof% leq.r_default.main

theorem leq.r_default.proof : leq.r_default.Stmt := by
  intro O hO v1 v2 res h
  simp only [leq.r_default] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (leq.r_default.main.ok O hO)

theorem b_and.step_sound (O : Ops) (hO : O.Sound) (v1 : Term) (v2 : Term) :
  Refines (b_and.spec v1 v2) (b_and.step O v1 v2) := by
  unfold b_and.step
  refine Refinement.firstSome_cons (fun res h => b_and.r_same.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => b_and.r_false_.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => b_and.r_true_.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => b_and.r_not.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => b_and.r_and_.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => b_and.r_or_.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => b_and.r_eq_neq.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => b_and.r_default.proof O hO v1 v2 res h) ?_
  exact Refinement.firstSome_nil

theorem b_or.step_sound (O : Ops) (hO : O.Sound) (v1 : Term) (v2 : Term) :
  Refines (b_or.spec v1 v2) (b_or.step O v1 v2) := by
  unfold b_or.step
  refine Refinement.firstSome_cons (fun res h => b_or.r_same.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => b_or.r_true_.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => b_or.r_false_.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => b_or.r_not.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => b_or.r_or_.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => b_or.r_and_.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => b_or.r_default.proof O hO v1 v2 res h) ?_
  exact Refinement.firstSome_nil

theorem b_not.step_sound (O : Ops) (hO : O.Sound) (sv : Term) :
  Refines (b_not.spec sv) (b_not.step O sv) := by
  unfold b_not.step
  refine Refinement.firstSome_cons (fun res h => b_not.r_true_.proof O hO sv res h) ?_
  refine Refinement.firstSome_cons (fun res h => b_not.r_false_.proof O hO sv res h) ?_
  refine Refinement.firstSome_cons (fun res h => b_not.r_not.proof O hO sv res h) ?_
  refine Refinement.firstSome_cons (fun res h => b_not.r_or_.proof O hO sv res h) ?_
  refine Refinement.firstSome_cons (fun res h => b_not.r_and_.proof O hO sv res h) ?_
  refine Refinement.firstSome_cons (fun res h => b_not.r_ite.proof O hO sv res h) ?_
  refine Refinement.firstSome_cons (fun res h => b_not.r_distinct.proof O hO sv res h) ?_
  refine Refinement.firstSome_cons (fun res h => b_not.r_lt.proof O hO sv res h) ?_
  refine Refinement.firstSome_cons (fun res h => b_not.r_leq.proof O hO sv res h) ?_
  refine Refinement.firstSome_cons (fun res h => b_not.r_default.proof O hO sv res h) ?_
  exact Refinement.firstSome_nil

theorem b_ite.step_sound (O : Ops) (hO : O.Sound) (guard : Term) (if_ : Term) (else_ : Term) :
  Refines (b_ite.spec guard if_ else_) (b_ite.step O guard if_ else_) := by
  unfold b_ite.step
  refine Refinement.firstSome_cons (fun res h => b_ite.r_true_.proof O hO guard if_ else_ res h) ?_
  refine Refinement.firstSome_cons (fun res h => b_ite.r_false_.proof O hO guard if_ else_ res h) ?_
  refine Refinement.firstSome_cons (fun res h => b_ite.r_bool.proof O hO guard if_ else_ res h) ?_
  refine Refinement.firstSome_cons (fun res h => b_ite.r_not_bool.proof O hO guard if_ else_ res h) ?_
  refine Refinement.firstSome_cons (fun res h => b_ite.r_false_then.proof O hO guard if_ else_ res h) ?_
  refine Refinement.firstSome_cons (fun res h => b_ite.r_true_then.proof O hO guard if_ else_ res h) ?_
  refine Refinement.firstSome_cons (fun res h => b_ite.r_false_else.proof O hO guard if_ else_ res h) ?_
  refine Refinement.firstSome_cons (fun res h => b_ite.r_true_else.proof O hO guard if_ else_ res h) ?_
  refine Refinement.firstSome_cons (fun res h => b_ite.r_not_guard.proof O hO guard if_ else_ res h) ?_
  refine Refinement.firstSome_cons (fun res h => b_ite.r_guard_then.proof O hO guard if_ else_ res h) ?_
  refine Refinement.firstSome_cons (fun res h => b_ite.r_guard_else.proof O hO guard if_ else_ res h) ?_
  refine Refinement.firstSome_cons (fun res h => b_ite.r_ite_then.proof O hO guard if_ else_ res h) ?_
  refine Refinement.firstSome_cons (fun res h => b_ite.r_ite_else.proof O hO guard if_ else_ res h) ?_
  refine Refinement.firstSome_cons (fun res h => b_ite.r_and_ite_then.proof O hO guard if_ else_ res h) ?_
  refine Refinement.firstSome_cons (fun res h => b_ite.r_or_ite_else.proof O hO guard if_ else_ res h) ?_
  refine Refinement.firstSome_cons (fun res h => b_ite.r_same.proof O hO guard if_ else_ res h) ?_
  refine Refinement.firstSome_cons (fun res h => b_ite.r_default.proof O hO guard if_ else_ res h) ?_
  exact Refinement.firstSome_nil

theorem sem_eq.step_sound (O : Ops) (hO : O.Sound) (v1 : Term) (v2 : Term) :
  Refines (sem_eq.spec v1 v2) (sem_eq.step O v1 v2) := by
  unfold sem_eq.step
  refine Refinement.firstSome_cons (fun res h => sem_eq.r_same.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => sem_eq.r_bools.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => sem_eq.r_ite_ite.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => sem_eq.r_false_.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => sem_eq.r_true_.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => sem_eq.r_nots.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => sem_eq.r_ints.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => sem_eq.r_add_self.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => sem_eq.r_add_add.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => sem_eq.r_add_const.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => sem_eq.r_sub_const.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => sem_eq.r_mul_const.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => sem_eq.r_default.proof O hO v1 v2 res h) ?_
  exact Refinement.firstSome_nil

theorem sem_eq_untyped.step_sound (O : Ops) (hO : O.Sound) (v1 : Term) (v2 : Term) :
  Refines (sem_eq_untyped.spec v1 v2) (sem_eq_untyped.step O v1 v2) := by
  unfold sem_eq_untyped.step
  refine Refinement.firstSome_cons (fun res h => sem_eq_untyped.r_ill_typed.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => sem_eq_untyped.r_typed.proof O hO v1 v2 res h) ?_
  exact Refinement.firstSome_nil

theorem b_distinct.step_sound (O : Ops) (hO : O.Sound) (l : (List Term)) :
  Refines (b_distinct.spec l) (b_distinct.step O l) := by
  unfold b_distinct.step
  refine Refinement.firstSome_cons (fun res h => b_distinct.r_small.proof O hO l res h) ?_
  refine Refinement.firstSome_cons (fun res h => b_distinct.r_distinct.proof O hO l res h) ?_
  refine Refinement.firstSome_cons (fun res h => b_distinct.r_not_distinct.proof O hO l res h) ?_
  refine Refinement.firstSome_cons (fun res h => b_distinct.r_default.proof O hO l res h) ?_
  exact Refinement.firstSome_nil

theorem add.step_sound (O : Ops) (hO : O.Sound) (v1 : Term) (v2 : Term) :
  Refines (add.spec v1 v2) (add.step O v1 v2) := by
  unfold add.step
  refine Refinement.firstSome_cons (fun res h => add.r_zero.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => add.r_lits.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => add.r_assoc.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => add.r_default.proof O hO v1 v2 res h) ?_
  exact Refinement.firstSome_nil

theorem sub.step_sound (O : Ops) (hO : O.Sound) (v1 : Term) (v2 : Term) :
  Refines (sub.spec v1 v2) (sub.step O v1 v2) := by
  unfold sub.step
  refine Refinement.firstSome_cons (fun res h => sub.r_zero.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => sub.r_lits.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => sub.r_vars.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => sub.r_sub_left.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => sub.r_sub_right.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => sub.r_left_sub.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => sub.r_right_sub.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => sub.r_add_self.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => sub.r_self_add.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => sub.r_default.proof O hO v1 v2 res h) ?_
  exact Refinement.firstSome_nil

theorem mul.step_sound (O : Ops) (hO : O.Sound) (v1 : Term) (v2 : Term) :
  Refines (mul.spec v1 v2) (mul.step O v1 v2) := by
  unfold mul.step
  refine Refinement.firstSome_cons (fun res h => mul.r_zero.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => mul.r_one.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => mul.r_lits.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => mul.r_default.proof O hO v1 v2 res h) ?_
  exact Refinement.firstSome_nil

theorem div.step_sound (O : Ops) (hO : O.Sound) (v1 : Term) (v2 : Term) :
  Refines (div.spec v1 v2) (div.step O v1 v2) := by
  unfold div.step
  refine Refinement.firstSome_cons (fun res h => div.r_one.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => div.r_lits.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => div.r_mul.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => div.r_default.proof O hO v1 v2 res h) ?_
  exact Refinement.firstSome_nil

theorem rem.step_sound (O : Ops) (hO : O.Sound) (v1 : Term) (v2 : Term) :
  Refines (rem.spec v1 v2) (rem.step O v1 v2) := by
  unfold rem.step
  refine Refinement.firstSome_cons (fun res h => rem.r_one.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => rem.r_multiple.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => rem.r_lits.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => rem.r_mul.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => rem.r_default.proof O hO v1 v2 res h) ?_
  exact Refinement.firstSome_nil

theorem mod_.step_sound (O : Ops) (hO : O.Sound) (v1 : Term) (v2 : Term) :
  Refines (mod_.spec v1 v2) (mod_.step O v1 v2) := by
  unfold mod_.step
  refine Refinement.firstSome_cons (fun res h => mod_.r_one.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => mod_.r_multiple.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => mod_.r_lits.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => mod_.r_mod_mod.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => mod_.r_add_mod.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => mod_.r_default.proof O hO v1 v2 res h) ?_
  exact Refinement.firstSome_nil

theorem neg.step_sound (O : Ops) (hO : O.Sound) (v : Term) :
  Refines (neg.spec v) (neg.step O v) := by
  unfold neg.step
  refine Refinement.firstSome_cons (fun res h => neg.r_lit.proof O hO v res h) ?_
  refine Refinement.firstSome_cons (fun res h => neg.r_default.proof O hO v res h) ?_
  exact Refinement.firstSome_nil

theorem lt.step_sound (O : Ops) (hO : O.Sound) (v1 : Term) (v2 : Term) :
  Refines (lt.spec v1 v2) (lt.step O v1 v2) := by
  unfold lt.step
  refine Refinement.firstSome_cons (fun res h => lt.r_lits.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => lt.r_same.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => lt.r_self_add.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => lt.r_add_self.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => lt.r_add_add.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => lt.r_add_const.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => lt.r_const_add.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => lt.r_sub_const.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => lt.r_rsub_const.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => lt.r_const_sub.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => lt.r_const_rsub.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => lt.r_const_mul.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => lt.r_mul_const.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => lt.r_mod_const.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => lt.r_const_mod.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => lt.r_const_ite.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => lt.r_ite_const.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => lt.r_default.proof O hO v1 v2 res h) ?_
  exact Refinement.firstSome_nil

theorem leq.step_sound (O : Ops) (hO : O.Sound) (v1 : Term) (v2 : Term) :
  Refines (leq.spec v1 v2) (leq.step O v1 v2) := by
  unfold leq.step
  refine Refinement.firstSome_cons (fun res h => leq.r_lits.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => leq.r_same.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => leq.r_self_add.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => leq.r_add_add.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => leq.r_add_const.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => leq.r_const_add.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => leq.r_sub_const.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => leq.r_rsub_const.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => leq.r_const_sub.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => leq.r_const_rsub.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => leq.r_const_mul.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => leq.r_mul_const.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => leq.r_mod_const.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => leq.r_const_rem.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => leq.r_const_mod.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => leq.r_const_ite.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => leq.r_ite_const.proof O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => leq.r_default.proof O hO v1 v2 res h) ?_
  exact Refinement.firstSome_nil

/-- Every rule function refines its spec, for any amount of fuel. -/
  theorem opsN_sound (orc : Oracle) (h : orc.Compat) :
  ∀ n, (opsN orc n).Sound
  | 0 =>
    { orc := h,
      b_and := fun v1 v2 => Refinement.refl,
      b_or := fun v1 v2 => Refinement.refl,
      b_not := fun sv => Refinement.refl,
      b_ite := fun guard if_ else_ => Refinement.refl,
      sem_eq := fun v1 v2 => Refinement.refl,
      sem_eq_untyped := fun v1 v2 => Refinement.refl,
      b_distinct := fun l => Refinement.refl,
      add := fun v1 v2 => Refinement.refl,
      sub := fun v1 v2 => Refinement.refl,
      mul := fun v1 v2 => Refinement.refl,
      div := fun v1 v2 => Refinement.refl,
      rem := fun v1 v2 => Refinement.refl,
      mod_ := fun v1 v2 => Refinement.refl,
      neg := fun v => Refinement.refl,
      lt := fun v1 v2 => Refinement.refl,
      leq := fun v1 v2 => Refinement.refl }
  | n + 1 =>
    have hO := opsN_sound orc h n
    { orc := hO.orc,
      b_and := b_and.step_sound _ hO,
      b_or := b_or.step_sound _ hO,
      b_not := b_not.step_sound _ hO,
      b_ite := b_ite.step_sound _ hO,
      sem_eq := sem_eq.step_sound _ hO,
      sem_eq_untyped := sem_eq_untyped.step_sound _ hO,
      b_distinct := b_distinct.step_sound _ hO,
      add := add.step_sound _ hO,
      sub := sub.step_sound _ hO,
      mul := mul.step_sound _ hO,
      div := div.step_sound _ hO,
      rem := rem.step_sound _ hO,
      mod_ := mod_.step_sound _ hO,
      neg := neg.step_sound _ hO,
      lt := lt.step_sound _ hO,
      leq := leq.step_sound _ hO }

end Tiny
