-- Generated by kanon from bool.kn, exists.kn, bitvec.kn, float.kn, ptr.kn, view.kn. Do not edit.
import Kanon.Statements
import Kanon.Model.Bitvec.ashr

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace Kanon

open Classical Kanon

def Bitvec.ashr.r_lits.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Bitvec.ashr.r_lits O v1 v2 = some res →
  Refines FS (Bitvec.ashr.spec v1 v2) res

def Bitvec.ashr.r_zero.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Bitvec.ashr.r_zero O v1 v2 = some res →
  Refines FS (Bitvec.ashr.spec v1 v2) res

def Bitvec.ashr.r_big.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Bitvec.ashr.r_big O v1 v2 = some res →
  Refines FS (Bitvec.ashr.spec v1 v2) res

def Bitvec.ashr.r_ashr.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Bitvec.ashr.r_ashr O v1 v2 = some res →
  Refines FS (Bitvec.ashr.spec v1 v2) res

def Bitvec.ashr.r_default.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (v1 : Term) (v2 : Term) (res : Term), Bitvec.ashr.r_default O v1 v2 = some res →
  Refines FS (Bitvec.ashr.spec v1 v2) res

def Bitvec.ashr.r_lits.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (i1 : Int) (t__2 : Ty) (i2 : Int) (t__5 : Ty),
  Refines FS (Bitvec.ashr.spec (Term.mk (Kind.BitVec i1) t__2) (Term.mk (Kind.BitVec i2) t__5))
  ((Term.mk (Kind.BitVec (lit_ashr (ty (Term.mk (Kind.BitVec i1) t__2)) (ty (Term.mk (Kind.BitVec i2) t__5)) i1 i2)) (ty (Term.mk (Kind.BitVec i1) t__2))))

def Bitvec.ashr.r_zero.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (v1 : Term) (kanon__2 : Int) (t__3 : Ty),
  (decide (kanon__2 = (0 : Int))) = true →
  Refines FS (Bitvec.ashr.spec v1 (Term.mk (Kind.BitVec kanon__2) t__3))
  (v1)

def Bitvec.ashr.r_big.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (v1 : Term) (s : Int) (t__3 : Ty),
  (decide (s ≥ (Bitvec.size v1))) = true →
  Refines FS (Bitvec.ashr.spec v1 (Term.mk (Kind.BitVec s) t__3))
  ((let sz := (Bitvec.size v1);
   (O.bitvec_ashr v1 (mk_masked sz (sz - (1 : Int))))))

def Bitvec.ashr.r_ashr.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (v : Term) (s1 : Int) (t__4 : Ty) (t__5 : Ty) (s2 : Int) (t__7 : Ty),
  Refines FS (Bitvec.ashr.spec (Term.mk (Kind.Op2 Op2.AShr v (Term.mk (Kind.BitVec s1) t__4)) t__5) (Term.mk (Kind.BitVec s2) t__7))
  ((let sz := (Bitvec.size (Term.mk (Kind.Op2 Op2.AShr v (Term.mk (Kind.BitVec s1) t__4)) t__5));
   (O.bitvec_ashr v (mk_masked sz (Bitvec.zmin (s1 + s2) (sz - (1 : Int)))))))

def Bitvec.ashr.r_default.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (v1 : Term) (v2 : Term),
  Refines FS (Bitvec.ashr.spec v1 v2)
  ((Term.mk (Kind.Op2 Op2.AShr v1 v2) (ty v1)))

end Kanon
