-- Generated by kanon from bool.kn, exists.kn, bitvec.kn, float.kn, ptr.kn, view.kn. Do not edit.
import Kanon.Statements
import Kanon.Model.Bitvec.div

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace Kanon

open Classical Kanon

def Bitvec.div.r_lits.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Nonzero v2 → Bitvec.div.r_lits O signed v1 v2 = some res →
  Refines FS (Bitvec.div.spec signed v1 v2) res

def Bitvec.div.r_one.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Nonzero v2 → Bitvec.div.r_one O signed v1 v2 = some res →
  Refines FS (Bitvec.div.spec signed v1 v2) res

def Bitvec.div.r_mul_lits.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Nonzero v2 → Bitvec.div.r_mul_lits O signed v1 v2 = some res →
  Refines FS (Bitvec.div.spec signed v1 v2) res

def Bitvec.div.r_mul_div.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Nonzero v2 → Bitvec.div.r_mul_div O signed v1 v2 = some res →
  Refines FS (Bitvec.div.spec signed v1 v2) res

def Bitvec.div.r_div_mul.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Nonzero v2 → Bitvec.div.r_div_mul O signed v1 v2 = some res →
  Refines FS (Bitvec.div.spec signed v1 v2) res

def Bitvec.div.r_div_div.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Nonzero v2 → Bitvec.div.r_div_div O signed v1 v2 = some res →
  Refines FS (Bitvec.div.spec signed v1 v2) res

def Bitvec.div.r_zext.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Nonzero v2 → Bitvec.div.r_zext O signed v1 v2 = some res →
  Refines FS (Bitvec.div.spec signed v1 v2) res

def Bitvec.div.r_default.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Nonzero v2 → Bitvec.div.r_default O signed v1 v2 = some res →
  Refines FS (Bitvec.div.spec signed v1 v2) res

def Bitvec.div.r_lits.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (l : Int) (t__2 : Ty) (r : Int) (t__4 : Ty),
  Nonzero (Term.mk (Kind.BitVec r) t__4) →
  Refines FS (Bitvec.div.spec signed (Term.mk (Kind.BitVec l) t__2) (Term.mk (Kind.BitVec r) t__4))
  ((mk_bv (Bitvec.size (Term.mk (Kind.BitVec l) t__2)) (if signed
                                                       then (lit_sdiv (ty (Term.mk (Kind.BitVec l) t__2)) (ty (Term.mk (Kind.BitVec r) t__4)) l r)
                                                       else (lit_udiv (ty (Term.mk (Kind.BitVec l) t__2)) (ty (Term.mk (Kind.BitVec r) t__4)) l r))))

def Bitvec.div.r_one.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (kanon__2 : Int) (t__3 : Ty),
  Nonzero (Term.mk (Kind.BitVec kanon__2) t__3) →
  (decide (kanon__2 = (1 : Int))) = true →
  Refines FS (Bitvec.div.spec signed v1 (Term.mk (Kind.BitVec kanon__2) t__3))
  (v1)

def Bitvec.div.r_mul_lits.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (checked : CoreMod.Checked) (w__3 : Int) (t__4 : Ty) (w__6 : Int) (t__7 : Ty) (t__9 : Ty) (w__11 : Int) (t__12 : Ty),
  Nonzero (Term.mk (Kind.BitVec w__11) t__12) →
  Refines FS (Bitvec.div.spec signed (Term.mk (Kind.Op2 (Op2.Mul checked) (Term.mk (Kind.BitVec w__3) t__4) (Term.mk (Kind.BitVec w__6) t__7)) t__9) (Term.mk (Kind.BitVec w__11) t__12))
  ((O.bitvec_div signed (O.bitvec_mul checked (Term.mk (Kind.BitVec w__3) t__4) (Term.mk (Kind.BitVec w__6) t__7)) (Term.mk (Kind.BitVec w__11) t__12)))

def Bitvec.div.r_mul_div.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (signed__2 : Bool) (n : Int) (t__5 : Ty) (x : Term) (t__7 : Ty) (d : Int) (t__10 : Ty),
  Nonzero (Term.mk (Kind.BitVec d) t__10) →
  ((! signed) && ((decide (d ≠ (0 : Int))) && (Bitvec.udivides d n))) = true →
  Refines FS (Bitvec.div.spec signed (Term.mk (Kind.Op2 (Op2.Mul ⟨signed__2, true⟩) (Term.mk (Kind.BitVec n) t__5) x) t__7) (Term.mk (Kind.BitVec d) t__10))
  ((O.bitvec_mul Bitvec.checked_unsigned x (mk_bv (Bitvec.size (Term.mk (Kind.Op2 (Op2.Mul ⟨signed__2, true⟩) (Term.mk (Kind.BitVec n) t__5) x) t__7)) (lit_udiv (ty (Term.mk (Kind.Op2 (Op2.Mul ⟨signed__2, true⟩) (Term.mk (Kind.BitVec n) t__5) x) t__7)) (ty (Term.mk (Kind.BitVec d) t__10)) n d))))

def Bitvec.div.r_mul_div.swap.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (signed__2 : Bool) (x : Term) (n : Int) (t__5 : Ty) (t__7 : Ty) (d : Int) (t__10 : Ty),
  Nonzero (Term.mk (Kind.BitVec d) t__10) →
  ((! signed) && ((decide (d ≠ (0 : Int))) && (Bitvec.udivides d n))) = true →
  Refines FS (Bitvec.div.spec signed (Term.mk (Kind.Op2 (Op2.Mul ⟨signed__2, true⟩) x (Term.mk (Kind.BitVec n) t__5)) t__7) (Term.mk (Kind.BitVec d) t__10))
  ((O.bitvec_mul Bitvec.checked_unsigned x (mk_bv (Bitvec.size (Term.mk (Kind.Op2 (Op2.Mul ⟨signed__2, true⟩) x (Term.mk (Kind.BitVec n) t__5)) t__7)) (lit_udiv (ty (Term.mk (Kind.Op2 (Op2.Mul ⟨signed__2, true⟩) x (Term.mk (Kind.BitVec n) t__5)) t__7)) (ty (Term.mk (Kind.BitVec d) t__10)) n d))))

def Bitvec.div.r_div_mul.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (signed__2 : Bool) (n : Int) (t__5 : Ty) (x : Term) (t__7 : Ty) (d : Int) (t__10 : Ty),
  Nonzero (Term.mk (Kind.BitVec d) t__10) →
  ((! signed) && ((decide (n ≠ (0 : Int))) && (Bitvec.udivides n d))) = true →
  Refines FS (Bitvec.div.spec signed (Term.mk (Kind.Op2 (Op2.Mul ⟨signed__2, true⟩) (Term.mk (Kind.BitVec n) t__5) x) t__7) (Term.mk (Kind.BitVec d) t__10))
  ((O.bitvec_div signed x (mk_bv (Bitvec.size (Term.mk (Kind.Op2 (Op2.Mul ⟨signed__2, true⟩) (Term.mk (Kind.BitVec n) t__5) x) t__7)) (lit_udiv (ty (Term.mk (Kind.BitVec d) t__10)) (ty (Term.mk (Kind.Op2 (Op2.Mul ⟨signed__2, true⟩) (Term.mk (Kind.BitVec n) t__5) x) t__7)) d n))))

def Bitvec.div.r_div_mul.swap.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (signed__2 : Bool) (x : Term) (n : Int) (t__5 : Ty) (t__7 : Ty) (d : Int) (t__10 : Ty),
  Nonzero (Term.mk (Kind.BitVec d) t__10) →
  ((! signed) && ((decide (n ≠ (0 : Int))) && (Bitvec.udivides n d))) = true →
  Refines FS (Bitvec.div.spec signed (Term.mk (Kind.Op2 (Op2.Mul ⟨signed__2, true⟩) x (Term.mk (Kind.BitVec n) t__5)) t__7) (Term.mk (Kind.BitVec d) t__10))
  ((O.bitvec_div signed x (mk_bv (Bitvec.size (Term.mk (Kind.Op2 (Op2.Mul ⟨signed__2, true⟩) x (Term.mk (Kind.BitVec n) t__5)) t__7)) (lit_udiv (ty (Term.mk (Kind.BitVec d) t__10)) (ty (Term.mk (Kind.Op2 (Op2.Mul ⟨signed__2, true⟩) x (Term.mk (Kind.BitVec n) t__5)) t__7)) d n))))

def Bitvec.div.r_div_div.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (x : Term) (n : Int) (t__5 : Ty) (t__6 : Ty) (d : Int) (t__8 : Ty),
  Nonzero (Term.mk (Kind.BitVec d) t__8) →
  ((! signed) && ((decide (n ≠ (0 : Int))) && (! (Bitvec.overflows_mul false (Bitvec.size (Term.mk (Kind.Op2 (Op2.Div false) x (Term.mk (Kind.BitVec n) t__5)) t__6)) n d)))) = true →
  Refines FS (Bitvec.div.spec signed (Term.mk (Kind.Op2 (Op2.Div false) x (Term.mk (Kind.BitVec n) t__5)) t__6) (Term.mk (Kind.BitVec d) t__8))
  ((O.bitvec_div signed x (mk_bv (Bitvec.size (Term.mk (Kind.Op2 (Op2.Div false) x (Term.mk (Kind.BitVec n) t__5)) t__6)) (lit_mul (ty (Term.mk (Kind.Op2 (Op2.Div false) x (Term.mk (Kind.BitVec n) t__5)) t__6)) (ty (Term.mk (Kind.BitVec d) t__8)) n d))))

def Bitvec.div.r_zext.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) («by» : Int) (x : Term) (t__5 : Ty) (z : Int) (t__7 : Ty),
  Nonzero (Term.mk (Kind.BitVec z) t__7) →
  ((! signed) && (decide ((Bitvec.msb_of (Term.mk (Kind.BitVec z) t__7)) < (Bitvec.size x)))) = true →
  Refines FS (Bitvec.div.spec signed (Term.mk (Kind.Op1 (Op1.BvExtend false «by») x) t__5) (Term.mk (Kind.BitVec z) t__7))
  ((O.bitvec_extend_ false «by» (O.bitvec_div signed x (mk_masked (Bitvec.size x) z))))

def Bitvec.div.r_default.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term),
  Nonzero v2 →
  Refines FS (Bitvec.div.spec signed v1 v2)
  ((Term.mk (Kind.Op2 (Op2.Div signed) v1 v2) (ty v1)))

end Kanon
