-- Generated by kanon from bool.kn, exists.kn, bitvec.kn, float.kn, ptr.kn, view.kn. Do not edit.
import Kanon.Statements
import Kanon.Model.Bitvec.lt

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace Kanon

open Classical Kanon

def Bitvec.lt.r_lits.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Bitvec.lt.r_lits O signed v1 v2 = some res →
  Refines FS (Bitvec.lt.spec signed v1 v2) res

def Bitvec.lt.r_same.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Bitvec.lt.r_same O signed v1 v2 = some res →
  Refines FS (Bitvec.lt.spec signed v1 v2) res

def Bitvec.lt.r_negs.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Bitvec.lt.r_negs O signed v1 v2 = some res →
  Refines FS (Bitvec.lt.spec signed v1 v2) res

def Bitvec.lt.r_neg_l.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Bitvec.lt.r_neg_l O signed v1 v2 = some res →
  Refines FS (Bitvec.lt.spec signed v1 v2) res

def Bitvec.lt.r_neg_r.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Bitvec.lt.r_neg_r O signed v1 v2 = some res →
  Refines FS (Bitvec.lt.spec signed v1 v2) res

def Bitvec.lt.r_const_add.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Bitvec.lt.r_const_add O signed v1 v2 = some res →
  Refines FS (Bitvec.lt.spec signed v1 v2) res

def Bitvec.lt.r_add_const.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Bitvec.lt.r_add_const O signed v1 v2 = some res →
  Refines FS (Bitvec.lt.spec signed v1 v2) res

def Bitvec.lt.r_self_add_r.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Bitvec.lt.r_self_add_r O signed v1 v2 = some res →
  Refines FS (Bitvec.lt.spec signed v1 v2) res

def Bitvec.lt.r_self_add_l.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Bitvec.lt.r_self_add_l O signed v1 v2 = some res →
  Refines FS (Bitvec.lt.spec signed v1 v2) res

def Bitvec.lt.r_add_add.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Bitvec.lt.r_add_add O signed v1 v2 = some res →
  Refines FS (Bitvec.lt.spec signed v1 v2) res

def Bitvec.lt.r_one.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Bitvec.lt.r_one O signed v1 v2 = some res →
  Refines FS (Bitvec.lt.spec signed v1 v2) res

def Bitvec.lt.r_of_bool.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Bitvec.lt.r_of_bool O signed v1 v2 = some res →
  Refines FS (Bitvec.lt.spec signed v1 v2) res

def Bitvec.lt.r_ite_l.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Bitvec.lt.r_ite_l O signed v1 v2 = some res →
  Refines FS (Bitvec.lt.spec signed v1 v2) res

def Bitvec.lt.r_ite_r.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Bitvec.lt.r_ite_r O signed v1 v2 = some res →
  Refines FS (Bitvec.lt.spec signed v1 v2) res

def Bitvec.lt.r_lt_zero.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Bitvec.lt.r_lt_zero O signed v1 v2 = some res →
  Refines FS (Bitvec.lt.spec signed v1 v2) res

def Bitvec.lt.r_max_l.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Bitvec.lt.r_max_l O signed v1 v2 = some res →
  Refines FS (Bitvec.lt.spec signed v1 v2) res

def Bitvec.lt.r_min_r.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Bitvec.lt.r_min_r O signed v1 v2 = some res →
  Refines FS (Bitvec.lt.spec signed v1 v2) res

def Bitvec.lt.r_min_l.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Bitvec.lt.r_min_l O signed v1 v2 = some res →
  Refines FS (Bitvec.lt.spec signed v1 v2) res

def Bitvec.lt.r_max_r.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Bitvec.lt.r_max_r O signed v1 v2 = some res →
  Refines FS (Bitvec.lt.spec signed v1 v2) res

def Bitvec.lt.r_const_mul.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Bitvec.lt.r_const_mul O signed v1 v2 = some res →
  Refines FS (Bitvec.lt.spec signed v1 v2) res

def Bitvec.lt.r_mul_const.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Bitvec.lt.r_mul_const O signed v1 v2 = some res →
  Refines FS (Bitvec.lt.spec signed v1 v2) res

def Bitvec.lt.r_mul_mul.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Bitvec.lt.r_mul_mul O signed v1 v2 = some res →
  Refines FS (Bitvec.lt.spec signed v1 v2) res

def Bitvec.lt.r_const_sub1.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Bitvec.lt.r_const_sub1 O signed v1 v2 = some res →
  Refines FS (Bitvec.lt.spec signed v1 v2) res

def Bitvec.lt.r_const_sub2.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Bitvec.lt.r_const_sub2 O signed v1 v2 = some res →
  Refines FS (Bitvec.lt.spec signed v1 v2) res

def Bitvec.lt.r_sub_const1.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Bitvec.lt.r_sub_const1 O signed v1 v2 = some res →
  Refines FS (Bitvec.lt.spec signed v1 v2) res

def Bitvec.lt.r_sub_const2.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Bitvec.lt.r_sub_const2 O signed v1 v2 = some res →
  Refines FS (Bitvec.lt.spec signed v1 v2) res

def Bitvec.lt.r_ub_r.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Bitvec.lt.r_ub_r O signed v1 v2 = some res →
  Refines FS (Bitvec.lt.spec signed v1 v2) res

def Bitvec.lt.r_ub_l.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Bitvec.lt.r_ub_l O signed v1 v2 = some res →
  Refines FS (Bitvec.lt.spec signed v1 v2) res

def Bitvec.lt.r_to_unsigned_l.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Bitvec.lt.r_to_unsigned_l O signed v1 v2 = some res →
  Refines FS (Bitvec.lt.spec signed v1 v2) res

def Bitvec.lt.r_to_unsigned_r.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Bitvec.lt.r_to_unsigned_r O signed v1 v2 = some res →
  Refines FS (Bitvec.lt.spec signed v1 v2) res

def Bitvec.lt.r_default.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Bitvec.lt.r_default O signed v1 v2 = some res →
  Refines FS (Bitvec.lt.spec signed v1 v2) res

def Bitvec.lt.r_lits.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (l : Int) (t__2 : Ty) (r : Int) (t__4 : Ty),
  Refines FS (Bitvec.lt.spec signed (Term.mk (Kind.BitVec l) t__2) (Term.mk (Kind.BitVec r) t__4))
  ((Bool.of_bool (decide ((Bitvec.to_z signed (Bitvec.size (Term.mk (Kind.BitVec l) t__2)) l) < (Bitvec.to_z signed (Bitvec.size (Term.mk (Kind.BitVec l) t__2)) r)))))

def Bitvec.lt.r_same.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term),
  (decide (v1 = v2)) = true →
  Refines FS (Bitvec.lt.spec signed v1 v2)
  (v_false)

def Bitvec.lt.r_negs.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (a : Term) (t__4 : Ty) (b : Term) (t__8 : Ty),
  signed = true →
  Refines FS (Bitvec.lt.spec signed (Term.mk (Kind.Op1 (Op1.Neg true) a) t__4) (Term.mk (Kind.Op1 (Op1.Neg true) b) t__8))
  ((O.bitvec_lt signed b a))

def Bitvec.lt.r_neg_l.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (a : Term) (t__4 : Ty) (c : Int) (t__6 : Ty),
  (signed && (! (Bitvec.is_int_min (Bitvec.size (Term.mk (Kind.Op1 (Op1.Neg true) a) t__4)) c))) = true →
  Refines FS (Bitvec.lt.spec signed (Term.mk (Kind.Op1 (Op1.Neg true) a) t__4) (Term.mk (Kind.BitVec c) t__6))
  ((O.bitvec_lt signed (O.bitvec_neg false (Term.mk (Kind.BitVec c) t__6)) a))

def Bitvec.lt.r_neg_r.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (c : Int) (t__2 : Ty) (a : Term) (t__6 : Ty),
  (signed && (! (Bitvec.is_int_min (Bitvec.size (Term.mk (Kind.BitVec c) t__2)) c))) = true →
  Refines FS (Bitvec.lt.spec signed (Term.mk (Kind.BitVec c) t__2) (Term.mk (Kind.Op1 (Op1.Neg true) a) t__6))
  ((O.bitvec_lt signed a (O.bitvec_neg false (Term.mk (Kind.BitVec c) t__2))))

def Bitvec.lt.r_const_add.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (c : Int) (t__2 : Ty) (checked : Checked) (r : Int) (t__6 : Ty) (x : Term) (t__8 : Ty),
  (Bitvec.checked_has signed checked) = true →
  Refines FS (Bitvec.lt.spec signed (Term.mk (Kind.BitVec c) t__2) (Term.mk (Kind.Op2 (Op2.Add checked) (Term.mk (Kind.BitVec r) t__6) x) t__8))
  ((if (Bitvec.overflows_sub signed (Bitvec.size (Term.mk (Kind.BitVec c) t__2)) c r)
   then (if (! signed)
        then v_true
        else (Term.mk (Kind.Op2 (Op2.Lt signed) (Term.mk (Kind.BitVec c) t__2) (Term.mk (Kind.Op2 (Op2.Add checked) (Term.mk (Kind.BitVec r) t__6) x) t__8)) Ty.TBool))
   else (O.bitvec_lt signed (mk_bv (Bitvec.size (Term.mk (Kind.BitVec c) t__2)) (lit_sub (ty (Term.mk (Kind.BitVec c) t__2)) (ty (Term.mk (Kind.BitVec c) t__2)) c r)) x)))

def Bitvec.lt.r_const_add.swap.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (c : Int) (t__2 : Ty) (checked : Checked) (x : Term) (r : Int) (t__6 : Ty) (t__8 : Ty),
  (Bitvec.checked_has signed checked) = true →
  Refines FS (Bitvec.lt.spec signed (Term.mk (Kind.BitVec c) t__2) (Term.mk (Kind.Op2 (Op2.Add checked) x (Term.mk (Kind.BitVec r) t__6)) t__8))
  ((if (Bitvec.overflows_sub signed (Bitvec.size (Term.mk (Kind.BitVec c) t__2)) c r)
   then (if (! signed)
        then v_true
        else (Term.mk (Kind.Op2 (Op2.Lt signed) (Term.mk (Kind.BitVec c) t__2) (Term.mk (Kind.Op2 (Op2.Add checked) x (Term.mk (Kind.BitVec r) t__6)) t__8)) Ty.TBool))
   else (O.bitvec_lt signed (mk_bv (Bitvec.size (Term.mk (Kind.BitVec c) t__2)) (lit_sub (ty (Term.mk (Kind.BitVec c) t__2)) (ty (Term.mk (Kind.BitVec c) t__2)) c r)) x)))

def Bitvec.lt.r_add_const.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (checked : Checked) (l : Int) (t__4 : Ty) (x : Term) (t__6 : Ty) (c : Int) (t__9 : Ty),
  (Bitvec.checked_has signed checked) = true →
  Refines FS (Bitvec.lt.spec signed (Term.mk (Kind.Op2 (Op2.Add checked) (Term.mk (Kind.BitVec l) t__4) x) t__6) (Term.mk (Kind.BitVec c) t__9))
  ((if (Bitvec.overflows_sub signed (Bitvec.size (Term.mk (Kind.Op2 (Op2.Add checked) (Term.mk (Kind.BitVec l) t__4) x) t__6)) c l)
   then (if (! signed)
        then v_false
        else (Term.mk (Kind.Op2 (Op2.Lt signed) (Term.mk (Kind.Op2 (Op2.Add checked) (Term.mk (Kind.BitVec l) t__4) x) t__6) (Term.mk (Kind.BitVec c) t__9)) Ty.TBool))
   else (O.bitvec_lt signed x (mk_bv (Bitvec.size (Term.mk (Kind.Op2 (Op2.Add checked) (Term.mk (Kind.BitVec l) t__4) x) t__6)) (lit_sub (ty (Term.mk (Kind.Op2 (Op2.Add checked) (Term.mk (Kind.BitVec l) t__4) x) t__6)) (ty (Term.mk (Kind.Op2 (Op2.Add checked) (Term.mk (Kind.BitVec l) t__4) x) t__6)) c l)))))

def Bitvec.lt.r_add_const.swap.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (checked : Checked) (x : Term) (l : Int) (t__4 : Ty) (t__6 : Ty) (c : Int) (t__9 : Ty),
  (Bitvec.checked_has signed checked) = true →
  Refines FS (Bitvec.lt.spec signed (Term.mk (Kind.Op2 (Op2.Add checked) x (Term.mk (Kind.BitVec l) t__4)) t__6) (Term.mk (Kind.BitVec c) t__9))
  ((if (Bitvec.overflows_sub signed (Bitvec.size (Term.mk (Kind.Op2 (Op2.Add checked) x (Term.mk (Kind.BitVec l) t__4)) t__6)) c l)
   then (if (! signed)
        then v_false
        else (Term.mk (Kind.Op2 (Op2.Lt signed) (Term.mk (Kind.Op2 (Op2.Add checked) x (Term.mk (Kind.BitVec l) t__4)) t__6) (Term.mk (Kind.BitVec c) t__9)) Ty.TBool))
   else (O.bitvec_lt signed x (mk_bv (Bitvec.size (Term.mk (Kind.Op2 (Op2.Add checked) x (Term.mk (Kind.BitVec l) t__4)) t__6)) (lit_sub (ty (Term.mk (Kind.Op2 (Op2.Add checked) x (Term.mk (Kind.BitVec l) t__4)) t__6)) (ty (Term.mk (Kind.Op2 (Op2.Add checked) x (Term.mk (Kind.BitVec l) t__4)) t__6)) c l)))))

def Bitvec.lt.r_self_add_r.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (checked : Checked) (kanon__4 : Term) (b : Term) (t__6 : Ty),
  ((decide (v1 = kanon__4)) && (Bitvec.checked_has signed checked)) = true →
  Refines FS (Bitvec.lt.spec signed v1 (Term.mk (Kind.Op2 (Op2.Add checked) kanon__4 b) t__6))
  ((O.bitvec_lt signed (bv_zero (Bitvec.size v1)) b))

def Bitvec.lt.r_self_add_r.swap.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (checked : Checked) (b : Term) (kanon__4 : Term) (t__6 : Ty),
  ((decide (v1 = kanon__4)) && (Bitvec.checked_has signed checked)) = true →
  Refines FS (Bitvec.lt.spec signed v1 (Term.mk (Kind.Op2 (Op2.Add checked) b kanon__4) t__6))
  ((O.bitvec_lt signed (bv_zero (Bitvec.size v1)) b))

def Bitvec.lt.r_self_add_l.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v2 : Term) (checked : Checked) (a : Term) (b : Term) (t__5 : Ty),
  ((decide (a = v2)) && (Bitvec.checked_has signed checked)) = true →
  Refines FS (Bitvec.lt.spec signed (Term.mk (Kind.Op2 (Op2.Add checked) a b) t__5) v2)
  ((O.bitvec_lt signed b (bv_zero (Bitvec.size (Term.mk (Kind.Op2 (Op2.Add checked) a b) t__5)))))

def Bitvec.lt.r_self_add_l.swap.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v2 : Term) (checked : Checked) (b : Term) (a : Term) (t__5 : Ty),
  ((decide (a = v2)) && (Bitvec.checked_has signed checked)) = true →
  Refines FS (Bitvec.lt.spec signed (Term.mk (Kind.Op2 (Op2.Add checked) b a) t__5) v2)
  ((O.bitvec_lt signed b (bv_zero (Bitvec.size (Term.mk (Kind.Op2 (Op2.Add checked) b a) t__5)))))

def Bitvec.lt.r_add_add.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (checked_l : Checked) (l : Int) (t__4 : Ty) (y : Term) (t__6 : Ty) (checked_r : Checked) (r : Int) (t__11 : Ty) (x : Term) (t__13 : Ty),
  ((Bitvec.checked_has signed checked_l) && (Bitvec.checked_has signed checked_r)) = true →
  Refines FS (Bitvec.lt.spec signed (Term.mk (Kind.Op2 (Op2.Add checked_l) (Term.mk (Kind.BitVec l) t__4) y) t__6) (Term.mk (Kind.Op2 (Op2.Add checked_r) (Term.mk (Kind.BitVec r) t__11) x) t__13))
  ((let n := (Bitvec.size (Term.mk (Kind.Op2 (Op2.Add checked_l) (Term.mk (Kind.BitVec l) t__4) y) t__6));
   (let sty := (ty (Term.mk (Kind.Op2 (Op2.Add checked_l) (Term.mk (Kind.BitVec l) t__4) y) t__6));
   (if (Bitvec.const_keeps_in_range signed n l r)
   then (O.bitvec_lt signed (O.bitvec_add (Bitvec.checked_of_signed signed) y (mk_bv n (lit_sub sty sty l r))) x)
   else (if (Bitvec.const_keeps_in_range signed n r l)
        then (O.bitvec_lt signed y (O.bitvec_add (Bitvec.checked_of_signed signed) x (mk_bv n (lit_sub sty sty r l))))
        else (Term.mk (Kind.Op2 (Op2.Lt signed) (Term.mk (Kind.Op2 (Op2.Add checked_l) (Term.mk (Kind.BitVec l) t__4) y) t__6) (Term.mk (Kind.Op2 (Op2.Add checked_r) (Term.mk (Kind.BitVec r) t__11) x) t__13)) Ty.TBool))))))

def Bitvec.lt.r_add_add.swap2.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (checked_l : Checked) (l : Int) (t__4 : Ty) (y : Term) (t__6 : Ty) (checked_r : Checked) (x : Term) (r : Int) (t__11 : Ty) (t__13 : Ty),
  ((Bitvec.checked_has signed checked_l) && (Bitvec.checked_has signed checked_r)) = true →
  Refines FS (Bitvec.lt.spec signed (Term.mk (Kind.Op2 (Op2.Add checked_l) (Term.mk (Kind.BitVec l) t__4) y) t__6) (Term.mk (Kind.Op2 (Op2.Add checked_r) x (Term.mk (Kind.BitVec r) t__11)) t__13))
  ((let n := (Bitvec.size (Term.mk (Kind.Op2 (Op2.Add checked_l) (Term.mk (Kind.BitVec l) t__4) y) t__6));
   (let sty := (ty (Term.mk (Kind.Op2 (Op2.Add checked_l) (Term.mk (Kind.BitVec l) t__4) y) t__6));
   (if (Bitvec.const_keeps_in_range signed n l r)
   then (O.bitvec_lt signed (O.bitvec_add (Bitvec.checked_of_signed signed) y (mk_bv n (lit_sub sty sty l r))) x)
   else (if (Bitvec.const_keeps_in_range signed n r l)
        then (O.bitvec_lt signed y (O.bitvec_add (Bitvec.checked_of_signed signed) x (mk_bv n (lit_sub sty sty r l))))
        else (Term.mk (Kind.Op2 (Op2.Lt signed) (Term.mk (Kind.Op2 (Op2.Add checked_l) (Term.mk (Kind.BitVec l) t__4) y) t__6) (Term.mk (Kind.Op2 (Op2.Add checked_r) x (Term.mk (Kind.BitVec r) t__11)) t__13)) Ty.TBool))))))

def Bitvec.lt.r_add_add.swap1.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (checked_l : Checked) (y : Term) (l : Int) (t__4 : Ty) (t__6 : Ty) (checked_r : Checked) (r : Int) (t__11 : Ty) (x : Term) (t__13 : Ty),
  ((Bitvec.checked_has signed checked_l) && (Bitvec.checked_has signed checked_r)) = true →
  Refines FS (Bitvec.lt.spec signed (Term.mk (Kind.Op2 (Op2.Add checked_l) y (Term.mk (Kind.BitVec l) t__4)) t__6) (Term.mk (Kind.Op2 (Op2.Add checked_r) (Term.mk (Kind.BitVec r) t__11) x) t__13))
  ((let n := (Bitvec.size (Term.mk (Kind.Op2 (Op2.Add checked_l) y (Term.mk (Kind.BitVec l) t__4)) t__6));
   (let sty := (ty (Term.mk (Kind.Op2 (Op2.Add checked_l) y (Term.mk (Kind.BitVec l) t__4)) t__6));
   (if (Bitvec.const_keeps_in_range signed n l r)
   then (O.bitvec_lt signed (O.bitvec_add (Bitvec.checked_of_signed signed) y (mk_bv n (lit_sub sty sty l r))) x)
   else (if (Bitvec.const_keeps_in_range signed n r l)
        then (O.bitvec_lt signed y (O.bitvec_add (Bitvec.checked_of_signed signed) x (mk_bv n (lit_sub sty sty r l))))
        else (Term.mk (Kind.Op2 (Op2.Lt signed) (Term.mk (Kind.Op2 (Op2.Add checked_l) y (Term.mk (Kind.BitVec l) t__4)) t__6) (Term.mk (Kind.Op2 (Op2.Add checked_r) (Term.mk (Kind.BitVec r) t__11) x) t__13)) Ty.TBool))))))

def Bitvec.lt.r_add_add.swap1_swap2.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (checked_l : Checked) (y : Term) (l : Int) (t__4 : Ty) (t__6 : Ty) (checked_r : Checked) (x : Term) (r : Int) (t__11 : Ty) (t__13 : Ty),
  ((Bitvec.checked_has signed checked_l) && (Bitvec.checked_has signed checked_r)) = true →
  Refines FS (Bitvec.lt.spec signed (Term.mk (Kind.Op2 (Op2.Add checked_l) y (Term.mk (Kind.BitVec l) t__4)) t__6) (Term.mk (Kind.Op2 (Op2.Add checked_r) x (Term.mk (Kind.BitVec r) t__11)) t__13))
  ((let n := (Bitvec.size (Term.mk (Kind.Op2 (Op2.Add checked_l) y (Term.mk (Kind.BitVec l) t__4)) t__6));
   (let sty := (ty (Term.mk (Kind.Op2 (Op2.Add checked_l) y (Term.mk (Kind.BitVec l) t__4)) t__6));
   (if (Bitvec.const_keeps_in_range signed n l r)
   then (O.bitvec_lt signed (O.bitvec_add (Bitvec.checked_of_signed signed) y (mk_bv n (lit_sub sty sty l r))) x)
   else (if (Bitvec.const_keeps_in_range signed n r l)
        then (O.bitvec_lt signed y (O.bitvec_add (Bitvec.checked_of_signed signed) x (mk_bv n (lit_sub sty sty r l))))
        else (Term.mk (Kind.Op2 (Op2.Lt signed) (Term.mk (Kind.Op2 (Op2.Add checked_l) y (Term.mk (Kind.BitVec l) t__4)) t__6) (Term.mk (Kind.Op2 (Op2.Add checked_r) x (Term.mk (Kind.BitVec r) t__11)) t__13)) Ty.TBool))))))

def Bitvec.lt.r_one.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (kanon__2 : Int) (t__3 : Ty),
  ((decide (kanon__2 = (1 : Int))) && (! signed)) = true →
  Refines FS (Bitvec.lt.spec signed v1 (Term.mk (Kind.BitVec kanon__2) t__3))
  ((O.bool_eq v1 (bv_zero (Bitvec.size v1))))

def Bitvec.lt.r_of_bool.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (n : Int) (b : Term) (t__5 : Ty),
  (! signed) = true →
  Refines FS (Bitvec.lt.spec signed v1 (Term.mk (Kind.Op1 (Op1.BvOfBool n) b) t__5))
  ((O.bool_and_ b (O.bool_eq v1 (bv_zero n))))

def Bitvec.lt.r_ite_l.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v2 : Term) (b : Term) (l : Term) (r : Term) (t__5 : Ty),
  Refines FS (Bitvec.lt.spec signed (Term.mk (Kind.Op3 Op3.Ite b l r) t__5) v2)
  ((O.bool_ite b (O.bitvec_lt signed l v2) (O.bitvec_lt signed r v2)))

def Bitvec.lt.r_ite_r.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (b : Term) (l : Term) (r : Term) (t__6 : Ty),
  Refines FS (Bitvec.lt.spec signed v1 (Term.mk (Kind.Op3 Op3.Ite b l r) t__6))
  ((O.bool_ite b (O.bitvec_lt signed v1 l) (O.bitvec_lt signed v1 r)))

def Bitvec.lt.r_lt_zero.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (kanon__2 : Int) (t__3 : Ty),
  ((decide (kanon__2 = (0 : Int))) && (signed && (! (Bitvec.is_checked_unsigned_op v1)))) = true →
  Refines FS (Bitvec.lt.spec signed v1 (Term.mk (Kind.BitVec kanon__2) t__3))
  ((O.bitvec_lt_zero v1))

def Bitvec.lt.r_max_l.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v2 : Term) (x : Int) (t__2 : Ty),
  (Bitvec.is_max_of signed (Bitvec.size (Term.mk (Kind.BitVec x) t__2)) x) = true →
  Refines FS (Bitvec.lt.spec signed (Term.mk (Kind.BitVec x) t__2) v2)
  (v_false)

def Bitvec.lt.r_min_r.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (x : Int) (t__3 : Ty),
  (Bitvec.is_min_of signed (Bitvec.size v1) x) = true →
  Refines FS (Bitvec.lt.spec signed v1 (Term.mk (Kind.BitVec x) t__3))
  (v_false)

def Bitvec.lt.r_min_l.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v2 : Term) (x : Int) (t__2 : Ty),
  (Bitvec.is_min_of signed (Bitvec.size (Term.mk (Kind.BitVec x) t__2)) x) = true →
  Refines FS (Bitvec.lt.spec signed (Term.mk (Kind.BitVec x) t__2) v2)
  ((O.bool_not_ (O.bool_eq (Term.mk (Kind.BitVec x) t__2) v2)))

def Bitvec.lt.r_max_r.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (x : Int) (t__3 : Ty),
  (Bitvec.is_max_of signed (Bitvec.size v1) x) = true →
  Refines FS (Bitvec.lt.spec signed v1 (Term.mk (Kind.BitVec x) t__3))
  ((O.bool_not_ (O.bool_eq v1 (Term.mk (Kind.BitVec x) t__3))))

def Bitvec.lt.r_const_mul.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (c2 : Int) (t__2 : Ty) (checked : Checked) (x : Term) (c1 : Int) (t__7 : Ty) (t__9 : Ty),
  ((Bitvec.checked_has signed checked) && (! (decide (c1 = (0 : Int))))) = true →
  Refines FS (Bitvec.lt.spec signed (Term.mk (Kind.BitVec c2) t__2) (Term.mk (Kind.Op2 (Op2.Mul checked) x (Term.mk (Kind.BitVec c1) t__7)) t__9))
  ((let z1 := (Bitvec.to_z signed (Bitvec.size (Term.mk (Kind.BitVec c2) t__2)) c1);
   (let z2 := (Bitvec.to_z signed (Bitvec.size (Term.mk (Kind.BitVec c2) t__2)) c2);
   (if ((divisible z2 z1) || (decide (z2 ≥ (0 : Int))))
   then (if (decide (z1 < (0 : Int)))
        then (if (signed && ((decide (z1 = (-1 : Int))) && (Bitvec.is_int_min (Bitvec.size (Term.mk (Kind.BitVec c2) t__2)) c2)))
             then v_true
             else (O.bitvec_lt signed x (O.bitvec_div signed (Term.mk (Kind.BitVec c2) t__2) (Term.mk (Kind.BitVec c1) t__7))))
        else (O.bitvec_lt signed (O.bitvec_div signed (Term.mk (Kind.BitVec c2) t__2) (Term.mk (Kind.BitVec c1) t__7)) x))
   else (if (decide (z1 < (0 : Int)))
        then (O.bitvec_leq signed x (O.bitvec_div signed (Term.mk (Kind.BitVec c2) t__2) (Term.mk (Kind.BitVec c1) t__7)))
        else (O.bitvec_leq signed (O.bitvec_div signed (Term.mk (Kind.BitVec c2) t__2) (Term.mk (Kind.BitVec c1) t__7)) x))))))

def Bitvec.lt.r_const_mul.swap.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (c2 : Int) (t__2 : Ty) (checked : Checked) (c1 : Int) (t__7 : Ty) (x : Term) (t__9 : Ty),
  ((Bitvec.checked_has signed checked) && (! (decide (c1 = (0 : Int))))) = true →
  Refines FS (Bitvec.lt.spec signed (Term.mk (Kind.BitVec c2) t__2) (Term.mk (Kind.Op2 (Op2.Mul checked) (Term.mk (Kind.BitVec c1) t__7) x) t__9))
  ((let z1 := (Bitvec.to_z signed (Bitvec.size (Term.mk (Kind.BitVec c2) t__2)) c1);
   (let z2 := (Bitvec.to_z signed (Bitvec.size (Term.mk (Kind.BitVec c2) t__2)) c2);
   (if ((divisible z2 z1) || (decide (z2 ≥ (0 : Int))))
   then (if (decide (z1 < (0 : Int)))
        then (if (signed && ((decide (z1 = (-1 : Int))) && (Bitvec.is_int_min (Bitvec.size (Term.mk (Kind.BitVec c2) t__2)) c2)))
             then v_true
             else (O.bitvec_lt signed x (O.bitvec_div signed (Term.mk (Kind.BitVec c2) t__2) (Term.mk (Kind.BitVec c1) t__7))))
        else (O.bitvec_lt signed (O.bitvec_div signed (Term.mk (Kind.BitVec c2) t__2) (Term.mk (Kind.BitVec c1) t__7)) x))
   else (if (decide (z1 < (0 : Int)))
        then (O.bitvec_leq signed x (O.bitvec_div signed (Term.mk (Kind.BitVec c2) t__2) (Term.mk (Kind.BitVec c1) t__7)))
        else (O.bitvec_leq signed (O.bitvec_div signed (Term.mk (Kind.BitVec c2) t__2) (Term.mk (Kind.BitVec c1) t__7)) x))))))

def Bitvec.lt.r_mul_const.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (checked : Checked) (x : Term) (c1 : Int) (t__5 : Ty) (t__7 : Ty) (c2 : Int) (t__10 : Ty),
  ((Bitvec.checked_has signed checked) && (! (decide (c1 = (0 : Int))))) = true →
  Refines FS (Bitvec.lt.spec signed (Term.mk (Kind.Op2 (Op2.Mul checked) x (Term.mk (Kind.BitVec c1) t__5)) t__7) (Term.mk (Kind.BitVec c2) t__10))
  ((let z1 := (Bitvec.to_z signed (Bitvec.size (Term.mk (Kind.Op2 (Op2.Mul checked) x (Term.mk (Kind.BitVec c1) t__5)) t__7)) c1);
   (let z2 := (Bitvec.to_z signed (Bitvec.size (Term.mk (Kind.Op2 (Op2.Mul checked) x (Term.mk (Kind.BitVec c1) t__5)) t__7)) c2);
   (if ((divisible z2 z1) || (decide (z2 < (0 : Int))))
   then (if (decide (z1 < (0 : Int)))
        then (if (signed && ((decide (z1 = (-1 : Int))) && (Bitvec.is_int_min (Bitvec.size (Term.mk (Kind.Op2 (Op2.Mul checked) x (Term.mk (Kind.BitVec c1) t__5)) t__7)) c2)))
             then v_false
             else (O.bitvec_lt signed (O.bitvec_div signed (Term.mk (Kind.BitVec c2) t__10) (Term.mk (Kind.BitVec c1) t__5)) x))
        else (O.bitvec_lt signed x (O.bitvec_div signed (Term.mk (Kind.BitVec c2) t__10) (Term.mk (Kind.BitVec c1) t__5))))
   else (if (decide (z1 < (0 : Int)))
        then (O.bitvec_leq signed (O.bitvec_div signed (Term.mk (Kind.BitVec c2) t__10) (Term.mk (Kind.BitVec c1) t__5)) x)
        else (O.bitvec_leq signed x (O.bitvec_div signed (Term.mk (Kind.BitVec c2) t__10) (Term.mk (Kind.BitVec c1) t__5))))))))

def Bitvec.lt.r_mul_const.swap.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (checked : Checked) (c1 : Int) (t__5 : Ty) (x : Term) (t__7 : Ty) (c2 : Int) (t__10 : Ty),
  ((Bitvec.checked_has signed checked) && (! (decide (c1 = (0 : Int))))) = true →
  Refines FS (Bitvec.lt.spec signed (Term.mk (Kind.Op2 (Op2.Mul checked) (Term.mk (Kind.BitVec c1) t__5) x) t__7) (Term.mk (Kind.BitVec c2) t__10))
  ((let z1 := (Bitvec.to_z signed (Bitvec.size (Term.mk (Kind.Op2 (Op2.Mul checked) (Term.mk (Kind.BitVec c1) t__5) x) t__7)) c1);
   (let z2 := (Bitvec.to_z signed (Bitvec.size (Term.mk (Kind.Op2 (Op2.Mul checked) (Term.mk (Kind.BitVec c1) t__5) x) t__7)) c2);
   (if ((divisible z2 z1) || (decide (z2 < (0 : Int))))
   then (if (decide (z1 < (0 : Int)))
        then (if (signed && ((decide (z1 = (-1 : Int))) && (Bitvec.is_int_min (Bitvec.size (Term.mk (Kind.Op2 (Op2.Mul checked) (Term.mk (Kind.BitVec c1) t__5) x) t__7)) c2)))
             then v_false
             else (O.bitvec_lt signed (O.bitvec_div signed (Term.mk (Kind.BitVec c2) t__10) (Term.mk (Kind.BitVec c1) t__5)) x))
        else (O.bitvec_lt signed x (O.bitvec_div signed (Term.mk (Kind.BitVec c2) t__10) (Term.mk (Kind.BitVec c1) t__5))))
   else (if (decide (z1 < (0 : Int)))
        then (O.bitvec_leq signed (O.bitvec_div signed (Term.mk (Kind.BitVec c2) t__10) (Term.mk (Kind.BitVec c1) t__5)) x)
        else (O.bitvec_leq signed x (O.bitvec_div signed (Term.mk (Kind.BitVec c2) t__10) (Term.mk (Kind.BitVec c1) t__5))))))))

def Bitvec.lt.r_mul_mul.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (checked_l : Checked) (a : Term) (x : Term) (t__5 : Ty) (checked_r : Checked) (kanon__9 : Term) (y : Term) (t__11 : Ty),
  ((decide (a = kanon__9)) && ((Bitvec.checked_has signed checked_l) && ((Bitvec.checked_has signed checked_r) && (Bitvec.cancellable signed a)))) = true →
  Refines FS (Bitvec.lt.spec signed (Term.mk (Kind.Op2 (Op2.Mul checked_l) a x) t__5) (Term.mk (Kind.Op2 (Op2.Mul checked_r) kanon__9 y) t__11))
  ((O.bitvec_lt signed x y))

def Bitvec.lt.r_mul_mul.swap2.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (checked_l : Checked) (a : Term) (x : Term) (t__5 : Ty) (checked_r : Checked) (y : Term) (kanon__9 : Term) (t__11 : Ty),
  ((decide (a = kanon__9)) && ((Bitvec.checked_has signed checked_l) && ((Bitvec.checked_has signed checked_r) && (Bitvec.cancellable signed a)))) = true →
  Refines FS (Bitvec.lt.spec signed (Term.mk (Kind.Op2 (Op2.Mul checked_l) a x) t__5) (Term.mk (Kind.Op2 (Op2.Mul checked_r) y kanon__9) t__11))
  ((O.bitvec_lt signed x y))

def Bitvec.lt.r_mul_mul.swap1.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (checked_l : Checked) (x : Term) (a : Term) (t__5 : Ty) (checked_r : Checked) (kanon__9 : Term) (y : Term) (t__11 : Ty),
  ((decide (a = kanon__9)) && ((Bitvec.checked_has signed checked_l) && ((Bitvec.checked_has signed checked_r) && (Bitvec.cancellable signed a)))) = true →
  Refines FS (Bitvec.lt.spec signed (Term.mk (Kind.Op2 (Op2.Mul checked_l) x a) t__5) (Term.mk (Kind.Op2 (Op2.Mul checked_r) kanon__9 y) t__11))
  ((O.bitvec_lt signed x y))

def Bitvec.lt.r_mul_mul.swap1_swap2.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (checked_l : Checked) (x : Term) (a : Term) (t__5 : Ty) (checked_r : Checked) (y : Term) (kanon__9 : Term) (t__11 : Ty),
  ((decide (a = kanon__9)) && ((Bitvec.checked_has signed checked_l) && ((Bitvec.checked_has signed checked_r) && (Bitvec.cancellable signed a)))) = true →
  Refines FS (Bitvec.lt.spec signed (Term.mk (Kind.Op2 (Op2.Mul checked_l) x a) t__5) (Term.mk (Kind.Op2 (Op2.Mul checked_r) y kanon__9) t__11))
  ((O.bitvec_lt signed x y))

def Bitvec.lt.r_const_sub1.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (c : Int) (t__2 : Ty) (checked : Checked) (x : Term) (k : Int) (t__7 : Ty) (t__8 : Ty),
  (Bitvec.checked_has signed checked) = true →
  Refines FS (Bitvec.lt.spec signed (Term.mk (Kind.BitVec c) t__2) (Term.mk (Kind.Op2 (Op2.Sub checked) x (Term.mk (Kind.BitVec k) t__7)) t__8))
  ((if (Bitvec.overflows_add signed (Bitvec.size (Term.mk (Kind.BitVec c) t__2)) c k)
   then (if (! signed)
        then v_false
        else (Term.mk (Kind.Op2 (Op2.Lt signed) (Term.mk (Kind.BitVec c) t__2) (Term.mk (Kind.Op2 (Op2.Sub checked) x (Term.mk (Kind.BitVec k) t__7)) t__8)) Ty.TBool))
   else (O.bitvec_lt signed (mk_bv (Bitvec.size (Term.mk (Kind.BitVec c) t__2)) (lit_add (ty (Term.mk (Kind.BitVec c) t__2)) (ty (Term.mk (Kind.BitVec c) t__2)) c k)) x)))

def Bitvec.lt.r_const_sub2.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (c : Int) (t__2 : Ty) (checked : Checked) (k : Int) (t__6 : Ty) (x : Term) (t__8 : Ty),
  (Bitvec.checked_has signed checked) = true →
  Refines FS (Bitvec.lt.spec signed (Term.mk (Kind.BitVec c) t__2) (Term.mk (Kind.Op2 (Op2.Sub checked) (Term.mk (Kind.BitVec k) t__6) x) t__8))
  ((if (Bitvec.overflows_sub signed (Bitvec.size (Term.mk (Kind.BitVec c) t__2)) k c)
   then (if (! signed)
        then v_false
        else (Term.mk (Kind.Op2 (Op2.Lt signed) (Term.mk (Kind.BitVec c) t__2) (Term.mk (Kind.Op2 (Op2.Sub checked) (Term.mk (Kind.BitVec k) t__6) x) t__8)) Ty.TBool))
   else (O.bitvec_lt signed x (mk_bv (Bitvec.size (Term.mk (Kind.BitVec c) t__2)) (lit_sub (ty (Term.mk (Kind.BitVec c) t__2)) (ty (Term.mk (Kind.BitVec c) t__2)) k c)))))

def Bitvec.lt.r_sub_const1.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (checked : Checked) (x : Term) (k : Int) (t__5 : Ty) (t__6 : Ty) (c : Int) (t__8 : Ty),
  (Bitvec.checked_has signed checked) = true →
  Refines FS (Bitvec.lt.spec signed (Term.mk (Kind.Op2 (Op2.Sub checked) x (Term.mk (Kind.BitVec k) t__5)) t__6) (Term.mk (Kind.BitVec c) t__8))
  ((if (Bitvec.overflows_add signed (Bitvec.size (Term.mk (Kind.Op2 (Op2.Sub checked) x (Term.mk (Kind.BitVec k) t__5)) t__6)) c k)
   then (if (! signed)
        then v_true
        else (Term.mk (Kind.Op2 (Op2.Lt signed) (Term.mk (Kind.Op2 (Op2.Sub checked) x (Term.mk (Kind.BitVec k) t__5)) t__6) (Term.mk (Kind.BitVec c) t__8)) Ty.TBool))
   else (O.bitvec_lt signed x (mk_bv (Bitvec.size (Term.mk (Kind.Op2 (Op2.Sub checked) x (Term.mk (Kind.BitVec k) t__5)) t__6)) (lit_add (ty (Term.mk (Kind.Op2 (Op2.Sub checked) x (Term.mk (Kind.BitVec k) t__5)) t__6)) (ty (Term.mk (Kind.Op2 (Op2.Sub checked) x (Term.mk (Kind.BitVec k) t__5)) t__6)) c k)))))

def Bitvec.lt.r_sub_const2.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (checked : Checked) (k : Int) (t__4 : Ty) (x : Term) (t__6 : Ty) (c : Int) (t__8 : Ty),
  (Bitvec.checked_has signed checked) = true →
  Refines FS (Bitvec.lt.spec signed (Term.mk (Kind.Op2 (Op2.Sub checked) (Term.mk (Kind.BitVec k) t__4) x) t__6) (Term.mk (Kind.BitVec c) t__8))
  ((if (Bitvec.overflows_sub signed (Bitvec.size (Term.mk (Kind.Op2 (Op2.Sub checked) (Term.mk (Kind.BitVec k) t__4) x) t__6)) k c)
   then (if (! signed)
        then v_true
        else (Term.mk (Kind.Op2 (Op2.Lt signed) (Term.mk (Kind.Op2 (Op2.Sub checked) (Term.mk (Kind.BitVec k) t__4) x) t__6) (Term.mk (Kind.BitVec c) t__8)) Ty.TBool))
   else (O.bitvec_lt signed (mk_bv (Bitvec.size (Term.mk (Kind.Op2 (Op2.Sub checked) (Term.mk (Kind.BitVec k) t__4) x) t__6)) (lit_sub (ty (Term.mk (Kind.Op2 (Op2.Sub checked) (Term.mk (Kind.BitVec k) t__4) x) t__6)) (ty (Term.mk (Kind.Op2 (Op2.Sub checked) (Term.mk (Kind.BitVec k) t__4) x) t__6)) k c)) x)))

def Bitvec.lt.r_ub_r.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (c : Int) (t__3 : Ty),
  ((! signed) && (decide ((Bitvec.unsigned_ub v1) < c))) = true →
  Refines FS (Bitvec.lt.spec signed v1 (Term.mk (Kind.BitVec c) t__3))
  (v_true)

def Bitvec.lt.r_ub_l.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v2 : Term) (c : Int) (t__2 : Ty),
  ((! signed) && (decide ((Bitvec.unsigned_ub v2) ≤ c))) = true →
  Refines FS (Bitvec.lt.spec signed (Term.mk (Kind.BitVec c) t__2) v2)
  (v_false)

def Bitvec.lt.r_to_unsigned_l.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v2 : Term) (c : Int) (t__2 : Ty),
  (signed && (Bitvec.is_checked_unsigned_op v2)) = true →
  Refines FS (Bitvec.lt.spec signed (Term.mk (Kind.BitVec c) t__2) v2)
  ((Bitvec.signed_to_unsigned_cmp O false true c (Term.mk (Kind.BitVec c) t__2) v2))

def Bitvec.lt.r_to_unsigned_r.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (c : Int) (t__3 : Ty),
  (signed && (Bitvec.is_checked_unsigned_op v1)) = true →
  Refines FS (Bitvec.lt.spec signed v1 (Term.mk (Kind.BitVec c) t__3))
  ((Bitvec.signed_to_unsigned_cmp O false false c v1 (Term.mk (Kind.BitVec c) t__3)))

def Bitvec.lt.r_default.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term),
  Refines FS (Bitvec.lt.spec signed v1 v2)
  ((Term.mk (Kind.Op2 (Op2.Lt signed) v1 v2) Ty.TBool))

end Kanon
