-- Generated by kanon from bool.kn, exists.kn, bitvec.kn, float.kn, ptr.kn, view.kn. Do not edit.
import Kanon.Statements
import Kanon.Model.Bitvec.rem

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace Kanon

open Classical Kanon

def Bitvec.rem.r_lits.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Nonzero v2 → Bitvec.rem.r_lits O signed v1 v2 = some res →
  Refines FS (Bitvec.rem.spec signed v1 v2) res

def Bitvec.rem.r_zero_r.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Nonzero v2 → Bitvec.rem.r_zero_r O signed v1 v2 = some res →
  Refines FS (Bitvec.rem.spec signed v1 v2) res

def Bitvec.rem.r_zero_l.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Nonzero v2 → Bitvec.rem.r_zero_l O signed v1 v2 = some res →
  Refines FS (Bitvec.rem.spec signed v1 v2) res

def Bitvec.rem.r_one_r.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Nonzero v2 → Bitvec.rem.r_one_r O signed v1 v2 = some res →
  Refines FS (Bitvec.rem.spec signed v1 v2) res

def Bitvec.rem.r_pow2.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Nonzero v2 → Bitvec.rem.r_pow2 O signed v1 v2 = some res →
  Refines FS (Bitvec.rem.spec signed v1 v2) res

def Bitvec.rem.r_add.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Nonzero v2 → Bitvec.rem.r_add O signed v1 v2 = some res →
  Refines FS (Bitvec.rem.spec signed v1 v2) res

def Bitvec.rem.r_rem_rem.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Nonzero v2 → Bitvec.rem.r_rem_rem O signed v1 v2 = some res →
  Refines FS (Bitvec.rem.spec signed v1 v2) res

def Bitvec.rem.r_default.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term) (res : Term), Nonzero v2 → Bitvec.rem.r_default O signed v1 v2 = some res →
  Refines FS (Bitvec.rem.spec signed v1 v2) res

def Bitvec.rem.r_lits.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (l : Int) (t__2 : Ty) (r : Int) (t__4 : Ty),
  Nonzero (Term.mk (Kind.BitVec r) t__4) →
  Refines FS (Bitvec.rem.spec signed (Term.mk (Kind.BitVec l) t__2) (Term.mk (Kind.BitVec r) t__4))
  ((mk_bv (Bitvec.size (Term.mk (Kind.BitVec l) t__2)) (if signed
                                                       then (lit_srem (ty (Term.mk (Kind.BitVec l) t__2)) (ty (Term.mk (Kind.BitVec r) t__4)) l r)
                                                       else (lit_urem (ty (Term.mk (Kind.BitVec l) t__2)) (ty (Term.mk (Kind.BitVec r) t__4)) l r))))

def Bitvec.rem.r_zero_r.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (kanon__2 : Int) (t__3 : Ty),
  Nonzero (Term.mk (Kind.BitVec kanon__2) t__3) →
  (decide (kanon__2 = (0 : Int))) = true →
  Refines FS (Bitvec.rem.spec signed v1 (Term.mk (Kind.BitVec kanon__2) t__3))
  (v1)

def Bitvec.rem.r_zero_l.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v2 : Term) (kanon__1 : Int) (t__2 : Ty),
  Nonzero v2 →
  (decide (kanon__1 = (0 : Int))) = true →
  Refines FS (Bitvec.rem.spec signed (Term.mk (Kind.BitVec kanon__1) t__2) v2)
  ((bv_zero (Bitvec.size (Term.mk (Kind.BitVec kanon__1) t__2))))

def Bitvec.rem.r_one_r.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (kanon__2 : Int) (t__3 : Ty),
  Nonzero (Term.mk (Kind.BitVec kanon__2) t__3) →
  ((decide (kanon__2 = (1 : Int))) && (! signed)) = true →
  Refines FS (Bitvec.rem.spec signed v1 (Term.mk (Kind.BitVec kanon__2) t__3))
  ((bv_zero (Bitvec.size v1)))

def Bitvec.rem.r_pow2.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (r : Int) (t__3 : Ty),
  Nonzero (Term.mk (Kind.BitVec r) t__3) →
  ((! signed) && ((Bitvec.is_pow2 r) && (decide (r > (1 : Int))))) = true →
  Refines FS (Bitvec.rem.spec signed v1 (Term.mk (Kind.BitVec r) t__3))
  ((let sz := (Bitvec.size v1);
   (let bitwidth := (log2 r);
   (let lower := (O.bitvec_extract (0 : Int) (bitwidth - (1 : Int)) v1);
   (O.bitvec_extend_ false (sz - bitwidth) lower)))))

def Bitvec.rem.r_add.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (ck : Checked) (d : Int) (t__4 : Ty) (r : Term) (t__6 : Ty) (d2 : Int) (t__9 : Ty),
  Nonzero (Term.mk (Kind.BitVec d2) t__9) →
  ((! signed) && (ck.unsigned && (decide (d = d2)))) = true →
  Refines FS (Bitvec.rem.spec signed (Term.mk (Kind.Op2 (Op2.Add ck) (Term.mk (Kind.BitVec d) t__4) r) t__6) (Term.mk (Kind.BitVec d2) t__9))
  ((O.bitvec_rem signed r (Term.mk (Kind.BitVec d2) t__9)))

def Bitvec.rem.r_add.swap.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (ck : Checked) (r : Term) (d : Int) (t__4 : Ty) (t__6 : Ty) (d2 : Int) (t__9 : Ty),
  Nonzero (Term.mk (Kind.BitVec d2) t__9) →
  ((! signed) && (ck.unsigned && (decide (d = d2)))) = true →
  Refines FS (Bitvec.rem.spec signed (Term.mk (Kind.Op2 (Op2.Add ck) r (Term.mk (Kind.BitVec d) t__4)) t__6) (Term.mk (Kind.BitVec d2) t__9))
  ((O.bitvec_rem signed r (Term.mk (Kind.BitVec d2) t__9)))

def Bitvec.rem.r_rem_rem.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (r : Term) (r1 : Int) (t__5 : Ty) (t__7 : Ty) (r2 : Int) (t__9 : Ty),
  Nonzero (Term.mk (Kind.BitVec r2) t__9) →
  ((! signed) && ((decide (r1 > (0 : Int))) && ((decide (r2 > (0 : Int))) && ((Bitvec.udivides r2 r1) || (Bitvec.udivides r1 r2))))) = true →
  Refines FS (Bitvec.rem.spec signed (Term.mk (Kind.Op2 (Op2.Rem false) r (Term.mk (Kind.BitVec r1) t__5)) t__7) (Term.mk (Kind.BitVec r2) t__9))
  ((let rhs := (if (decide (r1 ≤ r2))
               then (Term.mk (Kind.BitVec r1) t__5)
               else (Term.mk (Kind.BitVec r2) t__9));
   (O.bitvec_rem signed r rhs)))

def Bitvec.rem.r_default.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (signed : Bool) (v1 : Term) (v2 : Term),
  Nonzero v2 →
  Refines FS (Bitvec.rem.spec signed v1 v2)
  ((Term.mk (Kind.Op2 (Op2.Rem signed) v1 v2) (ty v1)))

end Kanon
