-- Generated by kanon from bool.kn, exists.kn, bitvec.kn, float.kn, ptr.kn, view.kn. Do not edit.
import Kanon.Statements
import Kanon.Model.Float.fmod_of_rem

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace Kanon

open Classical Kanon

def Float.fmod_of_rem.r_main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (r : Term) (v1 : Term) (v2 : Term) (res : Term), Float.fmod_of_rem.r_main O r v1 v2 = some res →
  Refines FS (Float.fmod_of_rem.spec r v1 v2) res

def Float.fmod_of_rem.r_main.main.Stmt : Prop :=
  ∀ (FS : FloatSem) (O : Ops), O.Sound FS →
  ∀ (r : Term) (v1 : Term) (v2 : Term),
  Refines FS (Float.fmod_of_rem.spec r v1 v2)
  ((O.bool_ite (O.bool_eq (O.float_is_negative r) (O.float_is_negative v1)) r (O.float_add r (O.bool_ite (O.float_is_negative v1) (O.float_neg (O.float_abs v2)) (O.float_abs v2)))))

end Kanon
