-- Generated by kanon from ptr.knl, ptr.kn. Do not edit.
import KanonCore.Embed
import CoreMod.Types
import CoreMod.Abstract

set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false
set_option maxHeartbeats 1000000

noncomputable section

namespace PtrMod

open Classical Kanon

/-- The sorts of the module. -/
inductive Srt where
  | TPointer (x1 : Int)
  deriving DecidableEq, Repr, Inhabited

/-- The nodes of the module, over the terms `T` of a language. -/
inductive Node (T : Type) where
  | Ptr (a1 : T) (a2 : T)
  | GetPtrLoc (a1 : T)
  | GetPtrOfs (a1 : T)

namespace Node

variable {T U : Type}

/-- The node with its children mapped by `f`. -/
def map (f : T → U) : Node T → Node U
  | (.Ptr a1 a2) => (.Ptr (f a1) (f a2))
  | (.GetPtrLoc a1) => (.GetPtrLoc (f a1))
  | (.GetPtrOfs a1) => (.GetPtrOfs (f a1))

/-- Every child of the node satisfies `P`. -/
def All (P : T → Prop) : Node T → Prop
  | (.Ptr a1 a2) => P a1 ∧ P a2
  | (.GetPtrLoc a1) => P a1
  | (.GetPtrOfs a1) => P a1

/-- The nodes have the same arguments, and their children are related by `R`. -/
def Rel (R : T → U → Prop) : Node T → Node U → Prop
  | (.Ptr a1 a2), (.Ptr a1' a2') => R a1 a1' ∧ R a2 a2'
  | (.GetPtrLoc a1), (.GetPtrLoc a1') => R a1 a1'
  | (.GetPtrOfs a1), (.GetPtrOfs a1') => R a1 a1'
  | _, _ => False

/-- The children of the node, in order. -/
def children : Node T → List T
  | (.Ptr a1 a2) => [a1] ++ [a2]
  | (.GetPtrLoc a1) => [a1]
  | (.GetPtrOfs a1) => [a1]

/-- Every child of the node satisfies `P` when all its children do. -/
theorem all_iff (P : T → Prop) (n : Node T) : n.All P ↔ ∀ c ∈ n.children, P c := by
  cases n <;> simp [All, children, or_imp, forall_and]

end Node

end PtrMod
