-- Generated by kanon from bitvec.knl, bitvec.kn. Do not edit.
import BitvecMod.Statements

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace BitvecMod

open Classical Kanon

def Bitvec.div.r_lits.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} {LBool : KanonBool.Syntax B} {LCore : CoreMod.Syntax B} (L : BitvecMod.Syntax B LBool LCore) [KanonBool.Sem LBool] [CoreMod.Sem LCore] [Sem L] (O : Ops L), O.Sound →
  ∀ (signed : Bool) (l : Int) (t__2 : S.Ty) (r : Int) (t__4 : S.Ty),
  L.Nonzero (B.node (L.BitVecK r) t__4) →
  S.Refines (BitvecMod.Bitvec.div.spec L signed (B.node (L.BitVecK l) t__2) (B.node (L.BitVecK r) t__4))
  ((L.bitvec_mk_bv (L.bitvec_size (B.node (L.BitVecK l) t__2)) (if signed
                                                               then (L.bitvec_lit_sdiv (S.ty (B.node (L.BitVecK l) t__2)) (S.ty (B.node (L.BitVecK r) t__4)) l r)
                                                               else (L.bitvec_lit_udiv (S.ty (B.node (L.BitVecK l) t__2)) (S.ty (B.node (L.BitVecK r) t__4)) l r))))

def Bitvec.div.r_one.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} {LBool : KanonBool.Syntax B} {LCore : CoreMod.Syntax B} (L : BitvecMod.Syntax B LBool LCore) [KanonBool.Sem LBool] [CoreMod.Sem LCore] [Sem L] (O : Ops L), O.Sound →
  ∀ (signed : Bool) (v1 : S.Term) (kanon__2 : Int) (t__3 : S.Ty),
  L.Nonzero (B.node (L.BitVecK kanon__2) t__3) →
  (decide (kanon__2 = (1 : Int))) = true →
  S.Refines (BitvecMod.Bitvec.div.spec L signed v1 (B.node (L.BitVecK kanon__2) t__3))
  (v1)

def Bitvec.div.r_mul_lits.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} {LBool : KanonBool.Syntax B} {LCore : CoreMod.Syntax B} (L : BitvecMod.Syntax B LBool LCore) [KanonBool.Sem LBool] [CoreMod.Sem LCore] [Sem L] (O : Ops L), O.Sound →
  ∀ (signed : Bool) (checked : CoreMod.Checked) (w__3 : Int) (t__4 : S.Ty) (w__6 : Int) (t__7 : S.Ty) (t__9 : S.Ty) (w__11 : Int) (t__12 : S.Ty),
  L.Nonzero (B.node (L.BitVecK w__11) t__12) →
  S.Refines (BitvecMod.Bitvec.div.spec L signed (B.node (L.MulK checked (B.node (L.BitVecK w__3) t__4) (B.node (L.BitVecK w__6) t__7)) t__9) (B.node (L.BitVecK w__11) t__12))
  ((O.bitvec_div signed (O.bitvec_mul checked (B.node (L.BitVecK w__3) t__4) (B.node (L.BitVecK w__6) t__7)) (B.node (L.BitVecK w__11) t__12)))

def Bitvec.div.r_mul_div.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} {LBool : KanonBool.Syntax B} {LCore : CoreMod.Syntax B} (L : BitvecMod.Syntax B LBool LCore) [KanonBool.Sem LBool] [CoreMod.Sem LCore] [Sem L] (O : Ops L), O.Sound →
  ∀ (signed : Bool) (signed__2 : Bool) (n : Int) (t__5 : S.Ty) (x : S.Term) (t__7 : S.Ty) (d : Int) (t__10 : S.Ty),
  L.Nonzero (B.node (L.BitVecK d) t__10) →
  ((! signed) && ((decide (d ≠ (0 : Int))) && (L.bitvec_udivides d n))) = true →
  S.Refines (BitvecMod.Bitvec.div.spec L signed (B.node (L.MulK ⟨signed__2, true⟩ (B.node (L.BitVecK n) t__5) x) t__7) (B.node (L.BitVecK d) t__10))
  ((O.bitvec_mul L.bitvec_checked_unsigned x (L.bitvec_mk_bv (L.bitvec_size (B.node (L.MulK ⟨signed__2, true⟩ (B.node (L.BitVecK n) t__5) x) t__7)) (L.bitvec_lit_udiv (S.ty (B.node (L.MulK ⟨signed__2, true⟩ (B.node (L.BitVecK n) t__5) x) t__7)) (S.ty (B.node (L.BitVecK d) t__10)) n d))))

def Bitvec.div.r_mul_div.swap.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} {LBool : KanonBool.Syntax B} {LCore : CoreMod.Syntax B} (L : BitvecMod.Syntax B LBool LCore) [KanonBool.Sem LBool] [CoreMod.Sem LCore] [Sem L] (O : Ops L), O.Sound →
  ∀ (signed : Bool) (signed__2 : Bool) (x : S.Term) (n : Int) (t__5 : S.Ty) (t__7 : S.Ty) (d : Int) (t__10 : S.Ty),
  L.Nonzero (B.node (L.BitVecK d) t__10) →
  ((! signed) && ((decide (d ≠ (0 : Int))) && (L.bitvec_udivides d n))) = true →
  S.Refines (BitvecMod.Bitvec.div.spec L signed (B.node (L.MulK ⟨signed__2, true⟩ x (B.node (L.BitVecK n) t__5)) t__7) (B.node (L.BitVecK d) t__10))
  ((O.bitvec_mul L.bitvec_checked_unsigned x (L.bitvec_mk_bv (L.bitvec_size (B.node (L.MulK ⟨signed__2, true⟩ x (B.node (L.BitVecK n) t__5)) t__7)) (L.bitvec_lit_udiv (S.ty (B.node (L.MulK ⟨signed__2, true⟩ x (B.node (L.BitVecK n) t__5)) t__7)) (S.ty (B.node (L.BitVecK d) t__10)) n d))))

def Bitvec.div.r_div_mul.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} {LBool : KanonBool.Syntax B} {LCore : CoreMod.Syntax B} (L : BitvecMod.Syntax B LBool LCore) [KanonBool.Sem LBool] [CoreMod.Sem LCore] [Sem L] (O : Ops L), O.Sound →
  ∀ (signed : Bool) (signed__2 : Bool) (n : Int) (t__5 : S.Ty) (x : S.Term) (t__7 : S.Ty) (d : Int) (t__10 : S.Ty),
  L.Nonzero (B.node (L.BitVecK d) t__10) →
  ((! signed) && ((decide (n ≠ (0 : Int))) && (L.bitvec_udivides n d))) = true →
  S.Refines (BitvecMod.Bitvec.div.spec L signed (B.node (L.MulK ⟨signed__2, true⟩ (B.node (L.BitVecK n) t__5) x) t__7) (B.node (L.BitVecK d) t__10))
  ((O.bitvec_div signed x (L.bitvec_mk_bv (L.bitvec_size (B.node (L.MulK ⟨signed__2, true⟩ (B.node (L.BitVecK n) t__5) x) t__7)) (L.bitvec_lit_udiv (S.ty (B.node (L.BitVecK d) t__10)) (S.ty (B.node (L.MulK ⟨signed__2, true⟩ (B.node (L.BitVecK n) t__5) x) t__7)) d n))))

def Bitvec.div.r_div_mul.swap.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} {LBool : KanonBool.Syntax B} {LCore : CoreMod.Syntax B} (L : BitvecMod.Syntax B LBool LCore) [KanonBool.Sem LBool] [CoreMod.Sem LCore] [Sem L] (O : Ops L), O.Sound →
  ∀ (signed : Bool) (signed__2 : Bool) (x : S.Term) (n : Int) (t__5 : S.Ty) (t__7 : S.Ty) (d : Int) (t__10 : S.Ty),
  L.Nonzero (B.node (L.BitVecK d) t__10) →
  ((! signed) && ((decide (n ≠ (0 : Int))) && (L.bitvec_udivides n d))) = true →
  S.Refines (BitvecMod.Bitvec.div.spec L signed (B.node (L.MulK ⟨signed__2, true⟩ x (B.node (L.BitVecK n) t__5)) t__7) (B.node (L.BitVecK d) t__10))
  ((O.bitvec_div signed x (L.bitvec_mk_bv (L.bitvec_size (B.node (L.MulK ⟨signed__2, true⟩ x (B.node (L.BitVecK n) t__5)) t__7)) (L.bitvec_lit_udiv (S.ty (B.node (L.BitVecK d) t__10)) (S.ty (B.node (L.MulK ⟨signed__2, true⟩ x (B.node (L.BitVecK n) t__5)) t__7)) d n))))

def Bitvec.div.r_div_div.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} {LBool : KanonBool.Syntax B} {LCore : CoreMod.Syntax B} (L : BitvecMod.Syntax B LBool LCore) [KanonBool.Sem LBool] [CoreMod.Sem LCore] [Sem L] (O : Ops L), O.Sound →
  ∀ (signed : Bool) (x : S.Term) (n : Int) (t__5 : S.Ty) (t__6 : S.Ty) (d : Int) (t__8 : S.Ty),
  L.Nonzero (B.node (L.BitVecK d) t__8) →
  ((! signed) && ((decide (n ≠ (0 : Int))) && (! (L.bitvec_overflows_mul false (L.bitvec_size (B.node (L.DivK false x (B.node (L.BitVecK n) t__5)) t__6)) n d)))) = true →
  S.Refines (BitvecMod.Bitvec.div.spec L signed (B.node (L.DivK false x (B.node (L.BitVecK n) t__5)) t__6) (B.node (L.BitVecK d) t__8))
  ((O.bitvec_div signed x (L.bitvec_mk_bv (L.bitvec_size (B.node (L.DivK false x (B.node (L.BitVecK n) t__5)) t__6)) (L.bitvec_lit_mul (S.ty (B.node (L.DivK false x (B.node (L.BitVecK n) t__5)) t__6)) (S.ty (B.node (L.BitVecK d) t__8)) n d))))

def Bitvec.div.r_zext.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} {LBool : KanonBool.Syntax B} {LCore : CoreMod.Syntax B} (L : BitvecMod.Syntax B LBool LCore) [KanonBool.Sem LBool] [CoreMod.Sem LCore] [Sem L] (O : Ops L), O.Sound →
  ∀ (signed : Bool) («by» : Int) (x : S.Term) (t__5 : S.Ty) (z : Int) (t__7 : S.Ty),
  L.Nonzero (B.node (L.BitVecK z) t__7) →
  ((! signed) && (decide ((L.bitvec_msb_of (B.node (L.BitVecK z) t__7)) < (L.bitvec_size x)))) = true →
  S.Refines (BitvecMod.Bitvec.div.spec L signed (B.node (L.BvExtendK false «by» x) t__5) (B.node (L.BitVecK z) t__7))
  ((O.bitvec_extend_ false «by» (O.bitvec_div signed x (L.bitvec_mk_masked (L.bitvec_size x) z))))

def Bitvec.div.r_default.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} {LBool : KanonBool.Syntax B} {LCore : CoreMod.Syntax B} (L : BitvecMod.Syntax B LBool LCore) [KanonBool.Sem LBool] [CoreMod.Sem LCore] [Sem L] (O : Ops L), O.Sound →
  ∀ (signed : Bool) (v1 : S.Term) (v2 : S.Term),
  L.Nonzero v2 →
  S.Refines (BitvecMod.Bitvec.div.spec L signed v1 v2)
  ((B.node (L.DivK signed v1 v2) (S.ty v1)))

end BitvecMod
