-- Generated by kanon from bitvec.knl, bitvec.kn. Do not edit.
import BitvecMod.Statements

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace BitvecMod

open Classical Kanon

def Bitvec.extend_.r_zero.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} {LBool : KanonBool.Syntax B} {LCore : CoreMod.Syntax B} (L : BitvecMod.Syntax B LBool LCore) [KanonBool.Sem LBool] [CoreMod.Sem LCore] [Sem L] (O : Ops L), O.Sound →
  ∀ (signed : Bool) (extend_by : Int) (v : S.Term),
  (decide (extend_by = (0 : Int))) = true →
  S.Refines (BitvecMod.Bitvec.extend_.spec L signed extend_by v)
  (v)

def Bitvec.extend_.r_lit.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} {LBool : KanonBool.Syntax B} {LCore : CoreMod.Syntax B} (L : BitvecMod.Syntax B LBool LCore) [KanonBool.Sem LBool] [CoreMod.Sem LCore] [Sem L] (O : Ops L), O.Sound →
  ∀ (signed : Bool) (extend_by : Int) (bv : Int) (t__2 : S.Ty),
  S.Refines (BitvecMod.Bitvec.extend_.spec L signed extend_by (B.node (L.BitVecK bv) t__2))
  ((L.bitvec_mk_bv ((L.bitvec_size (B.node (L.BitVecK bv) t__2)) + extend_by) 
  (if signed
  then (L.bitvec_lit_sext extend_by (S.ty (B.node (L.BitVecK bv) t__2)) bv)
  else (L.bitvec_lit_zext extend_by (S.ty (B.node (L.BitVecK bv) t__2)) bv))))

def Bitvec.extend_.r_extend.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} {LBool : KanonBool.Syntax B} {LCore : CoreMod.Syntax B} (L : BitvecMod.Syntax B LBool LCore) [KanonBool.Sem LBool] [CoreMod.Sem LCore] [Sem L] (O : Ops L), O.Sound →
  ∀ (signed : Bool) (extend_by : Int) (s : Bool) (prev_by : Int) (v : S.Term) (t__5 : S.Ty),
  (decide (s = signed)) = true →
  S.Refines (BitvecMod.Bitvec.extend_.spec L signed extend_by (B.node (L.BvExtendK s prev_by v) t__5))
  ((O.bitvec_extend_ signed (prev_by + extend_by) v))

def Bitvec.extend_.r_ite.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} {LBool : KanonBool.Syntax B} {LCore : CoreMod.Syntax B} (L : BitvecMod.Syntax B LBool LCore) [KanonBool.Sem LBool] [CoreMod.Sem LCore] [Sem L] (O : Ops L), O.Sound →
  ∀ (signed : Bool) (extend_by : Int) (b : S.Term) (l : S.Term) (r : S.Term) (t__5 : S.Ty),
  S.Refines (BitvecMod.Bitvec.extend_.spec L signed extend_by (B.node (LBool.IteK b l r) t__5))
  ((O.bool_ite b (O.bitvec_extend_ signed extend_by l) (O.bitvec_extend_ signed extend_by r)))

def Bitvec.extend_.r_of_bool.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} {LBool : KanonBool.Syntax B} {LCore : CoreMod.Syntax B} (L : BitvecMod.Syntax B LBool LCore) [KanonBool.Sem LBool] [CoreMod.Sem LCore] [Sem L] (O : Ops L), O.Sound →
  ∀ (signed : Bool) (extend_by : Int) (n : Int) (b : S.Term) (t__4 : S.Ty),
  ((! signed) || (decide (n > (1 : Int)))) = true →
  S.Refines (BitvecMod.Bitvec.extend_.spec L signed extend_by (B.node (L.BvOfBoolK n b) t__4))
  ((O.bitvec_of_bool ((L.bitvec_size (B.node (L.BvOfBoolK n b) t__4)) + extend_by) b))

def Bitvec.extend_.r_default.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} {LBool : KanonBool.Syntax B} {LCore : CoreMod.Syntax B} (L : BitvecMod.Syntax B LBool LCore) [KanonBool.Sem LBool] [CoreMod.Sem LCore] [Sem L] (O : Ops L), O.Sound →
  ∀ (signed : Bool) (extend_by : Int) (v : S.Term),
  S.Refines (BitvecMod.Bitvec.extend_.spec L signed extend_by v)
  ((B.node (L.BvExtendK signed extend_by v) (L.TBitVector ((L.bitvec_size v) + extend_by))))

end BitvecMod
