-- Generated by kanon from bitvec.knl, bitvec.kn. Do not edit.
import BitvecMod.Lift

set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false
set_option maxHeartbeats 1000000

noncomputable section

namespace BitvecMod

open Classical Kanon

def Bitvec.leq.r_same.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S), O.Sound →
  ∀ (signed : Bool) (v1 : S.Term) (v2 : S.Term),
  (decide (v1 = v2)) = true →
  S.Refines (BitvecMod.Bitvec.leq.spec signed v1 v2)
  (KanonBool.v_true)

def Bitvec.leq.r_lits.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S), O.Sound →
  ∀ (signed : Bool) (l : Int) (t__2 : S.Ty) (r : Int) (t__4 : S.Ty),
  S.Refines (BitvecMod.Bitvec.leq.spec signed (BitvecMod.mk (.BitVec l) t__2) (BitvecMod.mk (.BitVec r) t__4))
  ((KanonBool.Bool.of_bool (decide ((BitvecMod.Bitvec.to_z signed (BitvecMod.Bitvec.size (BitvecMod.mk (.BitVec l) t__2)) l) ≤ (BitvecMod.Bitvec.to_z signed (BitvecMod.Bitvec.size (BitvecMod.mk (.BitVec l) t__2)) r)))))

def Bitvec.leq.r_negs.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S), O.Sound →
  ∀ (signed : Bool) (a : S.Term) (t__4 : S.Ty) (b : S.Term) (t__8 : S.Ty),
  signed = true →
  S.Refines (BitvecMod.Bitvec.leq.spec signed (BitvecMod.mk (.Neg true a) t__4) (BitvecMod.mk (.Neg true b) t__8))
  ((O.bitvec_leq signed b a))

def Bitvec.leq.r_neg_l.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S), O.Sound →
  ∀ (signed : Bool) (a : S.Term) (t__4 : S.Ty) (c : Int) (t__6 : S.Ty),
  (signed && (! (BitvecMod.Bitvec.is_int_min (BitvecMod.Bitvec.size (BitvecMod.mk (.Neg true a) t__4)) c))) = true →
  S.Refines (BitvecMod.Bitvec.leq.spec signed (BitvecMod.mk (.Neg true a) t__4) (BitvecMod.mk (.BitVec c) t__6))
  ((O.bitvec_leq signed (O.bitvec_neg false (BitvecMod.mk (.BitVec c) t__6)) a))

def Bitvec.leq.r_neg_r.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S), O.Sound →
  ∀ (signed : Bool) (c : Int) (t__2 : S.Ty) (a : S.Term) (t__6 : S.Ty),
  (signed && (! (BitvecMod.Bitvec.is_int_min (BitvecMod.Bitvec.size (BitvecMod.mk (.BitVec c) t__2)) c))) = true →
  S.Refines (BitvecMod.Bitvec.leq.spec signed (BitvecMod.mk (.BitVec c) t__2) (BitvecMod.mk (.Neg true a) t__6))
  ((O.bitvec_leq signed a (O.bitvec_neg false (BitvecMod.mk (.BitVec c) t__2))))

def Bitvec.leq.r_const_add.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S), O.Sound →
  ∀ (signed : Bool) (c : Int) (t__2 : S.Ty) (checked : CoreMod.Checked) (r : Int) (t__6 : S.Ty) (x : S.Term) (t__8 : S.Ty),
  (BitvecMod.Bitvec.checked_has signed checked) = true →
  S.Refines (BitvecMod.Bitvec.leq.spec signed (BitvecMod.mk (.BitVec c) t__2) (BitvecMod.mk (.Add checked (BitvecMod.mk (.BitVec r) t__6) x) t__8))
  ((if (BitvecMod.Bitvec.overflows_sub signed (BitvecMod.Bitvec.size (BitvecMod.mk (.BitVec c) t__2)) c r)
   then (if (! signed)
        then KanonBool.v_true
        else (BitvecMod.mk (.Leq signed (BitvecMod.mk (.BitVec c) t__2) (BitvecMod.mk (.Add checked (BitvecMod.mk (.BitVec r) t__6) x) t__8)) (KanonBool.sort .TBool)))
   else (O.bitvec_leq signed (BitvecMod.mk_bv (BitvecMod.Bitvec.size (BitvecMod.mk (.BitVec c) t__2)) (BitvecMod.lit_sub (S.ty (BitvecMod.mk (.BitVec c) t__2)) (S.ty (BitvecMod.mk (.BitVec c) t__2)) c r)) x)))

def Bitvec.leq.r_const_add.swap.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S), O.Sound →
  ∀ (signed : Bool) (c : Int) (t__2 : S.Ty) (checked : CoreMod.Checked) (x : S.Term) (r : Int) (t__6 : S.Ty) (t__8 : S.Ty),
  (BitvecMod.Bitvec.checked_has signed checked) = true →
  S.Refines (BitvecMod.Bitvec.leq.spec signed (BitvecMod.mk (.BitVec c) t__2) (BitvecMod.mk (.Add checked x (BitvecMod.mk (.BitVec r) t__6)) t__8))
  ((if (BitvecMod.Bitvec.overflows_sub signed (BitvecMod.Bitvec.size (BitvecMod.mk (.BitVec c) t__2)) c r)
   then (if (! signed)
        then KanonBool.v_true
        else (BitvecMod.mk (.Leq signed (BitvecMod.mk (.BitVec c) t__2) (BitvecMod.mk (.Add checked x (BitvecMod.mk (.BitVec r) t__6)) t__8)) (KanonBool.sort .TBool)))
   else (O.bitvec_leq signed (BitvecMod.mk_bv (BitvecMod.Bitvec.size (BitvecMod.mk (.BitVec c) t__2)) (BitvecMod.lit_sub (S.ty (BitvecMod.mk (.BitVec c) t__2)) (S.ty (BitvecMod.mk (.BitVec c) t__2)) c r)) x)))

def Bitvec.leq.r_add_const.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S), O.Sound →
  ∀ (signed : Bool) (checked : CoreMod.Checked) (l : Int) (t__4 : S.Ty) (x : S.Term) (t__6 : S.Ty) (c : Int) (t__9 : S.Ty),
  (BitvecMod.Bitvec.checked_has signed checked) = true →
  S.Refines (BitvecMod.Bitvec.leq.spec signed (BitvecMod.mk (.Add checked (BitvecMod.mk (.BitVec l) t__4) x) t__6) (BitvecMod.mk (.BitVec c) t__9))
  ((if (BitvecMod.Bitvec.overflows_sub signed (BitvecMod.Bitvec.size (BitvecMod.mk (.Add checked (BitvecMod.mk (.BitVec l) t__4) x) t__6)) c l)
   then (if (! signed)
        then KanonBool.v_false
        else (BitvecMod.mk (.Leq signed (BitvecMod.mk (.Add checked (BitvecMod.mk (.BitVec l) t__4) x) t__6) (BitvecMod.mk (.BitVec c) t__9)) (KanonBool.sort .TBool)))
   else (O.bitvec_leq signed x (BitvecMod.mk_bv (BitvecMod.Bitvec.size (BitvecMod.mk (.Add checked (BitvecMod.mk (.BitVec l) t__4) x) t__6)) (BitvecMod.lit_sub (S.ty (BitvecMod.mk (.Add checked (BitvecMod.mk (.BitVec l) t__4) x) t__6)) (S.ty (BitvecMod.mk (.Add checked (BitvecMod.mk (.BitVec l) t__4) x) t__6)) c l)))))

def Bitvec.leq.r_add_const.swap.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S), O.Sound →
  ∀ (signed : Bool) (checked : CoreMod.Checked) (x : S.Term) (l : Int) (t__4 : S.Ty) (t__6 : S.Ty) (c : Int) (t__9 : S.Ty),
  (BitvecMod.Bitvec.checked_has signed checked) = true →
  S.Refines (BitvecMod.Bitvec.leq.spec signed (BitvecMod.mk (.Add checked x (BitvecMod.mk (.BitVec l) t__4)) t__6) (BitvecMod.mk (.BitVec c) t__9))
  ((if (BitvecMod.Bitvec.overflows_sub signed (BitvecMod.Bitvec.size (BitvecMod.mk (.Add checked x (BitvecMod.mk (.BitVec l) t__4)) t__6)) c l)
   then (if (! signed)
        then KanonBool.v_false
        else (BitvecMod.mk (.Leq signed (BitvecMod.mk (.Add checked x (BitvecMod.mk (.BitVec l) t__4)) t__6) (BitvecMod.mk (.BitVec c) t__9)) (KanonBool.sort .TBool)))
   else (O.bitvec_leq signed x (BitvecMod.mk_bv (BitvecMod.Bitvec.size (BitvecMod.mk (.Add checked x (BitvecMod.mk (.BitVec l) t__4)) t__6)) (BitvecMod.lit_sub (S.ty (BitvecMod.mk (.Add checked x (BitvecMod.mk (.BitVec l) t__4)) t__6)) (S.ty (BitvecMod.mk (.Add checked x (BitvecMod.mk (.BitVec l) t__4)) t__6)) c l)))))

def Bitvec.leq.r_add_add.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S), O.Sound →
  ∀ (signed : Bool) (checked_l : CoreMod.Checked) (l : Int) (t__4 : S.Ty) (y : S.Term) (t__6 : S.Ty) (checked_r : CoreMod.Checked) (r : Int) (t__11 : S.Ty) (x : S.Term) (t__13 : S.Ty),
  ((BitvecMod.Bitvec.checked_has signed checked_l) && (BitvecMod.Bitvec.checked_has signed checked_r)) = true →
  S.Refines (BitvecMod.Bitvec.leq.spec signed (BitvecMod.mk (.Add checked_l (BitvecMod.mk (.BitVec l) t__4) y) t__6) (BitvecMod.mk (.Add checked_r (BitvecMod.mk (.BitVec r) t__11) x) t__13))
  ((let n := (BitvecMod.Bitvec.size (BitvecMod.mk (.Add checked_l (BitvecMod.mk (.BitVec l) t__4) y) t__6));
   (let sty := (S.ty (BitvecMod.mk (.Add checked_l (BitvecMod.mk (.BitVec l) t__4) y) t__6));
   (if (BitvecMod.Bitvec.const_keeps_in_range signed n l r)
   then (O.bitvec_leq signed (O.bitvec_add (BitvecMod.Bitvec.checked_of_signed signed) y (BitvecMod.mk_bv n (BitvecMod.lit_sub sty sty l r))) x)
   else (if (BitvecMod.Bitvec.const_keeps_in_range signed n r l)
        then (O.bitvec_leq signed y (O.bitvec_add (BitvecMod.Bitvec.checked_of_signed signed) x (BitvecMod.mk_bv n (BitvecMod.lit_sub sty sty r l))))
        else (BitvecMod.mk (.Leq signed (BitvecMod.mk (.Add checked_l (BitvecMod.mk (.BitVec l) t__4) y) t__6) (BitvecMod.mk (.Add checked_r (BitvecMod.mk (.BitVec r) t__11) x) t__13)) (KanonBool.sort .TBool)))))))

def Bitvec.leq.r_add_add.swap2.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S), O.Sound →
  ∀ (signed : Bool) (checked_l : CoreMod.Checked) (l : Int) (t__4 : S.Ty) (y : S.Term) (t__6 : S.Ty) (checked_r : CoreMod.Checked) (x : S.Term) (r : Int) (t__11 : S.Ty) (t__13 : S.Ty),
  ((BitvecMod.Bitvec.checked_has signed checked_l) && (BitvecMod.Bitvec.checked_has signed checked_r)) = true →
  S.Refines (BitvecMod.Bitvec.leq.spec signed (BitvecMod.mk (.Add checked_l (BitvecMod.mk (.BitVec l) t__4) y) t__6) (BitvecMod.mk (.Add checked_r x (BitvecMod.mk (.BitVec r) t__11)) t__13))
  ((let n := (BitvecMod.Bitvec.size (BitvecMod.mk (.Add checked_l (BitvecMod.mk (.BitVec l) t__4) y) t__6));
   (let sty := (S.ty (BitvecMod.mk (.Add checked_l (BitvecMod.mk (.BitVec l) t__4) y) t__6));
   (if (BitvecMod.Bitvec.const_keeps_in_range signed n l r)
   then (O.bitvec_leq signed (O.bitvec_add (BitvecMod.Bitvec.checked_of_signed signed) y (BitvecMod.mk_bv n (BitvecMod.lit_sub sty sty l r))) x)
   else (if (BitvecMod.Bitvec.const_keeps_in_range signed n r l)
        then (O.bitvec_leq signed y (O.bitvec_add (BitvecMod.Bitvec.checked_of_signed signed) x (BitvecMod.mk_bv n (BitvecMod.lit_sub sty sty r l))))
        else (BitvecMod.mk (.Leq signed (BitvecMod.mk (.Add checked_l (BitvecMod.mk (.BitVec l) t__4) y) t__6) (BitvecMod.mk (.Add checked_r x (BitvecMod.mk (.BitVec r) t__11)) t__13)) (KanonBool.sort .TBool)))))))

def Bitvec.leq.r_add_add.swap1.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S), O.Sound →
  ∀ (signed : Bool) (checked_l : CoreMod.Checked) (y : S.Term) (l : Int) (t__4 : S.Ty) (t__6 : S.Ty) (checked_r : CoreMod.Checked) (r : Int) (t__11 : S.Ty) (x : S.Term) (t__13 : S.Ty),
  ((BitvecMod.Bitvec.checked_has signed checked_l) && (BitvecMod.Bitvec.checked_has signed checked_r)) = true →
  S.Refines (BitvecMod.Bitvec.leq.spec signed (BitvecMod.mk (.Add checked_l y (BitvecMod.mk (.BitVec l) t__4)) t__6) (BitvecMod.mk (.Add checked_r (BitvecMod.mk (.BitVec r) t__11) x) t__13))
  ((let n := (BitvecMod.Bitvec.size (BitvecMod.mk (.Add checked_l y (BitvecMod.mk (.BitVec l) t__4)) t__6));
   (let sty := (S.ty (BitvecMod.mk (.Add checked_l y (BitvecMod.mk (.BitVec l) t__4)) t__6));
   (if (BitvecMod.Bitvec.const_keeps_in_range signed n l r)
   then (O.bitvec_leq signed (O.bitvec_add (BitvecMod.Bitvec.checked_of_signed signed) y (BitvecMod.mk_bv n (BitvecMod.lit_sub sty sty l r))) x)
   else (if (BitvecMod.Bitvec.const_keeps_in_range signed n r l)
        then (O.bitvec_leq signed y (O.bitvec_add (BitvecMod.Bitvec.checked_of_signed signed) x (BitvecMod.mk_bv n (BitvecMod.lit_sub sty sty r l))))
        else (BitvecMod.mk (.Leq signed (BitvecMod.mk (.Add checked_l y (BitvecMod.mk (.BitVec l) t__4)) t__6) (BitvecMod.mk (.Add checked_r (BitvecMod.mk (.BitVec r) t__11) x) t__13)) (KanonBool.sort .TBool)))))))

def Bitvec.leq.r_add_add.swap1_swap2.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S), O.Sound →
  ∀ (signed : Bool) (checked_l : CoreMod.Checked) (y : S.Term) (l : Int) (t__4 : S.Ty) (t__6 : S.Ty) (checked_r : CoreMod.Checked) (x : S.Term) (r : Int) (t__11 : S.Ty) (t__13 : S.Ty),
  ((BitvecMod.Bitvec.checked_has signed checked_l) && (BitvecMod.Bitvec.checked_has signed checked_r)) = true →
  S.Refines (BitvecMod.Bitvec.leq.spec signed (BitvecMod.mk (.Add checked_l y (BitvecMod.mk (.BitVec l) t__4)) t__6) (BitvecMod.mk (.Add checked_r x (BitvecMod.mk (.BitVec r) t__11)) t__13))
  ((let n := (BitvecMod.Bitvec.size (BitvecMod.mk (.Add checked_l y (BitvecMod.mk (.BitVec l) t__4)) t__6));
   (let sty := (S.ty (BitvecMod.mk (.Add checked_l y (BitvecMod.mk (.BitVec l) t__4)) t__6));
   (if (BitvecMod.Bitvec.const_keeps_in_range signed n l r)
   then (O.bitvec_leq signed (O.bitvec_add (BitvecMod.Bitvec.checked_of_signed signed) y (BitvecMod.mk_bv n (BitvecMod.lit_sub sty sty l r))) x)
   else (if (BitvecMod.Bitvec.const_keeps_in_range signed n r l)
        then (O.bitvec_leq signed y (O.bitvec_add (BitvecMod.Bitvec.checked_of_signed signed) x (BitvecMod.mk_bv n (BitvecMod.lit_sub sty sty r l))))
        else (BitvecMod.mk (.Leq signed (BitvecMod.mk (.Add checked_l y (BitvecMod.mk (.BitVec l) t__4)) t__6) (BitvecMod.mk (.Add checked_r x (BitvecMod.mk (.BitVec r) t__11)) t__13)) (KanonBool.sort .TBool)))))))

def Bitvec.leq.r_self_add_r.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S), O.Sound →
  ∀ (signed : Bool) (v1 : S.Term) (checked : CoreMod.Checked) (kanon__4 : S.Term) (b : S.Term) (t__6 : S.Ty),
  ((decide (v1 = kanon__4)) && (BitvecMod.Bitvec.checked_has signed checked)) = true →
  S.Refines (BitvecMod.Bitvec.leq.spec signed v1 (BitvecMod.mk (.Add checked kanon__4 b) t__6))
  ((O.bitvec_leq signed (BitvecMod.bv_zero (BitvecMod.Bitvec.size v1)) b))

def Bitvec.leq.r_self_add_r.swap.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S), O.Sound →
  ∀ (signed : Bool) (v1 : S.Term) (checked : CoreMod.Checked) (b : S.Term) (kanon__4 : S.Term) (t__6 : S.Ty),
  ((decide (v1 = kanon__4)) && (BitvecMod.Bitvec.checked_has signed checked)) = true →
  S.Refines (BitvecMod.Bitvec.leq.spec signed v1 (BitvecMod.mk (.Add checked b kanon__4) t__6))
  ((O.bitvec_leq signed (BitvecMod.bv_zero (BitvecMod.Bitvec.size v1)) b))

def Bitvec.leq.r_self_add_l.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S), O.Sound →
  ∀ (signed : Bool) (v2 : S.Term) (checked : CoreMod.Checked) (a : S.Term) (b : S.Term) (t__5 : S.Ty),
  ((decide (a = v2)) && (BitvecMod.Bitvec.checked_has signed checked)) = true →
  S.Refines (BitvecMod.Bitvec.leq.spec signed (BitvecMod.mk (.Add checked a b) t__5) v2)
  ((O.bitvec_leq signed b (BitvecMod.bv_zero (BitvecMod.Bitvec.size (BitvecMod.mk (.Add checked a b) t__5)))))

def Bitvec.leq.r_self_add_l.swap.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S), O.Sound →
  ∀ (signed : Bool) (v2 : S.Term) (checked : CoreMod.Checked) (b : S.Term) (a : S.Term) (t__5 : S.Ty),
  ((decide (a = v2)) && (BitvecMod.Bitvec.checked_has signed checked)) = true →
  S.Refines (BitvecMod.Bitvec.leq.spec signed (BitvecMod.mk (.Add checked b a) t__5) v2)
  ((O.bitvec_leq signed b (BitvecMod.bv_zero (BitvecMod.Bitvec.size (BitvecMod.mk (.Add checked b a) t__5)))))

def Bitvec.leq.r_min_l.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S), O.Sound →
  ∀ (signed : Bool) (v2 : S.Term) (x : Int) (t__2 : S.Ty),
  (BitvecMod.Bitvec.is_min_of signed (BitvecMod.Bitvec.size (BitvecMod.mk (.BitVec x) t__2)) x) = true →
  S.Refines (BitvecMod.Bitvec.leq.spec signed (BitvecMod.mk (.BitVec x) t__2) v2)
  (KanonBool.v_true)

def Bitvec.leq.r_max_r.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S), O.Sound →
  ∀ (signed : Bool) (v1 : S.Term) (x : Int) (t__3 : S.Ty),
  (BitvecMod.Bitvec.is_max_of signed (BitvecMod.Bitvec.size v1) x) = true →
  S.Refines (BitvecMod.Bitvec.leq.spec signed v1 (BitvecMod.mk (.BitVec x) t__3))
  (KanonBool.v_true)

def Bitvec.leq.r_const_mul.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S), O.Sound →
  ∀ (signed : Bool) (c2 : Int) (t__2 : S.Ty) (checked : CoreMod.Checked) (x : S.Term) (c1 : Int) (t__7 : S.Ty) (t__9 : S.Ty),
  ((BitvecMod.Bitvec.checked_has signed checked) && (! (decide (c1 = (0 : Int))))) = true →
  S.Refines (BitvecMod.Bitvec.leq.spec signed (BitvecMod.mk (.BitVec c2) t__2) (BitvecMod.mk (.Mul checked x (BitvecMod.mk (.BitVec c1) t__7)) t__9))
  ((let z1 := (BitvecMod.Bitvec.to_z signed (BitvecMod.Bitvec.size (BitvecMod.mk (.BitVec c2) t__2)) c1);
   (let z2 := (BitvecMod.Bitvec.to_z signed (BitvecMod.Bitvec.size (BitvecMod.mk (.BitVec c2) t__2)) c2);
   (if (BitvecMod.divisible z2 z1)
   then (if (decide (z1 < (0 : Int)))
        then (if (signed && ((decide (z1 = (-1 : Int))) && (BitvecMod.Bitvec.is_int_min (BitvecMod.Bitvec.size (BitvecMod.mk (.BitVec c2) t__2)) c2)))
             then KanonBool.v_true
             else (O.bitvec_leq signed x (O.bitvec_div signed (BitvecMod.mk (.BitVec c2) t__2) (BitvecMod.mk (.BitVec c1) t__7))))
        else (O.bitvec_leq signed (O.bitvec_div signed (BitvecMod.mk (.BitVec c2) t__2) (BitvecMod.mk (.BitVec c1) t__7)) x))
   else (if (decide (z1 < (0 : Int)))
        then (if (decide (z2 < (0 : Int)))
             then (O.bitvec_leq signed x (O.bitvec_div signed (BitvecMod.mk (.BitVec c2) t__2) (BitvecMod.mk (.BitVec c1) t__7)))
             else (O.bitvec_lt signed x (O.bitvec_div signed (BitvecMod.mk (.BitVec c2) t__2) (BitvecMod.mk (.BitVec c1) t__7))))
        else (if (decide (z2 < (0 : Int)))
             then (O.bitvec_leq signed (O.bitvec_div signed (BitvecMod.mk (.BitVec c2) t__2) (BitvecMod.mk (.BitVec c1) t__7)) x)
             else (O.bitvec_lt signed (O.bitvec_div signed (BitvecMod.mk (.BitVec c2) t__2) (BitvecMod.mk (.BitVec c1) t__7)) x)))))))

def Bitvec.leq.r_const_mul.swap.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S), O.Sound →
  ∀ (signed : Bool) (c2 : Int) (t__2 : S.Ty) (checked : CoreMod.Checked) (c1 : Int) (t__7 : S.Ty) (x : S.Term) (t__9 : S.Ty),
  ((BitvecMod.Bitvec.checked_has signed checked) && (! (decide (c1 = (0 : Int))))) = true →
  S.Refines (BitvecMod.Bitvec.leq.spec signed (BitvecMod.mk (.BitVec c2) t__2) (BitvecMod.mk (.Mul checked (BitvecMod.mk (.BitVec c1) t__7) x) t__9))
  ((let z1 := (BitvecMod.Bitvec.to_z signed (BitvecMod.Bitvec.size (BitvecMod.mk (.BitVec c2) t__2)) c1);
   (let z2 := (BitvecMod.Bitvec.to_z signed (BitvecMod.Bitvec.size (BitvecMod.mk (.BitVec c2) t__2)) c2);
   (if (BitvecMod.divisible z2 z1)
   then (if (decide (z1 < (0 : Int)))
        then (if (signed && ((decide (z1 = (-1 : Int))) && (BitvecMod.Bitvec.is_int_min (BitvecMod.Bitvec.size (BitvecMod.mk (.BitVec c2) t__2)) c2)))
             then KanonBool.v_true
             else (O.bitvec_leq signed x (O.bitvec_div signed (BitvecMod.mk (.BitVec c2) t__2) (BitvecMod.mk (.BitVec c1) t__7))))
        else (O.bitvec_leq signed (O.bitvec_div signed (BitvecMod.mk (.BitVec c2) t__2) (BitvecMod.mk (.BitVec c1) t__7)) x))
   else (if (decide (z1 < (0 : Int)))
        then (if (decide (z2 < (0 : Int)))
             then (O.bitvec_leq signed x (O.bitvec_div signed (BitvecMod.mk (.BitVec c2) t__2) (BitvecMod.mk (.BitVec c1) t__7)))
             else (O.bitvec_lt signed x (O.bitvec_div signed (BitvecMod.mk (.BitVec c2) t__2) (BitvecMod.mk (.BitVec c1) t__7))))
        else (if (decide (z2 < (0 : Int)))
             then (O.bitvec_leq signed (O.bitvec_div signed (BitvecMod.mk (.BitVec c2) t__2) (BitvecMod.mk (.BitVec c1) t__7)) x)
             else (O.bitvec_lt signed (O.bitvec_div signed (BitvecMod.mk (.BitVec c2) t__2) (BitvecMod.mk (.BitVec c1) t__7)) x)))))))

def Bitvec.leq.r_mul_const.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S), O.Sound →
  ∀ (signed : Bool) (checked : CoreMod.Checked) (x : S.Term) (c1 : Int) (t__5 : S.Ty) (t__7 : S.Ty) (c2 : Int) (t__10 : S.Ty),
  ((BitvecMod.Bitvec.checked_has signed checked) && (! (decide (c1 = (0 : Int))))) = true →
  S.Refines (BitvecMod.Bitvec.leq.spec signed (BitvecMod.mk (.Mul checked x (BitvecMod.mk (.BitVec c1) t__5)) t__7) (BitvecMod.mk (.BitVec c2) t__10))
  ((let z1 := (BitvecMod.Bitvec.to_z signed (BitvecMod.Bitvec.size (BitvecMod.mk (.Mul checked x (BitvecMod.mk (.BitVec c1) t__5)) t__7)) c1);
   (let z2 := (BitvecMod.Bitvec.to_z signed (BitvecMod.Bitvec.size (BitvecMod.mk (.Mul checked x (BitvecMod.mk (.BitVec c1) t__5)) t__7)) c2);
   (if (BitvecMod.divisible z2 z1)
   then (if (decide (z1 < (0 : Int)))
        then (if (signed && ((decide (z1 = (-1 : Int))) && (BitvecMod.Bitvec.is_int_min (BitvecMod.Bitvec.size (BitvecMod.mk (.Mul checked x (BitvecMod.mk (.BitVec c1) t__5)) t__7)) c2)))
             then KanonBool.v_false
             else (O.bitvec_leq signed (O.bitvec_div signed (BitvecMod.mk (.BitVec c2) t__10) (BitvecMod.mk (.BitVec c1) t__5)) x))
        else (O.bitvec_leq signed x (O.bitvec_div signed (BitvecMod.mk (.BitVec c2) t__10) (BitvecMod.mk (.BitVec c1) t__5))))
   else (if (decide (z1 < (0 : Int)))
        then (if (decide (z2 < (0 : Int)))
             then (O.bitvec_lt signed (O.bitvec_div signed (BitvecMod.mk (.BitVec c2) t__10) (BitvecMod.mk (.BitVec c1) t__5)) x)
             else (O.bitvec_leq signed (O.bitvec_div signed (BitvecMod.mk (.BitVec c2) t__10) (BitvecMod.mk (.BitVec c1) t__5)) x))
        else (if (decide (z2 < (0 : Int)))
             then (O.bitvec_lt signed x (O.bitvec_div signed (BitvecMod.mk (.BitVec c2) t__10) (BitvecMod.mk (.BitVec c1) t__5)))
             else (O.bitvec_leq signed x (O.bitvec_div signed (BitvecMod.mk (.BitVec c2) t__10) (BitvecMod.mk (.BitVec c1) t__5)))))))))

def Bitvec.leq.r_mul_const.swap.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S), O.Sound →
  ∀ (signed : Bool) (checked : CoreMod.Checked) (c1 : Int) (t__5 : S.Ty) (x : S.Term) (t__7 : S.Ty) (c2 : Int) (t__10 : S.Ty),
  ((BitvecMod.Bitvec.checked_has signed checked) && (! (decide (c1 = (0 : Int))))) = true →
  S.Refines (BitvecMod.Bitvec.leq.spec signed (BitvecMod.mk (.Mul checked (BitvecMod.mk (.BitVec c1) t__5) x) t__7) (BitvecMod.mk (.BitVec c2) t__10))
  ((let z1 := (BitvecMod.Bitvec.to_z signed (BitvecMod.Bitvec.size (BitvecMod.mk (.Mul checked (BitvecMod.mk (.BitVec c1) t__5) x) t__7)) c1);
   (let z2 := (BitvecMod.Bitvec.to_z signed (BitvecMod.Bitvec.size (BitvecMod.mk (.Mul checked (BitvecMod.mk (.BitVec c1) t__5) x) t__7)) c2);
   (if (BitvecMod.divisible z2 z1)
   then (if (decide (z1 < (0 : Int)))
        then (if (signed && ((decide (z1 = (-1 : Int))) && (BitvecMod.Bitvec.is_int_min (BitvecMod.Bitvec.size (BitvecMod.mk (.Mul checked (BitvecMod.mk (.BitVec c1) t__5) x) t__7)) c2)))
             then KanonBool.v_false
             else (O.bitvec_leq signed (O.bitvec_div signed (BitvecMod.mk (.BitVec c2) t__10) (BitvecMod.mk (.BitVec c1) t__5)) x))
        else (O.bitvec_leq signed x (O.bitvec_div signed (BitvecMod.mk (.BitVec c2) t__10) (BitvecMod.mk (.BitVec c1) t__5))))
   else (if (decide (z1 < (0 : Int)))
        then (if (decide (z2 < (0 : Int)))
             then (O.bitvec_lt signed (O.bitvec_div signed (BitvecMod.mk (.BitVec c2) t__10) (BitvecMod.mk (.BitVec c1) t__5)) x)
             else (O.bitvec_leq signed (O.bitvec_div signed (BitvecMod.mk (.BitVec c2) t__10) (BitvecMod.mk (.BitVec c1) t__5)) x))
        else (if (decide (z2 < (0 : Int)))
             then (O.bitvec_lt signed x (O.bitvec_div signed (BitvecMod.mk (.BitVec c2) t__10) (BitvecMod.mk (.BitVec c1) t__5)))
             else (O.bitvec_leq signed x (O.bitvec_div signed (BitvecMod.mk (.BitVec c2) t__10) (BitvecMod.mk (.BitVec c1) t__5)))))))))

def Bitvec.leq.r_mul_mul.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S), O.Sound →
  ∀ (signed : Bool) (checked_l : CoreMod.Checked) (a : S.Term) (x : S.Term) (t__5 : S.Ty) (checked_r : CoreMod.Checked) (kanon__9 : S.Term) (y : S.Term) (t__11 : S.Ty),
  ((decide (a = kanon__9)) && ((BitvecMod.Bitvec.checked_has signed checked_l) && ((BitvecMod.Bitvec.checked_has signed checked_r) && (BitvecMod.Bitvec.cancellable O signed a)))) = true →
  S.Refines (BitvecMod.Bitvec.leq.spec signed (BitvecMod.mk (.Mul checked_l a x) t__5) (BitvecMod.mk (.Mul checked_r kanon__9 y) t__11))
  ((O.bitvec_leq signed x y))

def Bitvec.leq.r_mul_mul.swap2.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S), O.Sound →
  ∀ (signed : Bool) (checked_l : CoreMod.Checked) (a : S.Term) (x : S.Term) (t__5 : S.Ty) (checked_r : CoreMod.Checked) (y : S.Term) (kanon__9 : S.Term) (t__11 : S.Ty),
  ((decide (a = kanon__9)) && ((BitvecMod.Bitvec.checked_has signed checked_l) && ((BitvecMod.Bitvec.checked_has signed checked_r) && (BitvecMod.Bitvec.cancellable O signed a)))) = true →
  S.Refines (BitvecMod.Bitvec.leq.spec signed (BitvecMod.mk (.Mul checked_l a x) t__5) (BitvecMod.mk (.Mul checked_r y kanon__9) t__11))
  ((O.bitvec_leq signed x y))

def Bitvec.leq.r_mul_mul.swap1.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S), O.Sound →
  ∀ (signed : Bool) (checked_l : CoreMod.Checked) (x : S.Term) (a : S.Term) (t__5 : S.Ty) (checked_r : CoreMod.Checked) (kanon__9 : S.Term) (y : S.Term) (t__11 : S.Ty),
  ((decide (a = kanon__9)) && ((BitvecMod.Bitvec.checked_has signed checked_l) && ((BitvecMod.Bitvec.checked_has signed checked_r) && (BitvecMod.Bitvec.cancellable O signed a)))) = true →
  S.Refines (BitvecMod.Bitvec.leq.spec signed (BitvecMod.mk (.Mul checked_l x a) t__5) (BitvecMod.mk (.Mul checked_r kanon__9 y) t__11))
  ((O.bitvec_leq signed x y))

def Bitvec.leq.r_mul_mul.swap1_swap2.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S), O.Sound →
  ∀ (signed : Bool) (checked_l : CoreMod.Checked) (x : S.Term) (a : S.Term) (t__5 : S.Ty) (checked_r : CoreMod.Checked) (y : S.Term) (kanon__9 : S.Term) (t__11 : S.Ty),
  ((decide (a = kanon__9)) && ((BitvecMod.Bitvec.checked_has signed checked_l) && ((BitvecMod.Bitvec.checked_has signed checked_r) && (BitvecMod.Bitvec.cancellable O signed a)))) = true →
  S.Refines (BitvecMod.Bitvec.leq.spec signed (BitvecMod.mk (.Mul checked_l x a) t__5) (BitvecMod.mk (.Mul checked_r y kanon__9) t__11))
  ((O.bitvec_leq signed x y))

def Bitvec.leq.r_udiv_big.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S), O.Sound →
  ∀ (signed : Bool) (w__3 : S.Term) (d : Int) (t__5 : S.Ty) (t__6 : S.Ty) (n : Int) (t__8 : S.Ty),
  ((! signed) && (BitvecMod.Bitvec.overflows_mul false (BitvecMod.Bitvec.size (BitvecMod.mk (.Div false w__3 (BitvecMod.mk (.BitVec d) t__5)) t__6)) n d)) = true →
  S.Refines (BitvecMod.Bitvec.leq.spec signed (BitvecMod.mk (.Div false w__3 (BitvecMod.mk (.BitVec d) t__5)) t__6) (BitvecMod.mk (.BitVec n) t__8))
  (KanonBool.v_true)

def Bitvec.leq.r_ite_l.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S), O.Sound →
  ∀ (signed : Bool) (b : S.Term) (l : S.Term) (r : S.Term) (t__5 : S.Ty) (w__6 : Int) (t__7 : S.Ty),
  S.Refines (BitvecMod.Bitvec.leq.spec signed (KanonBool.mk (.Ite b l r) t__5) (BitvecMod.mk (.BitVec w__6) t__7))
  ((O.bool_ite b (O.bitvec_leq signed l (BitvecMod.mk (.BitVec w__6) t__7)) (O.bitvec_leq signed r (BitvecMod.mk (.BitVec w__6) t__7))))

def Bitvec.leq.r_ite_r.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S), O.Sound →
  ∀ (signed : Bool) (w__1 : Int) (t__2 : S.Ty) (b : S.Term) (l : S.Term) (r : S.Term) (t__7 : S.Ty),
  S.Refines (BitvecMod.Bitvec.leq.spec signed (BitvecMod.mk (.BitVec w__1) t__2) (KanonBool.mk (.Ite b l r) t__7))
  ((O.bool_ite b (O.bitvec_leq signed (BitvecMod.mk (.BitVec w__1) t__2) l) (O.bitvec_leq signed (BitvecMod.mk (.BitVec w__1) t__2) r)))

def Bitvec.leq.r_const_sub1.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S), O.Sound →
  ∀ (signed : Bool) (c : Int) (t__2 : S.Ty) (checked : CoreMod.Checked) (x : S.Term) (k : Int) (t__7 : S.Ty) (t__8 : S.Ty),
  (BitvecMod.Bitvec.checked_has signed checked) = true →
  S.Refines (BitvecMod.Bitvec.leq.spec signed (BitvecMod.mk (.BitVec c) t__2) (BitvecMod.mk (.Sub checked x (BitvecMod.mk (.BitVec k) t__7)) t__8))
  ((if (BitvecMod.Bitvec.overflows_add signed (BitvecMod.Bitvec.size (BitvecMod.mk (.BitVec c) t__2)) c k)
   then (if (! signed)
        then KanonBool.v_false
        else (BitvecMod.mk (.Leq signed (BitvecMod.mk (.BitVec c) t__2) (BitvecMod.mk (.Sub checked x (BitvecMod.mk (.BitVec k) t__7)) t__8)) (KanonBool.sort .TBool)))
   else (O.bitvec_leq signed (BitvecMod.mk_bv (BitvecMod.Bitvec.size (BitvecMod.mk (.BitVec c) t__2)) (BitvecMod.lit_add (S.ty (BitvecMod.mk (.BitVec c) t__2)) (S.ty (BitvecMod.mk (.BitVec c) t__2)) c k)) x)))

def Bitvec.leq.r_const_sub2.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S), O.Sound →
  ∀ (signed : Bool) (c : Int) (t__2 : S.Ty) (checked : CoreMod.Checked) (k : Int) (t__6 : S.Ty) (x : S.Term) (t__8 : S.Ty),
  (BitvecMod.Bitvec.checked_has signed checked) = true →
  S.Refines (BitvecMod.Bitvec.leq.spec signed (BitvecMod.mk (.BitVec c) t__2) (BitvecMod.mk (.Sub checked (BitvecMod.mk (.BitVec k) t__6) x) t__8))
  ((if (BitvecMod.Bitvec.overflows_sub signed (BitvecMod.Bitvec.size (BitvecMod.mk (.BitVec c) t__2)) k c)
   then (if (! signed)
        then KanonBool.v_false
        else (BitvecMod.mk (.Leq signed (BitvecMod.mk (.BitVec c) t__2) (BitvecMod.mk (.Sub checked (BitvecMod.mk (.BitVec k) t__6) x) t__8)) (KanonBool.sort .TBool)))
   else (O.bitvec_leq signed x (BitvecMod.mk_bv (BitvecMod.Bitvec.size (BitvecMod.mk (.BitVec c) t__2)) (BitvecMod.lit_sub (S.ty (BitvecMod.mk (.BitVec c) t__2)) (S.ty (BitvecMod.mk (.BitVec c) t__2)) k c)))))

def Bitvec.leq.r_sub_const1.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S), O.Sound →
  ∀ (signed : Bool) (checked : CoreMod.Checked) (x : S.Term) (k : Int) (t__5 : S.Ty) (t__6 : S.Ty) (c : Int) (t__8 : S.Ty),
  (BitvecMod.Bitvec.checked_has signed checked) = true →
  S.Refines (BitvecMod.Bitvec.leq.spec signed (BitvecMod.mk (.Sub checked x (BitvecMod.mk (.BitVec k) t__5)) t__6) (BitvecMod.mk (.BitVec c) t__8))
  ((if (BitvecMod.Bitvec.overflows_add signed (BitvecMod.Bitvec.size (BitvecMod.mk (.Sub checked x (BitvecMod.mk (.BitVec k) t__5)) t__6)) c k)
   then (if (! signed)
        then KanonBool.v_true
        else (BitvecMod.mk (.Leq signed (BitvecMod.mk (.Sub checked x (BitvecMod.mk (.BitVec k) t__5)) t__6) (BitvecMod.mk (.BitVec c) t__8)) (KanonBool.sort .TBool)))
   else (O.bitvec_leq signed x (BitvecMod.mk_bv (BitvecMod.Bitvec.size (BitvecMod.mk (.Sub checked x (BitvecMod.mk (.BitVec k) t__5)) t__6)) (BitvecMod.lit_add (S.ty (BitvecMod.mk (.Sub checked x (BitvecMod.mk (.BitVec k) t__5)) t__6)) (S.ty (BitvecMod.mk (.Sub checked x (BitvecMod.mk (.BitVec k) t__5)) t__6)) c k)))))

def Bitvec.leq.r_sub_const2.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S), O.Sound →
  ∀ (signed : Bool) (checked : CoreMod.Checked) (k : Int) (t__4 : S.Ty) (x : S.Term) (t__6 : S.Ty) (c : Int) (t__8 : S.Ty),
  (BitvecMod.Bitvec.checked_has signed checked) = true →
  S.Refines (BitvecMod.Bitvec.leq.spec signed (BitvecMod.mk (.Sub checked (BitvecMod.mk (.BitVec k) t__4) x) t__6) (BitvecMod.mk (.BitVec c) t__8))
  ((if (BitvecMod.Bitvec.overflows_sub signed (BitvecMod.Bitvec.size (BitvecMod.mk (.Sub checked (BitvecMod.mk (.BitVec k) t__4) x) t__6)) k c)
   then (if (! signed)
        then KanonBool.v_true
        else (BitvecMod.mk (.Leq signed (BitvecMod.mk (.Sub checked (BitvecMod.mk (.BitVec k) t__4) x) t__6) (BitvecMod.mk (.BitVec c) t__8)) (KanonBool.sort .TBool)))
   else (O.bitvec_leq signed (BitvecMod.mk_bv (BitvecMod.Bitvec.size (BitvecMod.mk (.Sub checked (BitvecMod.mk (.BitVec k) t__4) x) t__6)) (BitvecMod.lit_sub (S.ty (BitvecMod.mk (.Sub checked (BitvecMod.mk (.BitVec k) t__4) x) t__6)) (S.ty (BitvecMod.mk (.Sub checked (BitvecMod.mk (.BitVec k) t__4) x) t__6)) k c)) x)))

def Bitvec.leq.r_ub_r.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S), O.Sound →
  ∀ (signed : Bool) (v1 : S.Term) (c : Int) (t__3 : S.Ty),
  ((! signed) && (decide ((BitvecMod.Bitvec.unsigned_ub v1) ≤ c))) = true →
  S.Refines (BitvecMod.Bitvec.leq.spec signed v1 (BitvecMod.mk (.BitVec c) t__3))
  (KanonBool.v_true)

def Bitvec.leq.r_ub_l.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S), O.Sound →
  ∀ (signed : Bool) (v2 : S.Term) (c : Int) (t__2 : S.Ty),
  ((! signed) && (decide ((BitvecMod.Bitvec.unsigned_ub v2) < c))) = true →
  S.Refines (BitvecMod.Bitvec.leq.spec signed (BitvecMod.mk (.BitVec c) t__2) v2)
  (KanonBool.v_false)

def Bitvec.leq.r_to_unsigned_l.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S), O.Sound →
  ∀ (signed : Bool) (v2 : S.Term) (c : Int) (t__2 : S.Ty),
  (signed && (BitvecMod.Bitvec.is_checked_unsigned_op v2)) = true →
  S.Refines (BitvecMod.Bitvec.leq.spec signed (BitvecMod.mk (.BitVec c) t__2) v2)
  ((BitvecMod.Bitvec.signed_to_unsigned_cmp O true true c (BitvecMod.mk (.BitVec c) t__2) v2))

def Bitvec.leq.r_to_unsigned_r.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S), O.Sound →
  ∀ (signed : Bool) (v1 : S.Term) (c : Int) (t__3 : S.Ty),
  (signed && (BitvecMod.Bitvec.is_checked_unsigned_op v1)) = true →
  S.Refines (BitvecMod.Bitvec.leq.spec signed v1 (BitvecMod.mk (.BitVec c) t__3))
  ((BitvecMod.Bitvec.signed_to_unsigned_cmp O true false c v1 (BitvecMod.mk (.BitVec c) t__3)))

def Bitvec.leq.r_default.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S), O.Sound →
  ∀ (signed : Bool) (v1 : S.Term) (v2 : S.Term),
  S.Refines (BitvecMod.Bitvec.leq.spec signed v1 v2)
  ((BitvecMod.mk (.Leq signed v1 v2) (KanonBool.sort .TBool)))

end BitvecMod
