-- Generated by kanon from bitvec.knl, bitvec.kn. Do not edit.
import BitvecMod.Statements

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace BitvecMod

open Classical Kanon

def Bitvec.mul_overflows.r_lits.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} {LBool : KanonBool.Syntax B} {LCore : CoreMod.Syntax B} (L : BitvecMod.Syntax B LBool LCore) [KanonBool.Sem LBool] [CoreMod.Sem LCore] [Sem L] (O : Ops L), O.Sound →
  ∀ (signed : Bool) (i1 : Int) (t__2 : S.Ty) (i2 : Int) (t__5 : S.Ty),
  S.Refines (BitvecMod.Bitvec.mul_overflows.spec L signed (B.node (L.BitVecK i1) t__2) (B.node (L.BitVecK i2) t__5))
  ((B.node (LBool.BoolK (L.bitvec_lit_mul_overflows signed (S.ty (B.node (L.BitVecK i1) t__2)) (S.ty (B.node (L.BitVecK i2) t__5)) i1 i2)) LBool.TBool))

def Bitvec.mul_overflows.r_size1.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} {LBool : KanonBool.Syntax B} {LCore : CoreMod.Syntax B} (L : BitvecMod.Syntax B LBool LCore) [KanonBool.Sem LBool] [CoreMod.Sem LCore] [Sem L] (O : Ops L), O.Sound →
  ∀ (signed : Bool) (v1 : S.Term) (v2 : S.Term),
  (signed && (decide ((L.bitvec_size v1) = (1 : Int)))) = true →
  S.Refines (BitvecMod.Bitvec.mul_overflows.spec L signed v1 v2)
  ((let one := (L.bitvec_bv_one (1 : Int));
   (O.bool_and_ (O.bool_eq v1 one) (O.bool_eq v2 one))))

def Bitvec.mul_overflows.r_msb.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} {LBool : KanonBool.Syntax B} {LCore : CoreMod.Syntax B} (L : BitvecMod.Syntax B LBool LCore) [KanonBool.Sem LBool] [CoreMod.Sem LCore] [Sem L] (O : Ops L), O.Sound →
  ∀ (signed : Bool) (v1 : S.Term) (v2 : S.Term),
  ((signed && (decide (((L.bitvec_msb_of v1) + (L.bitvec_msb_of v2)) < ((L.bitvec_size v1) - (2 : Int))))) || ((! signed) && (decide (((L.bitvec_msb_of v1) + (L.bitvec_msb_of v2)) < ((L.bitvec_size v1) - (1 : Int)))))) = true →
  S.Refines (BitvecMod.Bitvec.mul_overflows.spec L signed v1 v2)
  (LBool.bool_v_false)

def Bitvec.mul_overflows.r_const.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} {LBool : KanonBool.Syntax B} {LCore : CoreMod.Syntax B} (L : BitvecMod.Syntax B LBool LCore) [KanonBool.Sem LBool] [CoreMod.Sem LCore] [Sem L] (O : Ops L), O.Sound →
  ∀ (signed : Bool) (v2 : S.Term) (z : Int) (t__2 : S.Ty),
  ((! signed) || (decide ((L.bitvec_size v2) > (1 : Int)))) = true →
  S.Refines (BitvecMod.Bitvec.mul_overflows.spec L signed (B.node (L.BitVecK z) t__2) v2)
  ((if ((decide (z = (0 : Int))) || (decide (z = (1 : Int))))
   then LBool.bool_v_false
   else (let n := (L.bitvec_size v2);
        (let z := (L.bitvec_to_z signed n z);
        (if signed
        then (let min_val := (- (L.bitvec_z_lsl (1 : Int) (n - (1 : Int))));
             (let max_val := ((L.bitvec_z_lsl (1 : Int) (n - (1 : Int))) - (1 : Int));
             (if (decide (z = (-1 : Int)))
             then (O.bool_eq v2 (L.bitvec_mk_masked n min_val))
             else (match (if (decide (z > (0 : Int)))
                         then ((L.bitvec_tdiv min_val z), (L.bitvec_tdiv max_val z))
                         else ((L.bitvec_tdiv max_val z), (L.bitvec_tdiv min_val z))) with
                  | (min_x, max_x) =>
                    (O.bool_or_ (O.bitvec_lt signed v2 (L.bitvec_mk_masked n min_x)) (O.bitvec_lt signed (L.bitvec_mk_masked n max_x) v2))))))
        else (O.bitvec_lt signed (L.bitvec_mk_masked n (L.bitvec_tdiv ((L.bitvec_z_lsl (1 : Int) n) - (1 : Int)) z)) v2))))))

def Bitvec.mul_overflows.r_const.swap.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} {LBool : KanonBool.Syntax B} {LCore : CoreMod.Syntax B} (L : BitvecMod.Syntax B LBool LCore) [KanonBool.Sem LBool] [CoreMod.Sem LCore] [Sem L] (O : Ops L), O.Sound →
  ∀ (signed : Bool) (v1 : S.Term) (z : Int) (t__2 : S.Ty),
  ((! signed) || (decide ((L.bitvec_size v1) > (1 : Int)))) = true →
  S.Refines (BitvecMod.Bitvec.mul_overflows.spec L signed v1 (B.node (L.BitVecK z) t__2))
  ((if ((decide (z = (0 : Int))) || (decide (z = (1 : Int))))
   then LBool.bool_v_false
   else (let n := (L.bitvec_size v1);
        (let z := (L.bitvec_to_z signed n z);
        (if signed
        then (let min_val := (- (L.bitvec_z_lsl (1 : Int) (n - (1 : Int))));
             (let max_val := ((L.bitvec_z_lsl (1 : Int) (n - (1 : Int))) - (1 : Int));
             (if (decide (z = (-1 : Int)))
             then (O.bool_eq v1 (L.bitvec_mk_masked n min_val))
             else (match (if (decide (z > (0 : Int)))
                         then ((L.bitvec_tdiv min_val z), (L.bitvec_tdiv max_val z))
                         else ((L.bitvec_tdiv max_val z), (L.bitvec_tdiv min_val z))) with
                  | (min_x, max_x) =>
                    (O.bool_or_ (O.bitvec_lt signed v1 (L.bitvec_mk_masked n min_x)) (O.bitvec_lt signed (L.bitvec_mk_masked n max_x) v1))))))
        else (O.bitvec_lt signed (L.bitvec_mk_masked n (L.bitvec_tdiv ((L.bitvec_z_lsl (1 : Int) n) - (1 : Int)) z)) v1))))))

def Bitvec.mul_overflows.r_div.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} {LBool : KanonBool.Syntax B} {LCore : CoreMod.Syntax B} (L : BitvecMod.Syntax B LBool LCore) [KanonBool.Sem LBool] [CoreMod.Sem LCore] [Sem L] (O : Ops L), O.Sound →
  ∀ (signed : Bool) (v1 : S.Term) (w__4 : S.Term) (kanon__5 : S.Term) (t__6 : S.Ty),
  ((decide (v1 = kanon__5)) && (! signed)) = true →
  S.Refines (BitvecMod.Bitvec.mul_overflows.spec L signed v1 (B.node (L.DivK false w__4 kanon__5) t__6))
  (LBool.bool_v_false)

def Bitvec.mul_overflows.r_div.swap.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} {LBool : KanonBool.Syntax B} {LCore : CoreMod.Syntax B} (L : BitvecMod.Syntax B LBool LCore) [KanonBool.Sem LBool] [CoreMod.Sem LCore] [Sem L] (O : Ops L), O.Sound →
  ∀ (signed : Bool) (v2 : S.Term) (w__4 : S.Term) (kanon__5 : S.Term) (t__6 : S.Ty),
  ((decide (v2 = kanon__5)) && (! signed)) = true →
  S.Refines (BitvecMod.Bitvec.mul_overflows.spec L signed (B.node (L.DivK false w__4 kanon__5) t__6) v2)
  (LBool.bool_v_false)

def Bitvec.mul_overflows.r_default.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} {LBool : KanonBool.Syntax B} {LCore : CoreMod.Syntax B} (L : BitvecMod.Syntax B LBool LCore) [KanonBool.Sem LBool] [CoreMod.Sem LCore] [Sem L] (O : Ops L), O.Sound →
  ∀ (signed : Bool) (v1 : S.Term) (v2 : S.Term),
  S.Refines (BitvecMod.Bitvec.mul_overflows.spec L signed v1 v2)
  ((B.node (if O.tag_le v1 v2
           then (L.MulOvfK signed v1 v2)
           else (L.MulOvfK signed v2 v1)) LBool.TBool))

end BitvecMod
