-- Generated by kanon from bitvec.knl, bitvec.kn. Do not edit.
import BitvecMod.Lift

set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false
set_option maxHeartbeats 1000000

noncomputable section

namespace BitvecMod

open Classical Kanon

def Bitvec.not_bool.r_lit.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S), O.Sound →
  ∀ (z : Int) (t__2 : S.Ty),
  S.Refines (BitvecMod.Bitvec.not_bool.spec (BitvecMod.mk (.BitVec z) t__2))
  ((if (decide (z = (0 : Int)))
   then (BitvecMod.bv_one (BitvecMod.Bitvec.size (BitvecMod.mk (.BitVec z) t__2)))
   else (BitvecMod.bv_zero (BitvecMod.Bitvec.size (BitvecMod.mk (.BitVec z) t__2)))))

def Bitvec.not_bool.r_of_bool.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S), O.Sound →
  ∀ (n : Int) (g : S.Term) (t__4 : S.Ty),
  S.Refines (BitvecMod.Bitvec.not_bool.spec (BitvecMod.mk (.BvOfBool n g) t__4))
  ((O.bitvec_of_bool n (O.bool_not_ g)))

def Bitvec.not_bool.r_default.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S), O.Sound →
  ∀ (v : S.Term),
  S.Refines (BitvecMod.Bitvec.not_bool.spec v)
  ((O.bitvec_of_bool (BitvecMod.Bitvec.size v) (O.bool_eq v (BitvecMod.bv_zero (BitvecMod.Bitvec.size v)))))

end BitvecMod
