-- Generated by kanon from bitvec.knl, bitvec.kn. Do not edit.
import BitvecMod.Statements

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace BitvecMod

open Classical Kanon

def Bitvec.to_bool.r_lit.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} {LBool : KanonBool.Syntax B} {LCore : CoreMod.Syntax B} (L : BitvecMod.Syntax B LBool LCore) [KanonBool.Sem LBool] [CoreMod.Sem LCore] [Sem L] (O : Ops L), O.Sound →
  ∀ (z : Int) (t__2 : S.Ty),
  S.Refines (BitvecMod.Bitvec.to_bool.spec L (B.node (L.BitVecK z) t__2))
  ((LBool.bool_of_bool (! (decide (z = (0 : Int))))))

def Bitvec.to_bool.r_of_bool.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} {LBool : KanonBool.Syntax B} {LCore : CoreMod.Syntax B} (L : BitvecMod.Syntax B LBool LCore) [KanonBool.Sem LBool] [CoreMod.Sem LCore] [Sem L] (O : Ops L), O.Sound →
  ∀ (w__1 : Int) (b : S.Term) (t__4 : S.Ty),
  S.Refines (BitvecMod.Bitvec.to_bool.spec L (B.node (L.BvOfBoolK w__1 b) t__4))
  (b)

def Bitvec.to_bool.r_default.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} {LBool : KanonBool.Syntax B} {LCore : CoreMod.Syntax B} (L : BitvecMod.Syntax B LBool LCore) [KanonBool.Sem LBool] [CoreMod.Sem LCore] [Sem L] (O : Ops L), O.Sound →
  ∀ (v : S.Term),
  S.Refines (BitvecMod.Bitvec.to_bool.spec L v)
  ((O.bool_not_ (O.bool_eq v (L.bitvec_bv_zero (L.bitvec_size v)))))

end BitvecMod
