-- Generated by kanon from bool.kn, exists.kn, bitvec.kn, float.kn, ptr.kn, view.kn. Do not edit.
import Kanon.Interface.Bitvec
import Kanon.Statements
import Kanon.Model.Bitvec.signed_to_unsigned_cmp
import Kanon.Lang.Bitvec
import Kanon.Lang.Bool
import Kanon.Lang.Core
import BitvecMod.Ops

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace Kanon

open Classical Kanon

/-- The model of the language, for the module `Bitvec`. -/
def Ops.toBitvec (FS : FloatSem) (O : Ops) : BitvecMod.Ops (S := (sem FS)) (bitvecSyntax FS) where
  tag_le := O.orc.tag_le
  bitvec_of_bool := O.bitvec_of_bool
  bitvec_to_bool := O.bitvec_to_bool
  bitvec_not_bool := O.bitvec_not_bool
  bitvec_add := O.bitvec_add
  bitvec_sub := O.bitvec_sub
  bitvec_neg := O.bitvec_neg
  bitvec_mod_ := O.bitvec_mod_
  bitvec_rem := O.bitvec_rem
  bitvec_not_ := O.bitvec_not_
  bitvec_and_ := O.bitvec_and_
  bitvec_or_ := O.bitvec_or_
  bitvec_xor := O.bitvec_xor
  bitvec_extract := O.bitvec_extract
  bitvec_extend_ := O.bitvec_extend_
  bitvec_concat := O.bitvec_concat
  bitvec_shl := O.bitvec_shl
  bitvec_lshr := O.bitvec_lshr
  bitvec_ashr := O.bitvec_ashr
  bitvec_mul := O.bitvec_mul
  bitvec_div := O.bitvec_div
  bitvec_lt_zero := O.bitvec_lt_zero
  bitvec_lt := O.bitvec_lt
  bitvec_leq := O.bitvec_leq
  bitvec_add_overflows := O.bitvec_add_overflows
  bitvec_mul_overflows := O.bitvec_mul_overflows
  bitvec_neg_overflows := O.bitvec_neg_overflows
  bitvec_sub_overflows := O.bitvec_sub_overflows
  bitvec_signed_to_unsigned_cmp := Bitvec.signed_to_unsigned_cmp O
  bool_and_ := O.bool_and_
  bool_or_ := O.bool_or_
  bool_not_ := O.bool_not_
  bool_ite := O.bool_ite
  bool_eq := O.bool_eq
  bool_eq_untyped := O.bool_eq_untyped
  bool_distinct := O.bool_distinct
  bool_sort_by_tag := O.orc.sort_by_tag

theorem Ops.Sound.toBitvec {FS : FloatSem} {O : Ops} (hO : O.Sound FS) : (Ops.toBitvec FS O).Sound where
  bitvec_of_bool := hO.bitvec_of_bool
  bitvec_to_bool := hO.bitvec_to_bool
  bitvec_not_bool := hO.bitvec_not_bool
  bitvec_add := hO.bitvec_add
  bitvec_sub := hO.bitvec_sub
  bitvec_neg := hO.bitvec_neg
  bitvec_mod_ := hO.bitvec_mod_
  bitvec_rem := hO.bitvec_rem
  bitvec_not_ := hO.bitvec_not_
  bitvec_and_ := hO.bitvec_and_
  bitvec_or_ := hO.bitvec_or_
  bitvec_xor := hO.bitvec_xor
  bitvec_extract := hO.bitvec_extract
  bitvec_extend_ := hO.bitvec_extend_
  bitvec_concat := hO.bitvec_concat
  bitvec_shl := hO.bitvec_shl
  bitvec_lshr := hO.bitvec_lshr
  bitvec_ashr := hO.bitvec_ashr
  bitvec_mul := hO.bitvec_mul
  bitvec_div := hO.bitvec_div
  bitvec_lt_zero := hO.bitvec_lt_zero
  bitvec_lt := hO.bitvec_lt
  bitvec_leq := hO.bitvec_leq
  bitvec_add_overflows := hO.bitvec_add_overflows
  bitvec_mul_overflows := hO.bitvec_mul_overflows
  bitvec_neg_overflows := hO.bitvec_neg_overflows
  bitvec_sub_overflows := hO.bitvec_sub_overflows
  bitvec_signed_to_unsigned_cmp_eq := by kanon_bridge Bitvec.signed_to_unsigned_cmp
  bool_and_ := hO.bool_and_
  bool_or_ := hO.bool_or_
  bool_not_ := hO.bool_not_
  bool_ite := hO.bool_ite
  bool_eq := hO.bool_eq
  bool_eq_untyped := hO.bool_eq_untyped
  bool_distinct := hO.bool_distinct
  bool_orc := hO.orc.bool

end Kanon
