-- Generated by kanon from bool.kn, exists.kn, bitvec.kn, float.kn, ptr.kn, view.kn. Do not edit.
import Kanon.Interface.Float
import Kanon.Statements
import Kanon.Model.Bitvec.signed_to_unsigned_cmp
import Kanon.Model.Float.to_float_raw
import Kanon.Lang.Bitvec
import Kanon.Lang.Bool
import Kanon.Lang.Core
import Kanon.Lang.Float
import FloatMod.Ops

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace Kanon

open Classical Kanon

/-- The model of the language, for the module `Float`. -/
def Ops.toFloat (FS : FloatSem) (O : Ops) : FloatMod.Ops (S := (sem FS)) (floatSyntax FS) where
  tag_le := O.orc.tag_le
  bitvec_of_bool := O.bitvec_of_bool
  bitvec_to_bool := O.bitvec_to_bool
  bitvec_not_bool := O.bitvec_not_bool
  bitvec_add := O.bitvec_add
  bitvec_sub := O.bitvec_sub
  bitvec_neg := O.bitvec_neg
  bitvec_mod_ := O.bitvec_mod_
  bitvec_rem := O.bitvec_rem
  bitvec_not_ := O.bitvec_not_
  bitvec_and_ := O.bitvec_and_
  bitvec_or_ := O.bitvec_or_
  bitvec_xor := O.bitvec_xor
  bitvec_extract := O.bitvec_extract
  bitvec_extend_ := O.bitvec_extend_
  bitvec_concat := O.bitvec_concat
  bitvec_shl := O.bitvec_shl
  bitvec_lshr := O.bitvec_lshr
  bitvec_ashr := O.bitvec_ashr
  bitvec_mul := O.bitvec_mul
  bitvec_div := O.bitvec_div
  bitvec_lt_zero := O.bitvec_lt_zero
  bitvec_lt := O.bitvec_lt
  bitvec_leq := O.bitvec_leq
  bitvec_add_overflows := O.bitvec_add_overflows
  bitvec_mul_overflows := O.bitvec_mul_overflows
  bitvec_neg_overflows := O.bitvec_neg_overflows
  bitvec_sub_overflows := O.bitvec_sub_overflows
  bitvec_signed_to_unsigned_cmp := Bitvec.signed_to_unsigned_cmp O
  bool_and_ := O.bool_and_
  bool_or_ := O.bool_or_
  bool_not_ := O.bool_not_
  bool_ite := O.bool_ite
  bool_eq := O.bool_eq
  bool_eq_untyped := O.bool_eq_untyped
  bool_distinct := O.bool_distinct
  bool_sort_by_tag := O.orc.sort_by_tag
  float_is_floatclass := O.float_is_floatclass
  float_is_negative := O.float_is_negative
  float_is_positive := O.float_is_positive
  float_cast := O.float_cast
  float_eq := O.float_eq
  float_lt := O.float_lt
  float_leq := O.float_leq
  float_add := O.float_add
  float_sub := O.float_sub
  float_div := O.float_div
  float_mul := O.float_mul
  float_rem := O.float_rem
  float_abs := O.float_abs
  float_neg := O.float_neg
  float_fma := O.float_fma
  float_fmod_of_rem := O.float_fmod_of_rem
  float_fmod := O.float_fmod
  float_min := O.float_min
  float_max := O.float_max
  float_sqrt := O.float_sqrt
  float_round := O.float_round
  float_of_float := O.float_of_float
  float_to_float := O.float_to_float
  float_to_float_bits := O.float_to_float_bits
  float_f_add := O.orc.f_add
  float_f_sub := O.orc.f_sub
  float_f_mul := O.orc.f_mul
  float_f_div := O.orc.f_div
  float_f_rem := O.orc.f_rem
  float_f_fmod := O.orc.f_fmod
  float_f_min := O.orc.f_min
  float_f_max := O.orc.f_max
  float_f_fma := O.orc.f_fma
  float_f_sqrt := O.orc.f_sqrt
  float_f_round := O.orc.f_round
  float_f_convert := O.orc.f_convert
  float_f_to_int := O.orc.f_to_int
  float_f_of_int := O.orc.f_of_int
  float_to_float_raw := Float.to_float_raw O

theorem Ops.Sound.toFloat {FS : FloatSem} {O : Ops} (hO : O.Sound FS) : (Ops.toFloat FS O).Sound where
  bitvec_of_bool := hO.bitvec_of_bool
  bitvec_to_bool := hO.bitvec_to_bool
  bitvec_not_bool := hO.bitvec_not_bool
  bitvec_add := hO.bitvec_add
  bitvec_sub := hO.bitvec_sub
  bitvec_neg := hO.bitvec_neg
  bitvec_mod_ := hO.bitvec_mod_
  bitvec_rem := hO.bitvec_rem
  bitvec_not_ := hO.bitvec_not_
  bitvec_and_ := hO.bitvec_and_
  bitvec_or_ := hO.bitvec_or_
  bitvec_xor := hO.bitvec_xor
  bitvec_extract := hO.bitvec_extract
  bitvec_extend_ := hO.bitvec_extend_
  bitvec_concat := hO.bitvec_concat
  bitvec_shl := hO.bitvec_shl
  bitvec_lshr := hO.bitvec_lshr
  bitvec_ashr := hO.bitvec_ashr
  bitvec_mul := hO.bitvec_mul
  bitvec_div := hO.bitvec_div
  bitvec_lt_zero := hO.bitvec_lt_zero
  bitvec_lt := hO.bitvec_lt
  bitvec_leq := hO.bitvec_leq
  bitvec_add_overflows := hO.bitvec_add_overflows
  bitvec_mul_overflows := hO.bitvec_mul_overflows
  bitvec_neg_overflows := hO.bitvec_neg_overflows
  bitvec_sub_overflows := hO.bitvec_sub_overflows
  bitvec_signed_to_unsigned_cmp_eq := by kanon_bridge Bitvec.signed_to_unsigned_cmp
  bool_and_ := hO.bool_and_
  bool_or_ := hO.bool_or_
  bool_not_ := hO.bool_not_
  bool_ite := hO.bool_ite
  bool_eq := hO.bool_eq
  bool_eq_untyped := hO.bool_eq_untyped
  bool_distinct := hO.bool_distinct
  bool_orc := hO.orc.bool
  float_is_floatclass := hO.float_is_floatclass
  float_is_negative := hO.float_is_negative
  float_is_positive := hO.float_is_positive
  float_cast := hO.float_cast
  float_eq := hO.float_eq
  float_lt := hO.float_lt
  float_leq := hO.float_leq
  float_add := hO.float_add
  float_sub := hO.float_sub
  float_div := hO.float_div
  float_mul := hO.float_mul
  float_rem := hO.float_rem
  float_abs := hO.float_abs
  float_neg := hO.float_neg
  float_fma := hO.float_fma
  float_fmod_of_rem := hO.float_fmod_of_rem
  float_fmod := hO.float_fmod
  float_min := hO.float_min
  float_max := hO.float_max
  float_sqrt := hO.float_sqrt
  float_round := hO.float_round
  float_of_float := hO.float_of_float
  float_to_float := hO.float_to_float
  float_to_float_bits := hO.float_to_float_bits
  float_orc := hO.orc.float
  float_to_float_raw_eq := by kanon_bridge Float.to_float_raw

end Kanon
