-- Generated by kanon from float.knl, float.kn. Do not edit.
import FloatMod.Statements.Float.is_positive
import FloatMod.Proofs
import KanonBool.Soundness.Comm
import BitvecMod.Soundness.Comm
import FloatMod.Soundness.Comm

set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false
set_option maxHeartbeats 1000000

noncomputable section

namespace FloatMod

open Classical Kanon

set_option maxHeartbeats 400000 in
theorem Float.is_positive.r_lit.main.ok : Float.is_positive.r_lit.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Float.is_positive.r_lit.main)

set_option maxHeartbeats 400000 in
theorem Float.is_positive.r_default.main.ok : Float.is_positive.r_default.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Float.is_positive.r_default.main)

theorem Float.is_positive.r_lit.sound {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [FloatMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] [FloatMod.Typed S] (O : Ops S) (hO : O.Sound) (v : S.Term) (res : S.Term)
    (h : Float.is_positive.r_lit O v = some res) : S.Refines (FloatMod.Float.is_positive.spec v) res := by
  unfold Float.is_positive.r_lit at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Float.is_positive.r_lit.main.ok O hO)

theorem Float.is_positive.r_default.sound {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [FloatMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] [FloatMod.Typed S] (O : Ops S) (hO : O.Sound) (v : S.Term) (res : S.Term)
    (h : Float.is_positive.r_default O v = some res) : S.Refines (FloatMod.Float.is_positive.spec v) res := by
  unfold Float.is_positive.r_default at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Float.is_positive.r_default.main.ok O hO)

end FloatMod
