-- Generated by kanon from float.knl, float.kn. Do not edit.
import FloatMod.Statements.Float.min
import FloatMod.Soundness.Laws

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace FloatMod

open Classical Kanon

set_option maxHeartbeats 400000 in
theorem Float.min.r_lits.main.ok : Float.min.r_lits.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Float.min.r_lits.main)

set_option maxHeartbeats 400000 in
theorem Float.min.r_default.main.ok : Float.min.r_default.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Float.min.r_default.main)

end FloatMod
