-- Generated by kanon from float.knl, float.kn. Do not edit.
import FloatMod.Statements.Float.round
import FloatMod.Soundness.Laws

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace FloatMod

open Classical Kanon

set_option maxHeartbeats 400000 in
theorem Float.round.r_lit.main.ok : Float.round.r_lit.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Float.round.r_lit.main)

set_option maxHeartbeats 400000 in
theorem Float.round.r_default.main.ok : Float.round.r_default.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Float.round.r_default.main)

end FloatMod
