-- Generated by kanon from ptr.knl, ptr.kn. Do not edit.
import PtrMod.Statements.Bool.sure_neq
import PtrMod.Proofs
import KanonBool.Soundness.Comm
import BitvecMod.Soundness.Comm

set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false
set_option maxHeartbeats 1000000

noncomputable section

namespace PtrMod

open Classical Kanon

set_option maxHeartbeats 400000 in
theorem Bool.sure_neq.c1.ok : Bool.sure_neq.c1.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.sure_neq.c1)

end PtrMod
