-- Generated by bvr from lang.bvl, bool.bvl, exists.bvl, bitvec.bvl, float.bvl, ptr.bvl. Do not edit.

import Bvr.Abstract

namespace Bvr

inductive Ty where
  | TBool
  | TFloat : Fp → Ty
  | TLoc : Int → Ty
  | TPointer : Int → Ty
  | TSeq : Ty → Ty
  | TBitVector : Int → Ty
  | TExtension : ExtTy → Ty
  deriving DecidableEq, Repr, Inhabited

mutual
inductive Kind where
  | Var : Int → Kind
  | Bool : Bool → Kind
  | Float : Float → Kind
  | Ptr : Term → Term → Kind
  | BitVec : Int → Kind
  | Seq : (List Term) → Kind
  | Unop : Unop → Term → Kind
  | Binop : Binop → Term → Term → Kind
  | Triop : Triop → Term → Term → Term → Kind
  | Nop : Nop → (List Term) → Kind
  | Exists : (List (Int × Ty)) → Term → Kind
  | Extension : Ext → Kind
inductive Term where
  | mk (kind : Kind) (ty : Ty)
end

def Term.kind : Term → Kind
  | .mk k _ => k

def Term.ty : Term → Ty
  | .mk _ t => t

@[simp] theorem Term.kind_mk (k : Kind) (t : Ty) : (Term.mk k t).kind = k := rfl
@[simp] theorem Term.ty_mk (k : Kind) (t : Ty) : (Term.mk k t).ty = t := rfl

instance : Inhabited Kind := ⟨.Var default⟩
instance : Inhabited Term := ⟨.mk default default⟩

end Bvr
