(** Bit-vector based values, with floating point support. Suitable for low-level
    languages.

    {1 Overview}

    A value language is a hash-consed term language (booleans, bit-vectors,
    floats, pointers, sequences, quantifiers) with simplifying smart
    constructors, whose types and constructors are generated by Kanon from
    declarations and rules (see the README of this directory). The code that is
    generic over such a language is written once, as functors, over the
    generated types and a {!Kanon_fns} implementation: {!Value_lang} (the
    contract of a language), {!Pp}, {!Eval}, {!Expr}, {!Svalue_sugar} (the
    untyped layer), {!Typed} (a phantom "ghost" type tracking the {e kind} of
    each value: integer, boolean, pointer, ...), assembled by {!Lang_make}.
    {!Encoding} lowers values to SMT, {!Bv_solver} drives Z3, and {!Analyses}
    are the abstract domain analyses used along the way. {!Bv_base} has the host
    types that the generated types refer to.

    {1 The language of the C tool}

    {!Lang} is the value language of soteria-c. A tool uses its typed layer
    directly:
    {@ocaml[
    include Bv_values.Lang.Typed
    ]}

    {1 Other languages}

    A tool that needs another language (soteria-rust adds aggregates and
    pointers to the shared modules) declares it for Kanon, and composes the
    generic code over the generated types and its implementation [K] of
    {!Kanon_fns}:
    {@ocaml[
    module L = Bv_values.Lang_make.Make (Types) (K)
    module Typed = Bv_values.Typed.Make (L)
    ]}
    ([Typed.Make_transparent] additionally exposes the ghost-typed values as the
    untyped ones.) To discharge path conditions, feed [Typed] to a solver from
    {!Bv_solver}. *)

module Analyses = Analyses
module Bv_base = Bv_base
module Bv_solver = Bv_solver
module Encoding = Encoding
module Eval = Eval
module Expr = Expr
module Kanon_fns = Kanon_fns
module Lang = Lang
module Lang_make = Lang_make
module Pp = Pp
module Save_counter = Save_counter
module Solver_lang = Solver_lang
module Svalue_sugar = Svalue_sugar
module Typed = Typed
module Typed_intf = Typed_intf
module Value_lang = Value_lang
module View_host = View_host
