-- Generated by kanon from core.knl. Do not edit.
import CoreMod.Lang
import CoreMod.Sem
import CoreMod.Types
import CoreMod.Abstract
import KanonCore.Model
import KanonCore.Attr
import KanonCore.Embed

set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false
set_option maxHeartbeats 1000000

noncomputable section

namespace CoreMod

open Classical Kanon

/-- The rule functions, oracles and extensible helpers of the module, in the model of a
language. -/
structure Ops (S : Kanon.Sem) extends Kanon.OpsBase S

variable {S : Kanon.Sem} [CoreMod.Lang S]

/-- What the proofs assume of the model: its rule functions refine their specs, its oracles
and extensible helpers do what they are assumed to do. -/
structure Ops.Sound (O : Ops S) : Prop

end CoreMod
