(** Random differential tests of the rule functions of Bv_values (see
    [soteria/bvr]). For every rule function, generated by [bvr ocaml-tests], it
    draws small well-typed arguments, and checks that the result of the rule
    function refines its spec (the raw term): it is well-typed, of the same
    type, and, under random assignments of the variables where the spec is not
    poison (a checked operation that overflows), it is not poison and evaluates
    to the same literal, with {!Eval}.

    [BVR_RULE_COUNT] sets the number of well-typed draws per function,
    [BVR_RULE_SEED] the seed, and [BVR_RULE_STATS] prints how often each rule
    fired. *)

open Soteria.Bv_values
module Typed = Typed.Make (Svalue.Dummy_ext) ()
module Sv = Typed.Svalue
module Eval = Typed.Eval

(* The names that the generated code uses *)
module Svalue_ast = Svalue
module Symex = Soteria.Symex

module Cases = struct
  open Sv.R

  [%%include_file "rules_diff.gen.ml"]
end

let env_int name default =
  Option.bind (Sys.getenv_opt name) int_of_string_opt |> Option.value ~default

let count = env_int "BVR_RULE_COUNT" 500
let seed = env_int "BVR_RULE_SEED" 0
let stats = Sys.getenv_opt "BVR_RULE_STATS" <> None
let assignments = 4
let rs = Random.State.make [| seed |]
let int k = Random.State.int rs k
let chance p = Random.State.float rs 1. < p
let pick l = List.nth l (int (List.length l))

(* ------------------------------------------------------------------ *)
(* Well-typedness, following the typing of the operators in lang.bvl  *)
(* ------------------------------------------------------------------ *)

let ty_of (v : Sv.t) = v.node.ty
let ok_ty : Sv.ty -> bool = function TBitVector n -> n > 0 | _ -> true

let rec wt (x : Sv.t) : bool =
  let ty = ty_of x in
  let bv v = match ty_of v with TBitVector n -> n | _ -> -1 in
  let fp v = match ty_of v with TFloat p -> Some p | _ -> None in
  let is_bool v = ty_of v = TBool in
  let same a b = Sv.equal_ty (ty_of a) (ty_of b) in
  ok_ty ty
  &&
  match x.node.kind with
  | Var _ -> true
  | Bool _ -> ty = TBool
  | BitVec _ -> bv x > 0
  | Float f -> fp x = Some (Floatml.AnyFloat.precision f)
  | Unop (op, a) -> (
      wt a
      &&
      match op with
      | Not -> is_bool a && ty = TBool
      | BvOfBool n -> is_bool a && bv x = n
      | BvOfFloat (_, _, n) -> fp a <> None && bv x = n
      | FloatOfBv (_, _, p) -> bv a > 0 && fp x = Some p
      | FloatOfBvRaw p -> bv a = Svalue.FloatPrecision.size p && fp x = Some p
      | FloatOfFloat (_, p) -> fp a <> None && fp x = Some p
      | BvExtract (i, j) -> 0 <= i && i <= j && j < bv a && bv x = j - i + 1
      | BvExtend (_, k) -> bv a > 0 && k >= 0 && bv x = bv a + k
      | BvNot | Neg _ -> bv a > 0 && same a x
      | FAbs | FNeg | FSqrt | FRound _ -> fp a <> None && same a x
      | FIs _ | FIsNeg | FIsPos -> fp a <> None && ty = TBool
      | GetPtrLoc | GetPtrOfs -> false)
  | Binop (op, a, b) -> (
      wt a
      && wt b
      &&
      match op with
      | And | Or -> is_bool a && is_bool b && ty = TBool
      | Eq -> same a b && ty = TBool
      | FEq | FLeq | FLt -> fp a <> None && same a b && ty = TBool
      | FAdd | FSub | FMul | FDiv | FRem | FMin | FMax ->
          fp a <> None && same a b && same a x
      | Add _ | Sub _ | Mul _ | Div _ | Rem _ | Mod | BitAnd | BitOr | BitXor
      | Shl | LShr | AShr ->
          bv a > 0 && same a b && same a x
      | AddOvf _ | SubOvf _ | MulOvf _ | Lt _ | Leq _ ->
          bv a > 0 && same a b && ty = TBool
      | BvConcat -> bv a > 0 && bv b > 0 && bv x = bv a + bv b)
  | Triop (Ite, g, a, b) ->
      wt g && wt a && wt b && is_bool g && same a b && same a x
  | Triop (Fma, a, b, c) ->
      wt a && wt b && wt c && fp a <> None && same a b && same a c && same a x
  | Nop (Distinct, l) ->
      List.for_all wt l
      && (match l with [] -> true | h :: t -> List.for_all (same h) t)
      && ty = TBool
  | Ptr _ | Seq _ | Exists _ | Extension _ -> false

(* ------------------------------------------------------------------ *)
(* Random terms                                                       *)
(* ------------------------------------------------------------------ *)

let bv_value n =
  let z =
    match int 6 with
    | 0 -> Z.zero
    | 1 -> Z.one
    | 2 -> Z.minus_one
    | 3 -> Z.shift_left Z.one (n - 1)
    | 4 -> Z.pred (Z.shift_left Z.one (n - 1))
    | _ -> Z.of_int (int (1 lsl min n 16))
  in
  Sv.BitVec.mk_masked n z

let float_value p =
  let open Sv.Float in
  match int 8 with
  | 0 -> zero p
  | 1 -> neg_zero p
  | 2 -> one p
  | 3 -> nan p
  | 4 -> infinity p
  | 5 -> neg_infinity p
  | _ -> mk_bits p (Z.of_int (int (1 lsl 16)))

let value : Sv.ty -> Sv.t = function
  | TBool -> Sv.Bool.of_bool (Random.State.bool rs)
  | TBitVector n -> bv_value n
  | TFloat p -> float_value p
  | _ -> assert false

(** A few variables per type, so that rules matching the same variable twice
    fire. *)
let var =
  let vars = Hashtbl.create 16 in
  fun ty ->
    let i = int 3 in
    match Hashtbl.find_opt vars (i, ty) with
    | Some v -> v
    | None ->
        let v = Sv.mk_var (Symex.Var.of_int (Hashtbl.length vars)) ty in
        Hashtbl.replace vars (i, ty) v;
        v

let random_ty () : Sv.ty =
  match int 10 with
  | 0 | 1 -> TBool
  | 2 -> TFloat (pick Svalue.FloatPrecision.[ F16; F32 ])
  | 3 -> TBitVector (pick [ 16; 32 ])
  | _ -> TBitVector (1 + int 8)

let checked () = { Svalue.signed = chance 0.5; unsigned = chance 0.5 }

let is_lit (v : Sv.t) =
  match v.node.kind with Bool _ | BitVec _ | Float _ -> true | _ -> false

(** A term of the same shape as [v], so that rules matching two similar terms
    fire: its operands may be swapped, a literal operand replaced, and a strict
    comparison made non-strict (or conversely). *)
let mutate (v : Sv.t) =
  match v.node.kind with
  | Binop (op, a, b) ->
      let op : Svalue.Binop.t =
        match op with
        | Lt s | Leq s -> pick Svalue.Binop.[ Lt s; Leq s ]
        | op -> op
      in
      let fresh x = if is_lit x then value (ty_of x) else x in
      let a, b = if chance 0.3 then (b, a) else (fresh a, fresh b) in
      if Sv.equal_ty (ty_of a) (ty_of b) || op = BvConcat then
        if chance 0.5 then Sv.(Binop (op, a, b) <| ty_of v)
        else Eval.eval_binop op a b
      else v
  | _ -> v

(** The state of a draw: the terms drawn so far, and the type of the bit-vectors
    that its comparisons compare. *)
type draw = { mutable pool : Sv.t list; cmp_ty : Sv.ty }

(** A term of type [ty], of depth at most [depth], built either raw or with the
    smart constructors. It is sometimes a term drawn before, so that rules
    matching a term twice fire. *)
let rec term d ty depth : Sv.t =
  match List.filter (fun v -> Sv.equal_ty (ty_of v) ty) d.pool with
  | _ :: _ as l when chance 0.25 -> pick l
  | _ :: _ as l when chance 0.25 -> mutate (pick l)
  | _ ->
      let v = fresh d ty depth in
      d.pool <- v :: d.pool;
      v

and fresh d ty depth =
  if depth = 0 || chance 0.4 then if chance 0.5 then value ty else var ty
  else
    let sub ty = term d ty (depth - 1) in
    let raw = chance 0.5 in
    let unop op a =
      if raw then Sv.(Unop (op, a) <| ty) else Eval.eval_unop op a
    in
    let binop op a b =
      if raw then Sv.(Binop (op, a, b) <| ty) else Eval.eval_binop op a b
    in
    (* the operands of a binary operator, often with a literal *)
    let operands ty =
      let a = sub ty in
      match int 3 with
      | 0 -> (a, sub ty)
      | 1 -> (a, value ty)
      | _ -> (value ty, a)
    in
    let ite () =
      let g = sub TBool in
      if raw then Sv.(Triop (Ite, g, sub ty, sub ty) <| ty)
      else Sv.Bool.ite g (sub ty) (sub ty)
    in
    match ty with
    | TBool -> (
        match int 7 with
        | 0 -> unop Not (sub TBool)
        | 1 -> binop (pick Svalue.Binop.[ And; Or ]) (sub TBool) (sub TBool)
        | 2 ->
            let t = if chance 0.7 then d.cmp_ty else random_ty () in
            binop Eq (sub t) (sub t)
        | 3 | 4 ->
            let t = d.cmp_ty in
            let op =
              pick
                Svalue.Binop.
                  [
                    Lt true;
                    Lt false;
                    Leq true;
                    Leq false;
                    AddOvf true;
                    AddOvf false;
                    SubOvf true;
                    SubOvf false;
                    MulOvf true;
                    MulOvf false;
                  ]
            in
            let a, b = operands t in
            binop op a b
        | 5 -> ite ()
        | _ -> fresh d ty 0)
    | TBitVector n -> (
        match int 9 with
        | 0 | 1 ->
            let op =
              pick
                Svalue.Binop.
                  [
                    Add (checked ());
                    Sub (checked ());
                    Mul (checked ());
                    Div (chance 0.5);
                    Rem (chance 0.5);
                    Mod;
                    BitAnd;
                    BitOr;
                    BitXor;
                    Shl;
                    LShr;
                    AShr;
                  ]
            in
            let a, b = operands ty in
            binop op a b
        | 2 -> unop (pick Svalue.Unop.[ BvNot; Neg (chance 0.5) ]) (sub ty)
        | 3 -> unop (BvOfBool n) (sub TBool)
        | 4 ->
            let k = int 4 in
            let i = int (k + 1) in
            unop (BvExtract (i, i + n - 1)) (sub (TBitVector (n + k)))
        | 5 when n > 1 ->
            let k = 1 + int (n - 1) in
            unop (BvExtend (chance 0.5, k)) (sub (TBitVector (n - k)))
        | 6 when n > 1 ->
            let k = 1 + int (n - 1) in
            binop BvConcat (sub (TBitVector k)) (sub (TBitVector (n - k)))
        | 7 -> ite ()
        | _ -> fresh d ty 0)
    | TFloat _ -> (
        match int 4 with
        | 0 -> unop (pick Svalue.Unop.[ FNeg; FAbs ]) (sub ty)
        | 1 -> binop FAdd (sub ty) (sub ty)
        | 2 -> ite ()
        | _ -> fresh d ty 0)
    | _ -> assert false

(** The arguments of one draw: most terms have the same type, so that the draw
    is likely to be well-typed. *)
let source () : Cases.source =
  let main = random_ty () in
  let depth = 2 in
  let cmp_ty : Sv.ty =
    match main with TBitVector _ -> main | _ -> TBitVector (1 + int 8)
  in
  let d = { pool = []; cmp_ty } in
  let any_term () =
    let ty = if chance 0.7 then main else random_ty () in
    term d ty depth
  in
  {
    int = (fun () -> Z.of_int (if chance 0.1 then pick [ 16; 32 ] else int 9));
    bool = (fun () -> Random.State.bool rs);
    term = any_term;
    terms = (fun () -> List.init (int 4) (fun _ -> term d main depth));
    choose = int;
  }

(* ------------------------------------------------------------------ *)
(* Evaluation                                                         *)
(* ------------------------------------------------------------------ *)

let eval env (v : Sv.t) =
  let eval_var _ v ty =
    match Hashtbl.find_opt env v with
    | Some x -> x
    | None ->
        let x = value ty in
        Hashtbl.replace env v x;
        x
  in
  Eval.eval ~force:true ~eval_var v

(** Whether [v] is not poison under [env], following [Bvr/Semantics.lean];
    [None] if the evaluation does not tell. *)
let rec defined env (v : Sv.t) : bool option =
  let ( &&& ) a b =
    match a with Some true -> b () | Some false -> Some false | None -> None
  in
  let lit x =
    match (eval env x).node.kind with Bool b -> Some b | _ -> None
  in
  let not_ x = Option.map not (lit x) in
  let all l =
    List.fold_left (fun acc x -> acc &&& fun () -> defined env x) (Some true) l
  in
  let parallel absorbing a b =
    let da = defined env a and db = defined env b in
    let absorbs d x = d = Some true && lit x = Some absorbing in
    if absorbs da a || absorbs db b then Some true
    else Option.bind da (fun da -> Option.map (( && ) da) db)
  in
  let checked (c : Svalue.checked) ovf a b =
    let no_ovf signed = not_ Sv.(Binop (ovf signed, a, b) <| TBool) in
    all [ a; b ] &&& fun () ->
    (if c.signed then no_ovf true else Some true) &&& fun () ->
    if c.unsigned then no_ovf false else Some true
  in
  match v.node.kind with
  | Var _ | Bool _ | BitVec _ | Float _ -> Some true
  | Binop (And, a, b) -> parallel false a b
  | Binop (Or, a, b) -> parallel true a b
  | Binop (Add c, a, b) -> checked c (fun s -> AddOvf s) a b
  | Binop (Sub c, a, b) -> checked c (fun s -> SubOvf s) a b
  | Binop (Mul c, a, b) -> checked c (fun s -> MulOvf s) a b
  | Unop (Neg true, a) ->
      let n = Sv.size_of (ty_of a) in
      let min = Sv.BitVec.mk_masked n (Z.shift_left Z.one (n - 1)) in
      defined env a &&& fun () -> not_ Sv.(Binop (Eq, a, min) <| TBool)
  | Triop (Ite, g, a, b) -> (
      defined env g &&& fun () ->
      match lit g with
      | Some g -> defined env (if g then a else b)
      | None -> None)
  | Unop (_, a) -> all [ a ]
  | Binop (_, a, b) -> all [ a; b ]
  | Triop (_, a, b, c) -> all [ a; b; c ]
  | Nop (_, l) -> all l
  | Ptr _ | Seq _ | Exists _ | Extension _ -> None

(* ------------------------------------------------------------------ *)
(* The tests                                                          *)
(* ------------------------------------------------------------------ *)

(** The outcome of a draw; [Passed] and [Failed] name the rule that fired. *)
type outcome =
  | Rejected
  | Inconclusive
  | Passed of string
  | Failed of string * string

(** The rule functions with no well-typed draw, as pointers are not drawn. *)
let undrawn = [ "ptr_loc"; "ptr_ofs" ]

let check (t : Cases.test) =
  match t.spec () with
  | exception _ -> Rejected
  | spec when not (wt spec) -> Rejected
  | spec -> (
      (* the assertions of the function are its preconditions *)
      match t.fired () with
      | exception Assert_failure _ -> Rejected
      | fired -> (
          match t.call () with
          | exception e ->
              Failed
                ( fired,
                  Fmt.str "raises %s on %a" (Printexc.to_string e) Sv.pp spec )
          | res when not (wt res && Sv.equal_ty (ty_of res) (ty_of spec)) ->
              Failed
                (fired, Fmt.str "%a is ill-typed, for %a" Sv.pp res Sv.pp spec)
          | res ->
              let rec go i conclusive =
                if i = assignments then
                  if conclusive then Passed fired else Inconclusive
                else
                  let env = Hashtbl.create 8 in
                  let fail msg =
                    Failed
                      ( fired,
                        Fmt.str "@[<v 2>%a@ simplified to %a@ %s@ under %a@]"
                          Sv.pp spec Sv.pp res msg
                          Fmt.(
                            iter_bindings ~sep:comma Hashtbl.iter
                              (pair ~sep:(any " := ") Symex.Var.pp Sv.pp))
                          env )
                  in
                  match defined env spec with
                  | Some false -> go (i + 1) conclusive
                  | None -> go (i + 1) false
                  | Some true -> (
                      let spec_v = eval env spec and res_v = eval env res in
                      match defined env res with
                      | Some false -> fail "is poison"
                      | None -> go (i + 1) false
                      | Some true ->
                          if not (is_lit spec_v && is_lit res_v) then
                            go (i + 1) (conclusive && Sv.equal spec_v res_v)
                          else if Sv.equal spec_v res_v then
                            go (i + 1) conclusive
                          else
                            fail
                              (Fmt.str "evaluates to %a instead of %a" Sv.pp
                                 res_v Sv.pp spec_v))
              in
              go 0 true))

let () =
  let failures = ref 0 in
  List.iter
    (fun (name, rules, make) ->
      let fired = Hashtbl.create 16 in
      let tested = ref 0 and inconclusive = ref 0 and shown = ref 0 in
      let attempts = ref 0 in
      while !tested < count && !attempts < 50 * count do
        incr attempts;
        let t = make (source ()) in
        match check t with
        | Rejected -> ()
        | Inconclusive ->
            incr tested;
            incr inconclusive
        | Passed r ->
            incr tested;
            Hashtbl.replace fired r
              (1 + Option.value ~default:0 (Hashtbl.find_opt fired r))
        | Failed (r, msg) ->
            incr tested;
            incr failures;
            incr shown;
            if !shown <= 3 then
              Fmt.pr "@[<v 2>FAIL %s (rule %s):@ %s@]@." name r msg
      done;
      let hits r = Option.value ~default:0 (Hashtbl.find_opt fired r) in
      if stats then
        Fmt.pr "@[<hov 2>%s: %d draws, %d inconclusive;@ %a@]@." name !tested
          !inconclusive
          Fmt.(list ~sep:sp (fun ft r -> pf ft "%s=%d" r (hits r)))
          rules;
      if !tested = 0 && not (List.mem name undrawn) then (
        incr failures;
        Fmt.pr "FAIL %s: no well-typed draw@." name))
    Cases.rule_fns;
  if stats then Fmt.pr "untested: %a@." Fmt.(list ~sep:sp string) Cases.untested;
  if !failures > 0 then exit 1
