-- Generated by kanon from bool.kn, exists.kn, bitvec.kn, float.kn, ptr.kn, view.kn. Do not edit.
import Kanon.Ops
import Kanon.Model.Bitvec.lit_add_overflows
import Kanon.Model.Bitvec.max_for
import Kanon.Model.Bitvec.min_for
import Kanon.Model.Bitvec.size
import Kanon.Model.Bitvec.to_z
import Kanon.Model.mk_commut_binop

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace Kanon

open Classical Kanon

def Bitvec.add_overflows.r_lits (O : Ops) (signed : Bool) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | lit_i1@(Term.mk (Kind.BitVec i1) _), lit_i2@(Term.mk (Kind.BitVec i2) _) =>
    (whenSome true
    ((Term.mk (Kind.Bool (Bitvec.lit_add_overflows signed (ty lit_i1) (ty lit_i2) i1 i2)) Ty.TBool)))
    | _, _ => none)

def Bitvec.add_overflows.r_zero (O : Ops) (signed : Bool) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | (Term.mk (Kind.BitVec kanon__1) _), _ =>
    (whenSome (decide (kanon__1 = (0 : Int))) (v_false))
    | _, _ => none)
  <|> (match v1, v2 with
        | _, (Term.mk (Kind.BitVec kanon__1) _) =>
        (whenSome (decide (kanon__1 = (0 : Int))) (v_false))
        | _, _ => none)

def Bitvec.add_overflows.r_size1 (O : Ops) (signed : Bool) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | _, _ =>
    (whenSome (decide ((Bitvec.size v1) = (1 : Int)))
    ((let one := (bv_one (1 : Int));
     (O.bool_and_ (O.bool_eq v1 one) (O.bool_eq v2 one))))))

def Bitvec.add_overflows.r_unsigned (O : Ops) (signed : Bool) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | (Term.mk (Kind.BitVec z) _), x =>
    (whenSome (! signed)
    ((O.bitvec_lt signed (mk_bv (Bitvec.size x) (lit_not (ty x) z)) x)))
    | _, _ => none)
  <|> (match v1, v2 with
        | x, (Term.mk (Kind.BitVec z) _) =>
        (whenSome (! signed)
        ((O.bitvec_lt signed (mk_bv (Bitvec.size x) (lit_not (ty x) z)) x)))
        | _, _ => none)

def Bitvec.add_overflows.r_signed (O : Ops) (signed : Bool) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | (Term.mk (Kind.BitVec z) _), x =>
    (whenSome signed
    ((let n := (Bitvec.size x);
     (let z := (Bitvec.to_z signed n z);
     (if (decide (z > (0 : Int)))
     then (O.bitvec_lt signed (mk_masked n ((Bitvec.max_for signed n) - z)) x)
     else (O.bitvec_lt signed x (mk_masked n ((Bitvec.min_for signed n) - z))))))))
    | _, _ => none)
  <|> (match v1, v2 with
        | x, (Term.mk (Kind.BitVec z) _) =>
        (whenSome signed
        ((let n := (Bitvec.size x);
         (let z := (Bitvec.to_z signed n z);
         (if (decide (z > (0 : Int)))
         then (O.bitvec_lt signed (mk_masked n ((Bitvec.max_for signed n) - z)) x)
         else (O.bitvec_lt signed x (mk_masked n ((Bitvec.min_for signed n) - z))))))))
        | _, _ => none)

def Bitvec.add_overflows.r_of_bools (O : Ops) (signed : Bool) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | (Term.mk (Kind.Op1 (Op1.BvOfBool n) b1) _), (Term.mk (Kind.Op1 (Op1.BvOfBool _) b2) _) =>
    (whenSome (decide (n > (1 : Int)))
    ((if (signed && (decide (n = (2 : Int))))
     then (O.bool_and_ b1 b2)
     else v_false)))
    | _, _ => none)
  <|> (match v1, v2 with
        | (Term.mk (Kind.Op1 (Op1.BvOfBool _) b2) _), (Term.mk (Kind.Op1 (Op1.BvOfBool n) b1) _) =>
        (whenSome (decide (n > (1 : Int)))
        ((if (signed && (decide (n = (2 : Int))))
         then (O.bool_and_ b1 b2)
         else v_false)))
        | _, _ => none)

def Bitvec.add_overflows.r_of_bool (O : Ops) (signed : Bool) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | (Term.mk (Kind.Op1 (Op1.BvOfBool _) b) _), other =>
    (whenSome (decide ((Bitvec.size other) > (1 : Int)))
    ((let n := (Bitvec.size other);
     (O.bool_and_ b (O.bool_eq other (mk_masked n (Bitvec.max_for signed n)))))))
    | _, _ => none)
  <|> (match v1, v2 with
        | other, (Term.mk (Kind.Op1 (Op1.BvOfBool _) b) _) =>
        (whenSome (decide ((Bitvec.size other) > (1 : Int)))
        ((let n := (Bitvec.size other);
         (O.bool_and_ b (O.bool_eq other (mk_masked n (Bitvec.max_for signed n)))))))
        | _, _ => none)

def Bitvec.add_overflows.r_default (O : Ops) (signed : Bool) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | _, _ =>
    (whenSome true
    ((Term.mk (mk_commut_binop O (Op2.AddOvf signed) v1 v2) Ty.TBool))))

def Bitvec.add_overflows.step (O : Ops) (signed : Bool) (v1 : Term) (v2 : Term) : Term :=
  (firstSome [Bitvec.add_overflows.r_lits O signed v1 v2, Bitvec.add_overflows.r_zero O signed v1 v2, Bitvec.add_overflows.r_size1 O signed v1 v2, Bitvec.add_overflows.r_unsigned O signed v1 v2, Bitvec.add_overflows.r_signed O signed v1 v2, Bitvec.add_overflows.r_of_bools O signed v1 v2, Bitvec.add_overflows.r_of_bool O signed v1 v2, Bitvec.add_overflows.r_default O signed v1 v2]).getD (Bitvec.add_overflows.spec signed v1 v2)

end Kanon
