-- Generated by kanon from bool.kn, exists.kn, bitvec.kn, float.kn, ptr.kn, view.kn. Do not edit.
import Kanon.Ops
import Kanon.Model.Bitvec.size
import Kanon.Model.Bitvec.zmin

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace Kanon

open Classical Kanon

def Bitvec.ashr.r_lits (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | lit_i1@(Term.mk (Kind.BitVec i1) _), lit_i2@(Term.mk (Kind.BitVec i2) _) =>
    (whenSome true
    ((Term.mk (Kind.BitVec (lit_ashr (ty lit_i1) (ty lit_i2) i1 i2)) (ty v1))))
    | _, _ => none)

def Bitvec.ashr.r_zero (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | _, (Term.mk (Kind.BitVec kanon__2) _) =>
    (whenSome (decide (kanon__2 = (0 : Int))) (v1))
    | _, _ => none)

def Bitvec.ashr.r_big (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | _, (Term.mk (Kind.BitVec s) _) =>
    (whenSome (decide (s ≥ (Bitvec.size v1)))
    ((let sz := (Bitvec.size v1);
     (O.bitvec_ashr v1 (mk_masked sz (sz - (1 : Int)))))))
    | _, _ => none)

def Bitvec.ashr.r_ashr (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | (Term.mk (Kind.Op2 Op2.AShr v (Term.mk (Kind.BitVec s1) _)) _), (Term.mk (Kind.BitVec s2) _) =>
    (whenSome true
    ((let sz := (Bitvec.size v1);
     (O.bitvec_ashr v (mk_masked sz (Bitvec.zmin (s1 + s2) (sz - (1 : Int))))))))
    | _, _ => none)

def Bitvec.ashr.r_default (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | _, _ =>
    (whenSome true ((Term.mk (Kind.Op2 Op2.AShr v1 v2) (ty v1)))))

def Bitvec.ashr.step (O : Ops) (v1 : Term) (v2 : Term) : Term :=
  (firstSome [Bitvec.ashr.r_lits O v1 v2, Bitvec.ashr.r_zero O v1 v2, Bitvec.ashr.r_big O v1 v2, Bitvec.ashr.r_ashr O v1 v2, Bitvec.ashr.r_default O v1 v2]).getD (Bitvec.ashr.spec v1 v2)

end Kanon
