-- Generated by kanon from bool.kn, exists.kn, bitvec.kn, float.kn, ptr.kn, view.kn. Do not edit.
import Kanon.Ops
import Kanon.Model.Bitvec.checked_unsigned
import Kanon.Model.Bitvec.msb_of
import Kanon.Model.Bitvec.overflows_mul
import Kanon.Model.Bitvec.size
import Kanon.Model.Bitvec.udivides

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace Kanon

open Classical Kanon

def Bitvec.div.r_lits (O : Ops) (signed : Bool) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | (Term.mk (Kind.BitVec l) _), (Term.mk (Kind.BitVec r) _) =>
    (whenSome true
    ((mk_bv (Bitvec.size v1) (if signed
                             then (lit_sdiv (ty v1) (ty v2) l r)
                             else (lit_udiv (ty v1) (ty v2) l r)))))
    | _, _ => none)

def Bitvec.div.r_one (O : Ops) (signed : Bool) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | _, (Term.mk (Kind.BitVec kanon__2) _) =>
    (whenSome (decide (kanon__2 = (1 : Int))) (v1))
    | _, _ => none)

def Bitvec.div.r_mul_lits (O : Ops) (signed : Bool) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | (Term.mk (Kind.Op2 (Op2.Mul checked) l@(Term.mk (Kind.BitVec _) _) r@(Term.mk (Kind.BitVec _) _)) _), (Term.mk (Kind.BitVec _) _) =>
    (whenSome true ((O.bitvec_div signed (O.bitvec_mul checked l r) v2)))
    | _, _ => none)

def Bitvec.div.r_mul_div (O : Ops) (signed : Bool) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | (Term.mk (Kind.Op2 (Op2.Mul ⟨_, true⟩) (Term.mk (Kind.BitVec n) _) x) _), (Term.mk (Kind.BitVec d) _) =>
    (whenSome ((! signed) && ((decide (d ≠ (0 : Int))) && (Bitvec.udivides d n)))
    ((O.bitvec_mul Bitvec.checked_unsigned x (mk_bv (Bitvec.size v1) (lit_udiv (ty v1) (ty v2) n d)))))
    | _, _ => none)
  <|> (match v1, v2 with
        | (Term.mk (Kind.Op2 (Op2.Mul ⟨_, true⟩) x (Term.mk (Kind.BitVec n) _)) _), (Term.mk (Kind.BitVec d) _) =>
        (whenSome ((! signed) && ((decide (d ≠ (0 : Int))) && (Bitvec.udivides d n)))
        ((O.bitvec_mul Bitvec.checked_unsigned x (mk_bv (Bitvec.size v1) (lit_udiv (ty v1) (ty v2) n d)))))
        | _, _ => none)

def Bitvec.div.r_div_mul (O : Ops) (signed : Bool) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | (Term.mk (Kind.Op2 (Op2.Mul ⟨_, true⟩) (Term.mk (Kind.BitVec n) _) x) _), (Term.mk (Kind.BitVec d) _) =>
    (whenSome ((! signed) && ((decide (n ≠ (0 : Int))) && (Bitvec.udivides n d)))
    ((O.bitvec_div signed x (mk_bv (Bitvec.size v1) (lit_udiv (ty v2) (ty v1) d n)))))
    | _, _ => none)
  <|> (match v1, v2 with
        | (Term.mk (Kind.Op2 (Op2.Mul ⟨_, true⟩) x (Term.mk (Kind.BitVec n) _)) _), (Term.mk (Kind.BitVec d) _) =>
        (whenSome ((! signed) && ((decide (n ≠ (0 : Int))) && (Bitvec.udivides n d)))
        ((O.bitvec_div signed x (mk_bv (Bitvec.size v1) (lit_udiv (ty v2) (ty v1) d n)))))
        | _, _ => none)

def Bitvec.div.r_div_div (O : Ops) (signed : Bool) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | (Term.mk (Kind.Op2 (Op2.Div false) x (Term.mk (Kind.BitVec n) _)) _), (Term.mk (Kind.BitVec d) _) =>
    (whenSome ((! signed) && ((decide (n ≠ (0 : Int))) && (! (Bitvec.overflows_mul false (Bitvec.size v1) n d))))
    ((O.bitvec_div signed x (mk_bv (Bitvec.size v1) (lit_mul (ty v1) (ty v2) n d)))))
    | _, _ => none)

def Bitvec.div.r_zext (O : Ops) (signed : Bool) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | (Term.mk (Kind.Op1 (Op1.BvExtend false «by») x) _), (Term.mk (Kind.BitVec z) _) =>
    (whenSome ((! signed) && (decide ((Bitvec.msb_of v2) < (Bitvec.size x))))
    ((O.bitvec_extend_ false «by» (O.bitvec_div signed x (mk_masked (Bitvec.size x) z)))))
    | _, _ => none)

def Bitvec.div.r_default (O : Ops) (signed : Bool) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | _, _ =>
    (whenSome true ((Term.mk (Kind.Op2 (Op2.Div signed) v1 v2) (ty v1)))))

def Bitvec.div.step (O : Ops) (signed : Bool) (v1 : Term) (v2 : Term) : Term :=
  (firstSome [Bitvec.div.r_lits O signed v1 v2, Bitvec.div.r_one O signed v1 v2, Bitvec.div.r_mul_lits O signed v1 v2, Bitvec.div.r_mul_div O signed v1 v2, Bitvec.div.r_div_mul O signed v1 v2, Bitvec.div.r_div_div O signed v1 v2, Bitvec.div.r_zext O signed v1 v2, Bitvec.div.r_default O signed v1 v2]).getD (Bitvec.div.spec signed v1 v2)

end Kanon
