-- Generated by kanon from bool.kn, exists.kn, bitvec.kn, float.kn, ptr.kn, view.kn. Do not edit.
import Kanon.Ops
import Kanon.Model.Bitvec.bits_in
import Kanon.Model.Bitvec.size
import Kanon.Model.mk_commut_binop

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace Kanon

open Classical Kanon

def Bitvec.or_.r_lits (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | lit_i1@(Term.mk (Kind.BitVec i1) _), lit_i2@(Term.mk (Kind.BitVec i2) _) =>
    (whenSome true
    ((Term.mk (Kind.BitVec (lit_or (ty lit_i1) (ty lit_i2) i1 i2)) (ty v1))))
    | _, _ => none)

def Bitvec.or_.r_zero (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | x, (Term.mk (Kind.BitVec kanon__2) _) =>
    (whenSome (decide (kanon__2 = (0 : Int))) (x))
    | _, _ => none)
  <|> (match v1, v2 with
        | (Term.mk (Kind.BitVec kanon__2) _), x =>
        (whenSome (decide (kanon__2 = (0 : Int))) (x))
        | _, _ => none)

def Bitvec.or_.r_same (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with | x, kanon__2 => (whenSome (decide (x = kanon__2)) (x)))

def Bitvec.or_.r_mask_and (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | v_m1@(Term.mk (Kind.BitVec m1) _), (Term.mk (Kind.Op2 Op2.BitAnd _ (Term.mk (Kind.BitVec m2) _)) _) =>
    (whenSome (Bitvec.bits_in m2 m1) (v_m1))
    | _, _ => none)
  <|> (match v1, v2 with
        | v_m1@(Term.mk (Kind.BitVec m1) _), (Term.mk (Kind.Op2 Op2.BitAnd (Term.mk (Kind.BitVec m2) _) _) _) =>
        (whenSome (Bitvec.bits_in m2 m1) (v_m1))
        | _, _ => none)
  <|> (match v1, v2 with
        | (Term.mk (Kind.Op2 Op2.BitAnd _ (Term.mk (Kind.BitVec m2) _)) _), v_m1@(Term.mk (Kind.BitVec m1) _) =>
        (whenSome (Bitvec.bits_in m2 m1) (v_m1))
        | _, _ => none)
  <|> (match v1, v2 with
        | (Term.mk (Kind.Op2 Op2.BitAnd (Term.mk (Kind.BitVec m2) _) _) _), v_m1@(Term.mk (Kind.BitVec m1) _) =>
        (whenSome (Bitvec.bits_in m2 m1) (v_m1))
        | _, _ => none)

def Bitvec.or_.r_masks (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | (Term.mk (Kind.BitVec m1) _), (Term.mk (Kind.Op2 Op2.BitOr x (Term.mk (Kind.BitVec m2) _)) _) =>
    (whenSome true
    ((O.bitvec_or_ x (mk_bv (Bitvec.size x) (lit_or (ty x) (ty x) m1 m2)))))
    | _, _ => none)
  <|> (match v1, v2 with
        | (Term.mk (Kind.BitVec m1) _), (Term.mk (Kind.Op2 Op2.BitOr (Term.mk (Kind.BitVec m2) _) x) _) =>
        (whenSome true
        ((O.bitvec_or_ x (mk_bv (Bitvec.size x) (lit_or (ty x) (ty x) m1 m2)))))
        | _, _ => none)
  <|> (match v1, v2 with
        | (Term.mk (Kind.Op2 Op2.BitOr x (Term.mk (Kind.BitVec m2) _)) _), (Term.mk (Kind.BitVec m1) _) =>
        (whenSome true
        ((O.bitvec_or_ x (mk_bv (Bitvec.size x) (lit_or (ty x) (ty x) m1 m2)))))
        | _, _ => none)
  <|> (match v1, v2 with
        | (Term.mk (Kind.Op2 Op2.BitOr (Term.mk (Kind.BitVec m2) _) x) _), (Term.mk (Kind.BitVec m1) _) =>
        (whenSome true
        ((O.bitvec_or_ x (mk_bv (Bitvec.size x) (lit_or (ty x) (ty x) m1 m2)))))
        | _, _ => none)

def Bitvec.or_.r_extend_shl (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | (Term.mk (Kind.Op1 (Op1.BvExtend false nx) base) _), (Term.mk (Kind.Op2 Op2.Shl (Term.mk (Kind.Op1 (Op1.BvExtend false _) tail) _) (Term.mk (Kind.BitVec shift) _)) _) =>
    (whenSome ((decide (shift = (Bitvec.size base))) && (decide (nx > (0 : Int))))
    ((let tail_size := (Bitvec.size tail);
     (if (decide (nx = tail_size))
     then (O.bitvec_concat tail base)
     else (if (decide (nx > tail_size))
          then (let new_base := (O.bitvec_concat tail base);
               (O.bitvec_extend_ false (nx - tail_size) new_base))
          else (let new_tail := (O.bitvec_extract (0 : Int) (nx - (1 : Int)) tail);
               (O.bitvec_concat new_tail base)))))))
    | _, _ => none)
  <|> (match v1, v2 with
        | (Term.mk (Kind.Op2 Op2.Shl (Term.mk (Kind.Op1 (Op1.BvExtend false _) tail) _) (Term.mk (Kind.BitVec shift) _)) _), (Term.mk (Kind.Op1 (Op1.BvExtend false nx) base) _) =>
        (whenSome ((decide (shift = (Bitvec.size base))) && (decide (nx > (0 : Int))))
        ((let tail_size := (Bitvec.size tail);
         (if (decide (nx = tail_size))
         then (O.bitvec_concat tail base)
         else (if (decide (nx > tail_size))
              then (let new_base := (O.bitvec_concat tail base);
                   (O.bitvec_extend_ false (nx - tail_size) new_base))
              else (let new_tail := (O.bitvec_extract (0 : Int) (nx - (1 : Int)) tail);
                   (O.bitvec_concat new_tail base)))))))
        | _, _ => none)

def Bitvec.or_.r_of_bools (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | (Term.mk (Kind.Op1 (Op1.BvOfBool n) b1) _), (Term.mk (Kind.Op1 (Op1.BvOfBool _) b2) _) =>
    (whenSome true ((O.bitvec_of_bool n (O.bool_or_ b1 b2))))
    | _, _ => none)

def Bitvec.or_.r_default (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | _, _ =>
    (whenSome true ((Term.mk (mk_commut_binop O Op2.BitOr v1 v2) (ty v1)))))

def Bitvec.or_.step (O : Ops) (v1 : Term) (v2 : Term) : Term :=
  (firstSome [Bitvec.or_.r_lits O v1 v2, Bitvec.or_.r_zero O v1 v2, Bitvec.or_.r_same O v1 v2, Bitvec.or_.r_mask_and O v1 v2, Bitvec.or_.r_masks O v1 v2, Bitvec.or_.r_extend_shl O v1 v2, Bitvec.or_.r_of_bools O v1 v2, Bitvec.or_.r_default O v1 v2]).getD (Bitvec.or_.spec v1 v2)

end Kanon
