-- Generated by kanon from float.knl, float.kn. Do not edit.
import FloatMod.Statements

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace FloatMod

open Classical Kanon

def Float.cast.r_lit.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} {LBool : KanonBool.Syntax B} {LCore : CoreMod.Syntax B} {LBitvec : BitvecMod.Syntax B LBool LCore} (L : FloatMod.Syntax B LBool LCore LBitvec) [KanonBool.Sem LBool] [CoreMod.Sem LCore] [BitvecMod.Sem LBitvec] [Sem L] (O : Ops L), O.Sound →
  ∀ (rounding : CoreMod.Rm) (fp : CoreMod.Fp) (f : CoreMod.Float) (t__2 : S.Ty),
  S.Refines (FloatMod.Float.cast.spec L rounding fp (B.node (L.FloatK f) t__2))
  ((let kanon__a1 := (O.float_f_convert rounding fp f);
   (B.node (L.FloatK kanon__a1) (L.TFloat (L.float_f_prec kanon__a1)))))

def Float.cast.r_default.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} {LBool : KanonBool.Syntax B} {LCore : CoreMod.Syntax B} {LBitvec : BitvecMod.Syntax B LBool LCore} (L : FloatMod.Syntax B LBool LCore LBitvec) [KanonBool.Sem LBool] [CoreMod.Sem LCore] [BitvecMod.Sem LBitvec] [Sem L] (O : Ops L), O.Sound →
  ∀ (rounding : CoreMod.Rm) (fp : CoreMod.Fp) (v : S.Term),
  S.Refines (FloatMod.Float.cast.spec L rounding fp v)
  ((B.node (L.FloatOfFloatK rounding fp v) (L.TFloat fp)))

end FloatMod
