-- Generated by kanon from float.knl, float.kn. Do not edit.
import FloatMod.Lift

set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false
set_option maxHeartbeats 1000000

noncomputable section

namespace FloatMod

open Classical Kanon

def Float.is_floatclass.r_lit.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [FloatMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] [FloatMod.Typed S] (O : Ops S), O.Sound →
  ∀ (fc : CoreMod.Fc) (f : CoreMod.Float) (t__2 : S.Ty),
  S.Refines (FloatMod.Float.is_floatclass.spec fc (FloatMod.mk (.Float f) t__2))
  ((KanonBool.mk (.Bool (FloatMod.f_is_class fc f)) (KanonBool.sort .TBool)))

def Float.is_floatclass.r_default.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [FloatMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] [FloatMod.Typed S] (O : Ops S), O.Sound →
  ∀ (fc : CoreMod.Fc) (sv : S.Term),
  S.Refines (FloatMod.Float.is_floatclass.spec fc sv)
  ((FloatMod.mk (.FIs fc sv) (KanonBool.sort .TBool)))

end FloatMod
