-- Generated by kanon from float.knl, float.kn. Do not edit.
import FloatMod.Lift

set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false
set_option maxHeartbeats 1000000

noncomputable section

namespace FloatMod

open Classical Kanon

def Float.of_float.r_lit.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [FloatMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] [FloatMod.Typed S] (O : Ops S), O.Sound →
  ∀ (rounding : CoreMod.Rm) (signed : Bool) (sz : Int) (f : CoreMod.Float) (t__2 : S.Ty),
  S.Refines (FloatMod.Float.of_float.spec rounding signed sz (FloatMod.mk (.Float f) t__2))
  (((firstSome [(match (O.float_f_to_int rounding signed sz f) with
                  | (some z) =>
                  some ((BitvecMod.mk_masked sz z))
                  | _ => none),
     (match (O.float_f_to_int rounding signed sz f) with
       | none =>
       some ((FloatMod.mk (.BvOfFloat rounding signed sz (FloatMod.mk (.Float f) t__2)) (BitvecMod.sort (.TBitVector sz))))
       | _ => none)]).getD
     Inhabited.default))

def Float.of_float.r_default.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [FloatMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] [FloatMod.Typed S] (O : Ops S), O.Sound →
  ∀ (rounding : CoreMod.Rm) (signed : Bool) (sz : Int) (v : S.Term),
  S.Refines (FloatMod.Float.of_float.spec rounding signed sz v)
  ((FloatMod.mk (.BvOfFloat rounding signed sz v) (BitvecMod.sort (.TBitVector sz))))

end FloatMod
