-- Generated by kanon from float.knl, float.kn. Do not edit.
import FloatMod.Statements

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace FloatMod

open Classical Kanon

def Float.sub.r_lits.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} {LBool : KanonBool.Syntax B} {LCore : CoreMod.Syntax B} {LBitvec : BitvecMod.Syntax B LBool LCore} (L : FloatMod.Syntax B LBool LCore LBitvec) [KanonBool.Sem LBool] [CoreMod.Sem LCore] [BitvecMod.Sem LBitvec] [Sem L] (O : Ops L), O.Sound →
  ∀ (f1 : CoreMod.Float) (t__2 : S.Ty) (f2 : CoreMod.Float) (t__4 : S.Ty),
  S.Refines (FloatMod.Float.sub.spec L (B.node (L.FloatK f1) t__2) (B.node (L.FloatK f2) t__4))
  ((let kanon__a1 := (O.float_f_sub f1 f2);
   (B.node (L.FloatK kanon__a1) (L.TFloat (L.float_f_prec kanon__a1)))))

def Float.sub.r_default.main.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} {LBool : KanonBool.Syntax B} {LCore : CoreMod.Syntax B} {LBitvec : BitvecMod.Syntax B LBool LCore} (L : FloatMod.Syntax B LBool LCore LBitvec) [KanonBool.Sem LBool] [CoreMod.Sem LCore] [BitvecMod.Sem LBitvec] [Sem L] (O : Ops L), O.Sound →
  ∀ (v1 : S.Term) (v2 : S.Term),
  S.Refines (FloatMod.Float.sub.spec L v1 v2)
  ((B.node (L.FSubK v1 v2) (S.ty v1)))

end FloatMod
