-- Generated by kanon from bool.kn, exists.kn, bitvec.kn, float.kn, ptr.kn, view.kn. Do not edit.
import KanonCore.Tactics
import Kanon.Statements.Bool.and_
import Kanon.Lifts
import Kanon.Nodes
import Kanon.Lib.Rule
import Kanon.Soundness.Laws.Op2.And
import Kanon.Soundness.Laws.Op2.Or
import Kanon.Soundness.Laws.Op2.Eq
import Kanon.Soundness.Laws.Op2.Add
import Kanon.Soundness.Laws.Op2.Mul
import Kanon.Soundness.Laws.Op2.BitAnd
import Kanon.Soundness.Laws.Op2.BitOr
import Kanon.Soundness.Laws.Op2.BitXor
import Kanon.Instance.Bool
import Kanon.Lang.Bool
import KanonBool.Soundness.Bool.and_
import Kanon.Proofs.Bool.and_

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace Kanon

open Classical Kanon

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_same.main.ok : Bool.and_.r_same.main.Stmt :=
  fun FS O hO => KanonBool.Bool.and_.r_same.main.ok (S := (sem FS)) (boolSyntax FS)
  (Ops.toBool FS O) (Ops.Sound.toBool hO)

theorem Bool.and_.r_same.proof : Bool.and_.r_same.Stmt := by
  intro FS O hO v1 v2 res h
  simp only [Bool.and_.r_same] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.and_.r_same.main.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_false_.main.ok : Bool.and_.r_false_.main.Stmt :=
  fun FS O hO => KanonBool.Bool.and_.r_false_.main.ok (S := (sem FS)) (boolSyntax FS)
  (Ops.toBool FS O) (Ops.Sound.toBool hO)

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_false_.swap.ok : Bool.and_.r_false_.swap.Stmt :=
  fun FS O hO => KanonBool.Bool.and_.r_false_.swap.ok (S := (sem FS)) (boolSyntax FS)
  (Ops.toBool FS O) (Ops.Sound.toBool hO)

theorem Bool.and_.r_false_.proof : Bool.and_.r_false_.Stmt := by
  intro FS O hO v1 v2 res h
  simp only [Bool.and_.r_false_] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.and_.r_false_.main.ok FS O hO)
  · kanon_arm h (Bool.and_.r_false_.swap.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_true_.main.ok : Bool.and_.r_true_.main.Stmt :=
  fun FS O hO => KanonBool.Bool.and_.r_true_.main.ok (S := (sem FS)) (boolSyntax FS)
  (Ops.toBool FS O) (Ops.Sound.toBool hO)

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_true_.swap.ok : Bool.and_.r_true_.swap.Stmt :=
  fun FS O hO => KanonBool.Bool.and_.r_true_.swap.ok (S := (sem FS)) (boolSyntax FS)
  (Ops.toBool FS O) (Ops.Sound.toBool hO)

theorem Bool.and_.r_true_.proof : Bool.and_.r_true_.Stmt := by
  intro FS O hO v1 v2 res h
  simp only [Bool.and_.r_true_] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.and_.r_true_.main.ok FS O hO)
  · kanon_arm h (Bool.and_.r_true_.swap.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_not.main.ok : Bool.and_.r_not.main.Stmt :=
  fun FS O hO => KanonBool.Bool.and_.r_not.main.ok (S := (sem FS)) (boolSyntax FS)
  (Ops.toBool FS O) (Ops.Sound.toBool hO)

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_not.swap.ok : Bool.and_.r_not.swap.Stmt :=
  fun FS O hO => KanonBool.Bool.and_.r_not.swap.ok (S := (sem FS)) (boolSyntax FS)
  (Ops.toBool FS O) (Ops.Sound.toBool hO)

theorem Bool.and_.r_not.proof : Bool.and_.r_not.Stmt := by
  intro FS O hO v1 v2 res h
  simp only [Bool.and_.r_not] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.and_.r_not.main.ok FS O hO)
  · kanon_arm h (Bool.and_.r_not.swap.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_and_.main.ok : Bool.and_.r_and_.main.Stmt :=
  fun FS O hO => KanonBool.Bool.and_.r_and_.main.ok (S := (sem FS)) (boolSyntax FS)
  (Ops.toBool FS O) (Ops.Sound.toBool hO)

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_and_.swap1.ok : Bool.and_.r_and_.swap1.Stmt :=
  fun FS O hO => KanonBool.Bool.and_.r_and_.swap1.ok (S := (sem FS)) (boolSyntax FS)
  (Ops.toBool FS O) (Ops.Sound.toBool hO)

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_and_.swap2.ok : Bool.and_.r_and_.swap2.Stmt :=
  fun FS O hO => KanonBool.Bool.and_.r_and_.swap2.ok (S := (sem FS)) (boolSyntax FS)
  (Ops.toBool FS O) (Ops.Sound.toBool hO)

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_and_.swap1_swap2.ok : Bool.and_.r_and_.swap1_swap2.Stmt :=
  fun FS O hO => KanonBool.Bool.and_.r_and_.swap1_swap2.ok (S := (sem FS)) (boolSyntax FS)
  (Ops.toBool FS O) (Ops.Sound.toBool hO)

theorem Bool.and_.r_and_.proof : Bool.and_.r_and_.Stmt := by
  intro FS O hO v1 v2 res h
  simp only [Bool.and_.r_and_] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.and_.r_and_.main.ok FS O hO)
  · kanon_arm h (Bool.and_.r_and_.swap1.ok FS O hO)
  · kanon_arm h (Bool.and_.r_and_.swap2.ok FS O hO)
  · kanon_arm h (Bool.and_.r_and_.swap1_swap2.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_or_.main.ok : Bool.and_.r_or_.main.Stmt :=
  fun FS O hO => KanonBool.Bool.and_.r_or_.main.ok (S := (sem FS)) (boolSyntax FS)
  (Ops.toBool FS O) (Ops.Sound.toBool hO)

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_or_.swap1.ok : Bool.and_.r_or_.swap1.Stmt :=
  fun FS O hO => KanonBool.Bool.and_.r_or_.swap1.ok (S := (sem FS)) (boolSyntax FS)
  (Ops.toBool FS O) (Ops.Sound.toBool hO)

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_or_.swap2.ok : Bool.and_.r_or_.swap2.Stmt :=
  fun FS O hO => KanonBool.Bool.and_.r_or_.swap2.ok (S := (sem FS)) (boolSyntax FS)
  (Ops.toBool FS O) (Ops.Sound.toBool hO)

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_or_.swap1_swap2.ok : Bool.and_.r_or_.swap1_swap2.Stmt :=
  fun FS O hO => KanonBool.Bool.and_.r_or_.swap1_swap2.ok (S := (sem FS)) (boolSyntax FS)
  (Ops.toBool FS O) (Ops.Sound.toBool hO)

theorem Bool.and_.r_or_.proof : Bool.and_.r_or_.Stmt := by
  intro FS O hO v1 v2 res h
  simp only [Bool.and_.r_or_] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.and_.r_or_.main.ok FS O hO)
  · kanon_arm h (Bool.and_.r_or_.swap1.ok FS O hO)
  · kanon_arm h (Bool.and_.r_or_.swap2.ok FS O hO)
  · kanon_arm h (Bool.and_.r_or_.swap1_swap2.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_eq_neq.main.ok : Bool.and_.r_eq_neq.main.Stmt :=
  fun FS O hO => KanonBool.Bool.and_.r_eq_neq.main.ok (S := (sem FS)) (boolSyntax FS)
  (Ops.toBool FS O) (Ops.Sound.toBool hO)

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_eq_neq.swap2.ok : Bool.and_.r_eq_neq.swap2.Stmt :=
  fun FS O hO => KanonBool.Bool.and_.r_eq_neq.swap2.ok (S := (sem FS)) (boolSyntax FS)
  (Ops.toBool FS O) (Ops.Sound.toBool hO)

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_eq_neq.swap1.ok : Bool.and_.r_eq_neq.swap1.Stmt :=
  fun FS O hO => KanonBool.Bool.and_.r_eq_neq.swap1.ok (S := (sem FS)) (boolSyntax FS)
  (Ops.toBool FS O) (Ops.Sound.toBool hO)

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_eq_neq.swap1_swap2.ok : Bool.and_.r_eq_neq.swap1_swap2.Stmt :=
  fun FS O hO => KanonBool.Bool.and_.r_eq_neq.swap1_swap2.ok (S := (sem FS)) (boolSyntax FS)
  (Ops.toBool FS O) (Ops.Sound.toBool hO)

theorem Bool.and_.r_eq_neq.proof : Bool.and_.r_eq_neq.Stmt := by
  intro FS O hO v1 v2 res h
  simp only [Bool.and_.r_eq_neq] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.and_.r_eq_neq.main.ok FS O hO)
  · kanon_arm h (Bool.and_.r_eq_neq.swap2.ok FS O hO)
  · kanon_arm h (Bool.and_.r_eq_neq.swap1.ok FS O hO)
  · kanon_arm h (Bool.and_.r_eq_neq.swap1_swap2.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_eq_extracts.main.ok : Bool.and_.r_eq_extracts.main.Stmt := kanon_proof% Bool.and_.r_eq_extracts.main

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_eq_extracts.swap2.ok : Bool.and_.r_eq_extracts.swap2.Stmt := by
  intro FS O hO w__2 t__3 s1 e1 x t__9 t__10 s2 e2 kanon__19 t__20 w__13 t__14 t__21 hg
  have : Refines FS (Term.mk (Kind.Op2 Op2.Eq (Term.mk (Kind.Op1 (Op1.BvExtract s2 e2) kanon__19) t__20) (Term.mk (Kind.BitVec w__13) t__14)) t__21)
    (Term.mk (Kind.Op2 Op2.Eq (Term.mk (Kind.BitVec w__13) t__14) (Term.mk (Kind.Op1 (Op1.BvExtract s2 e2) kanon__19) t__20)) t__21) :=
    Op2.Eq.comm.ok FS ..
  refine Refinement.trans ?_
    (Bool.and_.r_eq_extracts.main.ok FS O hO w__2 t__3 s1 e1 x t__9 t__10 w__13 t__14 s2 e2 kanon__19 t__20 t__21 hg)
  simp only [Bool.and_.spec]
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_eq_extracts.swap1.ok : Bool.and_.r_eq_extracts.swap1.Stmt := by
  intro FS O hO s1 e1 x t__9 w__2 t__3 t__10 w__13 t__14 s2 e2 kanon__19 t__20 t__21 hg
  have : Refines FS (Term.mk (Kind.Op2 Op2.Eq (Term.mk (Kind.Op1 (Op1.BvExtract s1 e1) x) t__9) (Term.mk (Kind.BitVec w__2) t__3)) t__10)
    (Term.mk (Kind.Op2 Op2.Eq (Term.mk (Kind.BitVec w__2) t__3) (Term.mk (Kind.Op1 (Op1.BvExtract s1 e1) x) t__9)) t__10) :=
    Op2.Eq.comm.ok FS ..
  refine Refinement.trans ?_
    (Bool.and_.r_eq_extracts.main.ok FS O hO w__2 t__3 s1 e1 x t__9 t__10 w__13 t__14 s2 e2 kanon__19 t__20 t__21 hg)
  simp only [Bool.and_.spec]
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_eq_extracts.swap1_swap2.ok : Bool.and_.r_eq_extracts.swap1_swap2.Stmt := by
  intro FS O hO s1 e1 x t__9 w__2 t__3 t__10 s2 e2 kanon__19 t__20 w__13 t__14 t__21 hg
  have : Refines FS (Term.mk (Kind.Op2 Op2.Eq (Term.mk (Kind.Op1 (Op1.BvExtract s1 e1) x) t__9) (Term.mk (Kind.BitVec w__2) t__3)) t__10)
    (Term.mk (Kind.Op2 Op2.Eq (Term.mk (Kind.BitVec w__2) t__3) (Term.mk (Kind.Op1 (Op1.BvExtract s1 e1) x) t__9)) t__10) :=
    Op2.Eq.comm.ok FS ..
  have : Refines FS (Term.mk (Kind.Op2 Op2.Eq (Term.mk (Kind.Op1 (Op1.BvExtract s2 e2) kanon__19) t__20) (Term.mk (Kind.BitVec w__13) t__14)) t__21)
    (Term.mk (Kind.Op2 Op2.Eq (Term.mk (Kind.BitVec w__13) t__14) (Term.mk (Kind.Op1 (Op1.BvExtract s2 e2) kanon__19) t__20)) t__21) :=
    Op2.Eq.comm.ok FS ..
  refine Refinement.trans ?_
    (Bool.and_.r_eq_extracts.main.ok FS O hO w__2 t__3 s1 e1 x t__9 t__10 w__13 t__14 s2 e2 kanon__19 t__20 t__21 hg)
  simp only [Bool.and_.spec]
  kanon_congr

theorem Bool.and_.r_eq_extracts.proof : Bool.and_.r_eq_extracts.Stmt := by
  intro FS O hO v1 v2 res h
  simp only [Bool.and_.r_eq_extracts] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.and_.r_eq_extracts.main.ok FS O hO)
  · kanon_arm h (Bool.and_.r_eq_extracts.swap2.ok FS O hO)
  · kanon_arm h (Bool.and_.r_eq_extracts.swap1.ok FS O hO)
  · kanon_arm h (Bool.and_.r_eq_extracts.swap1_swap2.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_upper_bounds.lt_lt.ok : Bool.and_.r_upper_bounds.lt_lt.Stmt := kanon_proof% Bool.and_.r_upper_bounds.lt_lt

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_upper_bounds.lt_leq.ok : Bool.and_.r_upper_bounds.lt_leq.Stmt := kanon_proof% Bool.and_.r_upper_bounds.lt_leq

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_upper_bounds.leq_lt.ok : Bool.and_.r_upper_bounds.leq_lt.Stmt := kanon_proof% Bool.and_.r_upper_bounds.leq_lt

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_upper_bounds.leq_leq.ok : Bool.and_.r_upper_bounds.leq_leq.Stmt := kanon_proof% Bool.and_.r_upper_bounds.leq_leq

theorem Bool.and_.r_upper_bounds.proof : Bool.and_.r_upper_bounds.Stmt := by
  intro FS O hO v1 v2 res h
  simp only [Bool.and_.r_upper_bounds] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.and_.r_upper_bounds.lt_lt.ok FS O hO)
  · kanon_arm h (Bool.and_.r_upper_bounds.lt_leq.ok FS O hO)
  · kanon_arm h (Bool.and_.r_upper_bounds.leq_lt.ok FS O hO)
  · kanon_arm h (Bool.and_.r_upper_bounds.leq_leq.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_lower_bounds.lt_lt.ok : Bool.and_.r_lower_bounds.lt_lt.Stmt := kanon_proof% Bool.and_.r_lower_bounds.lt_lt

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_lower_bounds.lt_leq.ok : Bool.and_.r_lower_bounds.lt_leq.Stmt := kanon_proof% Bool.and_.r_lower_bounds.lt_leq

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_lower_bounds.leq_lt.ok : Bool.and_.r_lower_bounds.leq_lt.Stmt := kanon_proof% Bool.and_.r_lower_bounds.leq_lt

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_lower_bounds.leq_leq.ok : Bool.and_.r_lower_bounds.leq_leq.Stmt := kanon_proof% Bool.and_.r_lower_bounds.leq_leq

theorem Bool.and_.r_lower_bounds.proof : Bool.and_.r_lower_bounds.Stmt := by
  intro FS O hO v1 v2 res h
  simp only [Bool.and_.r_lower_bounds] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.and_.r_lower_bounds.lt_lt.ok FS O hO)
  · kanon_arm h (Bool.and_.r_lower_bounds.lt_leq.ok FS O hO)
  · kanon_arm h (Bool.and_.r_lower_bounds.leq_lt.ok FS O hO)
  · kanon_arm h (Bool.and_.r_lower_bounds.leq_leq.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bool.and_.r_default.main.ok : Bool.and_.r_default.main.Stmt :=
  fun FS O hO => KanonBool.Bool.and_.r_default.main.ok (S := (sem FS)) (boolSyntax FS)
  (Ops.toBool FS O) (Ops.Sound.toBool hO)

theorem Bool.and_.r_default.proof : Bool.and_.r_default.Stmt := by
  intro FS O hO v1 v2 res h
  simp only [Bool.and_.r_default] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bool.and_.r_default.main.ok FS O hO)

theorem Bool.and_.step_sound (FS : FloatSem) (O : Ops) (hO : O.Sound FS) (v1 : Term) (v2 : Term) :
  Refines FS (Bool.and_.spec v1 v2) (Bool.and_.step O v1 v2) := by
  unfold Bool.and_.step
  refine Refinement.firstSome_cons (fun res h => Bool.and_.r_same.proof FS O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.and_.r_false_.proof FS O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.and_.r_true_.proof FS O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.and_.r_not.proof FS O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.and_.r_and_.proof FS O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.and_.r_or_.proof FS O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.and_.r_eq_neq.proof FS O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.and_.r_eq_extracts.proof FS O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.and_.r_upper_bounds.proof FS O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.and_.r_lower_bounds.proof FS O hO v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bool.and_.r_default.proof FS O hO v1 v2 res h) ?_
  exact Refinement.firstSome_nil

end Kanon
