-- Generated by kanon from bool.kn, exists.kn, bitvec.kn, float.kn, ptr.kn, view.kn. Do not edit.
import KanonCore.Tactics
import Kanon.Statements.Float.neg
import Kanon.Instance.Float
import Kanon.Lang.Bitvec
import Kanon.Lang.Bool
import Kanon.Lang.Core
import Kanon.Lang.Float
import FloatMod.Soundness.Float.neg

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace Kanon

open Classical Kanon

set_option maxHeartbeats 400000 in
theorem Float.neg.r_lit.main.ok : Float.neg.r_lit.main.Stmt :=
  fun FS O hO => FloatMod.Float.neg.r_lit.main.ok (S := (sem FS)) (floatSyntax FS)
  (Ops.toFloat FS O) (Ops.Sound.toFloat hO)

theorem Float.neg.r_lit.proof : Float.neg.r_lit.Stmt := by
  intro FS O hO v res h
  simp only [Float.neg.r_lit] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Float.neg.r_lit.main.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Float.neg.r_neg.main.ok : Float.neg.r_neg.main.Stmt :=
  fun FS O hO => FloatMod.Float.neg.r_neg.main.ok (S := (sem FS)) (floatSyntax FS)
  (Ops.toFloat FS O) (Ops.Sound.toFloat hO)

theorem Float.neg.r_neg.proof : Float.neg.r_neg.Stmt := by
  intro FS O hO v res h
  simp only [Float.neg.r_neg] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Float.neg.r_neg.main.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Float.neg.r_default.main.ok : Float.neg.r_default.main.Stmt :=
  fun FS O hO => FloatMod.Float.neg.r_default.main.ok (S := (sem FS)) (floatSyntax FS)
  (Ops.toFloat FS O) (Ops.Sound.toFloat hO)

theorem Float.neg.r_default.proof : Float.neg.r_default.Stmt := by
  intro FS O hO v res h
  simp only [Float.neg.r_default] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Float.neg.r_default.main.ok FS O hO)

theorem Float.neg.step_sound (FS : FloatSem) (O : Ops) (hO : O.Sound FS) (v : Term) :
  Refines FS (Float.neg.spec v) (Float.neg.step O v) := by
  unfold Float.neg.step
  refine Refinement.firstSome_cons (fun res h => Float.neg.r_lit.proof FS O hO v res h) ?_
  refine Refinement.firstSome_cons (fun res h => Float.neg.r_neg.proof FS O hO v res h) ?_
  refine Refinement.firstSome_cons (fun res h => Float.neg.r_default.proof FS O hO v res h) ?_
  exact Refinement.firstSome_nil

end Kanon
