-- Generated by kanon from bool.kn, exists.kn, bitvec.kn, float.kn, ptr.kn, view.kn. Do not edit.
import KanonCore.Tactics
import Kanon.Statements.Float.sqrt
import Kanon.Instance.Float
import Kanon.Lang.Bitvec
import Kanon.Lang.Bool
import Kanon.Lang.Core
import Kanon.Lang.Float
import FloatMod.Soundness.Float.sqrt

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace Kanon

open Classical Kanon

set_option maxHeartbeats 400000 in
theorem Float.sqrt.r_lit.main.ok : Float.sqrt.r_lit.main.Stmt :=
  fun FS O hO => FloatMod.Float.sqrt.r_lit.main.ok (S := (sem FS)) (floatSyntax FS)
  (Ops.toFloat FS O) (Ops.Sound.toFloat hO)

theorem Float.sqrt.r_lit.proof : Float.sqrt.r_lit.Stmt := by
  intro FS O hO v res h
  simp only [Float.sqrt.r_lit] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Float.sqrt.r_lit.main.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Float.sqrt.r_default.main.ok : Float.sqrt.r_default.main.Stmt :=
  fun FS O hO => FloatMod.Float.sqrt.r_default.main.ok (S := (sem FS)) (floatSyntax FS)
  (Ops.toFloat FS O) (Ops.Sound.toFloat hO)

theorem Float.sqrt.r_default.proof : Float.sqrt.r_default.Stmt := by
  intro FS O hO v res h
  simp only [Float.sqrt.r_default] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Float.sqrt.r_default.main.ok FS O hO)

theorem Float.sqrt.step_sound (FS : FloatSem) (O : Ops) (hO : O.Sound FS) (v : Term) :
  Refines FS (Float.sqrt.spec v) (Float.sqrt.step O v) := by
  unfold Float.sqrt.step
  refine Refinement.firstSome_cons (fun res h => Float.sqrt.r_lit.proof FS O hO v res h) ?_
  refine Refinement.firstSome_cons (fun res h => Float.sqrt.r_default.proof FS O hO v res h) ?_
  exact Refinement.firstSome_nil

end Kanon
