-- Generated by kanon from bool.kn, exists.kn, bitvec.kn, float.kn, ptr.kn, view.kn. Do not edit.
import KanonCore.Tactics
import Kanon.Statements.Float.to_float
import Kanon.Lifts
import Kanon.Nodes
import Kanon.Lib.Rule
import Kanon.Proofs.Float.to_float

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace Kanon

open Classical Kanon

set_option maxHeartbeats 400000 in
theorem Float.to_float.r_lit.main.ok : Float.to_float.r_lit.main.Stmt := kanon_proof% Float.to_float.r_lit.main

theorem Float.to_float.r_lit.proof : Float.to_float.r_lit.Stmt := by
  intro FS O hO rounding signed fp v res h
  simp only [Float.to_float.r_lit] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Float.to_float.r_lit.main.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Float.to_float.r_default.main.ok : Float.to_float.r_default.main.Stmt := kanon_proof% Float.to_float.r_default.main

theorem Float.to_float.r_default.proof : Float.to_float.r_default.Stmt := by
  intro FS O hO rounding signed fp v res h
  simp only [Float.to_float.r_default] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Float.to_float.r_default.main.ok FS O hO)

theorem Float.to_float.step_sound (FS : FloatSem) (O : Ops) (hO : O.Sound FS) (rounding : CoreMod.Rm) (signed : Bool) (fp : CoreMod.Fp) (v : Term) :
  Refines FS (Float.to_float.spec rounding signed fp v) (Float.to_float.step O rounding signed fp v) := by
  unfold Float.to_float.step
  refine Refinement.firstSome_cons (fun res h => Float.to_float.r_lit.proof FS O hO rounding signed fp v res h) ?_
  refine Refinement.firstSome_cons (fun res h => Float.to_float.r_default.proof FS O hO rounding signed fp v res h) ?_
  exact Refinement.firstSome_nil

end Kanon
