-- Generated by kanon from bitvec.knl, bitvec.kn. Do not edit.
import BitvecMod.Statements.Bool.eq
import BitvecMod.Soundness.Laws

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace BitvecMod

open Classical Kanon

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_bvs.bitVec_bitVec.ok : Bool.eq.r_bvs.bitVec_bitVec.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_bvs.bitVec_bitVec)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_bvs.locLit_locLit.ok : Bool.eq.r_bvs.locLit_locLit.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_bvs.locLit_locLit)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_neg.main.ok : Bool.eq.r_neg.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_neg.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_neg.swap.ok : Bool.eq.r_neg.swap.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_neg.swap)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_not.main.ok : Bool.eq.r_not.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_not.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_not.swap.ok : Bool.eq.r_not.swap.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_not.swap)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_add_const.main.ok : Bool.eq.r_add_const.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_add_const.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_add_const.swap1.ok : Bool.eq.r_add_const.swap1.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_add_const.swap1)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_add_const.swap2.ok : Bool.eq.r_add_const.swap2.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_add_const.swap2)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_add_const.swap1_swap2.ok : Bool.eq.r_add_const.swap1_swap2.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_add_const.swap1_swap2)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_sub_const1.main.ok : Bool.eq.r_sub_const1.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_sub_const1.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_sub_const1.swap.ok : Bool.eq.r_sub_const1.swap.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_sub_const1.swap)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_sub_const2.main.ok : Bool.eq.r_sub_const2.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_sub_const2.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_sub_const2.swap.ok : Bool.eq.r_sub_const2.swap.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_sub_const2.swap)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_self_add.main.ok : Bool.eq.r_self_add.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_self_add.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_self_add.swap1.ok : Bool.eq.r_self_add.swap1.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_self_add.swap1)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_self_add.swap2.ok : Bool.eq.r_self_add.swap2.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_self_add.swap2)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_self_add.swap1_swap2.ok : Bool.eq.r_self_add.swap1_swap2.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_self_add.swap1_swap2)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_add_add.main.ok : Bool.eq.r_add_add.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_add_add.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_add_add.swap2.ok : Bool.eq.r_add_add.swap2.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_add_add.swap2)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_add_add.swap1.ok : Bool.eq.r_add_add.swap1.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_add_add.swap1)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_add_add.swap1_swap2.ok : Bool.eq.r_add_add.swap1_swap2.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_add_add.swap1_swap2)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_mul_const.main.ok : Bool.eq.r_mul_const.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_mul_const.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_mul_const.swap1.ok : Bool.eq.r_mul_const.swap1.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_mul_const.swap1)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_mul_const.swap2.ok : Bool.eq.r_mul_const.swap2.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_mul_const.swap2)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_mul_const.swap1_swap2.ok : Bool.eq.r_mul_const.swap1_swap2.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_mul_const.swap1_swap2)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_mul_cancel.main.ok : Bool.eq.r_mul_cancel.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_mul_cancel.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_mul_cancel.swap2.ok : Bool.eq.r_mul_cancel.swap2.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_mul_cancel.swap2)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_mul_cancel.swap1.ok : Bool.eq.r_mul_cancel.swap1.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_mul_cancel.swap1)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_mul_cancel.swap1_swap2.ok : Bool.eq.r_mul_cancel.swap1_swap2.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_mul_cancel.swap1_swap2)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_or_zero.main.ok : Bool.eq.r_or_zero.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_or_zero.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_or_zero.swap.ok : Bool.eq.r_or_zero.swap.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_or_zero.swap)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_and_mask.main.ok : Bool.eq.r_and_mask.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_and_mask.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_and_mask.swap1.ok : Bool.eq.r_and_mask.swap1.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_and_mask.swap1)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_and_mask.swap2.ok : Bool.eq.r_and_mask.swap2.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_and_mask.swap2)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_and_mask.swap1_swap2.ok : Bool.eq.r_and_mask.swap1_swap2.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_and_mask.swap1_swap2)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_concat_const.main.ok : Bool.eq.r_concat_const.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_concat_const.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_concat_const.swap.ok : Bool.eq.r_concat_const.swap.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_concat_const.swap)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_zext_const.main.ok : Bool.eq.r_zext_const.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_zext_const.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_zext_const.swap.ok : Bool.eq.r_zext_const.swap.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_zext_const.swap)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_ite_concat.main.ok : Bool.eq.r_ite_concat.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_ite_concat.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_ite_concat.swap.ok : Bool.eq.r_ite_concat.swap.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_ite_concat.swap)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_concat_concat.main.ok : Bool.eq.r_concat_concat.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_concat_concat.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_ite_const.bitVec.ok : Bool.eq.r_ite_const.bitVec.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_ite_const.bitVec)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_ite_const.locLit.ok : Bool.eq.r_ite_const.locLit.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_ite_const.locLit)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_ite_const.bitVec_swap.ok : Bool.eq.r_ite_const.bitVec_swap.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_ite_const.bitVec_swap)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_ite_const.locLit_swap.ok : Bool.eq.r_ite_const.locLit_swap.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_ite_const.locLit_swap)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_of_bools.main.ok : Bool.eq.r_of_bools.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_of_bools.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_of_bool_const.main.ok : Bool.eq.r_of_bool_const.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_of_bool_const.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_of_bool_const.swap.ok : Bool.eq.r_of_bool_const.swap.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_of_bool_const.swap)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_msb.main.ok : Bool.eq.r_msb.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_msb.main)

end BitvecMod
