-- Generated by kanon from bitvec.knl, bitvec.kn. Do not edit.
import BitvecMod.Statements.Bool.eq
import BitvecMod.Proofs
import KanonBool.Soundness.Comm
import BitvecMod.Soundness.Comm

set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false
set_option maxHeartbeats 1000000

noncomputable section

namespace BitvecMod

open Classical Kanon

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_bvs.bitVec_bitVec.ok : Bool.eq.r_bvs.bitVec_bitVec.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_bvs.bitVec_bitVec)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_bvs.locLit_locLit.ok : Bool.eq.r_bvs.locLit_locLit.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_bvs.locLit_locLit)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_neg.main.ok : Bool.eq.r_neg.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_neg.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_neg.swap.ok : Bool.eq.r_neg.swap.Stmt := by
  intro S _ _ _ _ _ _ O hO w__4 x t__7 w__1 t__2
  refine Kanon.Sem.Refines.trans ?_
    (Bool.eq.r_neg.main.ok O hO w__1 t__2 w__4 x t__7)
  simp only [KanonBool.Bool.eq.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (KanonBool.Eq.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_not.main.ok : Bool.eq.r_not.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_not.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_not.swap.ok : Bool.eq.r_not.swap.Stmt := by
  intro S _ _ _ _ _ _ O hO x t__6 w__1 t__2
  refine Kanon.Sem.Refines.trans ?_
    (Bool.eq.r_not.main.ok O hO w__1 t__2 x t__6)
  simp only [KanonBool.Bool.eq.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (KanonBool.Eq.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_add_const.main.ok : Bool.eq.r_add_const.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_add_const.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_add_const.swap1.ok : Bool.eq.r_add_const.swap1.Stmt := by
  intro S _ _ _ _ _ _ O hO w__1 t__2 w__4 r w__6 t__7 t__10
  have : S.Refines (BitvecMod.mk (.Add w__4 r (BitvecMod.mk (.BitVec w__6) t__7)) t__10)
    (BitvecMod.mk (.Add w__4 (BitvecMod.mk (.BitVec w__6) t__7) r) t__10) :=
    BitvecMod.Add.comm.ok ..
  refine Kanon.Sem.Refines.trans ?_
    (Bool.eq.r_add_const.main.ok O hO w__1 t__2 w__4 w__6 t__7 r t__10)
  simp only [KanonBool.Bool.eq.spec, Kanon.NodeEmbed.ty_inj]
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_add_const.swap2.ok : Bool.eq.r_add_const.swap2.Stmt := by
  intro S _ _ _ _ _ _ O hO w__4 w__6 t__7 r t__10 w__1 t__2
  refine Kanon.Sem.Refines.trans ?_
    (Bool.eq.r_add_const.main.ok O hO w__1 t__2 w__4 w__6 t__7 r t__10)
  simp only [KanonBool.Bool.eq.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (KanonBool.Eq.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_add_const.swap1_swap2.ok : Bool.eq.r_add_const.swap1_swap2.Stmt := by
  intro S _ _ _ _ _ _ O hO w__4 r w__6 t__7 t__10 w__1 t__2
  have : S.Refines (BitvecMod.mk (.Add w__4 r (BitvecMod.mk (.BitVec w__6) t__7)) t__10)
    (BitvecMod.mk (.Add w__4 (BitvecMod.mk (.BitVec w__6) t__7) r) t__10) :=
    BitvecMod.Add.comm.ok ..
  refine Kanon.Sem.Refines.trans ?_
    (Bool.eq.r_add_const.main.ok O hO w__1 t__2 w__4 w__6 t__7 r t__10)
  simp only [KanonBool.Bool.eq.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (KanonBool.Eq.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_sub_const1.main.ok : Bool.eq.r_sub_const1.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_sub_const1.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_sub_const1.swap.ok : Bool.eq.r_sub_const1.swap.Stmt := by
  intro S _ _ _ _ _ _ O hO w__4 l w__7 t__8 t__10 w__1 t__2
  refine Kanon.Sem.Refines.trans ?_
    (Bool.eq.r_sub_const1.main.ok O hO w__1 t__2 w__4 l w__7 t__8 t__10)
  simp only [KanonBool.Bool.eq.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (KanonBool.Eq.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_sub_const2.main.ok : Bool.eq.r_sub_const2.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_sub_const2.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_sub_const2.swap.ok : Bool.eq.r_sub_const2.swap.Stmt := by
  intro S _ _ _ _ _ _ O hO w__4 w__6 t__7 r t__10 w__1 t__2
  refine Kanon.Sem.Refines.trans ?_
    (Bool.eq.r_sub_const2.main.ok O hO w__1 t__2 w__4 w__6 t__7 r t__10)
  simp only [KanonBool.Bool.eq.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (KanonBool.Eq.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_self_add.main.ok : Bool.eq.r_self_add.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_self_add.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_self_add.swap1.ok : Bool.eq.r_self_add.swap1.Stmt := by
  intro S _ _ _ _ _ _ O hO v1 w__2 bv t__6 kanon__4 t__7 hg
  have : S.Refines (BitvecMod.mk (.Add w__2 (BitvecMod.mk (.BitVec bv) t__6) kanon__4) t__7)
    (BitvecMod.mk (.Add w__2 kanon__4 (BitvecMod.mk (.BitVec bv) t__6)) t__7) :=
    BitvecMod.Add.comm.ok ..
  refine Kanon.Sem.Refines.trans ?_
    (Bool.eq.r_self_add.main.ok O hO v1 w__2 kanon__4 bv t__6 t__7 hg)
  simp only [KanonBool.Bool.eq.spec, Kanon.NodeEmbed.ty_inj]
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_self_add.swap2.ok : Bool.eq.r_self_add.swap2.Stmt := by
  intro S _ _ _ _ _ _ O hO v2 w__2 kanon__4 bv t__6 t__7 hg
  refine Kanon.Sem.Refines.trans ?_
    (Bool.eq.r_self_add.main.ok O hO v2 w__2 kanon__4 bv t__6 t__7 hg)
  simp only [KanonBool.Bool.eq.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (KanonBool.Eq.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_self_add.swap1_swap2.ok : Bool.eq.r_self_add.swap1_swap2.Stmt := by
  intro S _ _ _ _ _ _ O hO v2 w__2 bv t__6 kanon__4 t__7 hg
  have : S.Refines (BitvecMod.mk (.Add w__2 (BitvecMod.mk (.BitVec bv) t__6) kanon__4) t__7)
    (BitvecMod.mk (.Add w__2 kanon__4 (BitvecMod.mk (.BitVec bv) t__6)) t__7) :=
    BitvecMod.Add.comm.ok ..
  refine Kanon.Sem.Refines.trans ?_
    (Bool.eq.r_self_add.main.ok O hO v2 w__2 kanon__4 bv t__6 t__7 hg)
  simp only [KanonBool.Bool.eq.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (KanonBool.Eq.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_add_add.main.ok : Bool.eq.r_add_add.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_add_add.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_add_add.swap2.ok : Bool.eq.r_add_add.swap2.Stmt := by
  intro S _ _ _ _ _ _ O hO w__1 bv_l t__4 y t__7 w__9 x bv_r t__12 t__15
  have : S.Refines (BitvecMod.mk (.Add w__9 x (BitvecMod.mk (.BitVec bv_r) t__12)) t__15)
    (BitvecMod.mk (.Add w__9 (BitvecMod.mk (.BitVec bv_r) t__12) x) t__15) :=
    BitvecMod.Add.comm.ok ..
  refine Kanon.Sem.Refines.trans ?_
    (Bool.eq.r_add_add.main.ok O hO w__1 bv_l t__4 y t__7 w__9 bv_r t__12 x t__15)
  simp only [KanonBool.Bool.eq.spec, Kanon.NodeEmbed.ty_inj]
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_add_add.swap1.ok : Bool.eq.r_add_add.swap1.Stmt := by
  intro S _ _ _ _ _ _ O hO w__1 y bv_l t__4 t__7 w__9 bv_r t__12 x t__15
  have : S.Refines (BitvecMod.mk (.Add w__1 y (BitvecMod.mk (.BitVec bv_l) t__4)) t__7)
    (BitvecMod.mk (.Add w__1 (BitvecMod.mk (.BitVec bv_l) t__4) y) t__7) :=
    BitvecMod.Add.comm.ok ..
  refine Kanon.Sem.Refines.trans ?_
    (Bool.eq.r_add_add.main.ok O hO w__1 bv_l t__4 y t__7 w__9 bv_r t__12 x t__15)
  simp only [KanonBool.Bool.eq.spec, Kanon.NodeEmbed.ty_inj]
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_add_add.swap1_swap2.ok : Bool.eq.r_add_add.swap1_swap2.Stmt := by
  intro S _ _ _ _ _ _ O hO w__1 y bv_l t__4 t__7 w__9 x bv_r t__12 t__15
  have : S.Refines (BitvecMod.mk (.Add w__1 y (BitvecMod.mk (.BitVec bv_l) t__4)) t__7)
    (BitvecMod.mk (.Add w__1 (BitvecMod.mk (.BitVec bv_l) t__4) y) t__7) :=
    BitvecMod.Add.comm.ok ..
  have : S.Refines (BitvecMod.mk (.Add w__9 x (BitvecMod.mk (.BitVec bv_r) t__12)) t__15)
    (BitvecMod.mk (.Add w__9 (BitvecMod.mk (.BitVec bv_r) t__12) x) t__15) :=
    BitvecMod.Add.comm.ok ..
  refine Kanon.Sem.Refines.trans ?_
    (Bool.eq.r_add_add.main.ok O hO w__1 bv_l t__4 y t__7 w__9 bv_r t__12 x t__15)
  simp only [KanonBool.Bool.eq.spec, Kanon.NodeEmbed.ty_inj]
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_mul_const.main.ok : Bool.eq.r_mul_const.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_mul_const.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_mul_const.swap1.ok : Bool.eq.r_mul_const.swap1.Stmt := by
  intro S _ _ _ _ _ _ O hO n t__2 ck x m t__6 t__8 hg
  have : S.Refines (BitvecMod.mk (.Mul ck x (BitvecMod.mk (.BitVec m) t__6)) t__8)
    (BitvecMod.mk (.Mul ck (BitvecMod.mk (.BitVec m) t__6) x) t__8) :=
    BitvecMod.Mul.comm.ok ..
  refine Kanon.Sem.Refines.trans ?_
    (Bool.eq.r_mul_const.main.ok O hO n t__2 ck m t__6 x t__8 hg)
  simp only [KanonBool.Bool.eq.spec, Kanon.NodeEmbed.ty_inj]
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_mul_const.swap2.ok : Bool.eq.r_mul_const.swap2.Stmt := by
  intro S _ _ _ _ _ _ O hO ck m t__6 x t__8 n t__2 hg
  refine Kanon.Sem.Refines.trans ?_
    (Bool.eq.r_mul_const.main.ok O hO n t__2 ck m t__6 x t__8 hg)
  simp only [KanonBool.Bool.eq.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (KanonBool.Eq.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_mul_const.swap1_swap2.ok : Bool.eq.r_mul_const.swap1_swap2.Stmt := by
  intro S _ _ _ _ _ _ O hO ck x m t__6 t__8 n t__2 hg
  have : S.Refines (BitvecMod.mk (.Mul ck x (BitvecMod.mk (.BitVec m) t__6)) t__8)
    (BitvecMod.mk (.Mul ck (BitvecMod.mk (.BitVec m) t__6) x) t__8) :=
    BitvecMod.Mul.comm.ok ..
  refine Kanon.Sem.Refines.trans ?_
    (Bool.eq.r_mul_const.main.ok O hO n t__2 ck m t__6 x t__8 hg)
  simp only [KanonBool.Bool.eq.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (KanonBool.Eq.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_mul_cancel.main.ok : Bool.eq.r_mul_cancel.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_mul_cancel.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_mul_cancel.swap2.ok : Bool.eq.r_mul_cancel.swap2.Stmt := by
  intro S _ _ _ _ _ _ O hO ck1 a t__4 b t__6 ck2 d a2 t__11 t__13 hg
  have : S.Refines (BitvecMod.mk (.Mul ck2 d (BitvecMod.mk (.BitVec a2) t__11)) t__13)
    (BitvecMod.mk (.Mul ck2 (BitvecMod.mk (.BitVec a2) t__11) d) t__13) :=
    BitvecMod.Mul.comm.ok ..
  refine Kanon.Sem.Refines.trans ?_
    (Bool.eq.r_mul_cancel.main.ok O hO ck1 a t__4 b t__6 ck2 a2 t__11 d t__13 hg)
  simp only [KanonBool.Bool.eq.spec, Kanon.NodeEmbed.ty_inj]
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_mul_cancel.swap1.ok : Bool.eq.r_mul_cancel.swap1.Stmt := by
  intro S _ _ _ _ _ _ O hO ck1 b a t__4 t__6 ck2 a2 t__11 d t__13 hg
  have : S.Refines (BitvecMod.mk (.Mul ck1 b (BitvecMod.mk (.BitVec a) t__4)) t__6)
    (BitvecMod.mk (.Mul ck1 (BitvecMod.mk (.BitVec a) t__4) b) t__6) :=
    BitvecMod.Mul.comm.ok ..
  refine Kanon.Sem.Refines.trans ?_
    (Bool.eq.r_mul_cancel.main.ok O hO ck1 a t__4 b t__6 ck2 a2 t__11 d t__13 hg)
  simp only [KanonBool.Bool.eq.spec, Kanon.NodeEmbed.ty_inj]
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_mul_cancel.swap1_swap2.ok : Bool.eq.r_mul_cancel.swap1_swap2.Stmt := by
  intro S _ _ _ _ _ _ O hO ck1 b a t__4 t__6 ck2 d a2 t__11 t__13 hg
  have : S.Refines (BitvecMod.mk (.Mul ck1 b (BitvecMod.mk (.BitVec a) t__4)) t__6)
    (BitvecMod.mk (.Mul ck1 (BitvecMod.mk (.BitVec a) t__4) b) t__6) :=
    BitvecMod.Mul.comm.ok ..
  have : S.Refines (BitvecMod.mk (.Mul ck2 d (BitvecMod.mk (.BitVec a2) t__11)) t__13)
    (BitvecMod.mk (.Mul ck2 (BitvecMod.mk (.BitVec a2) t__11) d) t__13) :=
    BitvecMod.Mul.comm.ok ..
  refine Kanon.Sem.Refines.trans ?_
    (Bool.eq.r_mul_cancel.main.ok O hO ck1 a t__4 b t__6 ck2 a2 t__11 d t__13 hg)
  simp only [KanonBool.Bool.eq.spec, Kanon.NodeEmbed.ty_inj]
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_or_zero.main.ok : Bool.eq.r_or_zero.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_or_zero.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_or_zero.swap.ok : Bool.eq.r_or_zero.swap.Stmt := by
  intro S _ _ _ _ _ _ O hO l r t__6 kanon__1 t__2 hg
  refine Kanon.Sem.Refines.trans ?_
    (Bool.eq.r_or_zero.main.ok O hO kanon__1 t__2 l r t__6 hg)
  simp only [KanonBool.Bool.eq.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (KanonBool.Eq.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_and_mask.main.ok : Bool.eq.r_and_mask.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_and_mask.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_and_mask.swap1.ok : Bool.eq.r_and_mask.swap1.Stmt := by
  intro S _ _ _ _ _ _ O hO n t__2 w__7 mask t__6 t__8 hg
  have : S.Refines (BitvecMod.mk (.BitAnd w__7 (BitvecMod.mk (.BitVec mask) t__6)) t__8)
    (BitvecMod.mk (.BitAnd (BitvecMod.mk (.BitVec mask) t__6) w__7) t__8) :=
    BitvecMod.BitAnd.comm.ok ..
  refine Kanon.Sem.Refines.trans ?_
    (Bool.eq.r_and_mask.main.ok O hO n t__2 mask t__6 w__7 t__8 hg)
  simp only [KanonBool.Bool.eq.spec, Kanon.NodeEmbed.ty_inj]
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_and_mask.swap2.ok : Bool.eq.r_and_mask.swap2.Stmt := by
  intro S _ _ _ _ _ _ O hO mask t__6 w__7 t__8 n t__2 hg
  refine Kanon.Sem.Refines.trans ?_
    (Bool.eq.r_and_mask.main.ok O hO n t__2 mask t__6 w__7 t__8 hg)
  simp only [KanonBool.Bool.eq.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (KanonBool.Eq.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_and_mask.swap1_swap2.ok : Bool.eq.r_and_mask.swap1_swap2.Stmt := by
  intro S _ _ _ _ _ _ O hO w__7 mask t__6 t__8 n t__2 hg
  have : S.Refines (BitvecMod.mk (.BitAnd w__7 (BitvecMod.mk (.BitVec mask) t__6)) t__8)
    (BitvecMod.mk (.BitAnd (BitvecMod.mk (.BitVec mask) t__6) w__7) t__8) :=
    BitvecMod.BitAnd.comm.ok ..
  refine Kanon.Sem.Refines.trans ?_
    (Bool.eq.r_and_mask.main.ok O hO n t__2 mask t__6 w__7 t__8 hg)
  simp only [KanonBool.Bool.eq.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (KanonBool.Eq.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_concat_const.main.ok : Bool.eq.r_concat_const.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_concat_const.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_concat_const.swap.ok : Bool.eq.r_concat_const.swap.Stmt := by
  intro S _ _ _ _ _ _ O hO l r t__7 w__1 t__2
  refine Kanon.Sem.Refines.trans ?_
    (Bool.eq.r_concat_const.main.ok O hO w__1 t__2 l r t__7)
  simp only [KanonBool.Bool.eq.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (KanonBool.Eq.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_zext_const.main.ok : Bool.eq.r_zext_const.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_zext_const.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_zext_const.swap.ok : Bool.eq.r_zext_const.swap.Stmt := by
  intro S _ _ _ _ _ _ O hO z t__7 «by» bv t__5
  refine Kanon.Sem.Refines.trans ?_
    (Bool.eq.r_zext_const.main.ok O hO «by» bv t__5 z t__7)
  simp only [KanonBool.Bool.eq.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (KanonBool.Eq.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_ite_concat.main.ok : Bool.eq.r_ite_concat.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_ite_concat.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_ite_concat.swap.ok : Bool.eq.r_ite_concat.swap.Stmt := by
  intro S _ _ _ _ _ _ O hO l r t__13 b w__3 t__4 w__6 t__7 t__9
  refine Kanon.Sem.Refines.trans ?_
    (Bool.eq.r_ite_concat.main.ok O hO b w__3 t__4 w__6 t__7 t__9 l r t__13)
  simp only [KanonBool.Bool.eq.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (KanonBool.Eq.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_concat_concat.main.ok : Bool.eq.r_concat_concat.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_concat_concat.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_ite_const.bitVec.ok : Bool.eq.r_ite_const.bitVec.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_ite_const.bitVec)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_ite_const.locLit.ok : Bool.eq.r_ite_const.locLit.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_ite_const.locLit)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_ite_const.bitVec_swap.ok : Bool.eq.r_ite_const.bitVec_swap.Stmt := by
  intro S _ _ _ _ _ _ O hO w__6 t__7 b l t t__5
  refine Kanon.Sem.Refines.trans ?_
    (Bool.eq.r_ite_const.bitVec.ok O hO b l t t__5 w__6 t__7)
  simp only [KanonBool.Bool.eq.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (KanonBool.Eq.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_ite_const.locLit_swap.ok : Bool.eq.r_ite_const.locLit_swap.Stmt := by
  intro S _ _ _ _ _ _ O hO w__8 t__9 b l t t__5
  refine Kanon.Sem.Refines.trans ?_
    (Bool.eq.r_ite_const.locLit.ok O hO b l t t__5 w__8 t__9)
  simp only [KanonBool.Bool.eq.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (KanonBool.Eq.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_of_bools.main.ok : Bool.eq.r_of_bools.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_of_bools.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_of_bool_const.main.ok : Bool.eq.r_of_bool_const.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_of_bool_const.main)

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_of_bool_const.swap.ok : Bool.eq.r_of_bool_const.swap.Stmt := by
  intro S _ _ _ _ _ _ O hO z t__6 w__1 b t__4
  refine Kanon.Sem.Refines.trans ?_
    (Bool.eq.r_of_bool_const.main.ok O hO w__1 b t__4 z t__6)
  simp only [KanonBool.Bool.eq.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (KanonBool.Eq.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bool.eq.r_msb.main.ok : Bool.eq.r_msb.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bool.eq.r_msb.main)

theorem Bool.eq.r_bvs.sound {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.eq.r_bvs O v1 v2 = some res) : S.Refines (KanonBool.Bool.eq.spec v1 v2) res := by
  unfold Bool.eq.r_bvs at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.eq.r_bvs.bitVec_bitVec.ok O hO)
  · kanon_arm h (Bool.eq.r_bvs.locLit_locLit.ok O hO)

theorem Bool.eq.r_neg.sound {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.eq.r_neg O v1 v2 = some res) : S.Refines (KanonBool.Bool.eq.spec v1 v2) res := by
  unfold Bool.eq.r_neg at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.eq.r_neg.main.ok O hO)
  · kanon_arm h (Bool.eq.r_neg.swap.ok O hO)

theorem Bool.eq.r_not.sound {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.eq.r_not O v1 v2 = some res) : S.Refines (KanonBool.Bool.eq.spec v1 v2) res := by
  unfold Bool.eq.r_not at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.eq.r_not.main.ok O hO)
  · kanon_arm h (Bool.eq.r_not.swap.ok O hO)

theorem Bool.eq.r_add_const.sound {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.eq.r_add_const O v1 v2 = some res) : S.Refines (KanonBool.Bool.eq.spec v1 v2) res := by
  unfold Bool.eq.r_add_const at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.eq.r_add_const.main.ok O hO)
  · kanon_arm h (Bool.eq.r_add_const.swap1.ok O hO)
  · kanon_arm h (Bool.eq.r_add_const.swap2.ok O hO)
  · kanon_arm h (Bool.eq.r_add_const.swap1_swap2.ok O hO)

theorem Bool.eq.r_sub_const1.sound {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.eq.r_sub_const1 O v1 v2 = some res) : S.Refines (KanonBool.Bool.eq.spec v1 v2) res := by
  unfold Bool.eq.r_sub_const1 at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.eq.r_sub_const1.main.ok O hO)
  · kanon_arm h (Bool.eq.r_sub_const1.swap.ok O hO)

theorem Bool.eq.r_sub_const2.sound {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.eq.r_sub_const2 O v1 v2 = some res) : S.Refines (KanonBool.Bool.eq.spec v1 v2) res := by
  unfold Bool.eq.r_sub_const2 at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.eq.r_sub_const2.main.ok O hO)
  · kanon_arm h (Bool.eq.r_sub_const2.swap.ok O hO)

theorem Bool.eq.r_self_add.sound {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.eq.r_self_add O v1 v2 = some res) : S.Refines (KanonBool.Bool.eq.spec v1 v2) res := by
  unfold Bool.eq.r_self_add at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.eq.r_self_add.main.ok O hO)
  · kanon_arm h (Bool.eq.r_self_add.swap1.ok O hO)
  · kanon_arm h (Bool.eq.r_self_add.swap2.ok O hO)
  · kanon_arm h (Bool.eq.r_self_add.swap1_swap2.ok O hO)

theorem Bool.eq.r_add_add.sound {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.eq.r_add_add O v1 v2 = some res) : S.Refines (KanonBool.Bool.eq.spec v1 v2) res := by
  unfold Bool.eq.r_add_add at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.eq.r_add_add.main.ok O hO)
  · kanon_arm h (Bool.eq.r_add_add.swap2.ok O hO)
  · kanon_arm h (Bool.eq.r_add_add.swap1.ok O hO)
  · kanon_arm h (Bool.eq.r_add_add.swap1_swap2.ok O hO)

theorem Bool.eq.r_mul_const.sound {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.eq.r_mul_const O v1 v2 = some res) : S.Refines (KanonBool.Bool.eq.spec v1 v2) res := by
  unfold Bool.eq.r_mul_const at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.eq.r_mul_const.main.ok O hO)
  · kanon_arm h (Bool.eq.r_mul_const.swap1.ok O hO)
  · kanon_arm h (Bool.eq.r_mul_const.swap2.ok O hO)
  · kanon_arm h (Bool.eq.r_mul_const.swap1_swap2.ok O hO)

theorem Bool.eq.r_mul_cancel.sound {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.eq.r_mul_cancel O v1 v2 = some res) : S.Refines (KanonBool.Bool.eq.spec v1 v2) res := by
  unfold Bool.eq.r_mul_cancel at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.eq.r_mul_cancel.main.ok O hO)
  · kanon_arm h (Bool.eq.r_mul_cancel.swap2.ok O hO)
  · kanon_arm h (Bool.eq.r_mul_cancel.swap1.ok O hO)
  · kanon_arm h (Bool.eq.r_mul_cancel.swap1_swap2.ok O hO)

theorem Bool.eq.r_or_zero.sound {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.eq.r_or_zero O v1 v2 = some res) : S.Refines (KanonBool.Bool.eq.spec v1 v2) res := by
  unfold Bool.eq.r_or_zero at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.eq.r_or_zero.main.ok O hO)
  · kanon_arm h (Bool.eq.r_or_zero.swap.ok O hO)

theorem Bool.eq.r_and_mask.sound {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.eq.r_and_mask O v1 v2 = some res) : S.Refines (KanonBool.Bool.eq.spec v1 v2) res := by
  unfold Bool.eq.r_and_mask at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.eq.r_and_mask.main.ok O hO)
  · kanon_arm h (Bool.eq.r_and_mask.swap1.ok O hO)
  · kanon_arm h (Bool.eq.r_and_mask.swap2.ok O hO)
  · kanon_arm h (Bool.eq.r_and_mask.swap1_swap2.ok O hO)

theorem Bool.eq.r_concat_const.sound {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.eq.r_concat_const O v1 v2 = some res) : S.Refines (KanonBool.Bool.eq.spec v1 v2) res := by
  unfold Bool.eq.r_concat_const at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.eq.r_concat_const.main.ok O hO)
  · kanon_arm h (Bool.eq.r_concat_const.swap.ok O hO)

theorem Bool.eq.r_zext_const.sound {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.eq.r_zext_const O v1 v2 = some res) : S.Refines (KanonBool.Bool.eq.spec v1 v2) res := by
  unfold Bool.eq.r_zext_const at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.eq.r_zext_const.main.ok O hO)
  · kanon_arm h (Bool.eq.r_zext_const.swap.ok O hO)

theorem Bool.eq.r_ite_concat.sound {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.eq.r_ite_concat O v1 v2 = some res) : S.Refines (KanonBool.Bool.eq.spec v1 v2) res := by
  unfold Bool.eq.r_ite_concat at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.eq.r_ite_concat.main.ok O hO)
  · kanon_arm h (Bool.eq.r_ite_concat.swap.ok O hO)

theorem Bool.eq.r_concat_concat.sound {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.eq.r_concat_concat O v1 v2 = some res) : S.Refines (KanonBool.Bool.eq.spec v1 v2) res := by
  unfold Bool.eq.r_concat_concat at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.eq.r_concat_concat.main.ok O hO)

theorem Bool.eq.r_ite_const.sound {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.eq.r_ite_const O v1 v2 = some res) : S.Refines (KanonBool.Bool.eq.spec v1 v2) res := by
  unfold Bool.eq.r_ite_const at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.eq.r_ite_const.bitVec.ok O hO)
  · kanon_arm h (Bool.eq.r_ite_const.locLit.ok O hO)
  · kanon_arm h (Bool.eq.r_ite_const.bitVec_swap.ok O hO)
  · kanon_arm h (Bool.eq.r_ite_const.locLit_swap.ok O hO)

theorem Bool.eq.r_of_bools.sound {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.eq.r_of_bools O v1 v2 = some res) : S.Refines (KanonBool.Bool.eq.spec v1 v2) res := by
  unfold Bool.eq.r_of_bools at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.eq.r_of_bools.main.ok O hO)

theorem Bool.eq.r_of_bool_const.sound {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.eq.r_of_bool_const O v1 v2 = some res) : S.Refines (KanonBool.Bool.eq.spec v1 v2) res := by
  unfold Bool.eq.r_of_bool_const at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.eq.r_of_bool_const.main.ok O hO)
  · kanon_arm h (Bool.eq.r_of_bool_const.swap.ok O hO)

theorem Bool.eq.r_msb.sound {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bool.eq.r_msb O v1 v2 = some res) : S.Refines (KanonBool.Bool.eq.spec v1 v2) res := by
  unfold Bool.eq.r_msb at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bool.eq.r_msb.main.ok O hO)

end BitvecMod
