-- Generated by kanon from bool.kn, exists.kn, bitvec.kn, float.kn, ptr.kn, view.kn. Do not edit.
import KanonCore.Tactics
import Kanon.Statements.Bitvec.extract
import Kanon.Lifts
import Kanon.Nodes
import Kanon.Lib.Rule
import Kanon.Soundness.Laws.Op2.And
import Kanon.Soundness.Laws.Op2.Or
import Kanon.Soundness.Laws.Op2.Eq
import Kanon.Soundness.Laws.Op2.Add
import Kanon.Soundness.Laws.Op2.Mul
import Kanon.Soundness.Laws.Op2.BitAnd
import Kanon.Soundness.Laws.Op2.BitOr
import Kanon.Soundness.Laws.Op2.BitXor

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace Kanon

open Classical Kanon

set_option maxHeartbeats 400000 in
theorem Bitvec.extract.r_lit.main.ok : Bitvec.extract.r_lit.main.Stmt := kanon_proof% Bitvec.extract.r_lit.main

theorem Bitvec.extract.r_lit.proof : Bitvec.extract.r_lit.Stmt := by
  intro FS O hO from_ to_ v res h
  simp only [Bitvec.extract.r_lit] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bitvec.extract.r_lit.main.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.extract.r_full.main.ok : Bitvec.extract.r_full.main.Stmt := kanon_proof% Bitvec.extract.r_full.main

theorem Bitvec.extract.r_full.proof : Bitvec.extract.r_full.Stmt := by
  intro FS O hO from_ to_ v res h
  simp only [Bitvec.extract.r_full] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bitvec.extract.r_full.main.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.extract.r_and_.main.ok : Bitvec.extract.r_and_.main.Stmt := kanon_proof% Bitvec.extract.r_and_.main

theorem Bitvec.extract.r_and_.proof : Bitvec.extract.r_and_.Stmt := by
  intro FS O hO from_ to_ v res h
  simp only [Bitvec.extract.r_and_] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bitvec.extract.r_and_.main.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.extract.r_or_.main.ok : Bitvec.extract.r_or_.main.Stmt := kanon_proof% Bitvec.extract.r_or_.main

theorem Bitvec.extract.r_or_.proof : Bitvec.extract.r_or_.Stmt := by
  intro FS O hO from_ to_ v res h
  simp only [Bitvec.extract.r_or_] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bitvec.extract.r_or_.main.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.extract.r_xor.main.ok : Bitvec.extract.r_xor.main.Stmt := kanon_proof% Bitvec.extract.r_xor.main

theorem Bitvec.extract.r_xor.proof : Bitvec.extract.r_xor.Stmt := by
  intro FS O hO from_ to_ v res h
  simp only [Bitvec.extract.r_xor] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bitvec.extract.r_xor.main.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.extract.r_shl.main.ok : Bitvec.extract.r_shl.main.Stmt := kanon_proof% Bitvec.extract.r_shl.main

theorem Bitvec.extract.r_shl.proof : Bitvec.extract.r_shl.Stmt := by
  intro FS O hO from_ to_ v res h
  simp only [Bitvec.extract.r_shl] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bitvec.extract.r_shl.main.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.extract.r_lshr.main.ok : Bitvec.extract.r_lshr.main.Stmt := kanon_proof% Bitvec.extract.r_lshr.main

theorem Bitvec.extract.r_lshr.proof : Bitvec.extract.r_lshr.Stmt := by
  intro FS O hO from_ to_ v res h
  simp only [Bitvec.extract.r_lshr] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bitvec.extract.r_lshr.main.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.extract.r_ite.main.ok : Bitvec.extract.r_ite.main.Stmt := kanon_proof% Bitvec.extract.r_ite.main

theorem Bitvec.extract.r_ite.proof : Bitvec.extract.r_ite.Stmt := by
  intro FS O hO from_ to_ v res h
  simp only [Bitvec.extract.r_ite] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bitvec.extract.r_ite.main.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.extract.r_zext_high.main.ok : Bitvec.extract.r_zext_high.main.Stmt := kanon_proof% Bitvec.extract.r_zext_high.main

theorem Bitvec.extract.r_zext_high.proof : Bitvec.extract.r_zext_high.Stmt := by
  intro FS O hO from_ to_ v res h
  simp only [Bitvec.extract.r_zext_high] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bitvec.extract.r_zext_high.main.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.extract.r_sext_bit.main.ok : Bitvec.extract.r_sext_bit.main.Stmt := kanon_proof% Bitvec.extract.r_sext_bit.main

theorem Bitvec.extract.r_sext_bit.proof : Bitvec.extract.r_sext_bit.Stmt := by
  intro FS O hO from_ to_ v res h
  simp only [Bitvec.extract.r_sext_bit] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bitvec.extract.r_sext_bit.main.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.extract.r_ext_low.main.ok : Bitvec.extract.r_ext_low.main.Stmt := kanon_proof% Bitvec.extract.r_ext_low.main

theorem Bitvec.extract.r_ext_low.proof : Bitvec.extract.r_ext_low.Stmt := by
  intro FS O hO from_ to_ v res h
  simp only [Bitvec.extract.r_ext_low] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bitvec.extract.r_ext_low.main.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.extract.r_ext_orig.main.ok : Bitvec.extract.r_ext_orig.main.Stmt := kanon_proof% Bitvec.extract.r_ext_orig.main

theorem Bitvec.extract.r_ext_orig.proof : Bitvec.extract.r_ext_orig.Stmt := by
  intro FS O hO from_ to_ v res h
  simp only [Bitvec.extract.r_ext_orig] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bitvec.extract.r_ext_orig.main.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.extract.r_extract.main.ok : Bitvec.extract.r_extract.main.Stmt := kanon_proof% Bitvec.extract.r_extract.main

theorem Bitvec.extract.r_extract.proof : Bitvec.extract.r_extract.Stmt := by
  intro FS O hO from_ to_ v res h
  simp only [Bitvec.extract.r_extract] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bitvec.extract.r_extract.main.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.extract.r_concat.main.ok : Bitvec.extract.r_concat.main.Stmt := kanon_proof% Bitvec.extract.r_concat.main

theorem Bitvec.extract.r_concat.proof : Bitvec.extract.r_concat.Stmt := by
  intro FS O hO from_ to_ v res h
  simp only [Bitvec.extract.r_concat] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bitvec.extract.r_concat.main.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.extract.r_add_low.main.ok : Bitvec.extract.r_add_low.main.Stmt := kanon_proof% Bitvec.extract.r_add_low.main

theorem Bitvec.extract.r_add_low.proof : Bitvec.extract.r_add_low.Stmt := by
  intro FS O hO from_ to_ v res h
  simp only [Bitvec.extract.r_add_low] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bitvec.extract.r_add_low.main.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.extract.r_add_const.main.ok : Bitvec.extract.r_add_const.main.Stmt := kanon_proof% Bitvec.extract.r_add_const.main

set_option maxHeartbeats 400000 in
theorem Bitvec.extract.r_add_const.swap.ok : Bitvec.extract.r_add_const.swap.Stmt := by
  intro FS O hO from_ to_ w__1 x n t__4 t__6 hg
  have : Refines FS (Term.mk (Kind.Op2 (Op2.Add w__1) x (Term.mk (Kind.BitVec n) t__4)) t__6)
    (Term.mk (Kind.Op2 (Op2.Add w__1) (Term.mk (Kind.BitVec n) t__4) x) t__6) :=
    Op2.Add.comm.ok FS ..
  refine Refinement.trans ?_
    (Bitvec.extract.r_add_const.main.ok FS O hO from_ to_ w__1 n t__4 x t__6 hg)
  simp only [Bitvec.extract.spec]
  kanon_congr

theorem Bitvec.extract.r_add_const.proof : Bitvec.extract.r_add_const.Stmt := by
  intro FS O hO from_ to_ v res h
  simp only [Bitvec.extract.r_add_const] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bitvec.extract.r_add_const.main.ok FS O hO)
  · kanon_arm h (Bitvec.extract.r_add_const.swap.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.extract.r_mul_pow2.main.ok : Bitvec.extract.r_mul_pow2.main.Stmt := kanon_proof% Bitvec.extract.r_mul_pow2.main

set_option maxHeartbeats 400000 in
theorem Bitvec.extract.r_mul_pow2.swap.ok : Bitvec.extract.r_mul_pow2.swap.Stmt := by
  intro FS O hO from_ to_ w__1 w__5 n t__4 t__6 hg
  have : Refines FS (Term.mk (Kind.Op2 (Op2.Mul w__1) w__5 (Term.mk (Kind.BitVec n) t__4)) t__6)
    (Term.mk (Kind.Op2 (Op2.Mul w__1) (Term.mk (Kind.BitVec n) t__4) w__5) t__6) :=
    Op2.Mul.comm.ok FS ..
  refine Refinement.trans ?_
    (Bitvec.extract.r_mul_pow2.main.ok FS O hO from_ to_ w__1 n t__4 w__5 t__6 hg)
  simp only [Bitvec.extract.spec]
  kanon_congr

theorem Bitvec.extract.r_mul_pow2.proof : Bitvec.extract.r_mul_pow2.Stmt := by
  intro FS O hO from_ to_ v res h
  simp only [Bitvec.extract.r_mul_pow2] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bitvec.extract.r_mul_pow2.main.ok FS O hO)
  · kanon_arm h (Bitvec.extract.r_mul_pow2.swap.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.extract.r_mul_low.main.ok : Bitvec.extract.r_mul_low.main.Stmt := kanon_proof% Bitvec.extract.r_mul_low.main

theorem Bitvec.extract.r_mul_low.proof : Bitvec.extract.r_mul_low.Stmt := by
  intro FS O hO from_ to_ v res h
  simp only [Bitvec.extract.r_mul_low] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bitvec.extract.r_mul_low.main.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.extract.r_urem.main.ok : Bitvec.extract.r_urem.main.Stmt := kanon_proof% Bitvec.extract.r_urem.main

theorem Bitvec.extract.r_urem.proof : Bitvec.extract.r_urem.Stmt := by
  intro FS O hO from_ to_ v res h
  simp only [Bitvec.extract.r_urem] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bitvec.extract.r_urem.main.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.extract.r_default.main.ok : Bitvec.extract.r_default.main.Stmt := kanon_proof% Bitvec.extract.r_default.main

theorem Bitvec.extract.r_default.proof : Bitvec.extract.r_default.Stmt := by
  intro FS O hO from_ to_ v res h
  simp only [Bitvec.extract.r_default] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bitvec.extract.r_default.main.ok FS O hO)

theorem Bitvec.extract.step_sound (FS : FloatSem) (O : Ops) (hO : O.Sound FS) (from_ : Int) (to_ : Int) (v : Term) :
  Refines FS (Bitvec.extract.spec from_ to_ v) (Bitvec.extract.step O from_ to_ v) := by
  unfold Bitvec.extract.step
  refine Refinement.firstSome_cons (fun res h => Bitvec.extract.r_lit.proof FS O hO from_ to_ v res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bitvec.extract.r_full.proof FS O hO from_ to_ v res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bitvec.extract.r_and_.proof FS O hO from_ to_ v res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bitvec.extract.r_or_.proof FS O hO from_ to_ v res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bitvec.extract.r_xor.proof FS O hO from_ to_ v res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bitvec.extract.r_shl.proof FS O hO from_ to_ v res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bitvec.extract.r_lshr.proof FS O hO from_ to_ v res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bitvec.extract.r_ite.proof FS O hO from_ to_ v res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bitvec.extract.r_zext_high.proof FS O hO from_ to_ v res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bitvec.extract.r_sext_bit.proof FS O hO from_ to_ v res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bitvec.extract.r_ext_low.proof FS O hO from_ to_ v res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bitvec.extract.r_ext_orig.proof FS O hO from_ to_ v res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bitvec.extract.r_extract.proof FS O hO from_ to_ v res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bitvec.extract.r_concat.proof FS O hO from_ to_ v res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bitvec.extract.r_add_low.proof FS O hO from_ to_ v res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bitvec.extract.r_add_const.proof FS O hO from_ to_ v res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bitvec.extract.r_mul_pow2.proof FS O hO from_ to_ v res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bitvec.extract.r_mul_low.proof FS O hO from_ to_ v res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bitvec.extract.r_urem.proof FS O hO from_ to_ v res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bitvec.extract.r_default.proof FS O hO from_ to_ v res h) ?_
  exact Refinement.firstSome_nil

end Kanon
