-- Generated by kanon from bool.kn, exists.kn, bitvec.kn, float.kn, ptr.kn, view.kn. Do not edit.
import KanonCore.Tactics
import Kanon.Statements.Bitvec.mul
import Kanon.Instance.Bitvec
import Kanon.Lang.Bitvec
import Kanon.Lang.Bool
import Kanon.Lang.Core
import BitvecMod.Soundness.Bitvec.mul

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace Kanon

open Classical Kanon

set_option maxHeartbeats 400000 in
theorem Bitvec.mul.r_lits.main.ok : Bitvec.mul.r_lits.main.Stmt :=
  fun FS O hO => BitvecMod.Bitvec.mul.r_lits.main.ok (S := (sem FS)) (bitvecSyntax FS)
  (Ops.toBitvec FS O) (Ops.Sound.toBitvec hO)

theorem Bitvec.mul.r_lits.proof : Bitvec.mul.r_lits.Stmt := by
  intro FS O hO checked v1 v2 res h
  simp only [Bitvec.mul.r_lits] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bitvec.mul.r_lits.main.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.mul.r_one.main.ok : Bitvec.mul.r_one.main.Stmt :=
  fun FS O hO => BitvecMod.Bitvec.mul.r_one.main.ok (S := (sem FS)) (bitvecSyntax FS)
  (Ops.toBitvec FS O) (Ops.Sound.toBitvec hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.mul.r_one.swap.ok : Bitvec.mul.r_one.swap.Stmt :=
  fun FS O hO => BitvecMod.Bitvec.mul.r_one.swap.ok (S := (sem FS)) (bitvecSyntax FS)
  (Ops.toBitvec FS O) (Ops.Sound.toBitvec hO)

theorem Bitvec.mul.r_one.proof : Bitvec.mul.r_one.Stmt := by
  intro FS O hO checked v1 v2 res h
  simp only [Bitvec.mul.r_one] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bitvec.mul.r_one.main.ok FS O hO)
  · kanon_arm h (Bitvec.mul.r_one.swap.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.mul.r_zero.main.ok : Bitvec.mul.r_zero.main.Stmt :=
  fun FS O hO => BitvecMod.Bitvec.mul.r_zero.main.ok (S := (sem FS)) (bitvecSyntax FS)
  (Ops.toBitvec FS O) (Ops.Sound.toBitvec hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.mul.r_zero.swap.ok : Bitvec.mul.r_zero.swap.Stmt :=
  fun FS O hO => BitvecMod.Bitvec.mul.r_zero.swap.ok (S := (sem FS)) (bitvecSyntax FS)
  (Ops.toBitvec FS O) (Ops.Sound.toBitvec hO)

theorem Bitvec.mul.r_zero.proof : Bitvec.mul.r_zero.Stmt := by
  intro FS O hO checked v1 v2 res h
  simp only [Bitvec.mul.r_zero] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bitvec.mul.r_zero.main.ok FS O hO)
  · kanon_arm h (Bitvec.mul.r_zero.swap.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.mul.r_neg.main.ok : Bitvec.mul.r_neg.main.Stmt :=
  fun FS O hO => BitvecMod.Bitvec.mul.r_neg.main.ok (S := (sem FS)) (bitvecSyntax FS)
  (Ops.toBitvec FS O) (Ops.Sound.toBitvec hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.mul.r_neg.swap.ok : Bitvec.mul.r_neg.swap.Stmt :=
  fun FS O hO => BitvecMod.Bitvec.mul.r_neg.swap.ok (S := (sem FS)) (bitvecSyntax FS)
  (Ops.toBitvec FS O) (Ops.Sound.toBitvec hO)

theorem Bitvec.mul.r_neg.proof : Bitvec.mul.r_neg.Stmt := by
  intro FS O hO checked v1 v2 res h
  simp only [Bitvec.mul.r_neg] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bitvec.mul.r_neg.main.ok FS O hO)
  · kanon_arm h (Bitvec.mul.r_neg.swap.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.mul.r_mul_const.main.ok : Bitvec.mul.r_mul_const.main.Stmt :=
  fun FS O hO => BitvecMod.Bitvec.mul.r_mul_const.main.ok (S := (sem FS)) (bitvecSyntax FS)
  (Ops.toBitvec FS O) (Ops.Sound.toBitvec hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.mul.r_mul_const.swap1.ok : Bitvec.mul.r_mul_const.swap1.Stmt :=
  fun FS O hO => BitvecMod.Bitvec.mul.r_mul_const.swap1.ok (S := (sem FS)) (bitvecSyntax FS)
  (Ops.toBitvec FS O) (Ops.Sound.toBitvec hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.mul.r_mul_const.swap2.ok : Bitvec.mul.r_mul_const.swap2.Stmt :=
  fun FS O hO => BitvecMod.Bitvec.mul.r_mul_const.swap2.ok (S := (sem FS)) (bitvecSyntax FS)
  (Ops.toBitvec FS O) (Ops.Sound.toBitvec hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.mul.r_mul_const.swap1_swap2.ok : Bitvec.mul.r_mul_const.swap1_swap2.Stmt :=
  fun FS O hO => BitvecMod.Bitvec.mul.r_mul_const.swap1_swap2.ok (S := (sem FS)) (bitvecSyntax FS)
  (Ops.toBitvec FS O) (Ops.Sound.toBitvec hO)

theorem Bitvec.mul.r_mul_const.proof : Bitvec.mul.r_mul_const.Stmt := by
  intro FS O hO checked v1 v2 res h
  simp only [Bitvec.mul.r_mul_const] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bitvec.mul.r_mul_const.main.ok FS O hO)
  · kanon_arm h (Bitvec.mul.r_mul_const.swap1.ok FS O hO)
  · kanon_arm h (Bitvec.mul.r_mul_const.swap2.ok FS O hO)
  · kanon_arm h (Bitvec.mul.r_mul_const.swap1_swap2.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.mul.r_ite.main.ok : Bitvec.mul.r_ite.main.Stmt :=
  fun FS O hO => BitvecMod.Bitvec.mul.r_ite.main.ok (S := (sem FS)) (bitvecSyntax FS)
  (Ops.toBitvec FS O) (Ops.Sound.toBitvec hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.mul.r_ite.swap.ok : Bitvec.mul.r_ite.swap.Stmt :=
  fun FS O hO => BitvecMod.Bitvec.mul.r_ite.swap.ok (S := (sem FS)) (bitvecSyntax FS)
  (Ops.toBitvec FS O) (Ops.Sound.toBitvec hO)

theorem Bitvec.mul.r_ite.proof : Bitvec.mul.r_ite.Stmt := by
  intro FS O hO checked v1 v2 res h
  simp only [Bitvec.mul.r_ite] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bitvec.mul.r_ite.main.ok FS O hO)
  · kanon_arm h (Bitvec.mul.r_ite.swap.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.mul.r_default.main.ok : Bitvec.mul.r_default.main.Stmt :=
  fun FS O hO => BitvecMod.Bitvec.mul.r_default.main.ok (S := (sem FS)) (bitvecSyntax FS)
  (Ops.toBitvec FS O) (Ops.Sound.toBitvec hO)

theorem Bitvec.mul.r_default.proof : Bitvec.mul.r_default.Stmt := by
  intro FS O hO checked v1 v2 res h
  simp only [Bitvec.mul.r_default] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bitvec.mul.r_default.main.ok FS O hO)

theorem Bitvec.mul.step_sound (FS : FloatSem) (O : Ops) (hO : O.Sound FS) (checked : CoreMod.Checked) (v1 : Term) (v2 : Term) :
  Refines FS (Bitvec.mul.spec checked v1 v2) (Bitvec.mul.step O checked v1 v2) := by
  unfold Bitvec.mul.step
  refine Refinement.firstSome_cons (fun res h => Bitvec.mul.r_lits.proof FS O hO checked v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bitvec.mul.r_one.proof FS O hO checked v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bitvec.mul.r_zero.proof FS O hO checked v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bitvec.mul.r_neg.proof FS O hO checked v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bitvec.mul.r_mul_const.proof FS O hO checked v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bitvec.mul.r_ite.proof FS O hO checked v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bitvec.mul.r_default.proof FS O hO checked v1 v2 res h) ?_
  exact Refinement.firstSome_nil

end Kanon
