-- Generated by kanon from bool.kn, exists.kn, bitvec.kn, float.kn, ptr.kn, view.kn. Do not edit.
import KanonCore.Tactics
import Kanon.Statements.Bitvec.mul_overflows
import Kanon.Lifts
import Kanon.Nodes
import Kanon.Lib.Rule
import Kanon.Soundness.Laws.Op2.And
import Kanon.Soundness.Laws.Op2.Or
import Kanon.Soundness.Laws.Op2.Eq
import Kanon.Soundness.Laws.Op2.Add
import Kanon.Soundness.Laws.Op2.Mul
import Kanon.Soundness.Laws.Op2.MulOvf
import Kanon.Soundness.Laws.Op2.BitAnd
import Kanon.Soundness.Laws.Op2.BitOr
import Kanon.Soundness.Laws.Op2.BitXor

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace Kanon

open Classical Kanon

set_option maxHeartbeats 400000 in
theorem Bitvec.mul_overflows.r_lits.main.ok : Bitvec.mul_overflows.r_lits.main.Stmt := kanon_proof% Bitvec.mul_overflows.r_lits.main

theorem Bitvec.mul_overflows.r_lits.proof : Bitvec.mul_overflows.r_lits.Stmt := by
  intro FS O hO signed v1 v2 res h
  simp only [Bitvec.mul_overflows.r_lits] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bitvec.mul_overflows.r_lits.main.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.mul_overflows.r_size1.main.ok : Bitvec.mul_overflows.r_size1.main.Stmt := kanon_proof% Bitvec.mul_overflows.r_size1.main

theorem Bitvec.mul_overflows.r_size1.proof : Bitvec.mul_overflows.r_size1.Stmt := by
  intro FS O hO signed v1 v2 res h
  simp only [Bitvec.mul_overflows.r_size1] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bitvec.mul_overflows.r_size1.main.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.mul_overflows.r_msb.main.ok : Bitvec.mul_overflows.r_msb.main.Stmt := kanon_proof% Bitvec.mul_overflows.r_msb.main

theorem Bitvec.mul_overflows.r_msb.proof : Bitvec.mul_overflows.r_msb.Stmt := by
  intro FS O hO signed v1 v2 res h
  simp only [Bitvec.mul_overflows.r_msb] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bitvec.mul_overflows.r_msb.main.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.mul_overflows.r_const.main.ok : Bitvec.mul_overflows.r_const.main.Stmt := kanon_proof% Bitvec.mul_overflows.r_const.main

set_option maxHeartbeats 400000 in
theorem Bitvec.mul_overflows.r_const.swap.ok : Bitvec.mul_overflows.r_const.swap.Stmt := by
  intro FS O hO signed v1 z t__2 hg
  refine Refinement.trans ?_
    (Bitvec.mul_overflows.r_const.main.ok FS O hO signed v1 z t__2 hg)
  simp only [Bitvec.mul_overflows.spec]
  refine Refinement.trans (Op2.MulOvf.comm.ok FS ..) ?_
  kanon_congr

theorem Bitvec.mul_overflows.r_const.proof : Bitvec.mul_overflows.r_const.Stmt := by
  intro FS O hO signed v1 v2 res h
  simp only [Bitvec.mul_overflows.r_const] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bitvec.mul_overflows.r_const.main.ok FS O hO)
  · kanon_arm h (Bitvec.mul_overflows.r_const.swap.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.mul_overflows.r_div.main.ok : Bitvec.mul_overflows.r_div.main.Stmt := kanon_proof% Bitvec.mul_overflows.r_div.main

set_option maxHeartbeats 400000 in
theorem Bitvec.mul_overflows.r_div.swap.ok : Bitvec.mul_overflows.r_div.swap.Stmt := by
  intro FS O hO signed v2 w__4 kanon__5 t__6 hg
  refine Refinement.trans ?_
    (Bitvec.mul_overflows.r_div.main.ok FS O hO signed v2 w__4 kanon__5 t__6 hg)
  simp only [Bitvec.mul_overflows.spec]
  refine Refinement.trans (Op2.MulOvf.comm.ok FS ..) ?_
  kanon_congr

theorem Bitvec.mul_overflows.r_div.proof : Bitvec.mul_overflows.r_div.Stmt := by
  intro FS O hO signed v1 v2 res h
  simp only [Bitvec.mul_overflows.r_div] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bitvec.mul_overflows.r_div.main.ok FS O hO)
  · kanon_arm h (Bitvec.mul_overflows.r_div.swap.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.mul_overflows.r_default.main.ok : Bitvec.mul_overflows.r_default.main.Stmt := kanon_proof% Bitvec.mul_overflows.r_default.main

theorem Bitvec.mul_overflows.r_default.proof : Bitvec.mul_overflows.r_default.Stmt := by
  intro FS O hO signed v1 v2 res h
  simp only [Bitvec.mul_overflows.r_default] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bitvec.mul_overflows.r_default.main.ok FS O hO)

theorem Bitvec.mul_overflows.step_sound (FS : FloatSem) (O : Ops) (hO : O.Sound FS) (signed : Bool) (v1 : Term) (v2 : Term) :
  Refines FS (Bitvec.mul_overflows.spec signed v1 v2) (Bitvec.mul_overflows.step O signed v1 v2) := by
  unfold Bitvec.mul_overflows.step
  refine Refinement.firstSome_cons (fun res h => Bitvec.mul_overflows.r_lits.proof FS O hO signed v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bitvec.mul_overflows.r_size1.proof FS O hO signed v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bitvec.mul_overflows.r_msb.proof FS O hO signed v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bitvec.mul_overflows.r_const.proof FS O hO signed v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bitvec.mul_overflows.r_div.proof FS O hO signed v1 v2 res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bitvec.mul_overflows.r_default.proof FS O hO signed v1 v2 res h) ?_
  exact Refinement.firstSome_nil

end Kanon
