-- Generated by kanon from bool.kn, exists.kn, bitvec.kn, float.kn, ptr.kn, view.kn. Do not edit.
import KanonCore.Tactics
import Kanon.Statements.Bitvec.neg
import Kanon.Instance.Bitvec
import Kanon.Lang.Bitvec
import Kanon.Lang.Bool
import Kanon.Lang.Core
import BitvecMod.Soundness.Bitvec.neg

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace Kanon

open Classical Kanon

set_option maxHeartbeats 400000 in
theorem Bitvec.neg.r_lit.main.ok : Bitvec.neg.r_lit.main.Stmt :=
  fun FS O hO => BitvecMod.Bitvec.neg.r_lit.main.ok (S := (sem FS)) (bitvecSyntax FS)
  (Ops.toBitvec FS O) (Ops.Sound.toBitvec hO)

theorem Bitvec.neg.r_lit.proof : Bitvec.neg.r_lit.Stmt := by
  intro FS O hO checked v res h
  simp only [Bitvec.neg.r_lit] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bitvec.neg.r_lit.main.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.neg.r_neg.main.ok : Bitvec.neg.r_neg.main.Stmt :=
  fun FS O hO => BitvecMod.Bitvec.neg.r_neg.main.ok (S := (sem FS)) (bitvecSyntax FS)
  (Ops.toBitvec FS O) (Ops.Sound.toBitvec hO)

theorem Bitvec.neg.r_neg.proof : Bitvec.neg.r_neg.Stmt := by
  intro FS O hO checked v res h
  simp only [Bitvec.neg.r_neg] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bitvec.neg.r_neg.main.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.neg.r_ite.main.ok : Bitvec.neg.r_ite.main.Stmt :=
  fun FS O hO => BitvecMod.Bitvec.neg.r_ite.main.ok (S := (sem FS)) (bitvecSyntax FS)
  (Ops.toBitvec FS O) (Ops.Sound.toBitvec hO)

theorem Bitvec.neg.r_ite.proof : Bitvec.neg.r_ite.Stmt := by
  intro FS O hO checked v res h
  simp only [Bitvec.neg.r_ite] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bitvec.neg.r_ite.main.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.neg.r_of_bool.main.ok : Bitvec.neg.r_of_bool.main.Stmt :=
  fun FS O hO => BitvecMod.Bitvec.neg.r_of_bool.main.ok (S := (sem FS)) (bitvecSyntax FS)
  (Ops.toBitvec FS O) (Ops.Sound.toBitvec hO)

theorem Bitvec.neg.r_of_bool.proof : Bitvec.neg.r_of_bool.Stmt := by
  intro FS O hO checked v res h
  simp only [Bitvec.neg.r_of_bool] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bitvec.neg.r_of_bool.main.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.neg.r_default.main.ok : Bitvec.neg.r_default.main.Stmt :=
  fun FS O hO => BitvecMod.Bitvec.neg.r_default.main.ok (S := (sem FS)) (bitvecSyntax FS)
  (Ops.toBitvec FS O) (Ops.Sound.toBitvec hO)

theorem Bitvec.neg.r_default.proof : Bitvec.neg.r_default.Stmt := by
  intro FS O hO checked v res h
  simp only [Bitvec.neg.r_default] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bitvec.neg.r_default.main.ok FS O hO)

theorem Bitvec.neg.step_sound (FS : FloatSem) (O : Ops) (hO : O.Sound FS) (checked : Bool) (v : Term) :
  Refines FS (Bitvec.neg.spec checked v) (Bitvec.neg.step O checked v) := by
  unfold Bitvec.neg.step
  refine Refinement.firstSome_cons (fun res h => Bitvec.neg.r_lit.proof FS O hO checked v res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bitvec.neg.r_neg.proof FS O hO checked v res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bitvec.neg.r_ite.proof FS O hO checked v res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bitvec.neg.r_of_bool.proof FS O hO checked v res h) ?_
  refine Refinement.firstSome_cons (fun res h => Bitvec.neg.r_default.proof FS O hO checked v res h) ?_
  exact Refinement.firstSome_nil

end Kanon
