-- Generated by kanon from bool.kn, exists.kn, bitvec.kn, float.kn, ptr.kn, view.kn. Do not edit.
import Kanon.Statements.Bitvec.rem
import Kanon.Soundness.Laws

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace Kanon

open Classical Kanon

set_option maxHeartbeats 400000 in
theorem Bitvec.rem.r_lits.main.ok : Bitvec.rem.r_lits.main.Stmt := kanon_proof% Bitvec.rem.r_lits.main

theorem Bitvec.rem.r_lits.proof : Bitvec.rem.r_lits.Stmt := by
  intro FS O hO signed v1 v2 res hs_v2 h
  simp only [Bitvec.rem.r_lits] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bitvec.rem.r_lits.main.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.rem.r_zero_r.main.ok : Bitvec.rem.r_zero_r.main.Stmt := kanon_proof% Bitvec.rem.r_zero_r.main

theorem Bitvec.rem.r_zero_r.proof : Bitvec.rem.r_zero_r.Stmt := by
  intro FS O hO signed v1 v2 res hs_v2 h
  simp only [Bitvec.rem.r_zero_r] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bitvec.rem.r_zero_r.main.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.rem.r_zero_l.main.ok : Bitvec.rem.r_zero_l.main.Stmt := kanon_proof% Bitvec.rem.r_zero_l.main

theorem Bitvec.rem.r_zero_l.proof : Bitvec.rem.r_zero_l.Stmt := by
  intro FS O hO signed v1 v2 res hs_v2 h
  simp only [Bitvec.rem.r_zero_l] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bitvec.rem.r_zero_l.main.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.rem.r_one_r.main.ok : Bitvec.rem.r_one_r.main.Stmt := kanon_proof% Bitvec.rem.r_one_r.main

theorem Bitvec.rem.r_one_r.proof : Bitvec.rem.r_one_r.Stmt := by
  intro FS O hO signed v1 v2 res hs_v2 h
  simp only [Bitvec.rem.r_one_r] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bitvec.rem.r_one_r.main.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.rem.r_pow2.main.ok : Bitvec.rem.r_pow2.main.Stmt := kanon_proof% Bitvec.rem.r_pow2.main

theorem Bitvec.rem.r_pow2.proof : Bitvec.rem.r_pow2.Stmt := by
  intro FS O hO signed v1 v2 res hs_v2 h
  simp only [Bitvec.rem.r_pow2] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bitvec.rem.r_pow2.main.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.rem.r_add.main.ok : Bitvec.rem.r_add.main.Stmt := kanon_proof% Bitvec.rem.r_add.main

set_option maxHeartbeats 400000 in
theorem Bitvec.rem.r_add.swap.ok : Bitvec.rem.r_add.swap.Stmt := kanon_proof% Bitvec.rem.r_add.swap

theorem Bitvec.rem.r_add.proof : Bitvec.rem.r_add.Stmt := by
  intro FS O hO signed v1 v2 res hs_v2 h
  simp only [Bitvec.rem.r_add] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bitvec.rem.r_add.main.ok FS O hO)
  · kanon_arm h (Bitvec.rem.r_add.swap.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.rem.r_rem_rem.main.ok : Bitvec.rem.r_rem_rem.main.Stmt := kanon_proof% Bitvec.rem.r_rem_rem.main

theorem Bitvec.rem.r_rem_rem.proof : Bitvec.rem.r_rem_rem.Stmt := by
  intro FS O hO signed v1 v2 res hs_v2 h
  simp only [Bitvec.rem.r_rem_rem] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bitvec.rem.r_rem_rem.main.ok FS O hO)

set_option maxHeartbeats 400000 in
theorem Bitvec.rem.r_default.main.ok : Bitvec.rem.r_default.main.Stmt := kanon_proof% Bitvec.rem.r_default.main

theorem Bitvec.rem.r_default.proof : Bitvec.rem.r_default.Stmt := by
  intro FS O hO signed v1 v2 res hs_v2 h
  simp only [Bitvec.rem.r_default] at h
  repeat' rcases orElse_some h with h | h
  · kanon_arm h (Bitvec.rem.r_default.main.ok FS O hO)

theorem Bitvec.rem.step_sound (FS : FloatSem) (O : Ops) (hO : O.Sound FS) (signed : Bool) (v1 : Term) (v2 : Term) (hs_v2 : Nonzero v2) :
  Refines FS (Bitvec.rem.spec signed v1 v2) (Bitvec.rem.step O signed v1 v2) := by
  unfold Bitvec.rem.step
  refine Refinement.firstSome_cons (fun res h => Bitvec.rem.r_lits.proof FS O hO signed v1 v2 res hs_v2 h) ?_
  refine Refinement.firstSome_cons (fun res h => Bitvec.rem.r_zero_r.proof FS O hO signed v1 v2 res hs_v2 h) ?_
  refine Refinement.firstSome_cons (fun res h => Bitvec.rem.r_zero_l.proof FS O hO signed v1 v2 res hs_v2 h) ?_
  refine Refinement.firstSome_cons (fun res h => Bitvec.rem.r_one_r.proof FS O hO signed v1 v2 res hs_v2 h) ?_
  refine Refinement.firstSome_cons (fun res h => Bitvec.rem.r_pow2.proof FS O hO signed v1 v2 res hs_v2 h) ?_
  refine Refinement.firstSome_cons (fun res h => Bitvec.rem.r_add.proof FS O hO signed v1 v2 res hs_v2 h) ?_
  refine Refinement.firstSome_cons (fun res h => Bitvec.rem.r_rem_rem.proof FS O hO signed v1 v2 res hs_v2 h) ?_
  refine Refinement.firstSome_cons (fun res h => Bitvec.rem.r_default.proof FS O hO signed v1 v2 res hs_v2 h) ?_
  exact Refinement.firstSome_nil

end Kanon
