-- Generated by kanon from bool.kn, exists.kn, bitvec.kn, float.kn, ptr.kn, view.kn. Do not edit.
import Kanon.Statements
import Kanon.Lang.Bitvec
import Kanon.Lang.Bool
import Kanon.Lang.Core
import BitvecMod.Soundness.Laws

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace Kanon

open Classical Kanon

@[kanon_comm_lemma] theorem Op2.Mul.comm.ok : Op2.Mul.comm.Stmt :=
  fun FS x1 a b t => BitvecMod.Mul.comm.ok (S := (sem FS)) (bitvecSyntax FS) x1 a b t

end Kanon
