-- Generated by kanon from bool.kn, exists.kn, bitvec.kn, float.kn, ptr.kn, view.kn. Do not edit.
import Kanon.Ops
import Kanon.Model.Bitvec.is_bv
import Kanon.Model.Bitvec.size

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace Kanon

open Classical Kanon

def Bool.ite.r_true_ (O : Ops) (guard : Term) (if_ : Term) (else_ : Term) : Option Term :=
  (match guard, if_, else_ with
    | (Term.mk (Kind.Bool true) _), _, _ =>
    (whenSome true (if_))
    | _, _, _ => none)

def Bool.ite.r_false_ (O : Ops) (guard : Term) (if_ : Term) (else_ : Term) : Option Term :=
  (match guard, if_, else_ with
    | (Term.mk (Kind.Bool false) _), _, _ =>
    (whenSome true (else_))
    | _, _, _ => none)

def Bool.ite.r_bool (O : Ops) (guard : Term) (if_ : Term) (else_ : Term) : Option Term :=
  (match guard, if_, else_ with
    | _, (Term.mk (Kind.Bool true) _), (Term.mk (Kind.Bool false) _) =>
    (whenSome true (guard))
    | _, _, _ => none)

def Bool.ite.r_not_bool (O : Ops) (guard : Term) (if_ : Term) (else_ : Term) : Option Term :=
  (match guard, if_, else_ with
    | _, (Term.mk (Kind.Bool false) _), (Term.mk (Kind.Bool true) _) =>
    (whenSome true ((O.bool_not_ guard)))
    | _, _, _ => none)

def Bool.ite.r_false_then (O : Ops) (guard : Term) (if_ : Term) (else_ : Term) : Option Term :=
  (match guard, if_, else_ with
    | _, (Term.mk (Kind.Bool false) _), _ =>
    (whenSome true ((O.bool_and_ (O.bool_not_ guard) else_)))
    | _, _, _ => none)

def Bool.ite.r_true_then (O : Ops) (guard : Term) (if_ : Term) (else_ : Term) : Option Term :=
  (match guard, if_, else_ with
    | _, (Term.mk (Kind.Bool true) _), _ =>
    (whenSome true ((O.bool_or_ guard else_)))
    | _, _, _ => none)

def Bool.ite.r_false_else (O : Ops) (guard : Term) (if_ : Term) (else_ : Term) : Option Term :=
  (match guard, if_, else_ with
    | _, _, (Term.mk (Kind.Bool false) _) =>
    (whenSome true ((O.bool_and_ guard if_)))
    | _, _, _ => none)

def Bool.ite.r_true_else (O : Ops) (guard : Term) (if_ : Term) (else_ : Term) : Option Term :=
  (match guard, if_, else_ with
    | _, _, (Term.mk (Kind.Bool true) _) =>
    (whenSome true ((O.bool_or_ (O.bool_not_ guard) if_)))
    | _, _, _ => none)

def Bool.ite.r_not_guard (O : Ops) (guard : Term) (if_ : Term) (else_ : Term) : Option Term :=
  (match guard, if_, else_ with
    | (Term.mk (Kind.Op1 Op1.Not g) _), _, _ =>
    (whenSome true ((O.bool_ite g else_ if_)))
    | _, _, _ => none)

def Bool.ite.r_guard_then (O : Ops) (guard : Term) (if_ : Term) (else_ : Term) : Option Term :=
  (match guard, if_, else_ with
    | g, kanon__2, _ =>
    (whenSome (decide (g = kanon__2)) ((O.bool_or_ guard else_))))

def Bool.ite.r_guard_else (O : Ops) (guard : Term) (if_ : Term) (else_ : Term) : Option Term :=
  (match guard, if_, else_ with
    | g, _, kanon__3 =>
    (whenSome (decide (g = kanon__3)) ((O.bool_and_ guard if_))))

def Bool.ite.r_ite_then (O : Ops) (guard : Term) (if_ : Term) (else_ : Term) : Option Term :=
  (match guard, if_, else_ with
    | g, (Term.mk (Kind.Op3 Op3.Ite kanon__3 x _) _), _ =>
    (whenSome (decide (g = kanon__3)) ((O.bool_ite guard x else_)))
    | _, _, _ => none)

def Bool.ite.r_ite_else (O : Ops) (guard : Term) (if_ : Term) (else_ : Term) : Option Term :=
  (match guard, if_, else_ with
    | g, _, (Term.mk (Kind.Op3 Op3.Ite kanon__4 _ y) _) =>
    (whenSome (decide (g = kanon__4)) ((O.bool_ite guard if_ y)))
    | _, _, _ => none)

def Bool.ite.r_and_ite_then (O : Ops) (guard : Term) (if_ : Term) (else_ : Term) : Option Term :=
  (match guard, if_, else_ with
    | (Term.mk (Kind.Op2 Op2.And g _) _), (Term.mk (Kind.Op3 Op3.Ite kanon__7 x _) _), _ =>
    (whenSome (decide (g = kanon__7)) ((O.bool_ite guard x else_)))
    | _, _, _ => none)
  <|> (match guard, if_, else_ with
        | (Term.mk (Kind.Op2 Op2.And _ g) _), (Term.mk (Kind.Op3 Op3.Ite kanon__7 x _) _), _ =>
        (whenSome (decide (g = kanon__7)) ((O.bool_ite guard x else_)))
        | _, _, _ => none)

def Bool.ite.r_or_ite_else (O : Ops) (guard : Term) (if_ : Term) (else_ : Term) : Option Term :=
  (match guard, if_, else_ with
    | (Term.mk (Kind.Op2 Op2.Or g _) _), _, (Term.mk (Kind.Op3 Op3.Ite kanon__8 _ y) _) =>
    (whenSome (decide (g = kanon__8)) ((O.bool_ite guard if_ y)))
    | _, _, _ => none)
  <|> (match guard, if_, else_ with
        | (Term.mk (Kind.Op2 Op2.Or _ g) _), _, (Term.mk (Kind.Op3 Op3.Ite kanon__8 _ y) _) =>
        (whenSome (decide (g = kanon__8)) ((O.bool_ite guard if_ y)))
        | _, _, _ => none)

def Bool.ite.r_same (O : Ops) (guard : Term) (if_ : Term) (else_ : Term) : Option Term :=
  (match guard, if_, else_ with
    | _, x, kanon__3 =>
    (whenSome (decide (x = kanon__3)) (if_)))

def Bool.ite.r_bv_of_bool (O : Ops) (guard : Term) (if_ : Term) (else_ : Term) : Option Term :=
  (match guard, if_, else_ with
    | _, (Term.mk (Kind.BitVec kanon__2) _), (Term.mk (Kind.BitVec kanon__4) _) =>
    (whenSome (((decide (kanon__2 = (1 : Int))) && (decide (kanon__4 = (0 : Int)))) && (Bitvec.is_bv (ty if_)))
    ((O.bitvec_of_bool (Bitvec.size if_) guard)))
    | _, _, _ => none)

def Bool.ite.r_default (O : Ops) (guard : Term) (if_ : Term) (else_ : Term) : Option Term :=
  (match guard, if_, else_ with
    | _, _, _ =>
    (whenSome true ((Term.mk (Kind.Op3 Op3.Ite guard if_ else_) (ty if_)))))

def Bool.ite.step (O : Ops) (guard : Term) (if_ : Term) (else_ : Term) : Term :=
  (firstSome [Bool.ite.r_true_ O guard if_ else_, Bool.ite.r_false_ O guard if_ else_, Bool.ite.r_bool O guard if_ else_, Bool.ite.r_not_bool O guard if_ else_, Bool.ite.r_false_then O guard if_ else_, Bool.ite.r_true_then O guard if_ else_, Bool.ite.r_false_else O guard if_ else_, Bool.ite.r_true_else O guard if_ else_, Bool.ite.r_not_guard O guard if_ else_, Bool.ite.r_guard_then O guard if_ else_, Bool.ite.r_guard_else O guard if_ else_, Bool.ite.r_ite_then O guard if_ else_, Bool.ite.r_ite_else O guard if_ else_, Bool.ite.r_and_ite_then O guard if_ else_, Bool.ite.r_or_ite_else O guard if_ else_, Bool.ite.r_same O guard if_ else_, Bool.ite.r_bv_of_bool O guard if_ else_, Bool.ite.r_default O guard if_ else_]).getD (Bool.ite.spec guard if_ else_)

end Kanon
