-- Generated by kanon from float.knl, float.kn. Do not edit.
import FloatMod.Lift
import FloatMod.Soundness.Comm
import FloatMod.Soundness.Bool.sure_neq
import FloatMod.Soundness.Bool.eq
import FloatMod.Soundness.Float.is_floatclass
import FloatMod.Soundness.Float.is_negative
import FloatMod.Soundness.Float.is_positive
import FloatMod.Soundness.Float.cast
import FloatMod.Soundness.Float.eq
import FloatMod.Soundness.Float.lt
import FloatMod.Soundness.Float.leq
import FloatMod.Soundness.Float.add
import FloatMod.Soundness.Float.sub
import FloatMod.Soundness.Float.div
import FloatMod.Soundness.Float.mul
import FloatMod.Soundness.Float.rem
import FloatMod.Soundness.Float.abs
import FloatMod.Soundness.Float.neg
import FloatMod.Soundness.Float.fma
import FloatMod.Soundness.Float.fmod_of_rem
import FloatMod.Soundness.Float.fmod
import FloatMod.Soundness.Float.min
import FloatMod.Soundness.Float.max
import FloatMod.Soundness.Float.sqrt
import FloatMod.Soundness.Float.round
import FloatMod.Soundness.Float.of_float
import FloatMod.Soundness.Float.to_float
import FloatMod.Soundness.Float.to_float_bits

set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false
set_option maxHeartbeats 1000000

noncomputable section

namespace FloatMod

open Classical Kanon

end FloatMod
