-- Generated by kanon from float.knl, float.kn. Do not edit.
import FloatMod.Ops

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace FloatMod

open Classical Kanon

/-- The operands of `FEq` commute. -/
def FEq.comm.Stmt : Prop :=
  ∀ {S : Kanon.Sem} [DecidableEq S.Term] [DecidableEq S.Ty] {B : Kanon.Base S} {LBool : KanonBool.Syntax B} {LCore : CoreMod.Syntax B} {LBitvec : BitvecMod.Syntax B LBool LCore} (L : FloatMod.Syntax B LBool LCore LBitvec) [KanonBool.Sem LBool] [CoreMod.Sem LCore] [BitvecMod.Sem LBitvec] [Sem L] (a b : S.Term) (t : S.Ty),
  S.Refines (B.node (L.FEqK a b) t)
  (B.node (L.FEqK b a) t)

end FloatMod
