-- Generated by kanon from bitvec.knl, bitvec.kn. Do not edit.
import BitvecMod.Statements.Bitvec.and_
import BitvecMod.Proofs
import KanonBool.Soundness.Comm
import BitvecMod.Soundness.Comm

set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false
set_option maxHeartbeats 1000000

noncomputable section

namespace BitvecMod

open Classical Kanon

set_option maxHeartbeats 400000 in
theorem Bitvec.and_.r_lits.main.ok : Bitvec.and_.r_lits.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.and_.r_lits.main)

set_option maxHeartbeats 400000 in
theorem Bitvec.and_.r_zero.main.ok : Bitvec.and_.r_zero.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.and_.r_zero.main)

set_option maxHeartbeats 400000 in
theorem Bitvec.and_.r_zero.swap.ok : Bitvec.and_.r_zero.swap.Stmt := by
  intro S _ _ _ _ _ _ O hO v2 kanon__2 t__3 hg
  refine Kanon.Sem.Refines.trans ?_
    (Bitvec.and_.r_zero.main.ok O hO v2 kanon__2 t__3 hg)
  simp only [BitvecMod.Bitvec.and_.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (BitvecMod.BitAnd.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bitvec.and_.r_ones.main.ok : Bitvec.and_.r_ones.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.and_.r_ones.main)

set_option maxHeartbeats 400000 in
theorem Bitvec.and_.r_ones.swap.ok : Bitvec.and_.r_ones.swap.Stmt := by
  intro S _ _ _ _ _ _ O hO v1 mask t__2 hg
  refine Kanon.Sem.Refines.trans ?_
    (Bitvec.and_.r_ones.main.ok O hO v1 mask t__2 hg)
  simp only [BitvecMod.Bitvec.and_.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (BitvecMod.BitAnd.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bitvec.and_.r_lshr_mask.main.ok : Bitvec.and_.r_lshr_mask.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.and_.r_lshr_mask.main)

set_option maxHeartbeats 400000 in
theorem Bitvec.and_.r_lshr_mask.swap.ok : Bitvec.and_.r_lshr_mask.swap.Stmt := by
  intro S _ _ _ _ _ _ O hO mask t__8 w__2 shift t__4 t__5 hg
  refine Kanon.Sem.Refines.trans ?_
    (Bitvec.and_.r_lshr_mask.main.ok O hO w__2 shift t__4 t__5 mask t__8 hg)
  simp only [BitvecMod.Bitvec.and_.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (BitvecMod.BitAnd.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bitvec.and_.r_ite.main.ok : Bitvec.and_.r_ite.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.and_.r_ite.main)

set_option maxHeartbeats 400000 in
theorem Bitvec.and_.r_ite.swap.ok : Bitvec.and_.r_ite.swap.Stmt := by
  intro S _ _ _ _ _ _ O hO b l r t__8 w__1 t__2
  refine Kanon.Sem.Refines.trans ?_
    (Bitvec.and_.r_ite.main.ok O hO w__1 t__2 b l r t__8)
  simp only [BitvecMod.Bitvec.and_.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (BitvecMod.BitAnd.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bitvec.and_.r_masks.main.ok : Bitvec.and_.r_masks.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.and_.r_masks.main)

set_option maxHeartbeats 400000 in
theorem Bitvec.and_.r_masks.swap1.ok : Bitvec.and_.r_masks.swap1.Stmt := by
  intro S _ _ _ _ _ _ O hO m1 t__2 m2 t__6 x t__7
  have : S.Refines (BitvecMod.mk (.BitAnd (BitvecMod.mk (.BitVec m2) t__6) x) t__7)
    (BitvecMod.mk (.BitAnd x (BitvecMod.mk (.BitVec m2) t__6)) t__7) :=
    BitvecMod.BitAnd.comm.ok ..
  refine Kanon.Sem.Refines.trans ?_
    (Bitvec.and_.r_masks.main.ok O hO m1 t__2 x m2 t__6 t__7)
  simp only [BitvecMod.Bitvec.and_.spec, Kanon.NodeEmbed.ty_inj]
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bitvec.and_.r_masks.swap2.ok : Bitvec.and_.r_masks.swap2.Stmt := by
  intro S _ _ _ _ _ _ O hO x m2 t__6 t__7 m1 t__2
  refine Kanon.Sem.Refines.trans ?_
    (Bitvec.and_.r_masks.main.ok O hO m1 t__2 x m2 t__6 t__7)
  simp only [BitvecMod.Bitvec.and_.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (BitvecMod.BitAnd.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bitvec.and_.r_masks.swap1_swap2.ok : Bitvec.and_.r_masks.swap1_swap2.Stmt := by
  intro S _ _ _ _ _ _ O hO m2 t__6 x t__7 m1 t__2
  have : S.Refines (BitvecMod.mk (.BitAnd (BitvecMod.mk (.BitVec m2) t__6) x) t__7)
    (BitvecMod.mk (.BitAnd x (BitvecMod.mk (.BitVec m2) t__6)) t__7) :=
    BitvecMod.BitAnd.comm.ok ..
  refine Kanon.Sem.Refines.trans ?_
    (Bitvec.and_.r_masks.main.ok O hO m1 t__2 x m2 t__6 t__7)
  simp only [BitvecMod.Bitvec.and_.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (BitvecMod.BitAnd.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bitvec.and_.r_mask_or_mask.main.ok : Bitvec.and_.r_mask_or_mask.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.and_.r_mask_or_mask.main)

set_option maxHeartbeats 400000 in
theorem Bitvec.and_.r_mask_or_mask.swap1.ok : Bitvec.and_.r_mask_or_mask.swap1.Stmt := by
  intro S _ _ _ _ _ _ O hO w__1 t__2 w__5 t__6 x w__9 t__10 t__13 t__15
  have : S.Refines (BitvecMod.mk (.BitAnd x (BitvecMod.mk (.BitVec w__9) t__10)) t__13)
    (BitvecMod.mk (.BitAnd (BitvecMod.mk (.BitVec w__9) t__10) x) t__13) :=
    BitvecMod.BitAnd.comm.ok ..
  refine Kanon.Sem.Refines.trans ?_
    (Bitvec.and_.r_mask_or_mask.main.ok O hO w__1 t__2 w__5 t__6 w__9 t__10 x t__13 t__15)
  simp only [BitvecMod.Bitvec.and_.spec, Kanon.NodeEmbed.ty_inj]
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bitvec.and_.r_mask_or_mask.swap2.ok : Bitvec.and_.r_mask_or_mask.swap2.Stmt := by
  intro S _ _ _ _ _ _ O hO w__1 t__2 w__9 t__10 x t__13 w__5 t__6 t__15
  have : S.Refines (BitvecMod.mk (.BitOr (BitvecMod.mk (.BitAnd (BitvecMod.mk (.BitVec w__9) t__10) x) t__13) (BitvecMod.mk (.BitVec w__5) t__6)) t__15)
    (BitvecMod.mk (.BitOr (BitvecMod.mk (.BitVec w__5) t__6) (BitvecMod.mk (.BitAnd (BitvecMod.mk (.BitVec w__9) t__10) x) t__13)) t__15) :=
    BitvecMod.BitOr.comm.ok ..
  refine Kanon.Sem.Refines.trans ?_
    (Bitvec.and_.r_mask_or_mask.main.ok O hO w__1 t__2 w__5 t__6 w__9 t__10 x t__13 t__15)
  simp only [BitvecMod.Bitvec.and_.spec, Kanon.NodeEmbed.ty_inj]
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bitvec.and_.r_mask_or_mask.swap1_swap2.ok : Bitvec.and_.r_mask_or_mask.swap1_swap2.Stmt := by
  intro S _ _ _ _ _ _ O hO w__1 t__2 x w__9 t__10 t__13 w__5 t__6 t__15
  have : S.Refines (BitvecMod.mk (.BitAnd x (BitvecMod.mk (.BitVec w__9) t__10)) t__13)
    (BitvecMod.mk (.BitAnd (BitvecMod.mk (.BitVec w__9) t__10) x) t__13) :=
    BitvecMod.BitAnd.comm.ok ..
  have : S.Refines (BitvecMod.mk (.BitOr (BitvecMod.mk (.BitAnd x (BitvecMod.mk (.BitVec w__9) t__10)) t__13) (BitvecMod.mk (.BitVec w__5) t__6)) t__15)
    (BitvecMod.mk (.BitOr (BitvecMod.mk (.BitVec w__5) t__6) (BitvecMod.mk (.BitAnd (BitvecMod.mk (.BitVec w__9) t__10) x) t__13)) t__15) :=
    Kanon.Sem.Refines.trans (BitvecMod.BitOr.comm.ok ..) (by kanon_congr)
  refine Kanon.Sem.Refines.trans ?_
    (Bitvec.and_.r_mask_or_mask.main.ok O hO w__1 t__2 w__5 t__6 w__9 t__10 x t__13 t__15)
  simp only [BitvecMod.Bitvec.and_.spec, Kanon.NodeEmbed.ty_inj]
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bitvec.and_.r_mask_or_mask.swap3.ok : Bitvec.and_.r_mask_or_mask.swap3.Stmt := by
  intro S _ _ _ _ _ _ O hO w__5 t__6 w__9 t__10 x t__13 t__15 w__1 t__2
  refine Kanon.Sem.Refines.trans ?_
    (Bitvec.and_.r_mask_or_mask.main.ok O hO w__1 t__2 w__5 t__6 w__9 t__10 x t__13 t__15)
  simp only [BitvecMod.Bitvec.and_.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (BitvecMod.BitAnd.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bitvec.and_.r_mask_or_mask.swap1_swap3.ok : Bitvec.and_.r_mask_or_mask.swap1_swap3.Stmt := by
  intro S _ _ _ _ _ _ O hO w__5 t__6 x w__9 t__10 t__13 t__15 w__1 t__2
  have : S.Refines (BitvecMod.mk (.BitAnd x (BitvecMod.mk (.BitVec w__9) t__10)) t__13)
    (BitvecMod.mk (.BitAnd (BitvecMod.mk (.BitVec w__9) t__10) x) t__13) :=
    BitvecMod.BitAnd.comm.ok ..
  refine Kanon.Sem.Refines.trans ?_
    (Bitvec.and_.r_mask_or_mask.main.ok O hO w__1 t__2 w__5 t__6 w__9 t__10 x t__13 t__15)
  simp only [BitvecMod.Bitvec.and_.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (BitvecMod.BitAnd.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bitvec.and_.r_mask_or_mask.swap2_swap3.ok : Bitvec.and_.r_mask_or_mask.swap2_swap3.Stmt := by
  intro S _ _ _ _ _ _ O hO w__9 t__10 x t__13 w__5 t__6 t__15 w__1 t__2
  have : S.Refines (BitvecMod.mk (.BitOr (BitvecMod.mk (.BitAnd (BitvecMod.mk (.BitVec w__9) t__10) x) t__13) (BitvecMod.mk (.BitVec w__5) t__6)) t__15)
    (BitvecMod.mk (.BitOr (BitvecMod.mk (.BitVec w__5) t__6) (BitvecMod.mk (.BitAnd (BitvecMod.mk (.BitVec w__9) t__10) x) t__13)) t__15) :=
    BitvecMod.BitOr.comm.ok ..
  refine Kanon.Sem.Refines.trans ?_
    (Bitvec.and_.r_mask_or_mask.main.ok O hO w__1 t__2 w__5 t__6 w__9 t__10 x t__13 t__15)
  simp only [BitvecMod.Bitvec.and_.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (BitvecMod.BitAnd.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bitvec.and_.r_mask_or_mask.swap1_swap2_swap3.ok : Bitvec.and_.r_mask_or_mask.swap1_swap2_swap3.Stmt := by
  intro S _ _ _ _ _ _ O hO x w__9 t__10 t__13 w__5 t__6 t__15 w__1 t__2
  have : S.Refines (BitvecMod.mk (.BitAnd x (BitvecMod.mk (.BitVec w__9) t__10)) t__13)
    (BitvecMod.mk (.BitAnd (BitvecMod.mk (.BitVec w__9) t__10) x) t__13) :=
    BitvecMod.BitAnd.comm.ok ..
  have : S.Refines (BitvecMod.mk (.BitOr (BitvecMod.mk (.BitAnd x (BitvecMod.mk (.BitVec w__9) t__10)) t__13) (BitvecMod.mk (.BitVec w__5) t__6)) t__15)
    (BitvecMod.mk (.BitOr (BitvecMod.mk (.BitVec w__5) t__6) (BitvecMod.mk (.BitAnd (BitvecMod.mk (.BitVec w__9) t__10) x) t__13)) t__15) :=
    Kanon.Sem.Refines.trans (BitvecMod.BitOr.comm.ok ..) (by kanon_congr)
  refine Kanon.Sem.Refines.trans ?_
    (Bitvec.and_.r_mask_or_mask.main.ok O hO w__1 t__2 w__5 t__6 w__9 t__10 x t__13 t__15)
  simp only [BitvecMod.Bitvec.and_.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (BitvecMod.BitAnd.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bitvec.and_.r_mask_or.main.ok : Bitvec.and_.r_mask_or.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.and_.r_mask_or.main)

set_option maxHeartbeats 400000 in
theorem Bitvec.and_.r_mask_or.swap1.ok : Bitvec.and_.r_mask_or.swap1.Stmt := by
  intro S _ _ _ _ _ _ O hO m_and t__2 m_or t__7 w__5 t__8 hg
  have : S.Refines (BitvecMod.mk (.BitOr (BitvecMod.mk (.BitVec m_or) t__7) w__5) t__8)
    (BitvecMod.mk (.BitOr w__5 (BitvecMod.mk (.BitVec m_or) t__7)) t__8) :=
    BitvecMod.BitOr.comm.ok ..
  refine Kanon.Sem.Refines.trans ?_
    (Bitvec.and_.r_mask_or.main.ok O hO m_and t__2 w__5 m_or t__7 t__8 hg)
  simp only [BitvecMod.Bitvec.and_.spec, Kanon.NodeEmbed.ty_inj]
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bitvec.and_.r_mask_or.swap2.ok : Bitvec.and_.r_mask_or.swap2.Stmt := by
  intro S _ _ _ _ _ _ O hO w__5 m_or t__7 t__8 m_and t__2 hg
  refine Kanon.Sem.Refines.trans ?_
    (Bitvec.and_.r_mask_or.main.ok O hO m_and t__2 w__5 m_or t__7 t__8 hg)
  simp only [BitvecMod.Bitvec.and_.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (BitvecMod.BitAnd.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bitvec.and_.r_mask_or.swap1_swap2.ok : Bitvec.and_.r_mask_or.swap1_swap2.Stmt := by
  intro S _ _ _ _ _ _ O hO m_or t__7 w__5 t__8 m_and t__2 hg
  have : S.Refines (BitvecMod.mk (.BitOr (BitvecMod.mk (.BitVec m_or) t__7) w__5) t__8)
    (BitvecMod.mk (.BitOr w__5 (BitvecMod.mk (.BitVec m_or) t__7)) t__8) :=
    BitvecMod.BitOr.comm.ok ..
  refine Kanon.Sem.Refines.trans ?_
    (Bitvec.and_.r_mask_or.main.ok O hO m_and t__2 w__5 m_or t__7 t__8 hg)
  simp only [BitvecMod.Bitvec.and_.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (BitvecMod.BitAnd.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bitvec.and_.r_mask_or_disj.main.ok : Bitvec.and_.r_mask_or_disj.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.and_.r_mask_or_disj.main)

set_option maxHeartbeats 400000 in
theorem Bitvec.and_.r_mask_or_disj.swap1.ok : Bitvec.and_.r_mask_or_disj.swap1.Stmt := by
  intro S _ _ _ _ _ _ O hO m_and t__2 m_or t__7 x t__8 hg
  have : S.Refines (BitvecMod.mk (.BitOr (BitvecMod.mk (.BitVec m_or) t__7) x) t__8)
    (BitvecMod.mk (.BitOr x (BitvecMod.mk (.BitVec m_or) t__7)) t__8) :=
    BitvecMod.BitOr.comm.ok ..
  refine Kanon.Sem.Refines.trans ?_
    (Bitvec.and_.r_mask_or_disj.main.ok O hO m_and t__2 x m_or t__7 t__8 hg)
  simp only [BitvecMod.Bitvec.and_.spec, Kanon.NodeEmbed.ty_inj]
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bitvec.and_.r_mask_or_disj.swap2.ok : Bitvec.and_.r_mask_or_disj.swap2.Stmt := by
  intro S _ _ _ _ _ _ O hO x m_or t__7 t__8 m_and t__2 hg
  refine Kanon.Sem.Refines.trans ?_
    (Bitvec.and_.r_mask_or_disj.main.ok O hO m_and t__2 x m_or t__7 t__8 hg)
  simp only [BitvecMod.Bitvec.and_.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (BitvecMod.BitAnd.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bitvec.and_.r_mask_or_disj.swap1_swap2.ok : Bitvec.and_.r_mask_or_disj.swap1_swap2.Stmt := by
  intro S _ _ _ _ _ _ O hO m_or t__7 x t__8 m_and t__2 hg
  have : S.Refines (BitvecMod.mk (.BitOr (BitvecMod.mk (.BitVec m_or) t__7) x) t__8)
    (BitvecMod.mk (.BitOr x (BitvecMod.mk (.BitVec m_or) t__7)) t__8) :=
    BitvecMod.BitOr.comm.ok ..
  refine Kanon.Sem.Refines.trans ?_
    (Bitvec.and_.r_mask_or_disj.main.ok O hO m_and t__2 x m_or t__7 t__8 hg)
  simp only [BitvecMod.Bitvec.and_.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (BitvecMod.BitAnd.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bitvec.and_.r_right_mask.main.ok : Bitvec.and_.r_right_mask.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.and_.r_right_mask.main)

set_option maxHeartbeats 400000 in
theorem Bitvec.and_.r_right_mask.swap.ok : Bitvec.and_.r_right_mask.swap.Stmt := by
  intro S _ _ _ _ _ _ O hO l r t__7 mask t__2 hg
  refine Kanon.Sem.Refines.trans ?_
    (Bitvec.and_.r_right_mask.main.ok O hO mask t__2 l r t__7 hg)
  simp only [BitvecMod.Bitvec.and_.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (BitvecMod.BitAnd.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bitvec.and_.r_of_bool.main.ok : Bitvec.and_.r_of_bool.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.and_.r_of_bool.main)

set_option maxHeartbeats 400000 in
theorem Bitvec.and_.r_of_bool.swap.ok : Bitvec.and_.r_of_bool.swap.Stmt := by
  intro S _ _ _ _ _ _ O hO w__3 w__5 t__6 kanon__1 t__2 hg
  refine Kanon.Sem.Refines.trans ?_
    (Bitvec.and_.r_of_bool.main.ok O hO kanon__1 t__2 w__3 w__5 t__6 hg)
  simp only [BitvecMod.Bitvec.and_.spec, Kanon.NodeEmbed.ty_inj]
  refine Kanon.Sem.Refines.trans (BitvecMod.BitAnd.comm.ok ..) ?_
  kanon_congr

set_option maxHeartbeats 400000 in
theorem Bitvec.and_.r_of_bools.main.ok : Bitvec.and_.r_of_bools.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.and_.r_of_bools.main)

set_option maxHeartbeats 400000 in
theorem Bitvec.and_.r_ites.main.ok : Bitvec.and_.r_ites.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.and_.r_ites.main)

set_option maxHeartbeats 400000 in
theorem Bitvec.and_.r_default.main.ok : Bitvec.and_.r_default.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.and_.r_default.main)

theorem Bitvec.and_.r_lits.sound {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bitvec.and_.r_lits O v1 v2 = some res) : S.Refines (BitvecMod.Bitvec.and_.spec v1 v2) res := by
  unfold Bitvec.and_.r_lits at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bitvec.and_.r_lits.main.ok O hO)

theorem Bitvec.and_.r_zero.sound {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bitvec.and_.r_zero O v1 v2 = some res) : S.Refines (BitvecMod.Bitvec.and_.spec v1 v2) res := by
  unfold Bitvec.and_.r_zero at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bitvec.and_.r_zero.main.ok O hO)
  · kanon_arm h (Bitvec.and_.r_zero.swap.ok O hO)

theorem Bitvec.and_.r_ones.sound {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bitvec.and_.r_ones O v1 v2 = some res) : S.Refines (BitvecMod.Bitvec.and_.spec v1 v2) res := by
  unfold Bitvec.and_.r_ones at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bitvec.and_.r_ones.main.ok O hO)
  · kanon_arm h (Bitvec.and_.r_ones.swap.ok O hO)

theorem Bitvec.and_.r_lshr_mask.sound {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bitvec.and_.r_lshr_mask O v1 v2 = some res) : S.Refines (BitvecMod.Bitvec.and_.spec v1 v2) res := by
  unfold Bitvec.and_.r_lshr_mask at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bitvec.and_.r_lshr_mask.main.ok O hO)
  · kanon_arm h (Bitvec.and_.r_lshr_mask.swap.ok O hO)

theorem Bitvec.and_.r_ite.sound {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bitvec.and_.r_ite O v1 v2 = some res) : S.Refines (BitvecMod.Bitvec.and_.spec v1 v2) res := by
  unfold Bitvec.and_.r_ite at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bitvec.and_.r_ite.main.ok O hO)
  · kanon_arm h (Bitvec.and_.r_ite.swap.ok O hO)

theorem Bitvec.and_.r_masks.sound {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bitvec.and_.r_masks O v1 v2 = some res) : S.Refines (BitvecMod.Bitvec.and_.spec v1 v2) res := by
  unfold Bitvec.and_.r_masks at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bitvec.and_.r_masks.main.ok O hO)
  · kanon_arm h (Bitvec.and_.r_masks.swap1.ok O hO)
  · kanon_arm h (Bitvec.and_.r_masks.swap2.ok O hO)
  · kanon_arm h (Bitvec.and_.r_masks.swap1_swap2.ok O hO)

theorem Bitvec.and_.r_mask_or_mask.sound {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bitvec.and_.r_mask_or_mask O v1 v2 = some res) : S.Refines (BitvecMod.Bitvec.and_.spec v1 v2) res := by
  unfold Bitvec.and_.r_mask_or_mask at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bitvec.and_.r_mask_or_mask.main.ok O hO)
  · kanon_arm h (Bitvec.and_.r_mask_or_mask.swap1.ok O hO)
  · kanon_arm h (Bitvec.and_.r_mask_or_mask.swap2.ok O hO)
  · kanon_arm h (Bitvec.and_.r_mask_or_mask.swap1_swap2.ok O hO)
  · kanon_arm h (Bitvec.and_.r_mask_or_mask.swap3.ok O hO)
  · kanon_arm h (Bitvec.and_.r_mask_or_mask.swap1_swap3.ok O hO)
  · kanon_arm h (Bitvec.and_.r_mask_or_mask.swap2_swap3.ok O hO)
  · kanon_arm h (Bitvec.and_.r_mask_or_mask.swap1_swap2_swap3.ok O hO)

theorem Bitvec.and_.r_mask_or.sound {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bitvec.and_.r_mask_or O v1 v2 = some res) : S.Refines (BitvecMod.Bitvec.and_.spec v1 v2) res := by
  unfold Bitvec.and_.r_mask_or at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bitvec.and_.r_mask_or.main.ok O hO)
  · kanon_arm h (Bitvec.and_.r_mask_or.swap1.ok O hO)
  · kanon_arm h (Bitvec.and_.r_mask_or.swap2.ok O hO)
  · kanon_arm h (Bitvec.and_.r_mask_or.swap1_swap2.ok O hO)

theorem Bitvec.and_.r_mask_or_disj.sound {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bitvec.and_.r_mask_or_disj O v1 v2 = some res) : S.Refines (BitvecMod.Bitvec.and_.spec v1 v2) res := by
  unfold Bitvec.and_.r_mask_or_disj at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bitvec.and_.r_mask_or_disj.main.ok O hO)
  · kanon_arm h (Bitvec.and_.r_mask_or_disj.swap1.ok O hO)
  · kanon_arm h (Bitvec.and_.r_mask_or_disj.swap2.ok O hO)
  · kanon_arm h (Bitvec.and_.r_mask_or_disj.swap1_swap2.ok O hO)

theorem Bitvec.and_.r_right_mask.sound {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bitvec.and_.r_right_mask O v1 v2 = some res) : S.Refines (BitvecMod.Bitvec.and_.spec v1 v2) res := by
  unfold Bitvec.and_.r_right_mask at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bitvec.and_.r_right_mask.main.ok O hO)
  · kanon_arm h (Bitvec.and_.r_right_mask.swap.ok O hO)

theorem Bitvec.and_.r_of_bool.sound {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bitvec.and_.r_of_bool O v1 v2 = some res) : S.Refines (BitvecMod.Bitvec.and_.spec v1 v2) res := by
  unfold Bitvec.and_.r_of_bool at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bitvec.and_.r_of_bool.main.ok O hO)
  · kanon_arm h (Bitvec.and_.r_of_bool.swap.ok O hO)

theorem Bitvec.and_.r_of_bools.sound {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bitvec.and_.r_of_bools O v1 v2 = some res) : S.Refines (BitvecMod.Bitvec.and_.spec v1 v2) res := by
  unfold Bitvec.and_.r_of_bools at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bitvec.and_.r_of_bools.main.ok O hO)

theorem Bitvec.and_.r_ites.sound {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bitvec.and_.r_ites O v1 v2 = some res) : S.Refines (BitvecMod.Bitvec.and_.spec v1 v2) res := by
  unfold Bitvec.and_.r_ites at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bitvec.and_.r_ites.main.ok O hO)

theorem Bitvec.and_.r_default.sound {S : Kanon.Sem} [KanonBool.Lang S] [CoreMod.Lang S] [BitvecMod.Lang S] [KanonBool.Typed S] [CoreMod.Typed S] [BitvecMod.Typed S] (O : Ops S) (hO : O.Sound) (v1 : S.Term) (v2 : S.Term) (res : S.Term)
    (h : Bitvec.and_.r_default O v1 v2 = some res) : S.Refines (BitvecMod.Bitvec.and_.spec v1 v2) res := by
  unfold Bitvec.and_.r_default at h
  repeat' (replace h := Kanon.orElse_some h; rcases h with h | h)
  · kanon_arm h (Bitvec.and_.r_default.main.ok O hO)

end BitvecMod
