-- Generated by kanon from bitvec.knl, bitvec.kn. Do not edit.
import BitvecMod.Statements.Bitvec.div
import BitvecMod.Soundness.Laws

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace BitvecMod

open Classical Kanon

set_option maxHeartbeats 400000 in
theorem Bitvec.div.r_lits.main.ok : Bitvec.div.r_lits.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.div.r_lits.main)

set_option maxHeartbeats 400000 in
theorem Bitvec.div.r_one.main.ok : Bitvec.div.r_one.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.div.r_one.main)

set_option maxHeartbeats 400000 in
theorem Bitvec.div.r_mul_lits.main.ok : Bitvec.div.r_mul_lits.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.div.r_mul_lits.main)

set_option maxHeartbeats 400000 in
theorem Bitvec.div.r_mul_div.main.ok : Bitvec.div.r_mul_div.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.div.r_mul_div.main)

set_option maxHeartbeats 400000 in
theorem Bitvec.div.r_mul_div.swap.ok : Bitvec.div.r_mul_div.swap.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.div.r_mul_div.swap)

set_option maxHeartbeats 400000 in
theorem Bitvec.div.r_div_mul.main.ok : Bitvec.div.r_div_mul.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.div.r_div_mul.main)

set_option maxHeartbeats 400000 in
theorem Bitvec.div.r_div_mul.swap.ok : Bitvec.div.r_div_mul.swap.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.div.r_div_mul.swap)

set_option maxHeartbeats 400000 in
theorem Bitvec.div.r_div_div.main.ok : Bitvec.div.r_div_div.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.div.r_div_div.main)

set_option maxHeartbeats 400000 in
theorem Bitvec.div.r_zext.main.ok : Bitvec.div.r_zext.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.div.r_zext.main)

set_option maxHeartbeats 400000 in
theorem Bitvec.div.r_default.main.ok : Bitvec.div.r_default.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.div.r_default.main)

end BitvecMod
