-- Generated by kanon from bitvec.knl, bitvec.kn. Do not edit.
import BitvecMod.Statements.Bitvec.not_bool
import BitvecMod.Soundness.Laws

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace BitvecMod

open Classical Kanon

set_option maxHeartbeats 400000 in
theorem Bitvec.not_bool.r_lit.main.ok : Bitvec.not_bool.r_lit.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.not_bool.r_lit.main)

set_option maxHeartbeats 400000 in
theorem Bitvec.not_bool.r_of_bool.main.ok : Bitvec.not_bool.r_of_bool.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.not_bool.r_of_bool.main)

set_option maxHeartbeats 400000 in
theorem Bitvec.not_bool.r_default.main.ok : Bitvec.not_bool.r_default.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.not_bool.r_default.main)

end BitvecMod
