-- Generated by kanon from bitvec.knl, bitvec.kn. Do not edit.
import BitvecMod.Statements.Bitvec.of_bool
import BitvecMod.Soundness.Laws

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace BitvecMod

open Classical Kanon

set_option maxHeartbeats 400000 in
theorem Bitvec.of_bool.r_true_.main.ok : Bitvec.of_bool.r_true_.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.of_bool.r_true_.main)

set_option maxHeartbeats 400000 in
theorem Bitvec.of_bool.r_false_.main.ok : Bitvec.of_bool.r_false_.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.of_bool.r_false_.main)

set_option maxHeartbeats 400000 in
theorem Bitvec.of_bool.r_default.main.ok : Bitvec.of_bool.r_default.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.of_bool.r_default.main)

end BitvecMod
