-- Generated by kanon from bitvec.knl, bitvec.kn. Do not edit.
import BitvecMod.Statements.Bitvec.sub
import BitvecMod.Soundness.Laws

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace BitvecMod

open Classical Kanon

set_option maxHeartbeats 400000 in
theorem Bitvec.sub.r_lits.main.ok : Bitvec.sub.r_lits.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.sub.r_lits.main)

set_option maxHeartbeats 400000 in
theorem Bitvec.sub.r_zero_r.main.ok : Bitvec.sub.r_zero_r.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.sub.r_zero_r.main)

set_option maxHeartbeats 400000 in
theorem Bitvec.sub.r_zero_l.main.ok : Bitvec.sub.r_zero_l.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.sub.r_zero_l.main)

set_option maxHeartbeats 400000 in
theorem Bitvec.sub.r_same.main.ok : Bitvec.sub.r_same.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.sub.r_same.main)

set_option maxHeartbeats 400000 in
theorem Bitvec.sub.r_neg_r.main.ok : Bitvec.sub.r_neg_r.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.sub.r_neg_r.main)

set_option maxHeartbeats 400000 in
theorem Bitvec.sub.r_sub_const_l.main.ok : Bitvec.sub.r_sub_const_l.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.sub.r_sub_const_l.main)

set_option maxHeartbeats 400000 in
theorem Bitvec.sub.r_sub_const_r.main.ok : Bitvec.sub.r_sub_const_r.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.sub.r_sub_const_r.main)

set_option maxHeartbeats 400000 in
theorem Bitvec.sub.r_const_add.main.ok : Bitvec.sub.r_const_add.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.sub.r_const_add.main)

set_option maxHeartbeats 400000 in
theorem Bitvec.sub.r_const_add.swap.ok : Bitvec.sub.r_const_add.swap.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.sub.r_const_add.swap)

set_option maxHeartbeats 400000 in
theorem Bitvec.sub.r_add_const.main.ok : Bitvec.sub.r_add_const.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.sub.r_add_const.main)

set_option maxHeartbeats 400000 in
theorem Bitvec.sub.r_add_const.swap.ok : Bitvec.sub.r_add_const.swap.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.sub.r_add_const.swap)

set_option maxHeartbeats 400000 in
theorem Bitvec.sub.r_add_cancel_l.main.ok : Bitvec.sub.r_add_cancel_l.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.sub.r_add_cancel_l.main)

set_option maxHeartbeats 400000 in
theorem Bitvec.sub.r_add_cancel_l.swap.ok : Bitvec.sub.r_add_cancel_l.swap.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.sub.r_add_cancel_l.swap)

set_option maxHeartbeats 400000 in
theorem Bitvec.sub.r_add_cancel_r.main.ok : Bitvec.sub.r_add_cancel_r.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.sub.r_add_cancel_r.main)

set_option maxHeartbeats 400000 in
theorem Bitvec.sub.r_add_cancel_r.swap.ok : Bitvec.sub.r_add_cancel_r.swap.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.sub.r_add_cancel_r.swap)

set_option maxHeartbeats 400000 in
theorem Bitvec.sub.r_add_add.main.ok : Bitvec.sub.r_add_add.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.sub.r_add_add.main)

set_option maxHeartbeats 400000 in
theorem Bitvec.sub.r_add_add.swap2.ok : Bitvec.sub.r_add_add.swap2.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.sub.r_add_add.swap2)

set_option maxHeartbeats 400000 in
theorem Bitvec.sub.r_add_add.swap1.ok : Bitvec.sub.r_add_add.swap1.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.sub.r_add_add.swap1)

set_option maxHeartbeats 400000 in
theorem Bitvec.sub.r_add_add.swap1_swap2.ok : Bitvec.sub.r_add_add.swap1_swap2.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.sub.r_add_add.swap1_swap2)

set_option maxHeartbeats 400000 in
theorem Bitvec.sub.r_sub_sub.main.ok : Bitvec.sub.r_sub_sub.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.sub.r_sub_sub.main)

set_option maxHeartbeats 400000 in
theorem Bitvec.sub.r_ite_ite.main.ok : Bitvec.sub.r_ite_ite.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.sub.r_ite_ite.main)

set_option maxHeartbeats 400000 in
theorem Bitvec.sub.r_ite_l.main.ok : Bitvec.sub.r_ite_l.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.sub.r_ite_l.main)

set_option maxHeartbeats 400000 in
theorem Bitvec.sub.r_ite_r.main.ok : Bitvec.sub.r_ite_r.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.sub.r_ite_r.main)

set_option maxHeartbeats 400000 in
theorem Bitvec.sub.r_of_bool_l.main.ok : Bitvec.sub.r_of_bool_l.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.sub.r_of_bool_l.main)

set_option maxHeartbeats 400000 in
theorem Bitvec.sub.r_of_bool_r.main.ok : Bitvec.sub.r_of_bool_r.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.sub.r_of_bool_r.main)

set_option maxHeartbeats 400000 in
theorem Bitvec.sub.r_default.main.ok : Bitvec.sub.r_default.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.sub.r_default.main)

end BitvecMod
