-- Generated by kanon from bitvec.knl, bitvec.kn. Do not edit.
import BitvecMod.Statements.Bitvec.sub_overflows
import BitvecMod.Soundness.Laws

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace BitvecMod

open Classical Kanon

set_option maxHeartbeats 400000 in
theorem Bitvec.sub_overflows.r_lits.main.ok : Bitvec.sub_overflows.r_lits.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.sub_overflows.r_lits.main)

set_option maxHeartbeats 400000 in
theorem Bitvec.sub_overflows.r_same.main.ok : Bitvec.sub_overflows.r_same.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.sub_overflows.r_same.main)

set_option maxHeartbeats 400000 in
theorem Bitvec.sub_overflows.r_unsigned.main.ok : Bitvec.sub_overflows.r_unsigned.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.sub_overflows.r_unsigned.main)

set_option maxHeartbeats 400000 in
theorem Bitvec.sub_overflows.r_default.main.ok : Bitvec.sub_overflows.r_default.main.Stmt :=
  no_implicit_lambda% (kanon_proof% Bitvec.sub_overflows.r_default.main)

end BitvecMod
