-- Generated by kanon from bool.kn, exists.kn, bitvec.kn, float.kn, ptr.kn, view.kn. Do not edit.
import Kanon.Ops

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace Kanon

open Classical Kanon

def Float.max.r_lits (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | (Term.mk (Kind.Float f1) _), (Term.mk (Kind.Float f2) _) =>
    (whenSome true
    ((let kanon__a1 := (O.orc.f_max f1 f2);
     (Term.mk (Kind.Float kanon__a1) (Ty.TFloat (f_prec kanon__a1))))))
    | _, _ => none)

def Float.max.r_default (O : Ops) (v1 : Term) (v2 : Term) : Option Term :=
  (match v1, v2 with
    | _, _ =>
    (whenSome true ((Term.mk (Kind.Op2 Op2.FMax v1 v2) (ty v1)))))

def Float.max.step (O : Ops) (v1 : Term) (v2 : Term) : Term :=
  (firstSome [Float.max.r_lits O v1 v2, Float.max.r_default O v1 v2]).getD (Float.max.spec v1 v2)

end Kanon
