-- Generated by kanon from bool.kn, exists.kn, bitvec.kn, float.kn, ptr.kn, view.kn. Do not edit.
import KanonCore.Generic
import Kanon.Semantics

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace Kanon

open Classical Kanon

/-- The terms of the language, for the interfaces of its modules. -/
def modBase (FS : FloatSem) : Kanon.Base (sem FS) where
  Kind := Kind
  node := Term.mk
  ty_node _ _ := rfl

attribute [kanon_law] modBase

end Kanon
