-- Generated by kanon from bool.kn, exists.kn, bitvec.kn, float.kn, ptr.kn, view.kn. Do not edit.
import Kanon.Signatures
import Kanon.Model.Bitvec.min_for
import Kanon.Model.Bitvec.size
import Kanon.Model.Float.raw_fmod_of_rem

set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

noncomputable section

namespace Kanon

open Classical Kanon

/-- The primitives that the model is parameterised by. -/
structure Oracle where
  tag_le : Term → Term → Bool
  sort_by_tag : (List Term) → (List Term)
  f_add : Float → Float → Float
  f_sub : Float → Float → Float
  f_mul : Float → Float → Float
  f_div : Float → Float → Float
  f_rem : Float → Float → Float
  f_fmod : Float → Float → Float
  f_min : Float → Float → Float
  f_max : Float → Float → Float
  f_fma : Float → Float → Float → Float
  f_sqrt : Float → Float
  f_round : Rm → Float → Float
  f_convert : Rm → Fp → Float → Float
  f_to_int : Rm → Bool → Int → Float → (Option Int)
  f_of_int : Rm → Bool → Fp → Int → Int → (Option Float)

/-- The rule functions, as used by the rules. -/
structure Ops where
  orc : Oracle
  bool_and_ : Term → Term → Term
  bool_or_ : Term → Term → Term
  bool_not_ : Term → Term
  bool_ite : Term → Term → Term → Term
  bool_eq : Term → Term → Term
  bool_eq_untyped : Term → Term → Term
  bool_distinct : (List Term) → Term
  exists_mk : (List (Int × Ty)) → Term → Term
  bitvec_of_bool : Int → Term → Term
  bitvec_to_bool : Term → Term
  bitvec_not_bool : Term → Term
  bitvec_add : Checked → Term → Term → Term
  bitvec_sub : Checked → Term → Term → Term
  bitvec_neg : Bool → Term → Term
  bitvec_mod_ : Term → Term → Term
  bitvec_rem : Bool → Term → Term → Term
  bitvec_not_ : Term → Term
  bitvec_and_ : Term → Term → Term
  bitvec_or_ : Term → Term → Term
  bitvec_xor : Term → Term → Term
  bitvec_extract : Int → Int → Term → Term
  bitvec_extend_ : Bool → Int → Term → Term
  bitvec_concat : Term → Term → Term
  bitvec_shl : Term → Term → Term
  bitvec_lshr : Term → Term → Term
  bitvec_ashr : Term → Term → Term
  bitvec_mul : Checked → Term → Term → Term
  bitvec_div : Bool → Term → Term → Term
  bitvec_lt_zero : Term → Term
  bitvec_lt : Bool → Term → Term → Term
  bitvec_leq : Bool → Term → Term → Term
  bitvec_add_overflows : Bool → Term → Term → Term
  bitvec_mul_overflows : Bool → Term → Term → Term
  bitvec_neg_overflows : Term → Term
  bitvec_sub_overflows : Bool → Term → Term → Term
  float_is_floatclass : Fc → Term → Term
  float_is_negative : Term → Term
  float_is_positive : Term → Term
  float_cast : Rm → Fp → Term → Term
  float_eq : Term → Term → Term
  float_lt : Term → Term → Term
  float_leq : Term → Term → Term
  float_add : Term → Term → Term
  float_sub : Term → Term → Term
  float_div : Term → Term → Term
  float_mul : Term → Term → Term
  float_rem : Term → Term → Term
  float_abs : Term → Term
  float_neg : Term → Term
  float_fma : Term → Term → Term → Term
  float_fmod_of_rem : Term → Term → Term → Term
  float_fmod : Term → Term → Term
  float_min : Term → Term → Term
  float_max : Term → Term → Term
  float_sqrt : Term → Term
  float_round : Rm → Term → Term
  float_of_float : Rm → Bool → Int → Term → Term
  float_to_float : Rm → Bool → Fp → Term → Term
  float_to_float_bits : Fp → Term → Term
  ptr_loc : Term → Term
  ptr_ofs : Term → Term

def Bool.and_.spec (v1 : Term) (v2 : Term) : Term :=
  (Term.mk (Kind.Op2 Op2.And v1 v2) Ty.TBool)

def Bool.or_.spec (v1 : Term) (v2 : Term) : Term :=
  (Term.mk (Kind.Op2 Op2.Or v1 v2) Ty.TBool)

def Bool.not_.spec (sv : Term) : Term :=
  (Term.mk (Kind.Op1 Op1.Not sv) Ty.TBool)

def Bool.ite.spec (guard : Term) (if_ : Term) (else_ : Term) : Term :=
  (Term.mk (Kind.Op3 Op3.Ite guard if_ else_) (ty if_))

def Bool.eq.spec (v1 : Term) (v2 : Term) : Term :=
  (Term.mk (Kind.Op2 Op2.Eq v1 v2) Ty.TBool)

def Bool.eq_untyped.spec (v1 : Term) (v2 : Term) : Term :=
  (Term.mk (Kind.Op2 Op2.Eq v1 v2) Ty.TBool)

def Bool.distinct.spec (l : (List Term)) : Term :=
  (Term.mk (Kind.OpN OpN.Distinct l) Ty.TBool)

def Exists.mk.spec (binders : (List (Int × Ty))) (body : Term) : Term :=
  (Term.mk (Kind.Exists binders body) Ty.TBool)

def Bitvec.of_bool.spec (n : Int) (b : Term) : Term :=
  (Term.mk (Kind.Op1 (Op1.BvOfBool n) b) (Ty.TBitVector n))

def Bitvec.to_bool.spec (v : Term) : Term :=
  (Term.mk (Kind.Op1 Op1.Not (Term.mk (Kind.Op2 Op2.Eq v (bv_zero (Bitvec.size v))) Ty.TBool)) Ty.TBool)

def Bitvec.not_bool.spec (v : Term) : Term :=
  (Term.mk (Kind.Op1 (Op1.BvOfBool (Bitvec.size v)) (Term.mk (Kind.Op2 Op2.Eq v (bv_zero (Bitvec.size v))) Ty.TBool)) (Ty.TBitVector (Bitvec.size v)))

def Bitvec.add.spec (checked : Checked) (v1 : Term) (v2 : Term) : Term :=
  (Term.mk (Kind.Op2 (Op2.Add checked) v1 v2) (ty v1))

def Bitvec.sub.spec (checked : Checked) (v1 : Term) (v2 : Term) : Term :=
  (Term.mk (Kind.Op2 (Op2.Sub checked) v1 v2) (ty v1))

def Bitvec.neg.spec (checked : Bool) (v : Term) : Term :=
  (Term.mk (Kind.Op1 (Op1.Neg checked) v) (ty v))

def Bitvec.mod_.spec (v1 : Term) (v2 : Term) : Term :=
  (Term.mk (Kind.Op2 Op2.Mod v1 v2) (ty v1))

def Bitvec.rem.spec (signed : Bool) (v1 : Term) (v2 : Term) : Term :=
  (Term.mk (Kind.Op2 (Op2.Rem signed) v1 v2) (ty v1))

def Bitvec.not_.spec (v : Term) : Term :=
  (Term.mk (Kind.Op1 Op1.BvNot v) (ty v))

def Bitvec.and_.spec (v1 : Term) (v2 : Term) : Term :=
  (Term.mk (Kind.Op2 Op2.BitAnd v1 v2) (ty v1))

def Bitvec.or_.spec (v1 : Term) (v2 : Term) : Term :=
  (Term.mk (Kind.Op2 Op2.BitOr v1 v2) (ty v1))

def Bitvec.xor.spec (v1 : Term) (v2 : Term) : Term :=
  (Term.mk (Kind.Op2 Op2.BitXor v1 v2) (ty v1))

def Bitvec.extract.spec (from_ : Int) (to_ : Int) (v : Term) : Term :=
  (Term.mk (Kind.Op1 (Op1.BvExtract from_ to_) v) (Ty.TBitVector ((to_ - from_) + (1 : Int))))

def Bitvec.extend_.spec (signed : Bool) (extend_by : Int) (v : Term) : Term :=
  (Term.mk (Kind.Op1 (Op1.BvExtend signed extend_by) v) (Ty.TBitVector ((Bitvec.size v) + extend_by)))

def Bitvec.concat.spec (v1 : Term) (v2 : Term) : Term :=
  (Term.mk (Kind.Op2 Op2.BvConcat v1 v2) (Ty.TBitVector ((Bitvec.size v1) + (Bitvec.size v2))))

def Bitvec.shl.spec (v1 : Term) (v2 : Term) : Term :=
  (Term.mk (Kind.Op2 Op2.Shl v1 v2) (ty v1))

def Bitvec.lshr.spec (v1 : Term) (v2 : Term) : Term :=
  (Term.mk (Kind.Op2 Op2.LShr v1 v2) (ty v1))

def Bitvec.ashr.spec (v1 : Term) (v2 : Term) : Term :=
  (Term.mk (Kind.Op2 Op2.AShr v1 v2) (ty v1))

def Bitvec.mul.spec (checked : Checked) (v1 : Term) (v2 : Term) : Term :=
  (Term.mk (Kind.Op2 (Op2.Mul checked) v1 v2) (ty v1))

def Bitvec.div.spec (signed : Bool) (v1 : Term) (v2 : Term) : Term :=
  (Term.mk (Kind.Op2 (Op2.Div signed) v1 v2) (ty v1))

def Bitvec.lt_zero.spec (v : Term) : Term :=
  (Term.mk (Kind.Op2 (Op2.Lt true) v (bv_zero (Bitvec.size v))) Ty.TBool)

def Bitvec.lt.spec (signed : Bool) (v1 : Term) (v2 : Term) : Term :=
  (Term.mk (Kind.Op2 (Op2.Lt signed) v1 v2) Ty.TBool)

def Bitvec.leq.spec (signed : Bool) (v1 : Term) (v2 : Term) : Term :=
  (Term.mk (Kind.Op2 (Op2.Leq signed) v1 v2) Ty.TBool)

def Bitvec.add_overflows.spec (signed : Bool) (v1 : Term) (v2 : Term) : Term :=
  (Term.mk (Kind.Op2 (Op2.AddOvf signed) v1 v2) Ty.TBool)

def Bitvec.mul_overflows.spec (signed : Bool) (v1 : Term) (v2 : Term) : Term :=
  (Term.mk (Kind.Op2 (Op2.MulOvf signed) v1 v2) Ty.TBool)

def Bitvec.neg_overflows.spec (v : Term) : Term :=
  (Term.mk (Kind.Op2 Op2.Eq (mk_masked (Bitvec.size v) (Bitvec.min_for true (Bitvec.size v))) v) Ty.TBool)

def Bitvec.sub_overflows.spec (signed : Bool) (v1 : Term) (v2 : Term) : Term :=
  (Term.mk (Kind.Op2 (Op2.SubOvf signed) v1 v2) Ty.TBool)

def Float.is_floatclass.spec (fc : Fc) (sv : Term) : Term :=
  (Term.mk (Kind.Op1 (Op1.FIs fc) sv) Ty.TBool)

def Float.is_negative.spec (v : Term) : Term :=
  (Term.mk (Kind.Op1 Op1.FIsNeg v) Ty.TBool)

def Float.is_positive.spec (v : Term) : Term :=
  (Term.mk (Kind.Op1 Op1.FIsPos v) Ty.TBool)

def Float.cast.spec (rounding : Rm) (fp : Fp) (v : Term) : Term :=
  (Term.mk (Kind.Op1 (Op1.FloatOfFloat rounding fp) v) (Ty.TFloat fp))

def Float.eq.spec (v1 : Term) (v2 : Term) : Term :=
  (Term.mk (Kind.Op2 Op2.FEq v1 v2) Ty.TBool)

def Float.lt.spec (v1 : Term) (v2 : Term) : Term :=
  (Term.mk (Kind.Op2 Op2.FLt v1 v2) Ty.TBool)

def Float.leq.spec (v1 : Term) (v2 : Term) : Term :=
  (Term.mk (Kind.Op2 Op2.FLeq v1 v2) Ty.TBool)

def Float.add.spec (v1 : Term) (v2 : Term) : Term :=
  (Term.mk (Kind.Op2 Op2.FAdd v1 v2) (ty v1))

def Float.sub.spec (v1 : Term) (v2 : Term) : Term :=
  (Term.mk (Kind.Op2 Op2.FSub v1 v2) (ty v1))

def Float.div.spec (v1 : Term) (v2 : Term) : Term :=
  (Term.mk (Kind.Op2 Op2.FDiv v1 v2) (ty v1))

def Float.mul.spec (v1 : Term) (v2 : Term) : Term :=
  (Term.mk (Kind.Op2 Op2.FMul v1 v2) (ty v1))

def Float.rem.spec (v1 : Term) (v2 : Term) : Term :=
  (Term.mk (Kind.Op2 Op2.FRem v1 v2) (ty v1))

def Float.abs.spec (v : Term) : Term :=
  (Term.mk (Kind.Op1 Op1.FAbs v) (ty v))

def Float.neg.spec (v : Term) : Term :=
  (Term.mk (Kind.Op1 Op1.FNeg v) (ty v))

def Float.fma.spec (a : Term) (b : Term) (c : Term) : Term :=
  (Term.mk (Kind.Op3 Op3.Fma a b c) (ty a))

def Float.fmod_of_rem.spec (r : Term) (v1 : Term) (v2 : Term) : Term :=
  (Float.raw_fmod_of_rem r v1 v2)

def Float.fmod.spec (v1 : Term) (v2 : Term) : Term :=
  (Float.raw_fmod_of_rem (Term.mk (Kind.Op2 Op2.FRem v1 v2) (ty v1)) v1 v2)

def Float.min.spec (v1 : Term) (v2 : Term) : Term :=
  (Term.mk (Kind.Op2 Op2.FMin v1 v2) (ty v1))

def Float.max.spec (v1 : Term) (v2 : Term) : Term :=
  (Term.mk (Kind.Op2 Op2.FMax v1 v2) (ty v1))

def Float.sqrt.spec (v : Term) : Term :=
  (Term.mk (Kind.Op1 Op1.FSqrt v) (ty v))

def Float.round.spec (rm : Rm) (sv : Term) : Term :=
  (Term.mk (Kind.Op1 (Op1.FRound rm) sv) (ty sv))

def Float.of_float.spec (rounding : Rm) (signed : Bool) (sz : Int) (v : Term) : Term :=
  (Term.mk (Kind.Op1 (Op1.BvOfFloat rounding signed sz) v) (Ty.TBitVector sz))

def Float.to_float.spec (rounding : Rm) (signed : Bool) (fp : Fp) (v : Term) : Term :=
  (Term.mk (Kind.Op1 (Op1.FloatOfBv rounding signed fp) v) (Ty.TFloat fp))

def Float.to_float_bits.spec (fp : Fp) (v : Term) : Term :=
  (Term.mk (Kind.Op1 (Op1.FloatOfBvRaw fp) v) (Ty.TFloat fp))

def Ptr.loc.spec (p : Term) : Term :=
  (Term.mk (Kind.Op1 Op1.GetPtrLoc p) (Ty.TLoc (Bitvec.size p)))

def Ptr.ofs.spec (p : Term) : Term :=
  (Term.mk (Kind.Op1 Op1.GetPtrOfs p) (Ty.TBitVector (Bitvec.size p)))

def opsRaw (orc : Oracle) : Ops :=
  { orc := orc,
    bool_and_ := fun v1 v2 => Bool.and_.spec v1 v2,
    bool_or_ := fun v1 v2 => Bool.or_.spec v1 v2,
    bool_not_ := fun sv => Bool.not_.spec sv,
    bool_ite := fun guard if_ else_ => Bool.ite.spec guard if_ else_,
    bool_eq := fun v1 v2 => Bool.eq.spec v1 v2,
    bool_eq_untyped := fun v1 v2 => Bool.eq_untyped.spec v1 v2,
    bool_distinct := fun l => Bool.distinct.spec l,
    exists_mk := fun binders body => Exists.mk.spec binders body,
    bitvec_of_bool := fun n b => Bitvec.of_bool.spec n b,
    bitvec_to_bool := fun v => Bitvec.to_bool.spec v,
    bitvec_not_bool := fun v => Bitvec.not_bool.spec v,
    bitvec_add := fun checked v1 v2 => Bitvec.add.spec checked v1 v2,
    bitvec_sub := fun checked v1 v2 => Bitvec.sub.spec checked v1 v2,
    bitvec_neg := fun checked v => Bitvec.neg.spec checked v,
    bitvec_mod_ := fun v1 v2 => Bitvec.mod_.spec v1 v2,
    bitvec_rem := fun signed v1 v2 => Bitvec.rem.spec signed v1 v2,
    bitvec_not_ := fun v => Bitvec.not_.spec v,
    bitvec_and_ := fun v1 v2 => Bitvec.and_.spec v1 v2,
    bitvec_or_ := fun v1 v2 => Bitvec.or_.spec v1 v2,
    bitvec_xor := fun v1 v2 => Bitvec.xor.spec v1 v2,
    bitvec_extract := fun from_ to_ v => Bitvec.extract.spec from_ to_ v,
    bitvec_extend_ := fun signed extend_by v => Bitvec.extend_.spec signed extend_by v,
    bitvec_concat := fun v1 v2 => Bitvec.concat.spec v1 v2,
    bitvec_shl := fun v1 v2 => Bitvec.shl.spec v1 v2,
    bitvec_lshr := fun v1 v2 => Bitvec.lshr.spec v1 v2,
    bitvec_ashr := fun v1 v2 => Bitvec.ashr.spec v1 v2,
    bitvec_mul := fun checked v1 v2 => Bitvec.mul.spec checked v1 v2,
    bitvec_div := fun signed v1 v2 => Bitvec.div.spec signed v1 v2,
    bitvec_lt_zero := fun v => Bitvec.lt_zero.spec v,
    bitvec_lt := fun signed v1 v2 => Bitvec.lt.spec signed v1 v2,
    bitvec_leq := fun signed v1 v2 => Bitvec.leq.spec signed v1 v2,
    bitvec_add_overflows := fun signed v1 v2 => Bitvec.add_overflows.spec signed v1 v2,
    bitvec_mul_overflows := fun signed v1 v2 => Bitvec.mul_overflows.spec signed v1 v2,
    bitvec_neg_overflows := fun v => Bitvec.neg_overflows.spec v,
    bitvec_sub_overflows := fun signed v1 v2 => Bitvec.sub_overflows.spec signed v1 v2,
    float_is_floatclass := fun fc sv => Float.is_floatclass.spec fc sv,
    float_is_negative := fun v => Float.is_negative.spec v,
    float_is_positive := fun v => Float.is_positive.spec v,
    float_cast := fun rounding fp v => Float.cast.spec rounding fp v,
    float_eq := fun v1 v2 => Float.eq.spec v1 v2,
    float_lt := fun v1 v2 => Float.lt.spec v1 v2,
    float_leq := fun v1 v2 => Float.leq.spec v1 v2,
    float_add := fun v1 v2 => Float.add.spec v1 v2,
    float_sub := fun v1 v2 => Float.sub.spec v1 v2,
    float_div := fun v1 v2 => Float.div.spec v1 v2,
    float_mul := fun v1 v2 => Float.mul.spec v1 v2,
    float_rem := fun v1 v2 => Float.rem.spec v1 v2,
    float_abs := fun v => Float.abs.spec v,
    float_neg := fun v => Float.neg.spec v,
    float_fma := fun a b c => Float.fma.spec a b c,
    float_fmod_of_rem := fun r v1 v2 => Float.fmod_of_rem.spec r v1 v2,
    float_fmod := fun v1 v2 => Float.fmod.spec v1 v2,
    float_min := fun v1 v2 => Float.min.spec v1 v2,
    float_max := fun v1 v2 => Float.max.spec v1 v2,
    float_sqrt := fun v => Float.sqrt.spec v,
    float_round := fun rm sv => Float.round.spec rm sv,
    float_of_float := fun rounding signed sz v => Float.of_float.spec rounding signed sz v,
    float_to_float := fun rounding signed fp v => Float.to_float.spec rounding signed fp v,
    float_to_float_bits := fun fp v => Float.to_float_bits.spec fp v,
    ptr_loc := fun p => Ptr.loc.spec p,
    ptr_ofs := fun p => Ptr.ofs.spec p }

end Kanon
